import Operad.Basic
import Operad.Constructions
import Operad.Associativity
import Operad.Endomorphism
import Operad.Algebra
import Operad.Total
import Operad.PreLie
import Operad.AssAlgebra
import Operad.Suboperad
