import Operad.Basic
import Operad.Constructions
import Operad.Associativity
import Operad.Endomorphism
import Operad.Algebra
import Operad.Total
import Operad.PreLie
import Operad.TotalSpace
import Operad.AssAlgebra
import Operad.Suboperad
import Operad.Tree
import Operad.Free
import Operad.DG
import Operad.GradedPreLie
import Operad.TotalSpaceS
