/-
# The square of the bar differential

The bar differential of the free graded operad squares to zero modulo the ideal generated by
relations making the merge function associative up to sign (`FreeGr.barD_barD_mem`).

The proof is planar. On the combinations of planar trees with `n` leaves (`FreeGr.Pl`), embedded in
the free graded operad in the standard order (`FreeGr.ιP`), grafting at a position (`FreeGr.gF`),
merge-grafting at a position (`FreeGr.mF`), the parity involution (`FreeGr.twF`) and the bar
differential (`FreeGr.dF`) satisfy the Leibniz rule up to merge-grafting (`FreeGr.dF_gF`) and the
laws of merge-grafting with grafting, with positions instead of relabellings. Every tree with at
least two vertices is a tree grafted with the corolla of its last vertex. By induction on the
number of vertices:

* the square of the bar differential of a graft with a corolla is the graft of the square, plus
  `N = d (x ⊛ₚ c) + (d x) ⊛ₚ c` (`FreeGr.dF_dF_gF`);
* `N` reduces to merging two corollas into a tree in the two orders, at two leaves of one vertex
  (`P`) or at a leaf of a vertex and a leaf of the merged corolla (`S`), which reduce in turn to
  merging into a corolla, where the relations apply.
-/
import Operad.BarDescent

universe u v

namespace Operad

open Sym GerBV TreeOfArity
open scoped TensorProduct

namespace FreeGr

variable {T : ℕ → Type v} (μ : MergeFn T) (gp : ∀ k, T k → Bool) (R : Type u) [CommRing R]

/-! ## Planar combinations of trees -/

/-- **Combinations of planar trees** with `n` leaves. -/
abbrev Pl (n : ℕ) : Type (max u v) := TreeOfArity T n →₀ R

variable {R} in
/-- A planar tree, as a combination. -/
noncomputable def pt {n : ℕ} (t : TreeOfArity T n) : Pl (T := T) R n := Finsupp.single t 1

/-- **Planar trees in the standard order**, in the free graded operad. -/
noncomputable def ιP (n : ℕ) : Pl (T := T) R n →ₗ[R] FreeGr R gp (Fin n) :=
  Finsupp.linearCombination R fun t => SgnLin.bas (treeSgn gp) R (Reg.std t)

variable {gp R}

lemma ιP_pt {n : ℕ} (t : TreeOfArity T n) :
    ιP gp R n (pt t) = SgnLin.bas (treeSgn gp) R (Reg.std t) :=
  (Finsupp.linearCombination_single R _ _).trans (one_smul R _)

lemma std_injective {n : ℕ} : Function.Injective (Reg.std : TreeOfArity T n → _) := by
  intro s t h
  have h2 := congrArg (fun x : Reg (TreeOfArity T) (Fin n) => x.2.1) h
  simp only [Reg.std] at h2
  exact eq_of_heq (Sigma.mk.inj h2).2

lemma ιP_apply {n : ℕ} (x : Pl (T := T) R n) :
    (ιP gp R n x : Reg (TreeOfArity T) (Fin n) →₀ R) = Finsupp.mapDomain Reg.std x := by
  induction x using Finsupp.induction_linear with
  | zero => rw [map_zero, Finsupp.mapDomain_zero]; rfl
  | add x y hx hy => rw [map_add, Finsupp.mapDomain_add, ← hx, ← hy]; rfl
  | single t c =>
    rw [Finsupp.mapDomain_single, ← Finsupp.smul_single_one t c, map_smul]
    show c • ιP gp R n (pt t) = _
    rw [ιP_pt]
    exact Finsupp.smul_single_one _ c

lemma ιP_injective {n : ℕ} : Function.Injective (ιP gp R n) := by
  intro x y h
  have h' : Finsupp.mapDomain Reg.std x = Finsupp.mapDomain Reg.std y := by
    rw [← ιP_apply, ← ιP_apply]
    exact congrArg (fun z : FreeGr R gp (Fin n) => (z : Reg (TreeOfArity T) (Fin n) →₀ R)) h
  exact Finsupp.mapDomain_injective std_injective h'

/-! ## Positions -/

/-- **The positions of a composite**: the order isomorphism of the composite of standard orders
onto the standard order. -/
noncomputable def posEquiv (n a l m : ℕ) (h : a < n ∧ m + 1 = n + l) :
    Without (Fin n) ⟨a, h.1⟩ ⊕ Fin l ≃ Fin m :=
  (LinOrd.comp (⟨a, h.1⟩ : Fin n) (LinOrd.std n) (LinOrd.std l)).toRank.trans (finCongr (by
    rw [Fintype.card_sum, Reg.card_without, Fintype.card_fin, Fintype.card_fin]
    omega))

lemma map_toRank {X : Type} [Fintype X] [DecidableEq X] (L : LinOrd X) {m : ℕ}
    (h : Fintype.card X = m) : LinOrd.map (L.toRank.trans (finCongr h)) L = LinOrd.std m := by
  ext a b
  simp only [LinOrd.map_lt, LinOrd.std_lt, Fin.lt_def]
  rw [L.lt_iff_rank_lt, ← LinOrd.toRank_apply, ← LinOrd.toRank_apply]
  simp

lemma map_posEquiv_comp {n a l m : ℕ} (h : a < n ∧ m + 1 = n + l) :
    LinOrd.map (posEquiv n a l m h)
      (LinOrd.comp (⟨a, h.1⟩ : Fin n) (LinOrd.std n) (LinOrd.std l)) = LinOrd.std m :=
  map_toRank _ _

/-! ## Operations on planar trees -/

section Ops

variable (gp R)

/-- Contracting an edge of a planar tree. -/
def contrT {n : ℕ} (t : TreeOfArity T n) (k : ℕ) : TreeOfArity T n :=
  ⟨t.1.contr μ k, (Tree.arity_contr μ t.1 k).trans t.2⟩

/-- Grafting planar trees at a position. -/
def graftT {n l m : ℕ} (s : TreeOfArity T n) (a : ℕ) (u : TreeOfArity T l)
    (h : a < n ∧ m + 1 = n + l) : TreeOfArity T m :=
  ⟨s.1.graft a u.1, by
    have := Tree.arity_graft s.1 a u.1 (by rw [s.2]; exact h.1)
    rw [this, s.2, u.2]
    omega⟩

/-- Merge-grafting planar trees at a position. -/
def mgraftT {n l m : ℕ} (s : TreeOfArity T n) (a : ℕ) (u : TreeOfArity T l)
    (h : a < n ∧ m + 1 = n + l) : TreeOfArity T m :=
  ⟨s.1.mgraft μ a u.1, by
    have := Tree.arity_mgraft μ s.1 a u.1 (by rw [s.2]; exact h.1)
    rw [s.2, u.2] at this
    omega⟩

variable {μ}

@[simp] lemma contrT_val {n : ℕ} (t : TreeOfArity T n) (k : ℕ) :
    (contrT μ t k).1 = t.1.contr μ k := rfl

@[simp] lemma graftT_val {n l m : ℕ} (s : TreeOfArity T n) (a : ℕ) (u : TreeOfArity T l)
    (h : a < n ∧ m + 1 = n + l) : (graftT s a u h).1 = s.1.graft a u.1 := rfl

@[simp] lemma mgraftT_val {n l m : ℕ} (s : TreeOfArity T n) (a : ℕ) (u : TreeOfArity T l)
    (h : a < n ∧ m + 1 = n + l) : (mgraftT μ s a u h).1 = s.1.mgraft μ a u.1 := rfl

/-- The parity involution on planar trees. -/
noncomputable def twF (n : ℕ) : Pl (T := T) R n →ₗ[R] Pl (T := T) R n :=
  Finsupp.linearCombination R fun t => σ R (Tree.tpar gp t.1) • pt t

variable (μ) in
/-- **The bar differential on planar trees.** -/
noncomputable def dF (n : ℕ) : Pl (T := T) R n →ₗ[R] Pl (T := T) R n :=
  Finsupp.linearCombination R fun t : TreeOfArity T n =>
    ∑ k ∈ Finset.Ico 1 t.1.weight, σ R (Tree.contrSgn gp t.1 k) • pt (contrT μ t k)

/-- **Grafting at a position**, with its Koszul sign. -/
noncomputable def gF (a : ℕ) {n l : ℕ} (m : ℕ) : Pl (T := T) R n →ₗ[R] Pl (T := T) R l →ₗ[R] Pl (T := T) R m :=
  Finsupp.linearCombination R fun s : TreeOfArity T n =>
    Finsupp.linearCombination R fun u : TreeOfArity T l =>
      if h : a < n ∧ m + 1 = n + l then
        σ R (Tree.tpar gp u.1 && Tree.apar gp s.1 a) • pt (graftT s a u h)
      else 0

variable (μ) in
/-- **Merge-grafting at a position**, with its sign. -/
noncomputable def mF (a : ℕ) {n l : ℕ} (m : ℕ) : Pl (T := T) R n →ₗ[R] Pl (T := T) R l →ₗ[R] Pl (T := T) R m :=
  Finsupp.linearCombination R fun s : TreeOfArity T n =>
    Finsupp.linearCombination R fun u : TreeOfArity T l =>
      if h : a < n ∧ m + 1 = n + l then
        (if s.1.isLeaf = false ∧ u.1.isLeaf = false then
          σ R (Tree.mSgn gp s.1 a u.1) • pt (mgraftT μ s a u h) else 0)
      else 0

variable {gp R}

lemma twF_pt {n : ℕ} (t : TreeOfArity T n) :
    twF gp R n (pt t) = σ R (Tree.tpar gp t.1) • pt t :=
  (Finsupp.linearCombination_single R _ _).trans (one_smul R _)

lemma dF_pt {n : ℕ} (t : TreeOfArity T n) :
    dF μ gp R n (pt t)
      = ∑ k ∈ Finset.Ico 1 t.1.weight, σ R (Tree.contrSgn gp t.1 k) • pt (contrT μ t k) :=
  (Finsupp.linearCombination_single R _ _).trans (one_smul R _)

lemma gF_pt (a : ℕ) {n l m : ℕ} (s : TreeOfArity T n) (u : TreeOfArity T l) :
    gF gp R a m (pt s) (pt u)
      = if h : a < n ∧ m + 1 = n + l then
          σ R (Tree.tpar gp u.1 && Tree.apar gp s.1 a) • pt (graftT s a u h) else 0 := by
  unfold gF
  exact (LinearMap.congr_fun
    ((Finsupp.linearCombination_single R (1 : R) s).trans (one_smul R _)) _).trans
      ((Finsupp.linearCombination_single R (1 : R) u).trans (one_smul R _))

lemma mF_pt (a : ℕ) {n l m : ℕ} (s : TreeOfArity T n) (u : TreeOfArity T l) :
    mF μ gp R a m (pt s) (pt u)
      = if h : a < n ∧ m + 1 = n + l then
          (if s.1.isLeaf = false ∧ u.1.isLeaf = false then
            σ R (Tree.mSgn gp s.1 a u.1) • pt (mgraftT μ s a u h) else 0) else 0 := by
  unfold mF
  exact (LinearMap.congr_fun
    ((Finsupp.linearCombination_single R (1 : R) s).trans (one_smul R _)) _).trans
      ((Finsupp.linearCombination_single R (1 : R) u).trans (one_smul R _))

lemma gF_pt_of {a n l m : ℕ} (h : a < n ∧ m + 1 = n + l) (s : TreeOfArity T n)
    (u : TreeOfArity T l) :
    gF gp R a m (pt s) (pt u) = σ R (Tree.tpar gp u.1 && Tree.apar gp s.1 a) • pt (graftT s a u h) :=
  (gF_pt a s u).trans (dif_pos h)

lemma mF_pt_of {a n l m : ℕ} (h : a < n ∧ m + 1 = n + l) {s : TreeOfArity T n}
    {u : TreeOfArity T l} (hs : s.1.isLeaf = false) (hu : u.1.isLeaf = false) :
    mF μ gp R a m (pt s) (pt u) = σ R (Tree.mSgn gp s.1 a u.1) • pt (mgraftT μ s a u h) := by
  rw [mF_pt, dif_pos h, if_pos ⟨hs, hu⟩]

lemma mF_pt_leaf_right (a : ℕ) {n l m : ℕ} (s : TreeOfArity T n) {u : TreeOfArity T l}
    (hu : u.1.isLeaf = true) : mF μ gp R a m (pt s) (pt u) = 0 := by
  rw [mF_pt]
  split_ifs with h1 h2
  · exact absurd h2.2 (by rw [hu]; decide)
  · rfl
  · rfl

lemma mF_pt_leaf_left (a : ℕ) {n l m : ℕ} {s : TreeOfArity T n} (hs : s.1.isLeaf = true)
    (u : TreeOfArity T l) : mF μ gp R a m (pt s) (pt u) = 0 := by
  rw [mF_pt]
  split_ifs with h1 h2
  · exact absurd h2.1 (by rw [hs]; decide)
  · rfl
  · rfl

lemma gF_of_not {a n l m : ℕ} (h : ¬ (a < n ∧ m + 1 = n + l)) (x : Pl (T := T) R n)
    (y : Pl (T := T) R l) : gF gp R a m x y = 0 := by
  have : gF gp R a m (n := n) (l := l) = 0 :=
    Finsupp.lhom_ext' fun s => LinearMap.ext_ring
      (Finsupp.lhom_ext' fun u => LinearMap.ext_ring ((gF_pt a s u).trans (dif_neg h)))
  rw [this, LinearMap.zero_apply, LinearMap.zero_apply]

lemma mF_of_not {a n l m : ℕ} (h : ¬ (a < n ∧ m + 1 = n + l)) (x : Pl (T := T) R n)
    (y : Pl (T := T) R l) : mF μ gp R a m x y = 0 := by
  have : mF μ gp R a m (n := n) (l := l) = 0 :=
    Finsupp.lhom_ext' fun s => LinearMap.ext_ring
      (Finsupp.lhom_ext' fun u => LinearMap.ext_ring ((mF_pt a s u).trans (dif_neg h)))
  rw [this, LinearMap.zero_apply, LinearMap.zero_apply]

end Ops

/-! ## Planar trees in the free graded operad -/

section Compat

variable {μ}

lemma map_posEquiv_std_comp {a n l m : ℕ} (h : a < n ∧ m + 1 = n + l) (s : TreeOfArity T n)
    (u : TreeOfArity T l) :
    SetOperad.map (posEquiv n a l m h) (SetOperad.comp (⟨a, h.1⟩ : Fin n) (Reg.std s) (Reg.std u))
      = Reg.std (graftT s a u h) := by
  refine reg_ext (map_posEquiv_comp h) ?_
  rw [treeOf_map, treeOf_comp]
  show s.1.graft ((LinOrd.std n).rank ⟨a, h.1⟩) u.1 = s.1.graft a u.1
  rw [LinOrd.rank_std]

lemma map_posEquiv_std_mcomp {a n l m : ℕ} (h : a < n ∧ m + 1 = n + l) (s : TreeOfArity T n)
    (u : TreeOfArity T l) :
    SetOperad.map (posEquiv n a l m h) (mcompR μ (⟨a, h.1⟩ : Fin n) (Reg.std s) (Reg.std u))
      = Reg.std (mgraftT μ s a u h) := by
  refine reg_ext (map_posEquiv_comp h) ?_
  rw [treeOf_map, treeOf_mcompR]
  show s.1.mgraft μ ((LinOrd.std n).rank ⟨a, h.1⟩) u.1 = s.1.mgraft μ a u.1
  rw [LinOrd.rank_std]

lemma contrR_std {n : ℕ} (t : TreeOfArity T n) (k : ℕ) :
    contrR μ (Reg.std t) k = Reg.std (contrT μ t k) := rfl

lemma ιP_twF {n : ℕ} (x : Pl (T := T) R n) :
    ιP gp R n (twF gp R n x) = GrSpecies.tw (R := R) (V := FreeGr R gp) true (ιP gp R n x) := by
  have h := Lin.induction₁ (S := fun _ _ _ => TreeOfArity T n) (A := Unit)
    (ιP gp R n ∘ₗ twF gp R n) (GrSpecies.tw (R := R) (V := FreeGr R gp) true ∘ₗ ιP gp R n)
    (fun t => ?_) x
  · simpa using h
  show ιP gp R n (twF gp R n (pt t)) = GrSpecies.tw (R := R) (V := FreeGr R gp) true
    (ιP gp R n (pt t))
  rw [twF_pt, map_smul, ιP_pt, tw_bas]
  rfl

lemma ιP_dF {n : ℕ} (x : Pl (T := T) R n) :
    ιP gp R n (dF μ gp R n x) = barD μ gp R (Fin n) (ιP gp R n x) := by
  have h := Lin.induction₁ (S := fun _ _ _ => TreeOfArity T n) (A := Unit)
    (ιP gp R n ∘ₗ dF μ gp R n) (barD μ gp R (Fin n) ∘ₗ ιP gp R n) (fun t => ?_) x
  · simpa using h
  show ιP gp R n (dF μ gp R n (pt t)) = barD μ gp R (Fin n) (ιP gp R n (pt t))
  rw [dF_pt, map_sum, ιP_pt, barD_bas]
  refine Finset.sum_congr rfl fun k _ => ?_
  rw [map_smul, ιP_pt, contrR_std]
  rfl

lemma ιP_gF {a n l m : ℕ} (h : a < n ∧ m + 1 = n + l) (x : Pl (T := T) R n)
    (y : Pl (T := T) R l) :
    ιP gp R m (gF gp R a m x y) = GrOperad.map (R := R) (posEquiv n a l m h)
      (GrOperad.comp (R := R) (⟨a, h.1⟩ : Fin n) (ιP gp R n x) (ιP gp R l y)) := by
  have key : (gF gp R a m (n := n) (l := l)).compr₂ (ιP gp R m)
      = ((GrOperad.comp (R := R) (P := FreeGr R gp) (B := Fin l) (⟨a, h.1⟩ : Fin n)).compr₂
          (GrOperad.map (R := R) (posEquiv n a l m h))).compl₁₂ (ιP gp R n) (ιP gp R l) := by
    refine Finsupp.lhom_ext' fun s => LinearMap.ext_ring
      (Finsupp.lhom_ext' fun u => LinearMap.ext_ring ?_)
    show ιP gp R m (gF gp R a m (pt s) (pt u)) = GrOperad.map (R := R) (posEquiv n a l m h)
      (GrOperad.comp (R := R) (⟨a, h.1⟩ : Fin n) (ιP gp R n (pt s)) (ιP gp R l (pt u)))
    rw [gF_pt_of h, map_smul, ιP_pt, ιP_pt, ιP_pt, comp_bas_eq, map_smul, SgnLin.map_bas,
      map_posEquiv_std_comp]
    congr 1
    show σ R (Tree.tpar gp u.1 && Tree.apar gp s.1 a)
      = σ R (Tree.tpar gp u.1 && Tree.apar gp s.1 ((LinOrd.std n).rank ⟨a, h.1⟩))
    rw [LinOrd.rank_std]
  exact LinearMap.congr_fun (LinearMap.congr_fun key x) y

lemma ιP_mF {a n l m : ℕ} (h : a < n ∧ m + 1 = n + l) (x : Pl (T := T) R n)
    (y : Pl (T := T) R l) :
    ιP gp R m (mF μ gp R a m x y) = GrOperad.map (R := R) (posEquiv n a l m h)
      (mcomp μ gp R (⟨a, h.1⟩ : Fin n) (ιP gp R n x) (ιP gp R l y)) := by
  have key : (mF μ gp R a m (n := n) (l := l)).compr₂ (ιP gp R m)
      = ((mcomp μ gp R (B := Fin l) (⟨a, h.1⟩ : Fin n)).compr₂
          (GrOperad.map (R := R) (posEquiv n a l m h))).compl₁₂ (ιP gp R n) (ιP gp R l) := by
    refine Finsupp.lhom_ext' fun s => LinearMap.ext_ring
      (Finsupp.lhom_ext' fun u => LinearMap.ext_ring ?_)
    show ιP gp R m (mF μ gp R a m (pt s) (pt u)) = GrOperad.map (R := R) (posEquiv n a l m h)
      (mcomp μ gp R (⟨a, h.1⟩ : Fin n) (ιP gp R n (pt s)) (ιP gp R l (pt u)))
    rw [mF_pt, dif_pos h, ιP_pt, ιP_pt, mcomp_bas]
    have hrank : (LinOrd.std n).rank (⟨a, h.1⟩ : Fin n) = a := LinOrd.rank_std n _
    split_ifs with h1 h2 h2
    · rw [map_smul, ιP_pt, map_smul, SgnLin.map_bas, map_posEquiv_std_mcomp]
      congr 1
      show σ R (Tree.mSgn gp s.1 a u.1) = σ R (Tree.mSgn gp s.1 ((LinOrd.std n).rank ⟨a, h.1⟩) u.1)
      rw [hrank]
    · exact absurd h1 h2
    · exact absurd h2 h1
    · rw [map_zero, map_zero]
  exact LinearMap.congr_fun (LinearMap.congr_fun key x) y

variable (μ) in
/-- **The Leibniz rule up to merge-grafting**, for planar trees. -/
theorem dF_gF (hμ : MergeFn.Odd gp μ) (a : ℕ) {n l : ℕ} (m : ℕ) (x : Pl (T := T) R n)
    (y : Pl (T := T) R l) :
    dF μ gp R m (gF gp R a m x y)
      = gF gp R a m (dF μ gp R n x) y + gF gp R a m (twF gp R n x) (dF μ gp R l y)
        + mF μ gp R a m x y := by
  by_cases h : a < n ∧ m + 1 = n + l
  · apply ιP_injective (gp := gp)
    rw [ιP_dF, ιP_gF h, ← map_barD, barD_comp hμ, map_add, map_add, map_add, map_add, ιP_gF h,
      ιP_gF h, ιP_mF h, ιP_dF, ιP_dF, ιP_twF]
  · rw [gF_of_not h, gF_of_not h, gF_of_not h, mF_of_not h, map_zero, add_zero, add_zero]

end Compat

end FreeGr

end Operad
