/-
# The square of the bar differential

The bar differential of the free graded operad squares to zero modulo the ideal generated by
relations making the merge function associative up to sign (`FreeGr.barD_barD_mem`).

The proof is planar. On the combinations of planar trees with `n` leaves (`FreeGr.Pl`), embedded in
the free graded operad in the standard order (`FreeGr.ιP`), grafting at a position (`FreeGr.gF`),
merge-grafting at a position (`FreeGr.mF`), the parity involution (`FreeGr.twF`) and the bar
differential (`FreeGr.dF`) satisfy the Leibniz rule up to merge-grafting (`FreeGr.dF_gF`) and the
laws of merge-grafting with grafting, with positions instead of relabellings. Every tree with at
least two vertices is a tree grafted with the corolla of its last vertex. By induction on the
number of vertices:

* the square of the bar differential of a graft with a corolla is the graft of the square, plus
  `N = d (x ⊛ₚ c) + (d x) ⊛ₚ c` (`FreeGr.dF_dF_gF`);
* `N` reduces to merging two corollas into a tree in the two orders, at two leaves of one vertex
  (`P`) or at a leaf of a vertex and a leaf of the merged corolla (`S`), which reduce in turn to
  merging into a corolla, where the relations apply.
-/
import Operad.BarDescent

universe u v

namespace Operad

open Sym GerBV TreeOfArity
open scoped TensorProduct

namespace FreeGr

variable {T : ℕ → Type v} (μ : MergeFn T) (gp : ∀ k, T k → Bool) (R : Type u) [CommRing R]

/-! ## Planar combinations of trees -/

/-- **Combinations of planar trees** with `n` leaves. -/
abbrev Pl (n : ℕ) : Type (max u v) := TreeOfArity T n →₀ R

variable {R} in
/-- A planar tree, as a combination. -/
noncomputable def pt {n : ℕ} (t : TreeOfArity T n) : Pl (T := T) R n := Finsupp.single t 1

/-- **Planar trees in the standard order**, in the free graded operad. -/
noncomputable def ιP (n : ℕ) : Pl (T := T) R n →ₗ[R] FreeGr R gp (Fin n) :=
  Finsupp.linearCombination R fun t => SgnLin.bas (treeSgn gp) R (Reg.std t)

variable {gp R}

lemma ιP_pt {n : ℕ} (t : TreeOfArity T n) :
    ιP gp R n (pt t) = SgnLin.bas (treeSgn gp) R (Reg.std t) :=
  (Finsupp.linearCombination_single R _ _).trans (one_smul R _)

lemma std_injective {n : ℕ} : Function.Injective (Reg.std : TreeOfArity T n → _) := by
  intro s t h
  have h2 := congrArg (fun x : Reg (TreeOfArity T) (Fin n) => x.2.1) h
  simp only [Reg.std] at h2
  exact eq_of_heq (Sigma.mk.inj h2).2

lemma ιP_apply {n : ℕ} (x : Pl (T := T) R n) :
    (ιP gp R n x : Reg (TreeOfArity T) (Fin n) →₀ R) = Finsupp.mapDomain Reg.std x := by
  induction x using Finsupp.induction_linear with
  | zero => rw [map_zero, Finsupp.mapDomain_zero]; rfl
  | add x y hx hy => rw [map_add, Finsupp.mapDomain_add, ← hx, ← hy]; rfl
  | single t c =>
    rw [Finsupp.mapDomain_single, ← Finsupp.smul_single_one t c, map_smul]
    show c • ιP gp R n (pt t) = _
    rw [ιP_pt]
    exact Finsupp.smul_single_one _ c

lemma ιP_injective {n : ℕ} : Function.Injective (ιP gp R n) := by
  intro x y h
  have h' : Finsupp.mapDomain Reg.std x = Finsupp.mapDomain Reg.std y := by
    rw [← ιP_apply, ← ιP_apply]
    exact congrArg (fun z : FreeGr R gp (Fin n) => (z : Reg (TreeOfArity T) (Fin n) →₀ R)) h
  exact Finsupp.mapDomain_injective std_injective h'

/-! ## Positions -/

/-- **The positions of a composite**: the order isomorphism of the composite of standard orders
onto the standard order. -/
noncomputable def posEquiv (n a l m : ℕ) (h : a < n ∧ m + 1 = n + l) :
    Without (Fin n) ⟨a, h.1⟩ ⊕ Fin l ≃ Fin m :=
  (LinOrd.comp (⟨a, h.1⟩ : Fin n) (LinOrd.std n) (LinOrd.std l)).toRank.trans (finCongr (by
    rw [Fintype.card_sum, Reg.card_without, Fintype.card_fin, Fintype.card_fin]
    omega))

lemma map_toRank {X : Type} [Fintype X] [DecidableEq X] (L : LinOrd X) {m : ℕ}
    (h : Fintype.card X = m) : LinOrd.map (L.toRank.trans (finCongr h)) L = LinOrd.std m := by
  ext a b
  simp only [LinOrd.map_lt, LinOrd.std_lt, Fin.lt_def]
  rw [L.lt_iff_rank_lt, ← LinOrd.toRank_apply, ← LinOrd.toRank_apply]
  simp

lemma map_posEquiv_comp {n a l m : ℕ} (h : a < n ∧ m + 1 = n + l) :
    LinOrd.map (posEquiv n a l m h)
      (LinOrd.comp (⟨a, h.1⟩ : Fin n) (LinOrd.std n) (LinOrd.std l)) = LinOrd.std m :=
  map_toRank _ _

/-! ## Operations on planar trees -/

section Ops

variable (gp R)

/-- Contracting an edge of a planar tree. -/
def contrT {n : ℕ} (t : TreeOfArity T n) (k : ℕ) : TreeOfArity T n :=
  ⟨t.1.contr μ k, (Tree.arity_contr μ t.1 k).trans t.2⟩

/-- Grafting planar trees at a position. -/
def graftT {n l m : ℕ} (s : TreeOfArity T n) (a : ℕ) (u : TreeOfArity T l)
    (h : a < n ∧ m + 1 = n + l) : TreeOfArity T m :=
  ⟨s.1.graft a u.1, by
    have := Tree.arity_graft s.1 a u.1 (by rw [s.2]; exact h.1)
    rw [this, s.2, u.2]
    omega⟩

/-- Merge-grafting planar trees at a position. -/
def mgraftT {n l m : ℕ} (s : TreeOfArity T n) (a : ℕ) (u : TreeOfArity T l)
    (h : a < n ∧ m + 1 = n + l) : TreeOfArity T m :=
  ⟨s.1.mgraft μ a u.1, by
    have := Tree.arity_mgraft μ s.1 a u.1 (by rw [s.2]; exact h.1)
    rw [s.2, u.2] at this
    omega⟩

variable {μ}

@[simp] lemma contrT_val {n : ℕ} (t : TreeOfArity T n) (k : ℕ) :
    (contrT μ t k).1 = t.1.contr μ k := rfl

@[simp] lemma graftT_val {n l m : ℕ} (s : TreeOfArity T n) (a : ℕ) (u : TreeOfArity T l)
    (h : a < n ∧ m + 1 = n + l) : (graftT s a u h).1 = s.1.graft a u.1 := rfl

@[simp] lemma mgraftT_val {n l m : ℕ} (s : TreeOfArity T n) (a : ℕ) (u : TreeOfArity T l)
    (h : a < n ∧ m + 1 = n + l) : (mgraftT μ s a u h).1 = s.1.mgraft μ a u.1 := rfl

/-- The parity involution on planar trees. -/
noncomputable def twF (n : ℕ) : Pl (T := T) R n →ₗ[R] Pl (T := T) R n :=
  Finsupp.linearCombination R fun t => σ R (Tree.tpar gp t.1) • pt t

variable (μ) in
/-- **The bar differential on planar trees.** -/
noncomputable def dF (n : ℕ) : Pl (T := T) R n →ₗ[R] Pl (T := T) R n :=
  Finsupp.linearCombination R fun t : TreeOfArity T n =>
    ∑ k ∈ Finset.Ico 1 t.1.weight, σ R (Tree.contrSgn gp t.1 k) • pt (contrT μ t k)

/-- **Grafting at a position**, with its Koszul sign. -/
noncomputable def gF (a : ℕ) {n l : ℕ} (m : ℕ) :
    Pl (T := T) R n →ₗ[R] Pl (T := T) R l →ₗ[R] Pl (T := T) R m :=
  Finsupp.linearCombination R fun s : TreeOfArity T n =>
    Finsupp.linearCombination R fun u : TreeOfArity T l =>
      if h : a < n ∧ m + 1 = n + l then
        σ R (Tree.tpar gp u.1 && Tree.apar gp s.1 a) • pt (graftT s a u h)
      else 0

variable (μ) in
/-- **Merge-grafting at a position**, with its sign. -/
noncomputable def mF (a : ℕ) {n l : ℕ} (m : ℕ) :
    Pl (T := T) R n →ₗ[R] Pl (T := T) R l →ₗ[R] Pl (T := T) R m :=
  Finsupp.linearCombination R fun s : TreeOfArity T n =>
    Finsupp.linearCombination R fun u : TreeOfArity T l =>
      if h : a < n ∧ m + 1 = n + l then
        (if s.1.isLeaf = false ∧ u.1.isLeaf = false then
          σ R (Tree.mSgn gp s.1 a u.1) • pt (mgraftT μ s a u h) else 0)
      else 0

variable {gp R}

lemma twF_pt {n : ℕ} (t : TreeOfArity T n) :
    twF gp R n (pt t) = σ R (Tree.tpar gp t.1) • pt t :=
  (Finsupp.linearCombination_single R _ _).trans (one_smul R _)

lemma dF_pt {n : ℕ} (t : TreeOfArity T n) :
    dF μ gp R n (pt t)
      = ∑ k ∈ Finset.Ico 1 t.1.weight, σ R (Tree.contrSgn gp t.1 k) • pt (contrT μ t k) :=
  (Finsupp.linearCombination_single R _ _).trans (one_smul R _)

lemma gF_pt (a : ℕ) {n l m : ℕ} (s : TreeOfArity T n) (u : TreeOfArity T l) :
    gF gp R a m (pt s) (pt u)
      = if h : a < n ∧ m + 1 = n + l then
          σ R (Tree.tpar gp u.1 && Tree.apar gp s.1 a) • pt (graftT s a u h) else 0 := by
  unfold gF
  exact (LinearMap.congr_fun
    ((Finsupp.linearCombination_single R (1 : R) s).trans (one_smul R _)) _).trans
      ((Finsupp.linearCombination_single R (1 : R) u).trans (one_smul R _))

lemma mF_pt (a : ℕ) {n l m : ℕ} (s : TreeOfArity T n) (u : TreeOfArity T l) :
    mF μ gp R a m (pt s) (pt u)
      = if h : a < n ∧ m + 1 = n + l then
          (if s.1.isLeaf = false ∧ u.1.isLeaf = false then
            σ R (Tree.mSgn gp s.1 a u.1) • pt (mgraftT μ s a u h) else 0) else 0 := by
  unfold mF
  exact (LinearMap.congr_fun
    ((Finsupp.linearCombination_single R (1 : R) s).trans (one_smul R _)) _).trans
      ((Finsupp.linearCombination_single R (1 : R) u).trans (one_smul R _))

lemma gF_pt_of {a n l m : ℕ} (h : a < n ∧ m + 1 = n + l) (s : TreeOfArity T n)
    (u : TreeOfArity T l) :
    gF gp R a m (pt s) (pt u)
      = σ R (Tree.tpar gp u.1 && Tree.apar gp s.1 a) • pt (graftT s a u h) :=
  (gF_pt a s u).trans (dif_pos h)

lemma mF_pt_of {a n l m : ℕ} (h : a < n ∧ m + 1 = n + l) {s : TreeOfArity T n}
    {u : TreeOfArity T l} (hs : s.1.isLeaf = false) (hu : u.1.isLeaf = false) :
    mF μ gp R a m (pt s) (pt u) = σ R (Tree.mSgn gp s.1 a u.1) • pt (mgraftT μ s a u h) := by
  rw [mF_pt, dif_pos h, if_pos ⟨hs, hu⟩]

lemma mF_pt_leaf_right (a : ℕ) {n l m : ℕ} (s : TreeOfArity T n) {u : TreeOfArity T l}
    (hu : u.1.isLeaf = true) : mF μ gp R a m (pt s) (pt u) = 0 := by
  rw [mF_pt]
  split_ifs with h1 h2
  · exact absurd h2.2 (by rw [hu]; decide)
  · rfl
  · rfl

lemma mF_pt_leaf_left (a : ℕ) {n l m : ℕ} {s : TreeOfArity T n} (hs : s.1.isLeaf = true)
    (u : TreeOfArity T l) : mF μ gp R a m (pt s) (pt u) = 0 := by
  rw [mF_pt]
  split_ifs with h1 h2
  · exact absurd h2.1 (by rw [hs]; decide)
  · rfl
  · rfl

lemma gF_of_not {a n l m : ℕ} (h : ¬ (a < n ∧ m + 1 = n + l)) (x : Pl (T := T) R n)
    (y : Pl (T := T) R l) : gF gp R a m x y = 0 := by
  have : gF gp R a m (n := n) (l := l) = 0 :=
    Finsupp.lhom_ext' fun s => LinearMap.ext_ring
      (Finsupp.lhom_ext' fun u => LinearMap.ext_ring ((gF_pt a s u).trans (dif_neg h)))
  rw [this, LinearMap.zero_apply, LinearMap.zero_apply]

lemma mF_of_not {a n l m : ℕ} (h : ¬ (a < n ∧ m + 1 = n + l)) (x : Pl (T := T) R n)
    (y : Pl (T := T) R l) : mF μ gp R a m x y = 0 := by
  have : mF μ gp R a m (n := n) (l := l) = 0 :=
    Finsupp.lhom_ext' fun s => LinearMap.ext_ring
      (Finsupp.lhom_ext' fun u => LinearMap.ext_ring ((mF_pt a s u).trans (dif_neg h)))
  rw [this, LinearMap.zero_apply, LinearMap.zero_apply]

end Ops

/-! ## Planar trees in the free graded operad -/

section Compat

variable {μ}

lemma map_posEquiv_std_comp {a n l m : ℕ} (h : a < n ∧ m + 1 = n + l) (s : TreeOfArity T n)
    (u : TreeOfArity T l) :
    SetOperad.map (posEquiv n a l m h) (SetOperad.comp (⟨a, h.1⟩ : Fin n) (Reg.std s) (Reg.std u))
      = Reg.std (graftT s a u h) := by
  refine reg_ext (map_posEquiv_comp h) ?_
  rw [treeOf_map, treeOf_comp]
  show s.1.graft ((LinOrd.std n).rank ⟨a, h.1⟩) u.1 = s.1.graft a u.1
  rw [LinOrd.rank_std]

lemma map_posEquiv_std_mcomp {a n l m : ℕ} (h : a < n ∧ m + 1 = n + l) (s : TreeOfArity T n)
    (u : TreeOfArity T l) :
    SetOperad.map (posEquiv n a l m h) (mcompR μ (⟨a, h.1⟩ : Fin n) (Reg.std s) (Reg.std u))
      = Reg.std (mgraftT μ s a u h) := by
  refine reg_ext (map_posEquiv_comp h) ?_
  rw [treeOf_map, treeOf_mcompR]
  show s.1.mgraft μ ((LinOrd.std n).rank ⟨a, h.1⟩) u.1 = s.1.mgraft μ a u.1
  rw [LinOrd.rank_std]

lemma contrR_std {n : ℕ} (t : TreeOfArity T n) (k : ℕ) :
    contrR μ (Reg.std t) k = Reg.std (contrT μ t k) := rfl

lemma ιP_twF {n : ℕ} (x : Pl (T := T) R n) :
    ιP gp R n (twF gp R n x) = GrSpecies.tw (R := R) (V := FreeGr R gp) true (ιP gp R n x) := by
  have h := Lin.induction₁ (S := fun _ _ _ => TreeOfArity T n) (A := Unit)
    (ιP gp R n ∘ₗ twF gp R n) (GrSpecies.tw (R := R) (V := FreeGr R gp) true ∘ₗ ιP gp R n)
    (fun t => ?_) x
  · simpa using h
  show ιP gp R n (twF gp R n (pt t)) = GrSpecies.tw (R := R) (V := FreeGr R gp) true
    (ιP gp R n (pt t))
  rw [twF_pt, map_smul, ιP_pt, tw_bas]
  rfl

lemma ιP_dF {n : ℕ} (x : Pl (T := T) R n) :
    ιP gp R n (dF μ gp R n x) = barD μ gp R (Fin n) (ιP gp R n x) := by
  have h := Lin.induction₁ (S := fun _ _ _ => TreeOfArity T n) (A := Unit)
    (ιP gp R n ∘ₗ dF μ gp R n) (barD μ gp R (Fin n) ∘ₗ ιP gp R n) (fun t => ?_) x
  · simpa using h
  show ιP gp R n (dF μ gp R n (pt t)) = barD μ gp R (Fin n) (ιP gp R n (pt t))
  rw [dF_pt, map_sum, ιP_pt, barD_bas]
  refine Finset.sum_congr rfl fun k _ => ?_
  rw [map_smul, ιP_pt, contrR_std]
  rfl

lemma ιP_gF {a n l m : ℕ} (h : a < n ∧ m + 1 = n + l) (x : Pl (T := T) R n)
    (y : Pl (T := T) R l) :
    ιP gp R m (gF gp R a m x y) = GrOperad.map (R := R) (posEquiv n a l m h)
      (GrOperad.comp (R := R) (⟨a, h.1⟩ : Fin n) (ιP gp R n x) (ιP gp R l y)) := by
  have key : (gF gp R a m (n := n) (l := l)).compr₂ (ιP gp R m)
      = ((GrOperad.comp (R := R) (P := FreeGr R gp) (B := Fin l) (⟨a, h.1⟩ : Fin n)).compr₂
          (GrOperad.map (R := R) (posEquiv n a l m h))).compl₁₂ (ιP gp R n) (ιP gp R l) := by
    refine Finsupp.lhom_ext' fun s => LinearMap.ext_ring
      (Finsupp.lhom_ext' fun u => LinearMap.ext_ring ?_)
    show ιP gp R m (gF gp R a m (pt s) (pt u)) = GrOperad.map (R := R) (posEquiv n a l m h)
      (GrOperad.comp (R := R) (⟨a, h.1⟩ : Fin n) (ιP gp R n (pt s)) (ιP gp R l (pt u)))
    rw [gF_pt_of h, map_smul, ιP_pt, ιP_pt, ιP_pt, comp_bas_eq, map_smul, SgnLin.map_bas,
      map_posEquiv_std_comp]
    congr 1
    show σ R (Tree.tpar gp u.1 && Tree.apar gp s.1 a)
      = σ R (Tree.tpar gp u.1 && Tree.apar gp s.1 ((LinOrd.std n).rank ⟨a, h.1⟩))
    rw [LinOrd.rank_std]
  exact LinearMap.congr_fun (LinearMap.congr_fun key x) y

lemma ιP_mF {a n l m : ℕ} (h : a < n ∧ m + 1 = n + l) (x : Pl (T := T) R n)
    (y : Pl (T := T) R l) :
    ιP gp R m (mF μ gp R a m x y) = GrOperad.map (R := R) (posEquiv n a l m h)
      (mcomp μ gp R (⟨a, h.1⟩ : Fin n) (ιP gp R n x) (ιP gp R l y)) := by
  have key : (mF μ gp R a m (n := n) (l := l)).compr₂ (ιP gp R m)
      = ((mcomp μ gp R (B := Fin l) (⟨a, h.1⟩ : Fin n)).compr₂
          (GrOperad.map (R := R) (posEquiv n a l m h))).compl₁₂ (ιP gp R n) (ιP gp R l) := by
    refine Finsupp.lhom_ext' fun s => LinearMap.ext_ring
      (Finsupp.lhom_ext' fun u => LinearMap.ext_ring ?_)
    show ιP gp R m (mF μ gp R a m (pt s) (pt u)) = GrOperad.map (R := R) (posEquiv n a l m h)
      (mcomp μ gp R (⟨a, h.1⟩ : Fin n) (ιP gp R n (pt s)) (ιP gp R l (pt u)))
    rw [mF_pt, dif_pos h, ιP_pt, ιP_pt, mcomp_bas]
    have hrank : (LinOrd.std n).rank (⟨a, h.1⟩ : Fin n) = a := LinOrd.rank_std n _
    split_ifs with h1 h2 h2
    · rw [map_smul, ιP_pt, map_smul, SgnLin.map_bas, map_posEquiv_std_mcomp]
      congr 1
      show σ R (Tree.mSgn gp s.1 a u.1) = σ R (Tree.mSgn gp s.1 ((LinOrd.std n).rank ⟨a, h.1⟩) u.1)
      rw [hrank]
    · exact absurd h1 h2
    · exact absurd h2 h1
    · rw [map_zero, map_zero]
  exact LinearMap.congr_fun (LinearMap.congr_fun key x) y

variable (μ) in
/-- **The Leibniz rule up to merge-grafting**, for planar trees. -/
theorem dF_gF (hμ : MergeFn.Odd gp μ) (a : ℕ) {n l : ℕ} (m : ℕ) (x : Pl (T := T) R n)
    (y : Pl (T := T) R l) :
    dF μ gp R m (gF gp R a m x y)
      = gF gp R a m (dF μ gp R n x) y + gF gp R a m (twF gp R n x) (dF μ gp R l y)
        + mF μ gp R a m x y := by
  by_cases h : a < n ∧ m + 1 = n + l
  · apply ιP_injective (gp := gp)
    rw [ιP_dF, ιP_gF h, ← map_barD, barD_comp hμ, map_add, map_add, map_add, map_add, ιP_gF h,
      ιP_gF h, ιP_mF h, ιP_dF, ιP_dF, ιP_twF]
  · rw [gF_of_not h, gF_of_not h, gF_of_not h, mF_of_not h, map_zero, add_zero, add_zero]

end Compat

/-! ## The laws of merge-grafting with grafting, at positions -/

section PlanarLaws

variable {μ}

lemma isLeaf_of_lt {n : ℕ} (s : TreeOfArity T n) (h : 1 < n) : s.1.isLeaf = false := by
  by_contra h'
  have hl : s.1.isLeaf = true := by simpa using h'
  have := s.2
  rw [Tree.eq_leaf_of_isLeaf hl, Tree.arity_leaf] at this
  omega

lemma pt_eq {n : ℕ} {s t : TreeOfArity T n} (h : s.1 = t.1) : (pt s : Pl (T := T) R n) = pt t := by
  rw [Subtype.ext h]

/-- **Merging before a graft point.** -/
theorem mF_gF_after {p q q' n lu lv m₁ m₂ m : ℕ} (hpq : p < q) (hq : q < n)
    (hq' : q' + 1 = q + lv) (h₁ : m₁ + 1 = n + lu) (h₂ : m₂ + 1 = n + lv) (hm : m + 1 = m₁ + lv)
    (x : Pl (T := T) R n) (u : TreeOfArity T lu) (v : TreeOfArity T lv) :
    mF μ gp R p m (gF gp R q m₁ x (pt u)) (pt v)
      = σ R (Tree.tpar gp u.1 && Tree.tpar gp v.1) •
          gF gp R q' m (mF μ gp R p m₂ x (pt v)) (pt u) := by
  induction x using Finsupp.induction_linear with
  | zero => simp
  | add x y hx hy => simp only [map_add, LinearMap.add_apply, hx, hy, smul_add]
  | single s c =>
    rw [← Finsupp.smul_single_one s c,
      show (Finsupp.single s (1 : R) : Pl (T := T) R n) = pt s from rfl]
    simp only [map_smul, LinearMap.smul_apply]
    rw [smul_comm]
    congr 1
    have hs := isLeaf_of_lt s (by omega)
    have ha : q < s.1.arity := by rw [s.2]; exact hq
    by_cases hv : v.1.isLeaf = true
    · rw [gF_pt_of ⟨hq, h₁⟩, map_smul, LinearMap.smul_apply, mF_pt_leaf_right _ _ hv,
        mF_pt_leaf_right _ _ hv, map_zero, LinearMap.zero_apply, smul_zero, smul_zero]
    · have hv' : v.1.isLeaf = false := by simpa using hv
      have hG : (graftT s q u ⟨hq, h₁⟩).1.isLeaf = false := Tree.isLeaf_graft_left hs _ _
      have hM : q' < m₂ ∧ m + 1 = m₂ + lu := by omega
      rw [gF_pt_of ⟨hq, h₁⟩, map_smul, LinearMap.smul_apply,
        mF_pt_of (μ := μ) ⟨by omega, hm⟩ hG hv', mF_pt_of (μ := μ) ⟨by omega, h₂⟩ hs hv',
        map_smul, LinearMap.smul_apply, gF_pt_of hM, smul_smul, smul_smul, smul_smul]
      have htree : (mgraftT μ (graftT s q u ⟨hq, h₁⟩) p v ⟨by omega, hm⟩).1
          = (graftT (mgraftT μ s p v ⟨by omega, h₂⟩) q' u hM).1 := by
        simp only [mgraftT_val, graftT_val]
        rw [Tree.graft_mgraft_after μ s.1 p v.1 q u.1 hpq ha, v.2]
        congr 1
        omega
      rw [pt_eq htree]
      congr 1
      simp only [graftT_val, mgraftT_val, ← σ_xor]
      congr 1
      have e := Tree.mSgn_graft_after μ gp (s := s.1) (b := u.1) (u := v.1) hpq ha
      rw [v.2, show q - 1 + lv = q' by omega] at e
      rw [e, Bool.xor_assoc]

/-- **Merging after a graft point.** -/
theorem mF_gF_before (hμ : MergeFn.Odd gp μ) {p p' q n lu lv m₁ m₂ m : ℕ} (hqp : q < p)
    (hp : p < n) (hp' : p' + 1 = p + lu) (h₁ : m₁ + 1 = n + lu) (h₂ : m₂ + 1 = n + lv)
    (hm : m + 1 = m₁ + lv) (x : Pl (T := T) R n) (u : TreeOfArity T lu) (v : TreeOfArity T lv) :
    mF μ gp R p' m (gF gp R q m₁ x (pt u)) (pt v)
      = σ R (Tree.tpar gp u.1 && Tree.tpar gp v.1) •
          gF gp R q m (mF μ gp R p m₂ x (pt v)) (pt u) := by
  induction x using Finsupp.induction_linear with
  | zero => simp
  | add x y hx hy => simp only [map_add, LinearMap.add_apply, hx, hy, smul_add]
  | single s c =>
    rw [← Finsupp.smul_single_one s c,
      show (Finsupp.single s (1 : R) : Pl (T := T) R n) = pt s from rfl]
    simp only [map_smul, LinearMap.smul_apply]
    rw [smul_comm]
    congr 1
    have hs := isLeaf_of_lt s (by omega)
    have ha : p < s.1.arity := by rw [s.2]; exact hp
    by_cases hv : v.1.isLeaf = true
    · rw [gF_pt_of ⟨by omega, h₁⟩, map_smul, LinearMap.smul_apply, mF_pt_leaf_right _ _ hv,
        mF_pt_leaf_right _ _ hv, map_zero, LinearMap.zero_apply, smul_zero, smul_zero]
    · have hv' : v.1.isLeaf = false := by simpa using hv
      have hG : (graftT s q u ⟨by omega, h₁⟩).1.isLeaf = false := Tree.isLeaf_graft_left hs _ _
      have hM : q < m₂ ∧ m + 1 = m₂ + lu := by omega
      rw [gF_pt_of ⟨by omega, h₁⟩, map_smul, LinearMap.smul_apply,
        mF_pt_of (μ := μ) ⟨by omega, hm⟩ hG hv', mF_pt_of (μ := μ) ⟨hp, h₂⟩ hs hv',
        map_smul, LinearMap.smul_apply, gF_pt_of hM, smul_smul, smul_smul, smul_smul]
      have htree : (mgraftT μ (graftT s q u ⟨by omega, h₁⟩) p' v ⟨by omega, hm⟩).1
          = (graftT (mgraftT μ s p v ⟨hp, h₂⟩) q u hM).1 := by
        simp only [mgraftT_val, graftT_val]
        rw [← Tree.graft_mgraft_before μ s.1 q u.1 p v.1 hqp ha, u.2]
        congr 1
        omega
      rw [pt_eq htree]
      congr 1
      simp only [graftT_val, mgraftT_val, ← σ_xor]
      congr 1
      have e := Tree.mSgn_graft_before μ gp hμ (s := s.1) (b := u.1) (u := v.1) hqp ha hv'
      rw [u.2, show p - 1 + lu = p' by omega] at e
      rw [e, Bool.xor_assoc]

/-- **Merging into a grafted tree.** -/
theorem mF_gF_inner (hμ : MergeFn.Odd gp μ) {p q r n lu lv m₁ m₂ m : ℕ} (hq : q < n)
    (hr : r < lu) (hp : p = q + r) (h₁ : m₁ + 1 = n + lu) (h₂ : m₂ + 1 = lu + lv)
    (hm : m + 1 = m₁ + lv) (x : Pl (T := T) R n) {u : TreeOfArity T lu} (hu : u.1.isLeaf = false)
    (v : TreeOfArity T lv) :
    mF μ gp R p m (gF gp R q m₁ x (pt u)) (pt v)
      = gF gp R q m (twF gp R n x) (mF μ gp R r m₂ (pt u) (pt v)) := by
  subst hp
  induction x using Finsupp.induction_linear with
  | zero => simp
  | add x y hx hy => simp only [map_add, LinearMap.add_apply, hx, hy]
  | single s c =>
    rw [← Finsupp.smul_single_one s c,
      show (Finsupp.single s (1 : R) : Pl (T := T) R n) = pt s from rfl]
    simp only [map_smul, LinearMap.smul_apply]
    congr 1
    have ha : q < s.1.arity := by rw [s.2]; exact hq
    by_cases hv : v.1.isLeaf = true
    · rw [gF_pt_of ⟨hq, h₁⟩, map_smul, LinearMap.smul_apply, mF_pt_leaf_right _ _ hv,
        mF_pt_leaf_right _ _ hv, map_zero, smul_zero]
    · have hv' : v.1.isLeaf = false := by simpa using hv
      have hG : (graftT s q u ⟨hq, h₁⟩).1.isLeaf = false := Tree.isLeaf_graft hu
      have hM : q < n ∧ m + 1 = n + m₂ := by omega
      rw [gF_pt_of ⟨hq, h₁⟩, map_smul, LinearMap.smul_apply,
        mF_pt_of (μ := μ) ⟨by omega, hm⟩ hG hv', mF_pt_of (μ := μ) ⟨hr, h₂⟩ hu hv', twF_pt,
        map_smul, map_smul, LinearMap.smul_apply, gF_pt_of hM, smul_smul, smul_smul, smul_smul]
      have htree : (mgraftT μ (graftT s q u ⟨hq, h₁⟩) (q + r) v ⟨by omega, hm⟩).1
          = (graftT s q (mgraftT μ u r v ⟨hr, h₂⟩) hM).1 := by
        simp only [mgraftT_val, graftT_val]
        exact Tree.mgraft_graft_inner μ s.1 q u.1 r v.1 ha (by rw [u.2]; exact hr) hu
      rw [pt_eq htree]
      congr 1
      simp only [graftT_val, mgraftT_val, ← σ_xor]
      congr 1
      rw [Tree.mSgn_graft_inner μ gp hμ ha (by rw [u.2]; exact hr) hu hv']
      cases Tree.tpar gp s.1 <;> cases Tree.mSgn gp u.1 r v.1 <;>
        cases Tree.tpar gp (Tree.mgraft μ u.1 r v.1) && Tree.apar gp s.1 q <;> rfl

/-- **Merging corollas.** -/
theorem mF_corolla {a k l m : ℕ} (h : a < k ∧ m + 1 = k + l) (g : T k) (c : T l) :
    mF μ gp R a m (pt (corolla g)) (pt (corolla c)) = pt (corolla (μ k l g a c m)) := by
  rw [mF_pt_of (μ := μ) h rfl rfl]
  have hs : Tree.mSgn gp (corolla g).1 a (corolla c).1 = false := mSgn_corolla gp g c h.1
  rw [hs, σ_false, one_smul]
  refine pt_eq ?_
  show (Tree.node g (TreeOfArity.leaves k)).mgraft μ a (Tree.node c (TreeOfArity.leaves l))
    = Tree.node (μ k l g a c m) (TreeOfArity.leaves m)
  rw [corolla_mgraft μ g c h.1]
  have : Forest.spliceLen k a l = m := by have := spliceLen_eq (k := k) (j := a) l h.1; omega
  rw [this]

lemma dF_corolla {k : ℕ} (g : T k) : dF μ gp R k (pt (corolla g)) = 0 := by
  rw [dF_pt]
  have : (corolla g).1.weight = 1 := by
    show (Tree.node g (TreeOfArity.leaves k)).weight = 1
    rw [Tree.weight_node, weightF_leaves]
  rw [this, Finset.Ico_self, Finset.sum_empty]

lemma twF_twF {n : ℕ} (x : Pl (T := T) R n) : twF gp R n (twF gp R n x) = x := by
  induction x using Finsupp.induction_linear with
  | zero => simp
  | add x y hx hy => rw [map_add, map_add, hx, hy]
  | single s c =>
    rw [← Finsupp.smul_single_one s c,
      show (Finsupp.single s (1 : R) : Pl (T := T) R n) = pt s from rfl, map_smul, map_smul,
      twF_pt, map_smul, twF_pt, smul_smul, smul_smul, mul_assoc, σ_mul_self, mul_one]

lemma dF_twF (hμ : MergeFn.Odd gp μ) {n : ℕ} (x : Pl (T := T) R n) :
    dF μ gp R n (twF gp R n x) = -twF gp R n (dF μ gp R n x) := by
  induction x using Finsupp.induction_linear with
  | zero => simp
  | add x y hx hy => rw [map_add, map_add, hx, hy, map_add, map_add, neg_add]
  | single s c =>
    rw [← Finsupp.smul_single_one s c,
      show (Finsupp.single s (1 : R) : Pl (T := T) R n) = pt s from rfl, map_smul, map_smul,
      map_smul, map_smul, ← smul_neg]
    congr 1
    rw [twF_pt, map_smul, dF_pt, map_sum, Finset.smul_sum, ← Finset.sum_neg_distrib]
    refine Finset.sum_congr rfl fun k hk => ?_
    rw [Finset.mem_Ico] at hk
    rw [map_smul, twF_pt, contrT_val, Tree.tpar_contr μ gp hμ hk.1 hk.2, smul_smul, smul_smul,
      ← neg_smul]
    congr 1
    cases Tree.tpar gp s.1 <;> simp [mul_comm]

lemma twF_mF_pt (hμ : MergeFn.Odd gp μ) (a : ℕ) {n l m : ℕ} (s : TreeOfArity T n)
    (u : TreeOfArity T l) :
    twF gp R m (mF μ gp R a m (pt s) (pt u))
      = -(σ R (Tree.tpar gp s.1) * σ R (Tree.tpar gp u.1)) • mF μ gp R a m (pt s) (pt u) := by
  rw [mF_pt]
  split_ifs with h1 h2
  · rw [map_smul, twF_pt, mgraftT_val, Tree.tpar_mgraft μ gp hμ _ _ _
      (by rw [s.2]; exact h1.1) h2.1 h2.2, smul_smul, smul_smul]
    congr 1
    cases Tree.tpar gp s.1 <;> cases Tree.tpar gp u.1 <;> simp
  · simp
  · simp

lemma twF_mF (hμ : MergeFn.Odd gp μ) (a : ℕ) {n l m : ℕ} (x : Pl (T := T) R n)
    (y : Pl (T := T) R l) :
    twF gp R m (mF μ gp R a m x y) = -mF μ gp R a m (twF gp R n x) (twF gp R l y) := by
  induction x using Finsupp.induction_linear with
  | zero => simp
  | add x x' hx hx' => simp only [map_add, LinearMap.add_apply, hx, hx', neg_add]
  | single s c =>
    induction y using Finsupp.induction_linear with
    | zero => simp
    | add y y' hy hy' => simp only [map_add, hy, hy', neg_add]
    | single u d =>
      rw [← Finsupp.smul_single_one s c, ← Finsupp.smul_single_one u d,
        show (Finsupp.single s (1 : R) : Pl (T := T) R n) = pt s from rfl,
        show (Finsupp.single u (1 : R) : Pl (T := T) R l) = pt u from rfl]
      simp only [map_smul, LinearMap.smul_apply, twF_pt]
      rw [twF_mF_pt hμ]
      module

lemma twF_gF (a : ℕ) {n l m : ℕ} (x : Pl (T := T) R n) (y : Pl (T := T) R l) :
    twF gp R m (gF gp R a m x y) = gF gp R a m (twF gp R n x) (twF gp R l y) := by
  induction x using Finsupp.induction_linear with
  | zero => simp
  | add x x' hx hx' => simp only [map_add, LinearMap.add_apply, hx, hx']
  | single s c =>
    induction y using Finsupp.induction_linear with
    | zero => simp
    | add y y' hy hy' => simp only [map_add, hy, hy']
    | single u d =>
      rw [← Finsupp.smul_single_one s c, ← Finsupp.smul_single_one u d,
        show (Finsupp.single s (1 : R) : Pl (T := T) R n) = pt s from rfl,
        show (Finsupp.single u (1 : R) : Pl (T := T) R l) = pt u from rfl]
      simp only [map_smul, LinearMap.smul_apply, twF_pt]
      rw [gF_pt]
      split_ifs with h
      · rw [map_smul, twF_pt, graftT_val, Tree.tpar_graft gp _ _ _ (by rw [s.2]; exact h.1),
          σ_xor]
        module
      · simp

end PlanarLaws

/-! ## The last vertex of a tree -/

section LastVertex

lemma eq_leaves_of_weightF : ∀ {k : ℕ} (f : Forest T k), f.weightF = 0 →
    f = TreeOfArity.leaves k
  | 0, .nil, _ => rfl
  | _, .cons t f, h => by
    simp only [Tree.weightF_cons] at h
    have ht : t.weight = 0 := by omega
    have hf := eq_leaves_of_weightF f (by omega)
    cases t with
    | leaf =>
      rw [hf]
      rfl
    | node e g => simp at ht

/-- A tree with one vertex is a corolla. -/
lemma eq_corolla_of_weight {t : Tree T} (h : t.weight = 1) :
    ∃ (k : ℕ) (g : T k), t = Tree.node g (TreeOfArity.leaves k) := by
  cases t with
  | leaf => simp at h
  | node g f =>
    simp only [Tree.weight_node] at h
    exact ⟨_, g, by rw [eq_leaves_of_weightF f (by omega)]⟩

/-- **A tree with at least two vertices is a tree with one vertex less, grafted with the corolla
of its last vertex.** -/
lemma exists_graft_corolla {t : Tree T} (h : 2 ≤ t.weight) :
    ∃ (s : Tree T) (p k : ℕ) (g : T k), p < s.arity ∧ s.weight + 1 = t.weight ∧
      t = s.graft p (Tree.node g (TreeOfArity.leaves k)) := by
  obtain ⟨h1, h2, h3, h4⟩ := Tree.cutV_spec (t := t) (k := t.weight - 1) (by omega) rfl
  set s := (t.cutV (t.weight - 1)).1
  set u := (t.cutV (t.weight - 1)).2.1
  set p := (t.cutV (t.weight - 1)).2.2
  have hw := Tree.weight_graft s p u h2
  rw [h1] at hw
  have hv := Tree.vb_le_weight s p
  have hu := Tree.weight_pos h4
  obtain ⟨k, g, hg⟩ := eq_corolla_of_weight (t := u) (by omega)
  exact ⟨s, p, k, g, h2, by omega, by rw [← hg, h1]⟩

end LastVertex

/-! ## Membership in an ideal -/

section Ideal

variable {μ} (J : GrOperadIdeal R (FreeGr R gp))

/-- The planar combinations landing in an ideal. -/
noncomputable def JF (n : ℕ) : Submodule R (Pl (T := T) R n) := (J.sub (Fin n)).comap (ιP gp R n)

variable {J}

lemma gF_mem_left {a n l m : ℕ} {x : Pl (T := T) R n} (hx : x ∈ JF J n) (y : Pl (T := T) R l) :
    gF gp R a m x y ∈ JF J m := by
  by_cases h : a < n ∧ m + 1 = n + l
  · show ιP gp R m (gF gp R a m x y) ∈ J.sub (Fin m)
    rw [ιP_gF h]
    exact J.map_mem _ (J.comp_mem_left _ _ hx)
  · rw [gF_of_not h]
    exact zero_mem _

lemma gF_mem_right {a n l m : ℕ} (x : Pl (T := T) R n) {y : Pl (T := T) R l} (hy : y ∈ JF J l) :
    gF gp R a m x y ∈ JF J m := by
  by_cases h : a < n ∧ m + 1 = n + l
  · show ιP gp R m (gF gp R a m x y) ∈ J.sub (Fin m)
    rw [ιP_gF h]
    exact J.map_mem _ (J.comp_mem_right _ _ hy)
  · rw [gF_of_not h]
    exact zero_mem _

lemma ιP_corolla {k : ℕ} (g : T k) :
    ιP gp R k (pt (corolla g)) = gen (R := R) (gp := gp) g := ιP_pt _

variable (μ gp R) in
/-- **Associativity of the merge function modulo an ideal**, for merges in series and in
parallel. -/
structure AssocHyp (J : GrOperadIdeal R (FreeGr R gp)) : Prop where
  series : ∀ (kx lg lh : ℕ) (x : T kx) (g : T lg) (h : T lh) (p j m₁ m₂ m : ℕ), p < kx →
    j < lg → m₁ + 1 = lg + lh → m₂ + 1 = kx + lg → m + 1 = kx + m₁ →
    σ R (gp kx x) • gen (R := R) (gp := gp) (μ kx m₁ x p (μ lg lh g j h m₁) m)
      + gen (R := R) (gp := gp) (μ m₂ lh (μ kx lg x p g m₂) (p + j) h m) ∈ J.sub (Fin m)
  parallel : ∀ (kx l₁ l₂ : ℕ) (x : T kx) (a₁ : T l₁) (a₂ : T l₂) (p₁ p₂ p₂' m₁ m₂ m : ℕ),
    p₁ < p₂ → p₂ < kx → p₂' + 1 = p₂ + l₁ → m₁ + 1 = kx + l₁ → m₂ + 1 = kx + l₂ →
    m + 1 = m₁ + l₂ →
    σ R (gp l₁ a₁ && gp l₂ a₂) •
        gen (R := R) (gp := gp) (μ m₁ l₂ (μ kx l₁ x p₁ a₁ m₁) p₂' a₂ m)
      + gen (R := R) (gp := gp) (μ m₂ l₁ (μ kx l₂ x p₂ a₂ m₂) p₁ a₁ m) ∈ J.sub (Fin m)

end Ideal

/-! ## Merging two corollas in series -/

section Series

variable {μ}

variable (μ gp R) in
/-- **Merging two corollas in series**, in the two orders. -/
noncomputable def SF (p j m₁ m₂ m : ℕ) {n lg lh : ℕ} (x : Pl (T := T) R n) (g : TreeOfArity T lg)
    (h : TreeOfArity T lh) : Pl (T := T) R m :=
  mF μ gp R p m (twF gp R n x) (mF μ gp R j m₁ (pt g) (pt h))
    + mF μ gp R (p + j) m (mF μ gp R p m₂ x (pt g)) (pt h)

lemma SF_smul (p j m₁ m₂ m : ℕ) {n lg lh : ℕ} (c : R) (x : Pl (T := T) R n)
    (g : TreeOfArity T lg) (h : TreeOfArity T lh) :
    SF μ gp R p j m₁ m₂ m (c • x) g h = c • SF μ gp R p j m₁ m₂ m x g h := by
  simp only [SF, map_smul, LinearMap.smul_apply, smul_add]

lemma twF_gF_pt (a : ℕ) {n l m : ℕ} (x : Pl (T := T) R n) (c : TreeOfArity T l) :
    twF gp R m (gF gp R a m x (pt c))
      = σ R (Tree.tpar gp c.1) • gF gp R a m (twF gp R n x) (pt c) := by
  rw [twF_gF, twF_pt, map_smul]

lemma tpar_corolla' {k : ℕ} (g : T k) : Tree.tpar gp (corolla g).1 = gp k g :=
  Tree.tpar_corolla gp g

lemma isLeaf_corolla {k : ℕ} (g : T k) : (corolla g).1.isLeaf = false := rfl

lemma σ_and_not_xor (a b c : Bool) :
    σ R a * σ R (a && !(xor b c)) = σ R (a && xor b c) := by
  cases a <;> cases b <;> cases c <;> simp

lemma σ_and_and (a b c : Bool) :
    σ R (a && b) * σ R (a && c) = σ R (a && xor b c) := by
  cases a <;> cases b <;> cases c <;> simp

/-- Merging in series at a leaf before a graft point. -/
theorem SF_gF_after (hμ : MergeFn.Odd gp μ) {p j r r' n n₁ lc lg lh m₁ m₂ m mA mB : ℕ}
    (hpr : p < r) (hr : r < n₁) (hn : n + 1 = n₁ + lc) (hj : j < lg) (hm₁ : m₁ + 1 = lg + lh)
    (hm₂ : m₂ + 1 = n + lg) (hm : m + 1 = n + m₁) (hr' : r' + 1 = r + m₁)
    (hmA : mA + 1 = n₁ + m₁) (hmB : mB + 1 = n₁ + lg) (X : Pl (T := T) R n₁) (c : T lc)
    (g : T lg) (h : T lh) :
    SF μ gp R p j m₁ m₂ m (gF gp R r n X (pt (corolla c))) (corolla g) (corolla h)
      = σ R (gp lc c && xor (gp lg g) (gp lh h)) •
          gF gp R r' m (SF μ gp R p j m₁ mB mA X (corolla g) (corolla h)) (pt (corolla c)) := by
  have hY := mF_corolla (μ := μ) (gp := gp) (R := R) ⟨hj, hm₁⟩ g h
  obtain ⟨rB, hrB⟩ : ∃ rB, rB + 1 = r + lg := ⟨r + lg - 1, by omega⟩
  unfold SF
  rw [twF_gF_pt, hY, map_smul, LinearMap.smul_apply,
    mF_gF_after (μ := μ) hpr hr hr' hn hmA hm _ (corolla c) (corolla (μ lg lh g j h m₁)),
    mF_gF_after (μ := μ) hpr hr hrB hn hmB hm₂ X (corolla c) (corolla g), map_smul,
    LinearMap.smul_apply,
    mF_gF_after (μ := μ) (show p + j < rB by omega) (show rB < mB by omega)
      (show r' + 1 = rB + lh by omega) (show m₂ + 1 = mB + lc by omega)
      (show mA + 1 = mB + lh by omega) (show m + 1 = m₂ + lh by omega) _ (corolla c) (corolla h),
    map_add, LinearMap.add_apply, smul_add]
  simp only [tpar_corolla', hμ, smul_smul, σ_and_not_xor, σ_and_and]

/-- Merging in series at a leaf of the grafted corolla. -/
theorem SF_gF_inner (hμ : MergeFn.Odd gp μ) {p p' j r n n₁ lc lg lh m₁ m₂ m mD mE : ℕ}
    (hr : r < n₁) (hp : p = r + p') (hp' : p' < lc) (hn : n + 1 = n₁ + lc) (hj : j < lg)
    (hm₁ : m₁ + 1 = lg + lh) (hm₂ : m₂ + 1 = n + lg) (hm : m + 1 = n + m₁)
    (hmD : mD + 1 = lc + lg) (hmE : mE + 1 = lc + m₁) (X : Pl (T := T) R n₁) (c : T lc)
    (g : T lg) (h : T lh) :
    SF μ gp R p j m₁ m₂ m (gF gp R r n X (pt (corolla c))) (corolla g) (corolla h)
      = gF gp R r m X (SF μ gp R p' j m₁ mD mE (pt (corolla c)) (corolla g) (corolla h)) := by
  have hY := mF_corolla (μ := μ) (gp := gp) (R := R) ⟨hj, hm₁⟩ g h
  have hW := mF_corolla (μ := μ) (gp := gp) (R := R) ⟨hp', hmD⟩ c g
  unfold SF
  rw [twF_gF_pt, hY, map_smul, LinearMap.smul_apply,
    mF_gF_inner (μ := μ) hμ hr hp' hp hn hmE hm _ (isLeaf_corolla c) (corolla (μ lg lh g j h m₁)),
    twF_twF, mF_gF_inner (μ := μ) hμ hr hp' hp hn hmD hm₂ X (isLeaf_corolla c) (corolla g), hW,
    mF_gF_inner (μ := μ) hμ hr (show p' + j < mD by omega) (show p + j = r + (p' + j) by omega)
      (show m₂ + 1 = n₁ + mD by omega) (show mE + 1 = mD + lh by omega)
      (show m + 1 = m₂ + lh by omega) _ (isLeaf_corolla _) (corolla h),
    twF_twF, twF_pt, map_smul, LinearMap.smul_apply, map_add, map_smul]

/-- Merging in series at a leaf after a graft point. -/
theorem SF_gF_before (hμ : MergeFn.Odd gp μ) {p p₁ j r n n₁ lc lg lh m₁ m₂ m mA mB : ℕ}
    (hrp : r < p₁) (hp₁ : p₁ < n₁) (hp : p + 1 = p₁ + lc) (hn : n + 1 = n₁ + lc) (hj : j < lg)
    (hm₁ : m₁ + 1 = lg + lh) (hm₂ : m₂ + 1 = n + lg) (hm : m + 1 = n + m₁)
    (hmA : mA + 1 = n₁ + m₁) (hmB : mB + 1 = n₁ + lg) (X : Pl (T := T) R n₁) (c : T lc)
    (g : T lg) (h : T lh) :
    SF μ gp R p j m₁ m₂ m (gF gp R r n X (pt (corolla c))) (corolla g) (corolla h)
      = σ R (gp lc c && xor (gp lg g) (gp lh h)) •
          gF gp R r m (SF μ gp R p₁ j m₁ mB mA X (corolla g) (corolla h)) (pt (corolla c)) := by
  have hY := mF_corolla (μ := μ) (gp := gp) (R := R) ⟨hj, hm₁⟩ g h
  unfold SF
  rw [twF_gF_pt, hY, map_smul, LinearMap.smul_apply,
    mF_gF_before (μ := μ) hμ hrp hp₁ hp hn hmA hm _ (corolla c) (corolla (μ lg lh g j h m₁)),
    mF_gF_before (μ := μ) hμ hrp hp₁ hp hn hmB hm₂ X (corolla c) (corolla g), map_smul,
    LinearMap.smul_apply,
    mF_gF_before (μ := μ) hμ (show r < p₁ + j by omega) (show p₁ + j < mB by omega)
      (show p + j + 1 = p₁ + j + lc by omega) (show m₂ + 1 = mB + lc by omega)
      (show mA + 1 = mB + lh by omega) (show m + 1 = m₂ + lh by omega) _ (corolla c) (corolla h),
    map_add, LinearMap.add_apply, smul_add]
  simp only [tpar_corolla', hμ, smul_smul, σ_and_not_xor, σ_and_and]

/-- A planar tree with at least two vertices, as a graft with the corolla of its last vertex. -/
lemma pt_eq_gF {n : ℕ} (s : TreeOfArity T n) (h2 : 2 ≤ s.1.weight) :
    ∃ (n₁ r lc : ℕ) (s₁ : TreeOfArity T n₁) (c : T lc), r < n₁ ∧ n + 1 = n₁ + lc ∧
      s₁.1.weight + 1 = s.1.weight ∧
      (pt s : Pl (T := T) R n) = σ R (gp lc c && Tree.apar gp s₁.1 r) •
        gF gp R r n (pt s₁) (pt (corolla c)) := by
  obtain ⟨s₁, r, lc, c, hr, hw, hs⟩ := exists_graft_corolla h2
  have hn : n + 1 = s₁.arity + lc := by
    have h1 := Tree.arity_graft s₁ r (Tree.node c (TreeOfArity.leaves lc)) hr
    rw [← hs, s.2, Tree.arity_node, arityF_leaves] at h1
    omega
  refine ⟨s₁.arity, r, lc, ⟨s₁, rfl⟩, c, hr, hn, hw, ?_⟩
  rw [gF_pt_of ⟨hr, hn⟩, smul_smul, ← tpar_corolla' (gp := gp) c, σ_mul_self, one_smul]
  exact pt_eq (by rw [graftT_val]; exact hs)

variable (J : GrOperadIdeal R (FreeGr R gp))

/-- **Merging two corollas in series into a planar tree lands in the ideal.** -/
theorem SF_mem (hμ : MergeFn.Odd gp μ) (hA : AssocHyp μ gp R J) : ∀ (w n : ℕ)
    (s : TreeOfArity T n), s.1.weight ≤ w → ∀ {lg lh : ℕ} (g : T lg) (h : T lh)
    (p j m₁ m₂ m : ℕ), p < n → j < lg → m₁ + 1 = lg + lh → m₂ + 1 = n + lg → m + 1 = n + m₁ →
      SF μ gp R p j m₁ m₂ m (pt s) (corolla g) (corolla h) ∈ JF J m := by
  intro w
  induction w with
  | zero =>
    intro n s hw lg lh g h p j m₁ m₂ m hp hj hm₁ hm₂ hm
    have hl : s.1.isLeaf = true := by
      cases hs : s.1 with
      | leaf => rfl
      | node e f => rw [hs] at hw; simp at hw
    unfold SF
    rw [mF_corolla (μ := μ) ⟨hj, hm₁⟩, twF_pt, map_smul, LinearMap.smul_apply,
      mF_pt_leaf_left _ hl, mF_pt_leaf_left _ hl, map_zero, LinearMap.zero_apply, smul_zero,
      add_zero]
    exact zero_mem _
  | succ w ih =>
    intro n s hw lg lh g h p j m₁ m₂ m hp hj hm₁ hm₂ hm
    rcases Nat.lt_or_ge s.1.weight 2 with hw2 | hw2
    · by_cases hw0 : s.1.weight = 0
      · exact ih n s (by omega) g h p j m₁ m₂ m hp hj hm₁ hm₂ hm
      · -- a corolla
        obtain ⟨k, x, hx⟩ := eq_corolla_of_weight (t := s.1) (by omega)
        have hk : k = n := by
          have := s.2
          rw [hx, Tree.arity_node, arityF_leaves] at this
          exact this
        subst hk
        have hs : s = corolla x := Subtype.ext hx
        subst hs
        unfold SF
        rw [mF_corolla (μ := μ) ⟨hj, hm₁⟩, twF_pt, map_smul, LinearMap.smul_apply,
          mF_corolla (μ := μ) ⟨hp, hm⟩, mF_corolla (μ := μ) ⟨hp, hm₂⟩,
          mF_corolla (μ := μ) ⟨by omega, by omega⟩, tpar_corolla']
        show ιP gp R m _ ∈ J.sub (Fin m)
        rw [map_add, map_smul, ιP_corolla, ιP_corolla]
        exact hA.series _ _ _ x g h p j m₁ m₂ m hp hj hm₁ hm₂ hm
    · obtain ⟨n₁, r, lc, s₁, c, hr, hn, hw₁, hs⟩ := pt_eq_gF (R := R) (gp := gp) s hw2
      rw [hs, SF_smul]
      refine Submodule.smul_mem _ _ ?_
      rcases Nat.lt_or_ge p r with hpr | hpr
      · obtain ⟨r', hr'⟩ : ∃ r', r' + 1 = r + m₁ := ⟨r + m₁ - 1, by omega⟩
        obtain ⟨mA, hmA⟩ : ∃ mA, mA + 1 = n₁ + m₁ := ⟨n₁ + m₁ - 1, by omega⟩
        obtain ⟨mB, hmB⟩ : ∃ mB, mB + 1 = n₁ + lg := ⟨n₁ + lg - 1, by omega⟩
        rw [SF_gF_after (μ := μ) hμ hpr hr hn hj hm₁ hm₂ hm hr' hmA hmB]
        exact Submodule.smul_mem _ _ (gF_mem_left
          (ih n₁ s₁ (by omega) g h p j m₁ mB mA (by omega) hj hm₁ hmB hmA) _)
      · rcases Nat.lt_or_ge p (r + lc) with hpc | hpc
        · obtain ⟨mD, hmD⟩ : ∃ mD, mD + 1 = lc + lg := ⟨lc + lg - 1, by omega⟩
          obtain ⟨mE, hmE⟩ : ∃ mE, mE + 1 = lc + m₁ := ⟨lc + m₁ - 1, by omega⟩
          rw [SF_gF_inner (μ := μ) hμ hr (show p = r + (p - r) by omega) (show p - r < lc by omega)
            hn hj hm₁ hm₂ hm hmD hmE]
          refine gF_mem_right _ (ih lc (corolla c) ?_ g h (p - r) j m₁ mD mE (by omega) hj hm₁
            hmD hmE)
          show (Tree.node c (TreeOfArity.leaves lc)).weight ≤ w
          rw [Tree.weight_node, weightF_leaves]
          omega
        · obtain ⟨mA, hmA⟩ : ∃ mA, mA + 1 = n₁ + m₁ := ⟨n₁ + m₁ - 1, by omega⟩
          obtain ⟨mB, hmB⟩ : ∃ mB, mB + 1 = n₁ + lg := ⟨n₁ + lg - 1, by omega⟩
          rw [SF_gF_before (μ := μ) hμ (show r < p + 1 - lc by omega)
            (show p + 1 - lc < n₁ by omega) (show p + 1 = (p + 1 - lc) + lc by omega) hn hj hm₁
            hm₂ hm hmA hmB]
          exact Submodule.smul_mem _ _ (gF_mem_left
            (ih n₁ s₁ (by omega) g h (p + 1 - lc) j m₁ mB mA (by omega) hj hm₁ hmB hmA) _)

end Series

/-! ## Merging two corollas in parallel -/

section Parallel

variable {μ}

variable (μ gp R) in
/-- **Merging two corollas at two leaves**, in the two orders. -/
noncomputable def PF (p₁ p₂ p₂' m₁ m₂ m : ℕ) {n l₁ l₂ : ℕ} (x : Pl (T := T) R n)
    (a₁ : TreeOfArity T l₁) (a₂ : TreeOfArity T l₂) : Pl (T := T) R m :=
  σ R (Tree.tpar gp a₁.1 && Tree.tpar gp a₂.1) •
      mF μ gp R p₂' m (mF μ gp R p₁ m₁ x (pt a₁)) (pt a₂)
    + mF μ gp R p₁ m (mF μ gp R p₂ m₂ x (pt a₂)) (pt a₁)

lemma PF_smul (p₁ p₂ p₂' m₁ m₂ m : ℕ) {n l₁ l₂ : ℕ} (c : R) (x : Pl (T := T) R n)
    (a₁ : TreeOfArity T l₁) (a₂ : TreeOfArity T l₂) :
    PF μ gp R p₁ p₂ p₂' m₁ m₂ m (c • x) a₁ a₂ = c • PF μ gp R p₁ p₂ p₂' m₁ m₂ m x a₁ a₂ := by
  simp only [PF, map_smul, LinearMap.smul_apply, smul_add, smul_comm c]

/-- Merging in parallel at two leaves before a graft point. -/
theorem PF_gF_before_before {p₁ p₂ p₂' r n n₁ lc l₁ l₂ m₁ m₂ m r₁ r₂ r₁₂ mA mB mC : ℕ}
    (h12 : p₁ < p₂) (h2r : p₂ < r) (hr : r < n₁) (hn : n + 1 = n₁ + lc)
    (hp₂' : p₂' + 1 = p₂ + l₁) (hm₁ : m₁ + 1 = n + l₁) (hm₂ : m₂ + 1 = n + l₂)
    (hm : m + 1 = m₁ + l₂) (hr₁ : r₁ + 1 = r + l₁) (hr₂ : r₂ + 1 = r + l₂)
    (hr₁₂ : r₁₂ + 1 = r₁ + l₂) (hmA : mA + 1 = n₁ + l₁) (hmB : mB + 1 = n₁ + l₂)
    (hmC : mC + 1 = mA + l₂) (X : Pl (T := T) R n₁) (c : T lc) (a₁ : T l₁) (a₂ : T l₂) :
    PF μ gp R p₁ p₂ p₂' m₁ m₂ m (gF gp R r n X (pt (corolla c))) (corolla a₁) (corolla a₂)
      = (σ R (gp lc c && gp l₁ a₁) * σ R (gp lc c && gp l₂ a₂)) •
          gF gp R r₁₂ m (PF μ gp R p₁ p₂ p₂' mA mB mC X (corolla a₁) (corolla a₂))
            (pt (corolla c)) := by
  unfold PF
  rw [mF_gF_after (μ := μ) (by omega) hr hr₁ hn hmA hm₁ X (corolla c) (corolla a₁), map_smul,
    LinearMap.smul_apply,
    mF_gF_after (μ := μ) (show p₂' < r₁ by omega) (show r₁ < mA by omega) hr₁₂
      (show m₁ + 1 = mA + lc by omega) hmC (show m + 1 = m₁ + l₂ by omega) _ (corolla c)
      (corolla a₂),
    mF_gF_after (μ := μ) h2r hr hr₂ hn hmB hm₂ X (corolla c) (corolla a₂), map_smul,
    LinearMap.smul_apply,
    mF_gF_after (μ := μ) (show p₁ < r₂ by omega) (show r₂ < mB by omega)
      (show r₁₂ + 1 = r₂ + l₁ by omega) (show m₂ + 1 = mB + lc by omega)
      (show mC + 1 = mB + l₁ by omega) (show m + 1 = m₂ + l₁ by omega) _ (corolla c)
      (corolla a₁)]
  simp only [tpar_corolla', map_add, map_smul, LinearMap.add_apply, LinearMap.smul_apply,
    smul_add, smul_smul]
  congr 1
  · ring_nf
  · ring_nf

/-- Merging in parallel at two leaves after a graft point. -/
theorem PF_gF_after_after (hμ : MergeFn.Odd gp μ)
    {p₁ p₂ p₂' q₁ q₂ q₂' r n n₁ lc l₁ l₂ m₁ m₂ m mA mB mC : ℕ}
    (h12 : q₁ < q₂) (hrq : r < q₁) (hq₂ : q₂ < n₁) (hn : n + 1 = n₁ + lc)
    (hp₁ : p₁ + 1 = q₁ + lc) (hp₂ : p₂ + 1 = q₂ + lc) (hp₂' : p₂' + 1 = p₂ + l₁)
    (hq₂' : q₂' + 1 = q₂ + l₁) (hm₁ : m₁ + 1 = n + l₁) (hm₂ : m₂ + 1 = n + l₂)
    (hm : m + 1 = m₁ + l₂) (hmA : mA + 1 = n₁ + l₁) (hmB : mB + 1 = n₁ + l₂)
    (hmC : mC + 1 = mA + l₂) (X : Pl (T := T) R n₁) (c : T lc) (a₁ : T l₁) (a₂ : T l₂) :
    PF μ gp R p₁ p₂ p₂' m₁ m₂ m (gF gp R r n X (pt (corolla c))) (corolla a₁) (corolla a₂)
      = (σ R (gp lc c && gp l₁ a₁) * σ R (gp lc c && gp l₂ a₂)) •
          gF gp R r m (PF μ gp R q₁ q₂ q₂' mA mB mC X (corolla a₁) (corolla a₂))
            (pt (corolla c)) := by
  unfold PF
  rw [mF_gF_before (μ := μ) hμ hrq (by omega) hp₁ hn hmA hm₁ X (corolla c) (corolla a₁),
    map_smul, LinearMap.smul_apply,
    mF_gF_before (μ := μ) hμ (show r < q₂' by omega) (show q₂' < mA by omega)
      (show p₂' + 1 = q₂' + lc by omega) (show m₁ + 1 = mA + lc by omega) hmC hm _ (corolla c)
      (corolla a₂),
    mF_gF_before (μ := μ) hμ (by omega) hq₂ hp₂ hn hmB hm₂ X (corolla c) (corolla a₂), map_smul,
    LinearMap.smul_apply,
    mF_gF_before (μ := μ) hμ hrq (show q₁ < mB by omega) hp₁ (show m₂ + 1 = mB + lc by omega)
      (show mC + 1 = mB + l₁ by omega) (show m + 1 = m₂ + l₁ by omega) _ (corolla c)
      (corolla a₁)]
  simp only [tpar_corolla', map_add, map_smul, LinearMap.add_apply, LinearMap.smul_apply,
    smul_add, smul_smul]
  congr 1
  · ring_nf
  · ring_nf

/-- Merging in parallel at a leaf before a graft point and a leaf after it. -/
theorem PF_gF_before_after (hμ : MergeFn.Odd gp μ)
    {p₁ p₂ p₂' q₂ q₂' r r₁ n n₁ lc l₁ l₂ m₁ m₂ m mA mB mC : ℕ}
    (h1r : p₁ < r) (hrq : r < q₂) (hq₂ : q₂ < n₁) (hn : n + 1 = n₁ + lc)
    (hp₂ : p₂ + 1 = q₂ + lc) (hp₂' : p₂' + 1 = p₂ + l₁) (hq₂' : q₂' + 1 = q₂ + l₁)
    (hr₁ : r₁ + 1 = r + l₁) (hm₁ : m₁ + 1 = n + l₁) (hm₂ : m₂ + 1 = n + l₂)
    (hm : m + 1 = m₁ + l₂) (hmA : mA + 1 = n₁ + l₁) (hmB : mB + 1 = n₁ + l₂)
    (hmC : mC + 1 = mA + l₂) (X : Pl (T := T) R n₁) (c : T lc) (a₁ : T l₁) (a₂ : T l₂) :
    PF μ gp R p₁ p₂ p₂' m₁ m₂ m (gF gp R r n X (pt (corolla c))) (corolla a₁) (corolla a₂)
      = (σ R (gp lc c && gp l₁ a₁) * σ R (gp lc c && gp l₂ a₂)) •
          gF gp R r₁ m (PF μ gp R p₁ q₂ q₂' mA mB mC X (corolla a₁) (corolla a₂))
            (pt (corolla c)) := by
  unfold PF
  rw [mF_gF_after (μ := μ) h1r (by omega) hr₁ hn hmA hm₁ X (corolla c) (corolla a₁), map_smul,
    LinearMap.smul_apply,
    mF_gF_before (μ := μ) hμ (show r₁ < q₂' by omega) (show q₂' < mA by omega)
      (show p₂' + 1 = q₂' + lc by omega) (show m₁ + 1 = mA + lc by omega) hmC hm _ (corolla c)
      (corolla a₂),
    mF_gF_before (μ := μ) hμ hrq hq₂ hp₂ hn hmB hm₂ X (corolla c) (corolla a₂), map_smul,
    LinearMap.smul_apply,
    mF_gF_after (μ := μ) h1r (show r < mB by omega) hr₁ (show m₂ + 1 = mB + lc by omega)
      (show mC + 1 = mB + l₁ by omega) (show m + 1 = m₂ + l₁ by omega) _ (corolla c)
      (corolla a₁)]
  simp only [tpar_corolla', map_add, map_smul, LinearMap.add_apply, LinearMap.smul_apply,
    smul_add, smul_smul]
  congr 1
  · ring_nf
  · ring_nf

/-- Merging in parallel at two leaves of the grafted corolla. -/
theorem PF_gF_inner_inner (hμ : MergeFn.Odd gp μ)
    {p₁ p₂ p₂' j₁ j₂ j₂' r n n₁ lc l₁ l₂ m₁ m₂ m mD mD' mE : ℕ}
    (h12 : j₁ < j₂) (hj₂ : j₂ < lc) (hr : r < n₁) (hn : n + 1 = n₁ + lc)
    (hp₁ : p₁ = r + j₁) (hp₂ : p₂ = r + j₂) (hp₂' : p₂' + 1 = p₂ + l₁)
    (hj₂' : j₂' + 1 = j₂ + l₁) (hm₁ : m₁ + 1 = n + l₁) (hm₂ : m₂ + 1 = n + l₂)
    (hm : m + 1 = m₁ + l₂) (hmD : mD + 1 = lc + l₁) (hmD' : mD' + 1 = lc + l₂)
    (hmE : mE + 1 = mD + l₂) (X : Pl (T := T) R n₁) (c : T lc) (a₁ : T l₁) (a₂ : T l₂) :
    PF μ gp R p₁ p₂ p₂' m₁ m₂ m (gF gp R r n X (pt (corolla c))) (corolla a₁) (corolla a₂)
      = gF gp R r m X (PF μ gp R j₁ j₂ j₂' mD mD' mE (pt (corolla c)) (corolla a₁)
          (corolla a₂)) := by
  have hW₁ := mF_corolla (μ := μ) (gp := gp) (R := R) ⟨show j₁ < lc by omega, hmD⟩ c a₁
  have hW₂ := mF_corolla (μ := μ) (gp := gp) (R := R) ⟨hj₂, hmD'⟩ c a₂
  unfold PF
  rw [mF_gF_inner (μ := μ) hμ hr (show j₁ < lc by omega) hp₁ hn hmD hm₁ X (isLeaf_corolla c)
      (corolla a₁), hW₁,
    mF_gF_inner (μ := μ) hμ hr (show j₂' < mD by omega) (show p₂' = r + j₂' by omega)
      (show m₁ + 1 = n₁ + mD by omega) hmE hm _ (isLeaf_corolla _) (corolla a₂), twF_twF,
    mF_gF_inner (μ := μ) hμ hr hj₂ hp₂ hn hmD' hm₂ X (isLeaf_corolla c) (corolla a₂), hW₂,
    mF_gF_inner (μ := μ) hμ hr (show j₁ < mD' by omega) hp₁ (show m₂ + 1 = n₁ + mD' by omega)
      (show mE + 1 = mD' + l₁ by omega) (show m + 1 = m₂ + l₁ by omega) _ (isLeaf_corolla _)
      (corolla a₁), twF_twF, map_add, map_smul]

lemma σ_par_zero (c a₁ a₂ : Bool) :
    σ R (a₁ && a₂) * σ R (c && a₁) * σ R a₁ = σ R ((!(xor c a₂)) && a₁) := by
  cases c <;> cases a₁ <;> cases a₂ <;> simp

/-- Merging in parallel at a leaf before a graft point and a leaf of the grafted corolla. -/
theorem PF_gF_before_inner (hμ : MergeFn.Odd gp μ)
    {p₁ p₂ p₂' j₂ r r₁ n n₁ lc l₁ l₂ m₁ m₂ m mA mD : ℕ}
    (h1r : p₁ < r) (hr : r < n₁) (hj₂ : j₂ < lc) (hn : n + 1 = n₁ + lc) (hp₂ : p₂ = r + j₂)
    (hp₂' : p₂' + 1 = p₂ + l₁) (hr₁ : r₁ + 1 = r + l₁) (hm₁ : m₁ + 1 = n + l₁)
    (hm₂ : m₂ + 1 = n + l₂) (hm : m + 1 = m₁ + l₂) (hmA : mA + 1 = n₁ + l₁)
    (hmD : mD + 1 = lc + l₂) (X : Pl (T := T) R n₁) (c : T lc) (a₁ : T l₁) (a₂ : T l₂) :
    PF μ gp R p₁ p₂ p₂' m₁ m₂ m (gF gp R r n X (pt (corolla c))) (corolla a₁) (corolla a₂)
      = 0 := by
  have hW := mF_corolla (μ := μ) (gp := gp) (R := R) ⟨hj₂, hmD⟩ c a₂
  unfold PF
  rw [mF_gF_after (μ := μ) h1r hr hr₁ hn hmA hm₁ X (corolla c) (corolla a₁), map_smul,
    LinearMap.smul_apply,
    mF_gF_inner (μ := μ) hμ (show r₁ < mA by omega) hj₂ (show p₂' = r₁ + j₂ by omega)
      (show m₁ + 1 = mA + lc by omega) hmD hm _ (isLeaf_corolla c) (corolla a₂), hW,
    twF_mF hμ, twF_pt,
    mF_gF_inner (μ := μ) hμ hr hj₂ hp₂ hn hmD hm₂ X (isLeaf_corolla c) (corolla a₂), hW,
    mF_gF_after (μ := μ) h1r hr hr₁ (show m₂ + 1 = n₁ + mD by omega) hmA
      (show m + 1 = m₂ + l₁ by omega) _ (corolla (μ lc l₂ c j₂ a₂ mD)) (corolla a₁)]
  simp only [tpar_corolla', hμ, map_neg, map_smul, LinearMap.neg_apply, LinearMap.smul_apply,
    smul_neg, smul_smul]
  rw [← σ_par_zero, neg_add_eq_zero]
  congr 1
  ring

/-- Merging in parallel at a leaf of the grafted corolla and a leaf after the graft point. -/
theorem PF_gF_inner_after (hμ : MergeFn.Odd gp μ)
    {p₁ p₂ p₂' j₁ q₂ r n n₁ lc l₁ l₂ m₁ m₂ m mB mD : ℕ}
    (hj₁ : j₁ < lc) (hrq : r < q₂) (hq₂ : q₂ < n₁) (hn : n + 1 = n₁ + lc) (hp₁ : p₁ = r + j₁)
    (hp₂ : p₂ + 1 = q₂ + lc) (hp₂' : p₂' + 1 = p₂ + l₁) (hm₁ : m₁ + 1 = n + l₁)
    (hm₂ : m₂ + 1 = n + l₂) (hm : m + 1 = m₁ + l₂) (hmB : mB + 1 = n₁ + l₂)
    (hmD : mD + 1 = lc + l₁) (X : Pl (T := T) R n₁) (c : T lc) (a₁ : T l₁) (a₂ : T l₂) :
    PF μ gp R p₁ p₂ p₂' m₁ m₂ m (gF gp R r n X (pt (corolla c))) (corolla a₁) (corolla a₂)
      = 0 := by
  have hW := mF_corolla (μ := μ) (gp := gp) (R := R) ⟨hj₁, hmD⟩ c a₁
  unfold PF
  rw [mF_gF_inner (μ := μ) hμ (by omega) hj₁ hp₁ hn hmD hm₁ X (isLeaf_corolla c) (corolla a₁),
    hW,
    mF_gF_before (μ := μ) hμ hrq hq₂ (show p₂' + 1 = q₂ + mD by omega)
      (show m₁ + 1 = n₁ + mD by omega) hmB hm _ (corolla (μ lc l₁ c j₁ a₁ mD)) (corolla a₂),
    mF_gF_before (μ := μ) hμ hrq hq₂ hp₂ hn hmB hm₂ X (corolla c) (corolla a₂), map_smul,
    LinearMap.smul_apply,
    mF_gF_inner (μ := μ) hμ (show r < mB by omega) hj₁ hp₁ (show m₂ + 1 = mB + lc by omega) hmD
      (show m + 1 = m₂ + l₁ by omega) _ (isLeaf_corolla c) (corolla a₁), hW, twF_mF hμ, twF_pt]
  simp only [tpar_corolla', hμ, map_neg, map_smul, LinearMap.neg_apply, LinearMap.smul_apply,
    smul_neg, smul_smul]
  rw [add_neg_eq_zero]
  congr 1
  have key : σ R (gp l₁ a₁ && gp l₂ a₂) * σ R (!(xor (gp lc c) (gp l₁ a₁)) && gp l₂ a₂)
      = σ R (gp lc c && gp l₂ a₂) * σ R (gp l₂ a₂) := by
    cases gp lc c <;> cases gp l₁ a₁ <;> cases gp l₂ a₂ <;> simp
  linear_combination key

variable (J : GrOperadIdeal R (FreeGr R gp))

lemma weight_corolla_le {k w : ℕ} (c : T k) (hw : 1 ≤ w) : (corolla c).1.weight ≤ w := by
  show (Tree.node c (TreeOfArity.leaves k)).weight ≤ w
  rw [Tree.weight_node, weightF_leaves]
  omega

/-- **Merging two corollas in parallel into a planar tree lands in the ideal.** -/
theorem PF_mem (hμ : MergeFn.Odd gp μ) (hA : AssocHyp μ gp R J) : ∀ (w n : ℕ)
    (s : TreeOfArity T n), s.1.weight ≤ w → ∀ {l₁ l₂ : ℕ} (a₁ : T l₁) (a₂ : T l₂)
    (p₁ p₂ p₂' m₁ m₂ m : ℕ), p₁ < p₂ → p₂ < n → p₂' + 1 = p₂ + l₁ → m₁ + 1 = n + l₁ →
      m₂ + 1 = n + l₂ → m + 1 = m₁ + l₂ →
      PF μ gp R p₁ p₂ p₂' m₁ m₂ m (pt s) (corolla a₁) (corolla a₂) ∈ JF J m := by
  intro w
  induction w with
  | zero =>
    intro n s hw l₁ l₂ a₁ a₂ p₁ p₂ p₂' m₁ m₂ m h12 h2 _ _ _ _
    have hl : s.1 = Tree.leaf := by
      cases hs : s.1 with
      | leaf => rfl
      | node e f => rw [hs] at hw; simp at hw
    have := s.2
    rw [hl, Tree.arity_leaf] at this
    omega
  | succ w ih =>
    intro n s hw l₁ l₂ a₁ a₂ p₁ p₂ p₂' m₁ m₂ m h12 h2 hp₂' hm₁ hm₂ hm
    rcases Nat.lt_or_ge s.1.weight 2 with hw2 | hw2
    · by_cases hw0 : s.1.weight = 0
      · exact ih n s (by omega) a₁ a₂ p₁ p₂ p₂' m₁ m₂ m h12 h2 hp₂' hm₁ hm₂ hm
      · obtain ⟨k, x, hx⟩ := eq_corolla_of_weight (t := s.1) (by omega)
        have hk : k = n := by
          have := s.2
          rw [hx, Tree.arity_node, arityF_leaves] at this
          exact this
        subst hk
        have hs : s = corolla x := Subtype.ext hx
        subst hs
        unfold PF
        rw [mF_corolla (μ := μ) ⟨by omega, hm₁⟩, mF_corolla (μ := μ) ⟨by omega, hm⟩,
          mF_corolla (μ := μ) ⟨h2, hm₂⟩, mF_corolla (μ := μ) ⟨by omega, by omega⟩,
          tpar_corolla', tpar_corolla']
        show ιP gp R m _ ∈ J.sub (Fin m)
        rw [map_add, map_smul, ιP_corolla, ιP_corolla]
        exact hA.parallel _ _ _ x a₁ a₂ p₁ p₂ p₂' m₁ m₂ m h12 h2 hp₂' hm₁ hm₂ hm
    · obtain ⟨n₁, r, lc, s₁, c, hr, hn, hw₁, hs⟩ := pt_eq_gF (R := R) (gp := gp) s hw2
      rw [hs, PF_smul]
      refine Submodule.smul_mem _ _ ?_
      have hn₁ : 1 ≤ n₁ := by omega
      obtain ⟨mA, hmA⟩ : ∃ mA, mA + 1 = n₁ + l₁ := ⟨n₁ + l₁ - 1, by omega⟩
      obtain ⟨mB, hmB⟩ : ∃ mB, mB + 1 = n₁ + l₂ := ⟨n₁ + l₂ - 1, by omega⟩
      rcases Nat.lt_or_ge p₂ r with h2r | h2r
      · -- both before
        obtain ⟨mC, hmC⟩ : ∃ mC, mC + 1 = mA + l₂ := ⟨mA + l₂ - 1, by omega⟩
        obtain ⟨r₁, hr₁⟩ : ∃ r₁, r₁ + 1 = r + l₁ := ⟨r + l₁ - 1, by omega⟩
        obtain ⟨r₂, hr₂⟩ : ∃ r₂, r₂ + 1 = r + l₂ := ⟨r + l₂ - 1, by omega⟩
        obtain ⟨r₁₂, hr₁₂⟩ : ∃ r₁₂, r₁₂ + 1 = r₁ + l₂ := ⟨r₁ + l₂ - 1, by omega⟩
        rw [PF_gF_before_before (μ := μ) h12 h2r hr hn hp₂' hm₁ hm₂ hm hr₁ hr₂ hr₁₂ hmA hmB hmC]
        exact Submodule.smul_mem _ _ (gF_mem_left
          (ih n₁ s₁ (by omega) a₁ a₂ p₁ p₂ p₂' mA mB mC h12 (by omega) hp₂' hmA hmB hmC) _)
      rcases Nat.lt_or_ge p₁ r with h1r | h1r
      · obtain ⟨r₁, hr₁⟩ : ∃ r₁, r₁ + 1 = r + l₁ := ⟨r + l₁ - 1, by omega⟩
        rcases Nat.lt_or_ge p₂ (r + lc) with h2c | h2c
        · -- before and inside
          obtain ⟨mD, hmD⟩ : ∃ mD, mD + 1 = lc + l₂ := ⟨lc + l₂ - 1, by omega⟩
          rw [PF_gF_before_inner (μ := μ) hμ h1r hr (show p₂ - r < lc by omega) hn
            (show p₂ = r + (p₂ - r) by omega) hp₂' hr₁ hm₁ hm₂ hm hmA hmD]
          exact zero_mem _
        · -- before and after
          obtain ⟨mC, hmC⟩ : ∃ mC, mC + 1 = mA + l₂ := ⟨mA + l₂ - 1, by omega⟩
          obtain ⟨q₂', hq₂'⟩ : ∃ q₂', q₂' + 1 = (p₂ + 1 - lc) + l₁ := ⟨p₂ - lc + l₁, by omega⟩
          rw [PF_gF_before_after (μ := μ) hμ h1r (show r < p₂ + 1 - lc by omega)
            (show p₂ + 1 - lc < n₁ by omega) hn (show p₂ + 1 = (p₂ + 1 - lc) + lc by omega)
            hp₂' hq₂' hr₁ hm₁ hm₂ hm hmA hmB hmC]
          exact Submodule.smul_mem _ _ (gF_mem_left (ih n₁ s₁ (by omega) a₁ a₂ p₁ (p₂ + 1 - lc)
            q₂' mA mB mC (by omega) (by omega) hq₂' hmA hmB hmC) _)
      · rcases Nat.lt_or_ge p₂ (r + lc) with h2c | h2c
        · -- both inside
          obtain ⟨mD, hmD⟩ : ∃ mD, mD + 1 = lc + l₁ := ⟨lc + l₁ - 1, by omega⟩
          obtain ⟨mD', hmD'⟩ : ∃ mD', mD' + 1 = lc + l₂ := ⟨lc + l₂ - 1, by omega⟩
          obtain ⟨mE, hmE⟩ : ∃ mE, mE + 1 = mD + l₂ := ⟨mD + l₂ - 1, by omega⟩
          obtain ⟨j₂', hj₂'⟩ : ∃ j₂', j₂' + 1 = (p₂ - r) + l₁ := ⟨p₂ - r + l₁ - 1, by omega⟩
          rw [PF_gF_inner_inner (μ := μ) hμ (show p₁ - r < p₂ - r by omega)
            (show p₂ - r < lc by omega) hr hn (show p₁ = r + (p₁ - r) by omega)
            (show p₂ = r + (p₂ - r) by omega) hp₂' hj₂' hm₁ hm₂ hm hmD hmD' hmE]
          exact gF_mem_right _ (ih lc (corolla c) (weight_corolla_le c (by omega)) a₁ a₂
            (p₁ - r) (p₂ - r) j₂' mD mD' mE (by omega) (by omega) hj₂' hmD hmD' hmE)
        · rcases Nat.lt_or_ge p₁ (r + lc) with h1c | h1c
          · -- inside and after
            obtain ⟨mD, hmD⟩ : ∃ mD, mD + 1 = lc + l₁ := ⟨lc + l₁ - 1, by omega⟩
            rw [PF_gF_inner_after (μ := μ) hμ (show p₁ - r < lc by omega)
              (show r < p₂ + 1 - lc by omega) (show p₂ + 1 - lc < n₁ by omega) hn
              (show p₁ = r + (p₁ - r) by omega) (show p₂ + 1 = (p₂ + 1 - lc) + lc by omega) hp₂'
              hm₁ hm₂ hm hmB hmD]
            exact zero_mem _
          · -- both after
            obtain ⟨mC, hmC⟩ : ∃ mC, mC + 1 = mA + l₂ := ⟨mA + l₂ - 1, by omega⟩
            obtain ⟨q₂', hq₂'⟩ : ∃ q₂', q₂' + 1 = (p₂ + 1 - lc) + l₁ := ⟨p₂ - lc + l₁, by omega⟩
            rw [PF_gF_after_after (μ := μ) hμ (show p₁ + 1 - lc < p₂ + 1 - lc by omega)
              (show r < p₁ + 1 - lc by omega) (show p₂ + 1 - lc < n₁ by omega) hn
              (show p₁ + 1 = (p₁ + 1 - lc) + lc by omega)
              (show p₂ + 1 = (p₂ + 1 - lc) + lc by omega) hp₂' hq₂' hm₁ hm₂ hm hmA hmB hmC]
            exact Submodule.smul_mem _ _ (gF_mem_left (ih n₁ s₁ (by omega) a₁ a₂ (p₁ + 1 - lc)
              (p₂ + 1 - lc) q₂' mA mB mC (by omega) (by omega) hq₂' hmA hmB hmC) _)

end Parallel

/-! ## The square of the bar differential -/

section Square

variable {μ}

variable (μ gp R) in
/-- **The failure of the square of the bar differential to be a derivation**, at a graft with a
corolla. -/
noncomputable def NF (q m : ℕ) {n lh : ℕ} (x : Pl (T := T) R n) (h : TreeOfArity T lh) :
    Pl (T := T) R m :=
  dF μ gp R m (mF μ gp R q m x (pt h)) + mF μ gp R q m (dF μ gp R n x) (pt h)

lemma NF_smul (q m : ℕ) {n lh : ℕ} (c : R) (x : Pl (T := T) R n) (h : TreeOfArity T lh) :
    NF μ gp R q m (c • x) h = c • NF μ gp R q m x h := by
  simp only [NF, map_smul, LinearMap.smul_apply, smul_add]

lemma dF_gF_corolla (hμ : MergeFn.Odd gp μ) (a : ℕ) {n lc : ℕ} (m : ℕ) (x : Pl (T := T) R n)
    (c : T lc) :
    dF μ gp R m (gF gp R a m x (pt (corolla c)))
      = gF gp R a m (dF μ gp R n x) (pt (corolla c)) + mF μ gp R a m x (pt (corolla c)) := by
  rw [dF_gF μ hμ, dF_corolla, map_zero, add_zero]

/-- The failure at a graft point after the merge. -/
theorem NF_gF_after (hμ : MergeFn.Odd gp μ) {q r r' n n₁ lc lh m mA : ℕ} (hqr : q < r)
    (hr : r < n₁) (hn : n + 1 = n₁ + lc) (hm : m + 1 = n + lh) (hr' : r' + 1 = r + lh)
    (hmA : mA + 1 = n₁ + lh) (X : Pl (T := T) R n₁) (c : T lc) (h : T lh) :
    NF μ gp R q m (gF gp R r n X (pt (corolla c))) (corolla h)
      = σ R (gp lc c && gp lh h) • gF gp R r' m (NF μ gp R q mA X (corolla h)) (pt (corolla c))
        + PF μ gp R q r r' mA n m X (corolla h) (corolla c) := by
  unfold NF PF
  rw [mF_gF_after (μ := μ) hqr hr hr' hn hmA hm X (corolla c) (corolla h), map_smul,
    dF_gF_corolla hμ, dF_gF_corolla hμ, map_add, LinearMap.add_apply,
    mF_gF_after (μ := μ) hqr hr hr' hn hmA hm _ (corolla c) (corolla h)]
  simp only [tpar_corolla', map_add, LinearMap.add_apply, smul_add, Bool.and_comm (gp lh h)]
  abel

/-- The failure at a graft point before the merge. -/
theorem NF_gF_before (hμ : MergeFn.Odd gp μ) {q q₁ r n n₁ lc lh m mA : ℕ} (hrq : r < q₁)
    (hq₁ : q₁ < n₁) (hq : q + 1 = q₁ + lc) (hn : n + 1 = n₁ + lc) (hm : m + 1 = n + lh)
    (hmA : mA + 1 = n₁ + lh) (X : Pl (T := T) R n₁) (c : T lc) (h : T lh) :
    NF μ gp R q m (gF gp R r n X (pt (corolla c))) (corolla h)
      = σ R (gp lc c && gp lh h) • gF gp R r m (NF μ gp R q₁ mA X (corolla h)) (pt (corolla c))
        + σ R (gp lc c && gp lh h) • PF μ gp R r q₁ q n mA m X (corolla c) (corolla h) := by
  unfold NF PF
  rw [mF_gF_before (μ := μ) hμ hrq hq₁ hq hn hmA hm X (corolla c) (corolla h), map_smul,
    dF_gF_corolla hμ, dF_gF_corolla hμ, map_add, LinearMap.add_apply,
    mF_gF_before (μ := μ) hμ hrq hq₁ hq hn hmA hm _ (corolla c) (corolla h)]
  simp only [tpar_corolla', map_add, LinearMap.add_apply, smul_add, smul_smul, σ_mul_self,
    one_smul]
  abel

/-- The failure at a leaf of the grafted corolla. -/
theorem NF_gF_inner (hμ : MergeFn.Odd gp μ) {q j r n n₁ lc lh m mD : ℕ} (hr : r < n₁)
    (hj : j < lc) (hq : q = r + j) (hn : n + 1 = n₁ + lc) (hm : m + 1 = n + lh)
    (hmD : mD + 1 = lc + lh) (X : Pl (T := T) R n₁) (c : T lc) (h : T lh) :
    NF μ gp R q m (gF gp R r n X (pt (corolla c))) (corolla h)
      = SF μ gp R r j mD n m X (corolla c) (corolla h) := by
  have hW := mF_corolla (μ := μ) (gp := gp) (R := R) ⟨hj, hmD⟩ c h
  unfold NF SF
  rw [mF_gF_inner (μ := μ) hμ hr hj hq hn hmD hm X (isLeaf_corolla c) (corolla h), hW,
    dF_gF_corolla hμ, dF_gF_corolla hμ, map_add, LinearMap.add_apply,
    mF_gF_inner (μ := μ) hμ hr hj hq hn hmD hm _ (isLeaf_corolla c) (corolla h), hW,
    dF_twF hμ, ← hq]
  simp only [map_neg, LinearMap.neg_apply]
  abel

variable (J : GrOperadIdeal R (FreeGr R gp))

/-- **The failure of the square of the bar differential to be a derivation lands in the
ideal.** -/
theorem NF_mem (hμ : MergeFn.Odd gp μ) (hA : AssocHyp μ gp R J) : ∀ (w n : ℕ)
    (s : TreeOfArity T n), s.1.weight ≤ w → ∀ {lh : ℕ} (h : T lh) (q m : ℕ), q < n →
      m + 1 = n + lh → NF μ gp R q m (pt s) (corolla h) ∈ JF J m := by
  intro w
  induction w with
  | zero =>
    intro n s hw lh h q m hq hm
    have hl : s.1.isLeaf = true := by
      cases hs : s.1 with
      | leaf => rfl
      | node e f => rw [hs] at hw; simp at hw
    have hd : dF μ gp R n (pt s) = 0 := by
      rw [dF_pt, show s.1.weight = 0 by omega, Finset.Ico_eq_empty_of_le zero_le_one,
        Finset.sum_empty]
    unfold NF
    rw [mF_pt_leaf_left _ hl, hd, map_zero, map_zero, LinearMap.zero_apply, add_zero]
    exact zero_mem _
  | succ w ih =>
    intro n s hw lh h q m hq hm
    rcases Nat.lt_or_ge s.1.weight 2 with hw2 | hw2
    · have hd : dF μ gp R n (pt s) = 0 := by
        rw [dF_pt, Finset.Ico_eq_empty_of_le (by omega), Finset.sum_empty]
      by_cases hw0 : s.1.weight = 0
      · exact ih n s (by omega) h q m hq hm
      · obtain ⟨k, x, hx⟩ := eq_corolla_of_weight (t := s.1) (by omega)
        have hk : k = n := by
          have := s.2
          rw [hx, Tree.arity_node, arityF_leaves] at this
          exact this
        subst hk
        have hs : s = corolla x := Subtype.ext hx
        subst hs
        unfold NF
        rw [hd, map_zero, LinearMap.zero_apply, add_zero, mF_corolla (μ := μ) ⟨hq, hm⟩,
          dF_corolla]
        exact zero_mem _
    · obtain ⟨n₁, r, lc, s₁, c, hr, hn, hw₁, hs⟩ := pt_eq_gF (R := R) (gp := gp) s hw2
      rw [hs, NF_smul]
      refine Submodule.smul_mem _ _ ?_
      obtain ⟨mA, hmA⟩ : ∃ mA, mA + 1 = n₁ + lh := ⟨n₁ + lh - 1, by omega⟩
      rcases Nat.lt_or_ge q r with hqr | hqr
      · obtain ⟨r', hr'⟩ : ∃ r', r' + 1 = r + lh := ⟨r + lh - 1, by omega⟩
        rw [NF_gF_after (μ := μ) hμ hqr hr hn hm hr' hmA]
        exact add_mem (Submodule.smul_mem _ _ (gF_mem_left
            (ih n₁ s₁ (by omega) h q mA (by omega) hmA) _))
          (PF_mem J hμ hA w n₁ s₁ (by omega) h c q r r' mA n m hqr hr hr' hmA hn
            (by omega))
      · rcases Nat.lt_or_ge q (r + lc) with hqc | hqc
        · obtain ⟨mD, hmD⟩ : ∃ mD, mD + 1 = lc + lh := ⟨lc + lh - 1, by omega⟩
          rw [NF_gF_inner (μ := μ) hμ hr (show q - r < lc by omega) (show q = r + (q - r) by omega)
            hn hm hmD]
          exact SF_mem J hμ hA w n₁ s₁ (by omega) c h r (q - r) mD n m hr (by omega) hmD hn
            (by omega)
        · rw [NF_gF_before (μ := μ) hμ (show r < q + 1 - lc by omega)
            (show q + 1 - lc < n₁ by omega) (show q + 1 = (q + 1 - lc) + lc by omega) hn hm hmA]
          exact add_mem (Submodule.smul_mem _ _ (gF_mem_left
              (ih n₁ s₁ (by omega) h (q + 1 - lc) mA (by omega) hmA) _))
            (Submodule.smul_mem _ _ (PF_mem J hμ hA w n₁ s₁ (by omega) c h r (q + 1 - lc) q n mA
              m (by omega) (by omega) (by omega) hn hmA (by omega)))

/-- **The square of the bar differential of a planar tree lands in the ideal.** -/
theorem dF_dF_mem (hμ : MergeFn.Odd gp μ) (hA : AssocHyp μ gp R J) : ∀ (w n : ℕ)
    (s : TreeOfArity T n), s.1.weight ≤ w → dF μ gp R n (dF μ gp R n (pt s)) ∈ JF J n := by
  intro w
  induction w with
  | zero =>
    intro n s hw
    rw [dF_pt, Finset.Ico_eq_empty_of_le (by omega), Finset.sum_empty, map_zero]
    exact zero_mem _
  | succ w ih =>
    intro n s hw
    rcases Nat.lt_or_ge s.1.weight 2 with hw2 | hw2
    · rw [dF_pt, Finset.Ico_eq_empty_of_le (by omega), Finset.sum_empty, map_zero]
      exact zero_mem _
    · obtain ⟨n₁, r, lc, s₁, c, hr, hn, hw₁, hs⟩ := pt_eq_gF (R := R) (gp := gp) s hw2
      rw [hs, map_smul, map_smul]
      refine Submodule.smul_mem _ _ ?_
      rw [dF_gF_corolla hμ, map_add, dF_gF_corolla hμ, add_assoc]
      refine add_mem (gF_mem_left (ih n₁ s₁ (by omega)) _) ?_
      rw [add_comm]
      exact NF_mem J hμ hA w n₁ s₁ (by omega) c r n hr (by omega)

/-- **The square of the bar differential lands in the ideal** generated by relations making the
merge function associative. -/
theorem barD_barD_mem (hμ : MergeFn.Odd gp μ) (hA : AssocHyp μ gp R J) {A : Type} [Fintype A]
    [DecidableEq A] (x : FreeGr R gp A) : barD μ gp R A (barD μ gp R A x) ∈ J.sub A := by
  induction x using induction_bas with
  | zero => rw [map_zero, map_zero]; exact zero_mem _
  | add x y hx hy => rw [map_add, map_add]; exact add_mem hx hy
  | bas c t =>
    rw [map_smul, map_smul]
    refine Submodule.smul_mem _ c ?_
    have ht : SgnLin.bas (treeSgn gp) R t = GrOperad.map (R := R)
        ((finCongr t.2.2).trans t.1.toRank.symm) (ιP gp R _ (pt t.2.1.2)) := by
      rw [ιP_pt, SgnLin.map_bas]
      exact congrArg _ (Reg.eq_map_std t)
    rw [ht, ← map_barD, ← map_barD, ← ιP_dF, ← ιP_dF]
    exact J.map_mem _ (dF_dF_mem J hμ hA _ _ t.2.1.2 le_rfl)

end Square

end FreeGr

end Operad
