/-
# The square of the bar differential

The bar differential of the free graded operad squares to zero modulo the ideal generated by
relations making the merge function associative up to sign (`FreeGr.barD_barD_mem`).

The proof is planar. On the combinations of planar trees with `n` leaves (`FreeGr.Pl`), embedded in
the free graded operad in the standard order (`FreeGr.ιP`), grafting at a position (`FreeGr.gF`),
merge-grafting at a position (`FreeGr.mF`), the parity involution (`FreeGr.twF`) and the bar
differential (`FreeGr.dF`) satisfy the Leibniz rule up to merge-grafting (`FreeGr.dF_gF`) and the
laws of merge-grafting with grafting, with positions instead of relabellings. Every tree with at
least two vertices is a tree grafted with the corolla of its last vertex. By induction on the
number of vertices:

* the square of the bar differential of a graft with a corolla is the graft of the square, plus
  `N = d (x ⊛ₚ c) + (d x) ⊛ₚ c` (`FreeGr.dF_dF_gF`);
* `N` reduces to merging two corollas into a tree in the two orders, at two leaves of one vertex
  (`P`) or at a leaf of a vertex and a leaf of the merged corolla (`S`), which reduce in turn to
  merging into a corolla, where the relations apply.
-/
import Operad.BarDescent

universe u v

namespace Operad

open Sym GerBV TreeOfArity
open scoped TensorProduct

namespace FreeGr

variable {T : ℕ → Type v} (μ : MergeFn T) (gp : ∀ k, T k → Bool) (R : Type u) [CommRing R]

/-! ## Planar combinations of trees -/

/-- **Combinations of planar trees** with `n` leaves. -/
abbrev Pl (n : ℕ) : Type (max u v) := TreeOfArity T n →₀ R

variable {R} in
/-- A planar tree, as a combination. -/
noncomputable def pt {n : ℕ} (t : TreeOfArity T n) : Pl (T := T) R n := Finsupp.single t 1

/-- **Planar trees in the standard order**, in the free graded operad. -/
noncomputable def ιP (n : ℕ) : Pl (T := T) R n →ₗ[R] FreeGr R gp (Fin n) :=
  Finsupp.linearCombination R fun t => SgnLin.bas (treeSgn gp) R (Reg.std t)

variable {gp R}

lemma ιP_pt {n : ℕ} (t : TreeOfArity T n) :
    ιP gp R n (pt t) = SgnLin.bas (treeSgn gp) R (Reg.std t) :=
  (Finsupp.linearCombination_single R _ _).trans (one_smul R _)

lemma std_injective {n : ℕ} : Function.Injective (Reg.std : TreeOfArity T n → _) := by
  intro s t h
  have h2 := congrArg (fun x : Reg (TreeOfArity T) (Fin n) => x.2.1) h
  simp only [Reg.std] at h2
  exact eq_of_heq (Sigma.mk.inj h2).2

lemma ιP_apply {n : ℕ} (x : Pl (T := T) R n) :
    (ιP gp R n x : Reg (TreeOfArity T) (Fin n) →₀ R) = Finsupp.mapDomain Reg.std x := by
  induction x using Finsupp.induction_linear with
  | zero => rw [map_zero, Finsupp.mapDomain_zero]; rfl
  | add x y hx hy => rw [map_add, Finsupp.mapDomain_add, ← hx, ← hy]; rfl
  | single t c =>
    rw [Finsupp.mapDomain_single, ← Finsupp.smul_single_one t c, map_smul]
    show c • ιP gp R n (pt t) = _
    rw [ιP_pt]
    exact Finsupp.smul_single_one _ c

lemma ιP_injective {n : ℕ} : Function.Injective (ιP gp R n) := by
  intro x y h
  have h' : Finsupp.mapDomain Reg.std x = Finsupp.mapDomain Reg.std y := by
    rw [← ιP_apply, ← ιP_apply]
    exact congrArg (fun z : FreeGr R gp (Fin n) => (z : Reg (TreeOfArity T) (Fin n) →₀ R)) h
  exact Finsupp.mapDomain_injective std_injective h'

/-! ## Positions -/

/-- **The positions of a composite**: the order isomorphism of the composite of standard orders
onto the standard order. -/
noncomputable def posEquiv (n a l m : ℕ) (h : a < n ∧ m + 1 = n + l) :
    Without (Fin n) ⟨a, h.1⟩ ⊕ Fin l ≃ Fin m :=
  (LinOrd.comp (⟨a, h.1⟩ : Fin n) (LinOrd.std n) (LinOrd.std l)).toRank.trans (finCongr (by
    rw [Fintype.card_sum, Reg.card_without, Fintype.card_fin, Fintype.card_fin]
    omega))

lemma map_toRank {X : Type} [Fintype X] [DecidableEq X] (L : LinOrd X) {m : ℕ}
    (h : Fintype.card X = m) : LinOrd.map (L.toRank.trans (finCongr h)) L = LinOrd.std m := by
  ext a b
  simp only [LinOrd.map_lt, LinOrd.std_lt, Fin.lt_def]
  rw [L.lt_iff_rank_lt, ← LinOrd.toRank_apply, ← LinOrd.toRank_apply]
  simp

lemma map_posEquiv_comp {n a l m : ℕ} (h : a < n ∧ m + 1 = n + l) :
    LinOrd.map (posEquiv n a l m h)
      (LinOrd.comp (⟨a, h.1⟩ : Fin n) (LinOrd.std n) (LinOrd.std l)) = LinOrd.std m :=
  map_toRank _ _

/-! ## Operations on planar trees -/

section Ops

variable (gp R)

/-- Contracting an edge of a planar tree. -/
def contrT {n : ℕ} (t : TreeOfArity T n) (k : ℕ) : TreeOfArity T n :=
  ⟨t.1.contr μ k, (Tree.arity_contr μ t.1 k).trans t.2⟩

/-- Grafting planar trees at a position. -/
def graftT {n l m : ℕ} (s : TreeOfArity T n) (a : ℕ) (u : TreeOfArity T l)
    (h : a < n ∧ m + 1 = n + l) : TreeOfArity T m :=
  ⟨s.1.graft a u.1, by
    have := Tree.arity_graft s.1 a u.1 (by rw [s.2]; exact h.1)
    rw [this, s.2, u.2]
    omega⟩

/-- Merge-grafting planar trees at a position. -/
def mgraftT {n l m : ℕ} (s : TreeOfArity T n) (a : ℕ) (u : TreeOfArity T l)
    (h : a < n ∧ m + 1 = n + l) : TreeOfArity T m :=
  ⟨s.1.mgraft μ a u.1, by
    have := Tree.arity_mgraft μ s.1 a u.1 (by rw [s.2]; exact h.1)
    rw [s.2, u.2] at this
    omega⟩

variable {μ}

@[simp] lemma contrT_val {n : ℕ} (t : TreeOfArity T n) (k : ℕ) :
    (contrT μ t k).1 = t.1.contr μ k := rfl

@[simp] lemma graftT_val {n l m : ℕ} (s : TreeOfArity T n) (a : ℕ) (u : TreeOfArity T l)
    (h : a < n ∧ m + 1 = n + l) : (graftT s a u h).1 = s.1.graft a u.1 := rfl

@[simp] lemma mgraftT_val {n l m : ℕ} (s : TreeOfArity T n) (a : ℕ) (u : TreeOfArity T l)
    (h : a < n ∧ m + 1 = n + l) : (mgraftT μ s a u h).1 = s.1.mgraft μ a u.1 := rfl

/-- The parity involution on planar trees. -/
noncomputable def twF (n : ℕ) : Pl (T := T) R n →ₗ[R] Pl (T := T) R n :=
  Finsupp.linearCombination R fun t => σ R (Tree.tpar gp t.1) • pt t

variable (μ) in
/-- **The bar differential on planar trees.** -/
noncomputable def dF (n : ℕ) : Pl (T := T) R n →ₗ[R] Pl (T := T) R n :=
  Finsupp.linearCombination R fun t : TreeOfArity T n =>
    ∑ k ∈ Finset.Ico 1 t.1.weight, σ R (Tree.contrSgn gp t.1 k) • pt (contrT μ t k)

/-- **Grafting at a position**, with its Koszul sign. -/
noncomputable def gF (a : ℕ) {n l : ℕ} (m : ℕ) : Pl (T := T) R n →ₗ[R] Pl (T := T) R l →ₗ[R] Pl (T := T) R m :=
  Finsupp.linearCombination R fun s : TreeOfArity T n =>
    Finsupp.linearCombination R fun u : TreeOfArity T l =>
      if h : a < n ∧ m + 1 = n + l then
        σ R (Tree.tpar gp u.1 && Tree.apar gp s.1 a) • pt (graftT s a u h)
      else 0

variable (μ) in
/-- **Merge-grafting at a position**, with its sign. -/
noncomputable def mF (a : ℕ) {n l : ℕ} (m : ℕ) : Pl (T := T) R n →ₗ[R] Pl (T := T) R l →ₗ[R] Pl (T := T) R m :=
  Finsupp.linearCombination R fun s : TreeOfArity T n =>
    Finsupp.linearCombination R fun u : TreeOfArity T l =>
      if h : a < n ∧ m + 1 = n + l then
        (if s.1.isLeaf = false ∧ u.1.isLeaf = false then
          σ R (Tree.mSgn gp s.1 a u.1) • pt (mgraftT μ s a u h) else 0)
      else 0

variable {gp R}

lemma twF_pt {n : ℕ} (t : TreeOfArity T n) :
    twF gp R n (pt t) = σ R (Tree.tpar gp t.1) • pt t :=
  (Finsupp.linearCombination_single R _ _).trans (one_smul R _)

lemma dF_pt {n : ℕ} (t : TreeOfArity T n) :
    dF μ gp R n (pt t)
      = ∑ k ∈ Finset.Ico 1 t.1.weight, σ R (Tree.contrSgn gp t.1 k) • pt (contrT μ t k) :=
  (Finsupp.linearCombination_single R _ _).trans (one_smul R _)

lemma gF_pt (a : ℕ) {n l m : ℕ} (s : TreeOfArity T n) (u : TreeOfArity T l) :
    gF gp R a m (pt s) (pt u)
      = if h : a < n ∧ m + 1 = n + l then
          σ R (Tree.tpar gp u.1 && Tree.apar gp s.1 a) • pt (graftT s a u h) else 0 := by
  unfold gF
  exact (LinearMap.congr_fun
    ((Finsupp.linearCombination_single R (1 : R) s).trans (one_smul R _)) _).trans
      ((Finsupp.linearCombination_single R (1 : R) u).trans (one_smul R _))

lemma mF_pt (a : ℕ) {n l m : ℕ} (s : TreeOfArity T n) (u : TreeOfArity T l) :
    mF μ gp R a m (pt s) (pt u)
      = if h : a < n ∧ m + 1 = n + l then
          (if s.1.isLeaf = false ∧ u.1.isLeaf = false then
            σ R (Tree.mSgn gp s.1 a u.1) • pt (mgraftT μ s a u h) else 0) else 0 := by
  unfold mF
  exact (LinearMap.congr_fun
    ((Finsupp.linearCombination_single R (1 : R) s).trans (one_smul R _)) _).trans
      ((Finsupp.linearCombination_single R (1 : R) u).trans (one_smul R _))

lemma gF_pt_of {a n l m : ℕ} (h : a < n ∧ m + 1 = n + l) (s : TreeOfArity T n)
    (u : TreeOfArity T l) :
    gF gp R a m (pt s) (pt u) = σ R (Tree.tpar gp u.1 && Tree.apar gp s.1 a) • pt (graftT s a u h) :=
  (gF_pt a s u).trans (dif_pos h)

lemma mF_pt_of {a n l m : ℕ} (h : a < n ∧ m + 1 = n + l) {s : TreeOfArity T n}
    {u : TreeOfArity T l} (hs : s.1.isLeaf = false) (hu : u.1.isLeaf = false) :
    mF μ gp R a m (pt s) (pt u) = σ R (Tree.mSgn gp s.1 a u.1) • pt (mgraftT μ s a u h) := by
  rw [mF_pt, dif_pos h, if_pos ⟨hs, hu⟩]

lemma mF_pt_leaf_right (a : ℕ) {n l m : ℕ} (s : TreeOfArity T n) {u : TreeOfArity T l}
    (hu : u.1.isLeaf = true) : mF μ gp R a m (pt s) (pt u) = 0 := by
  rw [mF_pt]
  split_ifs with h1 h2
  · exact absurd h2.2 (by rw [hu]; decide)
  · rfl
  · rfl

lemma mF_pt_leaf_left (a : ℕ) {n l m : ℕ} {s : TreeOfArity T n} (hs : s.1.isLeaf = true)
    (u : TreeOfArity T l) : mF μ gp R a m (pt s) (pt u) = 0 := by
  rw [mF_pt]
  split_ifs with h1 h2
  · exact absurd h2.1 (by rw [hs]; decide)
  · rfl
  · rfl

lemma gF_of_not {a n l m : ℕ} (h : ¬ (a < n ∧ m + 1 = n + l)) (x : Pl (T := T) R n)
    (y : Pl (T := T) R l) : gF gp R a m x y = 0 := by
  have : gF gp R a m (n := n) (l := l) = 0 :=
    Finsupp.lhom_ext' fun s => LinearMap.ext_ring
      (Finsupp.lhom_ext' fun u => LinearMap.ext_ring ((gF_pt a s u).trans (dif_neg h)))
  rw [this, LinearMap.zero_apply, LinearMap.zero_apply]

lemma mF_of_not {a n l m : ℕ} (h : ¬ (a < n ∧ m + 1 = n + l)) (x : Pl (T := T) R n)
    (y : Pl (T := T) R l) : mF μ gp R a m x y = 0 := by
  have : mF μ gp R a m (n := n) (l := l) = 0 :=
    Finsupp.lhom_ext' fun s => LinearMap.ext_ring
      (Finsupp.lhom_ext' fun u => LinearMap.ext_ring ((mF_pt a s u).trans (dif_neg h)))
  rw [this, LinearMap.zero_apply, LinearMap.zero_apply]

end Ops

/-! ## Planar trees in the free graded operad -/

section Compat

variable {μ}

lemma map_posEquiv_std_comp {a n l m : ℕ} (h : a < n ∧ m + 1 = n + l) (s : TreeOfArity T n)
    (u : TreeOfArity T l) :
    SetOperad.map (posEquiv n a l m h) (SetOperad.comp (⟨a, h.1⟩ : Fin n) (Reg.std s) (Reg.std u))
      = Reg.std (graftT s a u h) := by
  refine reg_ext (map_posEquiv_comp h) ?_
  rw [treeOf_map, treeOf_comp]
  show s.1.graft ((LinOrd.std n).rank ⟨a, h.1⟩) u.1 = s.1.graft a u.1
  rw [LinOrd.rank_std]

lemma map_posEquiv_std_mcomp {a n l m : ℕ} (h : a < n ∧ m + 1 = n + l) (s : TreeOfArity T n)
    (u : TreeOfArity T l) :
    SetOperad.map (posEquiv n a l m h) (mcompR μ (⟨a, h.1⟩ : Fin n) (Reg.std s) (Reg.std u))
      = Reg.std (mgraftT μ s a u h) := by
  refine reg_ext (map_posEquiv_comp h) ?_
  rw [treeOf_map, treeOf_mcompR]
  show s.1.mgraft μ ((LinOrd.std n).rank ⟨a, h.1⟩) u.1 = s.1.mgraft μ a u.1
  rw [LinOrd.rank_std]

lemma contrR_std {n : ℕ} (t : TreeOfArity T n) (k : ℕ) :
    contrR μ (Reg.std t) k = Reg.std (contrT μ t k) := rfl

lemma ιP_twF {n : ℕ} (x : Pl (T := T) R n) :
    ιP gp R n (twF gp R n x) = GrSpecies.tw (R := R) (V := FreeGr R gp) true (ιP gp R n x) := by
  have h := Lin.induction₁ (S := fun _ _ _ => TreeOfArity T n) (A := Unit)
    (ιP gp R n ∘ₗ twF gp R n) (GrSpecies.tw (R := R) (V := FreeGr R gp) true ∘ₗ ιP gp R n)
    (fun t => ?_) x
  · simpa using h
  show ιP gp R n (twF gp R n (pt t)) = GrSpecies.tw (R := R) (V := FreeGr R gp) true
    (ιP gp R n (pt t))
  rw [twF_pt, map_smul, ιP_pt, tw_bas]
  rfl

lemma ιP_dF {n : ℕ} (x : Pl (T := T) R n) :
    ιP gp R n (dF μ gp R n x) = barD μ gp R (Fin n) (ιP gp R n x) := by
  have h := Lin.induction₁ (S := fun _ _ _ => TreeOfArity T n) (A := Unit)
    (ιP gp R n ∘ₗ dF μ gp R n) (barD μ gp R (Fin n) ∘ₗ ιP gp R n) (fun t => ?_) x
  · simpa using h
  show ιP gp R n (dF μ gp R n (pt t)) = barD μ gp R (Fin n) (ιP gp R n (pt t))
  rw [dF_pt, map_sum, ιP_pt, barD_bas]
  refine Finset.sum_congr rfl fun k _ => ?_
  rw [map_smul, ιP_pt, contrR_std]
  rfl

lemma ιP_gF {a n l m : ℕ} (h : a < n ∧ m + 1 = n + l) (x : Pl (T := T) R n)
    (y : Pl (T := T) R l) :
    ιP gp R m (gF gp R a m x y) = GrOperad.map (R := R) (posEquiv n a l m h)
      (GrOperad.comp (R := R) (⟨a, h.1⟩ : Fin n) (ιP gp R n x) (ιP gp R l y)) := by
  have key : (gF gp R a m (n := n) (l := l)).compr₂ (ιP gp R m)
      = ((GrOperad.comp (R := R) (P := FreeGr R gp) (B := Fin l) (⟨a, h.1⟩ : Fin n)).compr₂
          (GrOperad.map (R := R) (posEquiv n a l m h))).compl₁₂ (ιP gp R n) (ιP gp R l) := by
    refine Finsupp.lhom_ext' fun s => LinearMap.ext_ring
      (Finsupp.lhom_ext' fun u => LinearMap.ext_ring ?_)
    show ιP gp R m (gF gp R a m (pt s) (pt u)) = GrOperad.map (R := R) (posEquiv n a l m h)
      (GrOperad.comp (R := R) (⟨a, h.1⟩ : Fin n) (ιP gp R n (pt s)) (ιP gp R l (pt u)))
    rw [gF_pt_of h, map_smul, ιP_pt, ιP_pt, ιP_pt, comp_bas_eq, map_smul, SgnLin.map_bas,
      map_posEquiv_std_comp]
    congr 1
    show σ R (Tree.tpar gp u.1 && Tree.apar gp s.1 a)
      = σ R (Tree.tpar gp u.1 && Tree.apar gp s.1 ((LinOrd.std n).rank ⟨a, h.1⟩))
    rw [LinOrd.rank_std]
  exact LinearMap.congr_fun (LinearMap.congr_fun key x) y

lemma ιP_mF {a n l m : ℕ} (h : a < n ∧ m + 1 = n + l) (x : Pl (T := T) R n)
    (y : Pl (T := T) R l) :
    ιP gp R m (mF μ gp R a m x y) = GrOperad.map (R := R) (posEquiv n a l m h)
      (mcomp μ gp R (⟨a, h.1⟩ : Fin n) (ιP gp R n x) (ιP gp R l y)) := by
  have key : (mF μ gp R a m (n := n) (l := l)).compr₂ (ιP gp R m)
      = ((mcomp μ gp R (B := Fin l) (⟨a, h.1⟩ : Fin n)).compr₂
          (GrOperad.map (R := R) (posEquiv n a l m h))).compl₁₂ (ιP gp R n) (ιP gp R l) := by
    refine Finsupp.lhom_ext' fun s => LinearMap.ext_ring
      (Finsupp.lhom_ext' fun u => LinearMap.ext_ring ?_)
    show ιP gp R m (mF μ gp R a m (pt s) (pt u)) = GrOperad.map (R := R) (posEquiv n a l m h)
      (mcomp μ gp R (⟨a, h.1⟩ : Fin n) (ιP gp R n (pt s)) (ιP gp R l (pt u)))
    rw [mF_pt, dif_pos h, ιP_pt, ιP_pt, mcomp_bas]
    have hrank : (LinOrd.std n).rank (⟨a, h.1⟩ : Fin n) = a := LinOrd.rank_std n _
    split_ifs with h1 h2 h2
    · rw [map_smul, ιP_pt, map_smul, SgnLin.map_bas, map_posEquiv_std_mcomp]
      congr 1
      show σ R (Tree.mSgn gp s.1 a u.1) = σ R (Tree.mSgn gp s.1 ((LinOrd.std n).rank ⟨a, h.1⟩) u.1)
      rw [hrank]
    · exact absurd h1 h2
    · exact absurd h2 h1
    · rw [map_zero, map_zero]
  exact LinearMap.congr_fun (LinearMap.congr_fun key x) y

variable (μ) in
/-- **The Leibniz rule up to merge-grafting**, for planar trees. -/
theorem dF_gF (hμ : MergeFn.Odd gp μ) (a : ℕ) {n l : ℕ} (m : ℕ) (x : Pl (T := T) R n)
    (y : Pl (T := T) R l) :
    dF μ gp R m (gF gp R a m x y)
      = gF gp R a m (dF μ gp R n x) y + gF gp R a m (twF gp R n x) (dF μ gp R l y)
        + mF μ gp R a m x y := by
  by_cases h : a < n ∧ m + 1 = n + l
  · apply ιP_injective (gp := gp)
    rw [ιP_dF, ιP_gF h, ← map_barD, barD_comp hμ, map_add, map_add, map_add, map_add, ιP_gF h,
      ιP_gF h, ιP_mF h, ιP_dF, ιP_dF, ιP_twF]
  · rw [gF_of_not h, gF_of_not h, gF_of_not h, mF_of_not h, map_zero, add_zero, add_zero]

end Compat

/-! ## The laws of merge-grafting with grafting, at positions -/

section PlanarLaws

variable {μ}

lemma isLeaf_of_lt {n : ℕ} (s : TreeOfArity T n) (h : 1 < n) : s.1.isLeaf = false := by
  by_contra h'
  have hl : s.1.isLeaf = true := by simpa using h'
  have := s.2
  rw [Tree.eq_leaf_of_isLeaf hl, Tree.arity_leaf] at this
  omega

lemma pt_eq {n : ℕ} {s t : TreeOfArity T n} (h : s.1 = t.1) : (pt s : Pl (T := T) R n) = pt t := by
  rw [Subtype.ext h]

/-- **Merging before a graft point.** -/
theorem mF_gF_after {p q q' n lu lv m₁ m₂ m : ℕ} (hpq : p < q) (hq : q < n)
    (hq' : q' + 1 = q + lv) (h₁ : m₁ + 1 = n + lu) (h₂ : m₂ + 1 = n + lv) (hm : m + 1 = m₁ + lv)
    (x : Pl (T := T) R n) (u : TreeOfArity T lu) (v : TreeOfArity T lv) :
    mF μ gp R p m (gF gp R q m₁ x (pt u)) (pt v)
      = σ R (Tree.tpar gp u.1 && Tree.tpar gp v.1) •
          gF gp R q' m (mF μ gp R p m₂ x (pt v)) (pt u) := by
  induction x using Finsupp.induction_linear with
  | zero => simp
  | add x y hx hy => simp only [map_add, LinearMap.add_apply, hx, hy, smul_add]
  | single s c =>
    rw [← Finsupp.smul_single_one s c,
      show (Finsupp.single s (1 : R) : Pl (T := T) R n) = pt s from rfl]
    simp only [map_smul, LinearMap.smul_apply]
    rw [smul_comm]
    congr 1
    have hs := isLeaf_of_lt s (by omega)
    have ha : q < s.1.arity := by rw [s.2]; exact hq
    by_cases hv : v.1.isLeaf = true
    · rw [gF_pt_of ⟨hq, h₁⟩, map_smul, LinearMap.smul_apply, mF_pt_leaf_right _ _ hv,
        mF_pt_leaf_right _ _ hv, map_zero, LinearMap.zero_apply, smul_zero, smul_zero]
    · have hv' : v.1.isLeaf = false := by simpa using hv
      have hG : (graftT s q u ⟨hq, h₁⟩).1.isLeaf = false := Tree.isLeaf_graft_left hs _ _
      have hM : q' < m₂ ∧ m + 1 = m₂ + lu := by omega
      rw [gF_pt_of ⟨hq, h₁⟩, map_smul, LinearMap.smul_apply,
        mF_pt_of (μ := μ) ⟨by omega, hm⟩ hG hv', mF_pt_of (μ := μ) ⟨by omega, h₂⟩ hs hv',
        map_smul, LinearMap.smul_apply, gF_pt_of hM, smul_smul, smul_smul, smul_smul]
      have htree : (mgraftT μ (graftT s q u ⟨hq, h₁⟩) p v ⟨by omega, hm⟩).1
          = (graftT (mgraftT μ s p v ⟨by omega, h₂⟩) q' u hM).1 := by
        simp only [mgraftT_val, graftT_val]
        rw [Tree.graft_mgraft_after μ s.1 p v.1 q u.1 hpq ha, v.2]
        congr 1
        omega
      rw [pt_eq htree]
      congr 1
      simp only [graftT_val, mgraftT_val, ← σ_xor]
      congr 1
      have e := Tree.mSgn_graft_after μ gp (s := s.1) (b := u.1) (u := v.1) hpq ha
      rw [v.2, show q - 1 + lv = q' by omega] at e
      rw [e, Bool.xor_assoc]

/-- **Merging after a graft point.** -/
theorem mF_gF_before (hμ : MergeFn.Odd gp μ) {p p' q n lu lv m₁ m₂ m : ℕ} (hqp : q < p)
    (hp : p < n) (hp' : p' + 1 = p + lu) (h₁ : m₁ + 1 = n + lu) (h₂ : m₂ + 1 = n + lv)
    (hm : m + 1 = m₁ + lv) (x : Pl (T := T) R n) (u : TreeOfArity T lu) (v : TreeOfArity T lv) :
    mF μ gp R p' m (gF gp R q m₁ x (pt u)) (pt v)
      = σ R (Tree.tpar gp u.1 && Tree.tpar gp v.1) •
          gF gp R q m (mF μ gp R p m₂ x (pt v)) (pt u) := by
  induction x using Finsupp.induction_linear with
  | zero => simp
  | add x y hx hy => simp only [map_add, LinearMap.add_apply, hx, hy, smul_add]
  | single s c =>
    rw [← Finsupp.smul_single_one s c,
      show (Finsupp.single s (1 : R) : Pl (T := T) R n) = pt s from rfl]
    simp only [map_smul, LinearMap.smul_apply]
    rw [smul_comm]
    congr 1
    have hs := isLeaf_of_lt s (by omega)
    have ha : p < s.1.arity := by rw [s.2]; exact hp
    by_cases hv : v.1.isLeaf = true
    · rw [gF_pt_of ⟨by omega, h₁⟩, map_smul, LinearMap.smul_apply, mF_pt_leaf_right _ _ hv,
        mF_pt_leaf_right _ _ hv, map_zero, LinearMap.zero_apply, smul_zero, smul_zero]
    · have hv' : v.1.isLeaf = false := by simpa using hv
      have hG : (graftT s q u ⟨by omega, h₁⟩).1.isLeaf = false := Tree.isLeaf_graft_left hs _ _
      have hM : q < m₂ ∧ m + 1 = m₂ + lu := by omega
      rw [gF_pt_of ⟨by omega, h₁⟩, map_smul, LinearMap.smul_apply,
        mF_pt_of (μ := μ) ⟨by omega, hm⟩ hG hv', mF_pt_of (μ := μ) ⟨hp, h₂⟩ hs hv',
        map_smul, LinearMap.smul_apply, gF_pt_of hM, smul_smul, smul_smul, smul_smul]
      have htree : (mgraftT μ (graftT s q u ⟨by omega, h₁⟩) p' v ⟨by omega, hm⟩).1
          = (graftT (mgraftT μ s p v ⟨hp, h₂⟩) q u hM).1 := by
        simp only [mgraftT_val, graftT_val]
        rw [← Tree.graft_mgraft_before μ s.1 q u.1 p v.1 hqp ha, u.2]
        congr 1
        omega
      rw [pt_eq htree]
      congr 1
      simp only [graftT_val, mgraftT_val, ← σ_xor]
      congr 1
      have e := Tree.mSgn_graft_before μ gp hμ (s := s.1) (b := u.1) (u := v.1) hqp ha hv'
      rw [u.2, show p - 1 + lu = p' by omega] at e
      rw [e, Bool.xor_assoc]

/-- **Merging into a grafted tree.** -/
theorem mF_gF_inner (hμ : MergeFn.Odd gp μ) {p q r n lu lv m₁ m₂ m : ℕ} (hq : q < n)
    (hr : r < lu) (hp : p = q + r) (h₁ : m₁ + 1 = n + lu) (h₂ : m₂ + 1 = lu + lv)
    (hm : m + 1 = m₁ + lv) (x : Pl (T := T) R n) {u : TreeOfArity T lu} (hu : u.1.isLeaf = false)
    (v : TreeOfArity T lv) :
    mF μ gp R p m (gF gp R q m₁ x (pt u)) (pt v)
      = gF gp R q m (twF gp R n x) (mF μ gp R r m₂ (pt u) (pt v)) := by
  subst hp
  induction x using Finsupp.induction_linear with
  | zero => simp
  | add x y hx hy => simp only [map_add, LinearMap.add_apply, hx, hy]
  | single s c =>
    rw [← Finsupp.smul_single_one s c,
      show (Finsupp.single s (1 : R) : Pl (T := T) R n) = pt s from rfl]
    simp only [map_smul, LinearMap.smul_apply]
    congr 1
    have ha : q < s.1.arity := by rw [s.2]; exact hq
    by_cases hv : v.1.isLeaf = true
    · rw [gF_pt_of ⟨hq, h₁⟩, map_smul, LinearMap.smul_apply, mF_pt_leaf_right _ _ hv,
        mF_pt_leaf_right _ _ hv, map_zero, smul_zero]
    · have hv' : v.1.isLeaf = false := by simpa using hv
      have hG : (graftT s q u ⟨hq, h₁⟩).1.isLeaf = false := Tree.isLeaf_graft hu
      have hM : q < n ∧ m + 1 = n + m₂ := by omega
      rw [gF_pt_of ⟨hq, h₁⟩, map_smul, LinearMap.smul_apply,
        mF_pt_of (μ := μ) ⟨by omega, hm⟩ hG hv', mF_pt_of (μ := μ) ⟨hr, h₂⟩ hu hv', twF_pt,
        map_smul, map_smul, LinearMap.smul_apply, gF_pt_of hM, smul_smul, smul_smul, smul_smul]
      have htree : (mgraftT μ (graftT s q u ⟨hq, h₁⟩) (q + r) v ⟨by omega, hm⟩).1
          = (graftT s q (mgraftT μ u r v ⟨hr, h₂⟩) hM).1 := by
        simp only [mgraftT_val, graftT_val]
        exact Tree.mgraft_graft_inner μ s.1 q u.1 r v.1 ha (by rw [u.2]; exact hr) hu
      rw [pt_eq htree]
      congr 1
      simp only [graftT_val, mgraftT_val, ← σ_xor]
      congr 1
      rw [Tree.mSgn_graft_inner μ gp hμ ha (by rw [u.2]; exact hr) hu hv']
      cases Tree.tpar gp s.1 <;> cases Tree.mSgn gp u.1 r v.1 <;>
        cases Tree.tpar gp (Tree.mgraft μ u.1 r v.1) && Tree.apar gp s.1 q <;> rfl

/-- **Merging corollas.** -/
theorem mF_corolla {a k l m : ℕ} (h : a < k ∧ m + 1 = k + l) (g : T k) (c : T l) :
    mF μ gp R a m (pt (corolla g)) (pt (corolla c)) = pt (corolla (μ k l g a c m)) := by
  rw [mF_pt_of (μ := μ) h rfl rfl]
  have hs : Tree.mSgn gp (corolla g).1 a (corolla c).1 = false := mSgn_corolla gp g c h.1
  rw [hs, σ_false, one_smul]
  refine pt_eq ?_
  show (Tree.node g (TreeOfArity.leaves k)).mgraft μ a (Tree.node c (TreeOfArity.leaves l))
    = Tree.node (μ k l g a c m) (TreeOfArity.leaves m)
  rw [corolla_mgraft μ g c h.1]
  have : Forest.spliceLen k a l = m := by have := spliceLen_eq (k := k) (j := a) l h.1; omega
  rw [this]

lemma dF_corolla {k : ℕ} (g : T k) : dF μ gp R k (pt (corolla g)) = 0 := by
  rw [dF_pt]
  have : (corolla g).1.weight = 1 := by
    show (Tree.node g (TreeOfArity.leaves k)).weight = 1
    rw [Tree.weight_node, weightF_leaves]
  rw [this, Finset.Ico_self, Finset.sum_empty]

lemma twF_twF {n : ℕ} (x : Pl (T := T) R n) : twF gp R n (twF gp R n x) = x := by
  induction x using Finsupp.induction_linear with
  | zero => simp
  | add x y hx hy => rw [map_add, map_add, hx, hy]
  | single s c =>
    rw [← Finsupp.smul_single_one s c,
      show (Finsupp.single s (1 : R) : Pl (T := T) R n) = pt s from rfl, map_smul, map_smul,
      twF_pt, map_smul, twF_pt, smul_smul, smul_smul, mul_assoc, σ_mul_self, mul_one]

lemma dF_twF (hμ : MergeFn.Odd gp μ) {n : ℕ} (x : Pl (T := T) R n) :
    dF μ gp R n (twF gp R n x) = -twF gp R n (dF μ gp R n x) := by
  induction x using Finsupp.induction_linear with
  | zero => simp
  | add x y hx hy => rw [map_add, map_add, hx, hy, map_add, map_add, neg_add]
  | single s c =>
    rw [← Finsupp.smul_single_one s c,
      show (Finsupp.single s (1 : R) : Pl (T := T) R n) = pt s from rfl, map_smul, map_smul,
      map_smul, map_smul, ← smul_neg]
    congr 1
    rw [twF_pt, map_smul, dF_pt, map_sum, Finset.smul_sum, ← Finset.sum_neg_distrib]
    refine Finset.sum_congr rfl fun k hk => ?_
    rw [Finset.mem_Ico] at hk
    rw [map_smul, twF_pt, contrT_val, Tree.tpar_contr μ gp hμ hk.1 hk.2, smul_smul, smul_smul,
      ← neg_smul]
    congr 1
    cases Tree.tpar gp s.1 <;> simp [mul_comm]

lemma twF_mF_pt (hμ : MergeFn.Odd gp μ) (a : ℕ) {n l m : ℕ} (s : TreeOfArity T n)
    (u : TreeOfArity T l) :
    twF gp R m (mF μ gp R a m (pt s) (pt u))
      = -(σ R (Tree.tpar gp s.1) * σ R (Tree.tpar gp u.1)) • mF μ gp R a m (pt s) (pt u) := by
  rw [mF_pt]
  split_ifs with h1 h2
  · rw [map_smul, twF_pt, mgraftT_val, Tree.tpar_mgraft μ gp hμ _ _ _
      (by rw [s.2]; exact h1.1) h2.1 h2.2, smul_smul, smul_smul]
    congr 1
    cases Tree.tpar gp s.1 <;> cases Tree.tpar gp u.1 <;> simp
  · simp
  · simp

lemma twF_mF (hμ : MergeFn.Odd gp μ) (a : ℕ) {n l m : ℕ} (x : Pl (T := T) R n)
    (y : Pl (T := T) R l) :
    twF gp R m (mF μ gp R a m x y) = -mF μ gp R a m (twF gp R n x) (twF gp R l y) := by
  induction x using Finsupp.induction_linear with
  | zero => simp
  | add x x' hx hx' => simp only [map_add, LinearMap.add_apply, hx, hx', neg_add]
  | single s c =>
    induction y using Finsupp.induction_linear with
    | zero => simp
    | add y y' hy hy' => simp only [map_add, hy, hy', neg_add]
    | single u d =>
      rw [← Finsupp.smul_single_one s c, ← Finsupp.smul_single_one u d,
        show (Finsupp.single s (1 : R) : Pl (T := T) R n) = pt s from rfl,
        show (Finsupp.single u (1 : R) : Pl (T := T) R l) = pt u from rfl]
      simp only [map_smul, LinearMap.smul_apply, twF_pt]
      rw [twF_mF_pt hμ]
      module

lemma twF_gF (a : ℕ) {n l m : ℕ} (x : Pl (T := T) R n) (y : Pl (T := T) R l) :
    twF gp R m (gF gp R a m x y) = gF gp R a m (twF gp R n x) (twF gp R l y) := by
  induction x using Finsupp.induction_linear with
  | zero => simp
  | add x x' hx hx' => simp only [map_add, LinearMap.add_apply, hx, hx']
  | single s c =>
    induction y using Finsupp.induction_linear with
    | zero => simp
    | add y y' hy hy' => simp only [map_add, hy, hy']
    | single u d =>
      rw [← Finsupp.smul_single_one s c, ← Finsupp.smul_single_one u d,
        show (Finsupp.single s (1 : R) : Pl (T := T) R n) = pt s from rfl,
        show (Finsupp.single u (1 : R) : Pl (T := T) R l) = pt u from rfl]
      simp only [map_smul, LinearMap.smul_apply, twF_pt]
      rw [gF_pt]
      split_ifs with h
      · rw [map_smul, twF_pt, graftT_val, Tree.tpar_graft gp _ _ _ (by rw [s.2]; exact h.1),
          σ_xor]
        module
      · simp

end PlanarLaws

/-! ## The last vertex of a tree -/

section LastVertex

lemma eq_leaves_of_weightF : ∀ {k : ℕ} (f : Forest T k), f.weightF = 0 →
    f = TreeOfArity.leaves k
  | 0, .nil, _ => rfl
  | _, .cons t f, h => by
    simp only [Tree.weightF_cons] at h
    have ht : t.weight = 0 := by omega
    have hf := eq_leaves_of_weightF f (by omega)
    cases t with
    | leaf =>
      rw [hf]
      rfl
    | node e g => simp at ht

/-- A tree with one vertex is a corolla. -/
lemma eq_corolla_of_weight {t : Tree T} (h : t.weight = 1) :
    ∃ (k : ℕ) (g : T k), t = Tree.node g (TreeOfArity.leaves k) := by
  cases t with
  | leaf => simp at h
  | node g f =>
    simp only [Tree.weight_node] at h
    exact ⟨_, g, by rw [eq_leaves_of_weightF f (by omega)]⟩

/-- **A tree with at least two vertices is a tree with one vertex less, grafted with the corolla
of its last vertex.** -/
lemma exists_graft_corolla {t : Tree T} (h : 2 ≤ t.weight) :
    ∃ (s : Tree T) (p k : ℕ) (g : T k), p < s.arity ∧ s.weight + 1 = t.weight ∧
      t = s.graft p (Tree.node g (TreeOfArity.leaves k)) := by
  obtain ⟨h1, h2, h3, h4⟩ := Tree.cutV_spec (t := t) (k := t.weight - 1) (by omega) rfl
  set s := (t.cutV (t.weight - 1)).1
  set u := (t.cutV (t.weight - 1)).2.1
  set p := (t.cutV (t.weight - 1)).2.2
  have hw := Tree.weight_graft s p u h2
  rw [h1] at hw
  have hv := Tree.vb_le_weight s p
  have hu := Tree.weight_pos h4
  obtain ⟨k, g, hg⟩ := eq_corolla_of_weight (t := u) (by omega)
  exact ⟨s, p, k, g, h2, by omega, by rw [← hg, h1]⟩

end LastVertex

/-! ## Membership in an ideal -/

section Ideal

variable {μ} (J : GrOperadIdeal R (FreeGr R gp))

/-- The planar combinations landing in an ideal. -/
noncomputable def JF (n : ℕ) : Submodule R (Pl (T := T) R n) := (J.sub (Fin n)).comap (ιP gp R n)

variable {J}

lemma gF_mem_left {a n l m : ℕ} {x : Pl (T := T) R n} (hx : x ∈ JF J n) (y : Pl (T := T) R l) :
    gF gp R a m x y ∈ JF J m := by
  by_cases h : a < n ∧ m + 1 = n + l
  · show ιP gp R m (gF gp R a m x y) ∈ J.sub (Fin m)
    rw [ιP_gF h]
    exact J.map_mem _ (J.comp_mem_left _ _ hx)
  · rw [gF_of_not h]
    exact zero_mem _

lemma gF_mem_right {a n l m : ℕ} (x : Pl (T := T) R n) {y : Pl (T := T) R l} (hy : y ∈ JF J l) :
    gF gp R a m x y ∈ JF J m := by
  by_cases h : a < n ∧ m + 1 = n + l
  · show ιP gp R m (gF gp R a m x y) ∈ J.sub (Fin m)
    rw [ιP_gF h]
    exact J.map_mem _ (J.comp_mem_right _ _ hy)
  · rw [gF_of_not h]
    exact zero_mem _

lemma ιP_corolla {k : ℕ} (g : T k) :
    ιP gp R k (pt (corolla g)) = gen (R := R) (gp := gp) g := ιP_pt _

variable (μ gp R) in
/-- **Associativity of the merge function modulo an ideal**, for merges in series and in
parallel. -/
structure AssocHyp (J : GrOperadIdeal R (FreeGr R gp)) : Prop where
  series : ∀ (kx lg lh : ℕ) (x : T kx) (g : T lg) (h : T lh) (p j m₁ m₂ m : ℕ), p < kx →
    j < lg → m₁ + 1 = lg + lh → m₂ + 1 = kx + lg → m + 1 = kx + m₁ →
    σ R (gp kx x) • gen (R := R) (gp := gp) (μ kx m₁ x p (μ lg lh g j h m₁) m)
      + gen (R := R) (gp := gp) (μ m₂ lh (μ kx lg x p g m₂) (p + j) h m) ∈ J.sub (Fin m)
  parallel : ∀ (kx l₁ l₂ : ℕ) (x : T kx) (a₁ : T l₁) (a₂ : T l₂) (p₁ p₂ m₁ m₂ m : ℕ),
    p₁ < p₂ → p₂ < kx → m₁ + 1 = kx + l₁ → m₂ + 1 = kx + l₂ → m + 1 = m₁ + l₂ →
    σ R (gp l₁ a₁ && gp l₂ a₂) •
        gen (R := R) (gp := gp) (μ m₁ l₂ (μ kx l₁ x p₁ a₁ m₁) (p₂ + l₁ - 1) a₂ m)
      + gen (R := R) (gp := gp) (μ m₂ l₁ (μ kx l₂ x p₂ a₂ m₂) p₁ a₁ m) ∈ J.sub (Fin m)

end Ideal

/-! ## Merging two corollas in series -/

section Series

variable {μ}

variable (μ gp R) in
/-- **Merging two corollas in series**, in the two orders. -/
noncomputable def SF (p j m₁ m₂ m : ℕ) {n lg lh : ℕ} (x : Pl (T := T) R n) (g : TreeOfArity T lg)
    (h : TreeOfArity T lh) : Pl (T := T) R m :=
  mF μ gp R p m (twF gp R n x) (mF μ gp R j m₁ (pt g) (pt h))
    + mF μ gp R (p + j) m (mF μ gp R p m₂ x (pt g)) (pt h)

lemma SF_smul (p j m₁ m₂ m : ℕ) {n lg lh : ℕ} (c : R) (x : Pl (T := T) R n)
    (g : TreeOfArity T lg) (h : TreeOfArity T lh) :
    SF μ gp R p j m₁ m₂ m (c • x) g h = c • SF μ gp R p j m₁ m₂ m x g h := by
  simp only [SF, map_smul, LinearMap.smul_apply, smul_add]

lemma twF_gF_pt (a : ℕ) {n l m : ℕ} (x : Pl (T := T) R n) (c : TreeOfArity T l) :
    twF gp R m (gF gp R a m x (pt c)) = σ R (Tree.tpar gp c.1) • gF gp R a m (twF gp R n x) (pt c) := by
  rw [twF_gF, twF_pt, map_smul]

lemma tpar_corolla' {k : ℕ} (g : T k) : Tree.tpar gp (corolla g).1 = gp k g :=
  Tree.tpar_corolla gp g

lemma isLeaf_corolla {k : ℕ} (g : T k) : (corolla g).1.isLeaf = false := rfl

lemma σ_and_not_xor (a b c : Bool) :
    σ R a * σ R (a && !(xor b c)) = σ R (a && xor b c) := by
  cases a <;> cases b <;> cases c <;> simp

lemma σ_and_and (a b c : Bool) :
    σ R (a && b) * σ R (a && c) = σ R (a && xor b c) := by
  cases a <;> cases b <;> cases c <;> simp

/-- Merging in series at a leaf before a graft point. -/
theorem SF_gF_after (hμ : MergeFn.Odd gp μ) {p j r r' n n₁ lc lg lh m₁ m₂ m mA mB : ℕ}
    (hpr : p < r) (hr : r < n₁) (hn : n + 1 = n₁ + lc) (hj : j < lg) (hm₁ : m₁ + 1 = lg + lh)
    (hm₂ : m₂ + 1 = n + lg) (hm : m + 1 = n + m₁) (hr' : r' + 1 = r + m₁)
    (hmA : mA + 1 = n₁ + m₁) (hmB : mB + 1 = n₁ + lg) (X : Pl (T := T) R n₁) (c : T lc)
    (g : T lg) (h : T lh) :
    SF μ gp R p j m₁ m₂ m (gF gp R r n X (pt (corolla c))) (corolla g) (corolla h)
      = σ R (gp lc c && xor (gp lg g) (gp lh h)) •
          gF gp R r' m (SF μ gp R p j m₁ mB mA X (corolla g) (corolla h)) (pt (corolla c)) := by
  have hY := mF_corolla (μ := μ) (gp := gp) (R := R) ⟨hj, hm₁⟩ g h
  obtain ⟨rB, hrB⟩ : ∃ rB, rB + 1 = r + lg := ⟨r + lg - 1, by omega⟩
  unfold SF
  rw [twF_gF_pt, hY, map_smul, LinearMap.smul_apply,
    mF_gF_after (μ := μ) hpr hr hr' hn hmA hm _ (corolla c) (corolla (μ lg lh g j h m₁)),
    mF_gF_after (μ := μ) hpr hr hrB hn hmB hm₂ X (corolla c) (corolla g), map_smul,
    LinearMap.smul_apply,
    mF_gF_after (μ := μ) (show p + j < rB by omega) (show rB < mB by omega)
      (show r' + 1 = rB + lh by omega) (show m₂ + 1 = mB + lc by omega)
      (show mA + 1 = mB + lh by omega) (show m + 1 = m₂ + lh by omega) _ (corolla c) (corolla h),
    map_add, LinearMap.add_apply, smul_add]
  simp only [tpar_corolla', hμ, smul_smul, σ_and_not_xor, σ_and_and]

/-- Merging in series at a leaf of the grafted corolla. -/
theorem SF_gF_inner (hμ : MergeFn.Odd gp μ) {p p' j r n n₁ lc lg lh m₁ m₂ m mD mE : ℕ}
    (hr : r < n₁) (hp : p = r + p') (hp' : p' < lc) (hn : n + 1 = n₁ + lc) (hj : j < lg)
    (hm₁ : m₁ + 1 = lg + lh) (hm₂ : m₂ + 1 = n + lg) (hm : m + 1 = n + m₁)
    (hmD : mD + 1 = lc + lg) (hmE : mE + 1 = lc + m₁) (X : Pl (T := T) R n₁) (c : T lc)
    (g : T lg) (h : T lh) :
    SF μ gp R p j m₁ m₂ m (gF gp R r n X (pt (corolla c))) (corolla g) (corolla h)
      = gF gp R r m X (SF μ gp R p' j m₁ mD mE (pt (corolla c)) (corolla g) (corolla h)) := by
  have hY := mF_corolla (μ := μ) (gp := gp) (R := R) ⟨hj, hm₁⟩ g h
  have hW := mF_corolla (μ := μ) (gp := gp) (R := R) ⟨hp', hmD⟩ c g
  unfold SF
  rw [twF_gF_pt, hY, map_smul, LinearMap.smul_apply,
    mF_gF_inner (μ := μ) hμ hr hp' hp hn hmE hm _ (isLeaf_corolla c) (corolla (μ lg lh g j h m₁)),
    twF_twF, mF_gF_inner (μ := μ) hμ hr hp' hp hn hmD hm₂ X (isLeaf_corolla c) (corolla g), hW,
    mF_gF_inner (μ := μ) hμ hr (show p' + j < mD by omega) (show p + j = r + (p' + j) by omega)
      (show m₂ + 1 = n₁ + mD by omega) (show mE + 1 = mD + lh by omega)
      (show m + 1 = m₂ + lh by omega) _ (isLeaf_corolla _) (corolla h),
    twF_twF, twF_pt, map_smul, LinearMap.smul_apply, map_add, map_smul]

/-- Merging in series at a leaf after a graft point. -/
theorem SF_gF_before (hμ : MergeFn.Odd gp μ) {p p₁ j r n n₁ lc lg lh m₁ m₂ m mA mB : ℕ}
    (hrp : r < p₁) (hp₁ : p₁ < n₁) (hp : p + 1 = p₁ + lc) (hn : n + 1 = n₁ + lc) (hj : j < lg)
    (hm₁ : m₁ + 1 = lg + lh) (hm₂ : m₂ + 1 = n + lg) (hm : m + 1 = n + m₁)
    (hmA : mA + 1 = n₁ + m₁) (hmB : mB + 1 = n₁ + lg) (X : Pl (T := T) R n₁) (c : T lc)
    (g : T lg) (h : T lh) :
    SF μ gp R p j m₁ m₂ m (gF gp R r n X (pt (corolla c))) (corolla g) (corolla h)
      = σ R (gp lc c && xor (gp lg g) (gp lh h)) •
          gF gp R r m (SF μ gp R p₁ j m₁ mB mA X (corolla g) (corolla h)) (pt (corolla c)) := by
  have hY := mF_corolla (μ := μ) (gp := gp) (R := R) ⟨hj, hm₁⟩ g h
  unfold SF
  rw [twF_gF_pt, hY, map_smul, LinearMap.smul_apply,
    mF_gF_before (μ := μ) hμ hrp hp₁ hp hn hmA hm _ (corolla c) (corolla (μ lg lh g j h m₁)),
    mF_gF_before (μ := μ) hμ hrp hp₁ hp hn hmB hm₂ X (corolla c) (corolla g), map_smul,
    LinearMap.smul_apply,
    mF_gF_before (μ := μ) hμ (show r < p₁ + j by omega) (show p₁ + j < mB by omega)
      (show p + j + 1 = p₁ + j + lc by omega) (show m₂ + 1 = mB + lc by omega)
      (show mA + 1 = mB + lh by omega) (show m + 1 = m₂ + lh by omega) _ (corolla c) (corolla h),
    map_add, LinearMap.add_apply, smul_add]
  simp only [tpar_corolla', hμ, smul_smul, σ_and_not_xor, σ_and_and]

end Series

end FreeGr

end Operad
