/-
# Koszul duality for binary quadratic operads

For binary generators `G`, the free operad has, in arity three, a basis of `12 |G|²` monomials:
`g (h (x_{σ0}, x_{σ1}), x_{σ2})` and `g (x_{σ0}, h (x_{σ1}, x_{σ2}))` for `g, h ∈ G` and
`σ ∈ 𝔖₃` (`basis3`). They are independent because they act on a free model, the labelled trees
with each generator grafting its two inputs (`Words`), as different trees (`mono3_independent`),
and they span because there are as many of them as operations of arity three in the free set
operad (`FreeBin.regIso`).

**Koszul duality.** Over a field `K` and for finitely many generators:

* the relations of arity three generated by a set of relators `r` are the span of its orbit under
  relabelling (`span_sub_three`), so two sets of relators with the same orbit span present the
  same operad (`span_eq_of_span_orbit3_eq`);
* the **Koszul pairing** `pair3` makes the monomials orthogonal, each of square `±1`: the
  signature of its relabelling, negated for the second shape. It is symmetric and nondegenerate,
  and relabelling multiplies it by the signature (`pair3_map`);
* the **Koszul dual relations** `dualRel r` are the orthogonal of the relations; they are stable
  under relabelling, of the complementary dimension `12 |G|² - dim` (`finrank_dualRel`), and
  **duality is an involution**: `dualRel (dualRel r) = span (orbit r)` (`dualRel_dualRel`,
  `dual_dual`). `BinPres.dual r` is the Koszul dual operad;
* orthogonal relators whose spans have complementary dimensions are dual to each other
  (`dualRel_eq_of_orthogonal`); the lower bounds on the dimensions come from vectors with private
  coordinates (`le_finrank_of_private`).

The classical dualities follow: `Ass^! = Ass` (`BinAss.dual`), `PreLie^! = Perm` and
`Perm^! = PreLie` (`PreLie.dual`, `BinPerm.dual`), `Leib^! = Zinb` and `Zinb^! = Leib`, and Loday's
`Dend^! = Dias` and `Dias^! = Dend`, with `≺` paired with `⊣` and `≻` with `⊢`. Each is an equality
of operads: the dual relations generate the same operad ideal as the classical relators
(`BinPres.dual_eq`).

The generators here carry the regular action of `𝔖₂` (no relators of arity two); commutative and
anticommutative generators, and `Com^! = Lie`, are in `Operad.BinaryKoszulSym`.
-/
import Operad.FreeBinary
import Operad.ShuffleTree
import Mathlib.LinearAlgebra.BilinearForm.Orthogonal

universe u v

namespace Operad

open Sym SetOperad

namespace FreeBin

variable (G : Type v)

/-- **The monomials of arity three**: the shape (`false` for `g (h (·, ·), ·)`, `true` for
`g (·, h (·, ·))`), the two generators and the relabelling of the inputs. -/
abbrev Mono3 := Bool × G × G × Equiv.Perm (Fin 3)

variable {G}

/-- The operation of the free set operad of a monomial of arity three. -/
def mono3Set : Mono3 G → FreeSet (BinGen G) (Fin 3)
  | (false, g, h, σ) => Pres.mk (.map (fin3Left.symm.trans σ)
      (Syn.bin (gen g) (Syn.bin (gen h) .one .one) .one))
  | (true, g, h, σ) => Pres.mk (.map (fin3Right.symm.trans σ)
      (Syn.bin (gen g) .one (Syn.bin (gen h) .one .one)))

variable (R : Type u) [CommRing R]

/-- **The monomial of arity three**, in the free operad in modules. -/
noncomputable def mono3 (m : Mono3 G) : FreeBin R G (Fin 3) := Finsupp.single (mono3Set m) 1

lemma mono3_false (g h : G) (σ : Equiv.Perm (Fin 3)) : mono3 R (false, g, h, σ) = binL g h σ :=
  rfl

lemma mono3_true (g h : G) (σ : Equiv.Perm (Fin 3)) : mono3 R (true, g, h, σ) = binR g h σ :=
  rfl

/-! ### A free model -/

variable (G) in
/-- **Words**: the formal combinations of trees with labelled leaves. -/
abbrev Words := LTree G →₀ R

/-- **Grafting under a generator**, a bilinear operation on words. -/
noncomputable def graftL (g : G) : Words G R →ₗ[R] Words G R →ₗ[R] Words G R :=
  Finsupp.lift (Words G R →ₗ[R] Words G R) R (LTree G) fun a =>
    Finsupp.lift (Words G R) R (LTree G) fun b => Finsupp.single (.node g a b) 1

lemma graftL_single (g : G) (a b : LTree G) :
    graftL R g (Finsupp.single a 1) (Finsupp.single b 1) = Finsupp.single (.node g a b) 1 := by
  simp [graftL]

variable {R} in
/-- A bilinear operation, as an operation of the endomorphism operad. -/
def bilinOp {V : Type v} [AddCommGroup V] [Module R V] (β : V →ₗ[R] V →ₗ[R] V) :
    EndOp R V (Fin 2) where
  toFun w := β (w 0) (w 1)
  map_update_add' w i x y := by
    fin_cases i <;> simp [Function.update, map_add]
  map_update_smul' w i c x := by
    fin_cases i <;> simp [Function.update, map_smul]

lemma bilinOp_apply {V : Type v} [AddCommGroup V] [Module R V] (β : V →ₗ[R] V →ₗ[R] V)
    (x y : V) : bilinOp β ![x, y] = β x y := rfl

/-- The word of a monomial. -/
def word : Mono3 G → LTree G
  | (false, g, h, σ) => .node g (.node h (.leaf (σ 0)) (.leaf (σ 1))) (.leaf (σ 2))
  | (true, g, h, σ) => .node g (.leaf (σ 0)) (.node h (.leaf (σ 1)) (.leaf (σ 2)))

lemma perm3_ext {σ σ' : Equiv.Perm (Fin 3)} (h0 : (σ 0 : ℕ) = σ' 0) (h1 : (σ 1 : ℕ) = σ' 1)
    (h2 : (σ 2 : ℕ) = σ' 2) : σ = σ' := by
  ext k
  fin_cases k
  · exact h0
  · exact h1
  · exact h2

lemma word_injective : Function.Injective (word (G := G)) := by
  rintro ⟨_ | _, g, h, σ⟩ ⟨_ | _, g', h', σ'⟩ heq <;>
    simp only [word, LTree.node.injEq, LTree.leaf.injEq, reduceCtorEq, and_false] at heq
  · obtain ⟨rfl, ⟨rfl, h0, h1⟩, h2⟩ := heq
    rw [perm3_ext h0 h1 h2]
  · obtain ⟨rfl, h0, rfl, h1, h2⟩ := heq
    rw [perm3_ext h0 h1 h2]

/-- **A monomial acts on the free model as its word.** -/
lemma binHom_mono3_word (m : Mono3 G) :
    (binHom (fun g => bilinOp (graftL R g))).app (Fin 3) (mono3 R m)
      (fun k => Finsupp.single (.leaf k) 1) = Finsupp.single (word m) 1 := by
  rcases m with ⟨_ | _, g, h, σ⟩
  · rw [mono3_false, binHom_binL]
    simp only [bilinOp_apply, graftL_single]
    rfl
  · rw [mono3_true, binHom_binR]
    simp only [bilinOp_apply, graftL_single]
    rfl

/-- **The monomials of arity three are linearly independent.** -/
theorem mono3_independent : LinearIndependent R (mono3 (G := G) R) := by
  classical
  rw [linearIndependent_iff']
  intro s c hc m hm
  have := congrArg (fun x => (binHom (fun g => bilinOp (graftL R g))).app (Fin 3) x
    (fun k => Finsupp.single (.leaf k) 1)) hc
  simp only [map_sum, map_smul, MultilinearMap.coe_sum, MultilinearMap.smul_apply,
    Finset.sum_apply, binHom_mono3_word, map_zero, MultilinearMap.zero_apply] at this
  have h2 := congrArg (fun f : Words G R => f (word m)) this
  simp only [Finsupp.coe_finsetSum, Finset.sum_apply, Finsupp.coe_smul, Pi.smul_apply,
    smul_eq_mul, Finsupp.coe_zero, Pi.zero_apply] at h2
  rw [Finset.sum_eq_single m] at h2
  · simpa using h2
  · intro b _ hb
    rw [Finsupp.single_apply, if_neg (fun h => hb (word_injective h)), mul_zero]
  · intro hm'
    exact absurd hm hm'

/-! ### The basis -/

section Basis

variable [Fintype G] [DecidableEq G]

/-- The trees of arity three: the two combs. -/
def comb3 : Bool × G × G → BTree.OfArity G 3
  | (false, g, h) => ⟨.node g (.node h .leaf .leaf) .leaf, rfl⟩
  | (true, g, h) => ⟨.node g .leaf (.node h .leaf .leaf), rfl⟩

omit [Fintype G] [DecidableEq G] in
lemma comb3_bijective : Function.Bijective (comb3 (G := G)) := by
  constructor
  · intro x y hxy
    have h := congrArg Subtype.val hxy
    rcases x with ⟨_ | _, g, h₁⟩ <;> rcases y with ⟨_ | _, g', h₁'⟩ <;>
      simp only [comb3, BTree.node.injEq, reduceCtorEq, and_false, and_true, true_and] at h
    · obtain ⟨rfl, rfl⟩ := h
      rfl
    · obtain ⟨rfl, rfl⟩ := h
      rfl
  · rintro ⟨t, ht⟩
    rcases t with _ | ⟨g, l, r⟩
    · simp at ht
    · simp only [BTree.arity_node] at ht
      have hl := BTree.arity_pos l
      have hr := BTree.arity_pos r
      have two : ∀ u : BTree G, u.arity = 2 → ∃ h, u = .node h .leaf .leaf := by
        intro u hu
        rcases u with _ | ⟨h, a, b⟩
        · simp at hu
        · simp only [BTree.arity_node] at hu
          have ha := BTree.arity_pos a
          have hb := BTree.arity_pos b
          exact ⟨h, by rw [BTree.eq_leaf_of_arity_eq_one (by omega : a.arity = 1),
            BTree.eq_leaf_of_arity_eq_one (by omega : b.arity = 1)]⟩
      by_cases h1 : l.arity = 1
      · obtain rfl := BTree.eq_leaf_of_arity_eq_one h1
        obtain ⟨h, rfl⟩ := two r (by simp only [BTree.arity_leaf] at ht; omega)
        exact ⟨(true, g, h), rfl⟩
      · obtain ⟨h, rfl⟩ := two l (by omega)
        obtain rfl := BTree.eq_leaf_of_arity_eq_one
          (by simp only [BTree.arity_node, BTree.arity_leaf] at ht; omega : r.arity = 1)
        exact ⟨(false, g, h), rfl⟩

/-- **There are `2 |G|²` trees of arity three.** -/
lemma card_ofArity_three : Fintype.card (BTree.OfArity G 3) = 2 * Fintype.card G ^ 2 := by
  rw [← Fintype.card_congr (Equiv.ofBijective _ comb3_bijective), Fintype.card_prod,
    Fintype.card_prod, Fintype.card_bool]
  ring

omit [Fintype G] [DecidableEq G] in
lemma finite_reg (N : ℕ → Type v) [∀ n, Finite (N n)] (A : Type) [Fintype A] [DecidableEq A] :
    Finite (Reg N A) :=
  Finite.of_equiv (LinOrd A × N (Fintype.card A))
    (Equiv.prodCongr (Equiv.refl _) (arrEquiv N _).symm)

/-- **There are `12 |G|²` operations of arity three** in the free set operad. -/
lemma natCard_freeSet_three : Nat.card (FreeSet (BinGen G) (Fin 3)) = 12 * Fintype.card G ^ 2 := by
  rw [Nat.card_congr (regIso.equiv (Fin 3)), card_reg, Fintype.card_fin, Nat.card_eq_fintype_card,
    card_ofArity_three, show (3 : ℕ).factorial = 6 from rfl]
  ring

/-- **Every operation of arity three of the free set operad is a monomial**, in exactly one
way. -/
theorem mono3Set_bijective : Function.Bijective (mono3Set (G := G)) := by
  have hinj : Function.Injective (mono3Set (G := G)) := fun m m' h =>
    (mono3_independent (G := G) ℤ).injective (by
      show Finsupp.single (mono3Set m) (1 : ℤ) = Finsupp.single (mono3Set m') 1
      rw [h])
  haveI := finite_reg (BTree.OfArity G) (Fin 3)
  haveI : Finite (FreeSet (BinGen G) (Fin 3)) := Finite.of_equiv _ (regIso.equiv (Fin 3)).symm
  refine hinj.bijective_of_nat_card_le ?_
  rw [natCard_freeSet_three, Nat.card_eq_fintype_card]
  simp only [Fintype.card_prod, Fintype.card_bool, Fintype.card_perm, Fintype.card_fin,
    show (3 : ℕ).factorial = 6 from rfl]
  nlinarith [sq_nonneg (Fintype.card G)]

/-- **The monomials of arity three span**: every element of arity three is a combination of
them. -/
theorem span_mono3 : Submodule.span R (Set.range (mono3 (G := G) R)) = ⊤ := by
  rw [eq_top_iff]
  rintro x -
  induction x using Finsupp.induction_linear with
  | zero => exact Submodule.zero_mem _
  | add x y hx hy => exact Submodule.add_mem _ hx hy
  | single a r =>
    obtain ⟨m, rfl⟩ := mono3Set_bijective.2 a
    have : Finsupp.single (mono3Set m) r = r • mono3 R m := by
      rw [mono3, Finsupp.smul_single, smul_eq_mul, mul_one]
    rw [this]
    exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨m, rfl⟩)

/-- **The basis of monomials** of the free operad on binary generators, in arity three. -/
noncomputable def basis3 : Module.Basis (Mono3 G) R (FreeBin R G (Fin 3)) :=
  Module.Basis.mk (mono3_independent R) (span_mono3 R).ge

@[simp] lemma basis3_apply (m : Mono3 G) : basis3 R m = mono3 R m := by
  simp [basis3]

end Basis

/-! ## Arities zero and one -/

section LowArity

variable {A : Type} [Fintype A] [DecidableEq A]

/-- **There is no operation without inputs.** -/
lemma isEmpty_freeSet (h : Fintype.card A = 0) : IsEmpty (FreeSet (BinGen G) A) := by
  refine ⟨fun x => ?_⟩
  obtain ⟨_, ⟨⟨n, t⟩, hn⟩⟩ := regIso.equiv A x
  have := BTree.arity_pos t.1
  rw [t.2] at this
  simp only at hn
  omega

/-- **The only operation with one input is the identity.** -/
lemma subsingleton_freeSet (h : Fintype.card A = 1) : Subsingleton (FreeSet (BinGen G) A) := by
  refine ⟨fun x y => (regIso.equiv A).injective ?_⟩
  haveI : Subsingleton A := Fintype.card_le_one_iff_subsingleton.1 h.le
  obtain ⟨L, ⟨⟨n, t⟩, hn⟩⟩ := regIso.equiv A x
  obtain ⟨L', ⟨⟨n', t'⟩, hn'⟩⟩ := regIso.equiv A y
  simp only at hn hn'
  refine Reg.ext (LinOrd.eq_of_subsingleton _ _) (BTree.OfArity.arr_ext ?_)
  show t.1 = t'.1
  rw [BTree.eq_leaf_of_arity_eq_one (t.2.trans (hn.trans h)),
    BTree.eq_leaf_of_arity_eq_one (t'.2.trans (hn'.trans h))]

lemma freeBin_eq_zero (h : Fintype.card A = 0) (x : FreeBin R G A) : x = 0 := by
  haveI := isEmpty_freeSet (G := G) h
  exact Finsupp.ext fun a => isEmptyElim a

lemma freeBin_eq_smul_single (h : Fintype.card A = 1) (t : FreeSet (BinGen G) A)
    (x : FreeBin R G A) : x = x t • Finsupp.single t 1 := by
  haveI := subsingleton_freeSet (G := G) h
  ext a
  rw [Subsingleton.elim a t]
  simp

omit [Fintype A] [DecidableEq A] in
/-- Composing the identity, relabelled, on the right is a relabelling. -/
lemma comp_map_one {S : (A : Type) → [Fintype A] → [DecidableEq A] → Type v} [SetOperad S]
    [Fintype A] [DecidableEq A] {B : Type} [Fintype B] [DecidableEq B] (i : A) (s : S A)
    (u : Unit ≃ B) :
    SetOperad.comp i s (SetOperad.map u SetOperad.one)
      = SetOperad.map ((rightUnitEquiv i).symm.trans (Equiv.sumCongr (Equiv.refl _) u)) s := by
  rw [comp_map_right, comp_one', map_trans]

omit [Fintype A] [DecidableEq A] in
/-- Composing into the identity, relabelled, is a relabelling. -/
lemma map_one_comp {S : (A : Type) → [Fintype A] → [DecidableEq A] → Type v} [SetOperad S]
    [Fintype A] [DecidableEq A] {B : Type} [Fintype B] [DecidableEq B] (u : Unit ≃ A) {i : A}
    (hi : u () = i) (y : S B) :
    SetOperad.comp i (SetOperad.map u SetOperad.one) y
      = SetOperad.map ((leftUnitEquiv B).symm.trans
          ((compEquiv u (Equiv.refl B) ()).trans (slotEquiv hi))) y := by
  rw [comp_map_left_of u hi, one_comp']
  simp only [map_trans]

end LowArity

/-! ## The ideal generated in arity three -/

section Ideal3

/-- The relabellings of a set of elements of arity three. -/
def orbit3 (r : Set (FreeBin R G (Fin 3))) : Set (FreeBin R G (Fin 3)) :=
  {x | ∃ τ : Equiv.Perm (Fin 3), ∃ y ∈ r, x = SymOperad.map (R := R) τ y}

/-- Composing with the identity, relabelled, on the right is a relabelling, linearly. -/
lemma comp_single_unit {A : Type} [Fintype A] [DecidableEq A] {B : Type} [Fintype B] [DecidableEq B]
    (i : A) (u : Unit ≃ B) (x : FreeBin R G A) :
    SymOperad.comp (R := R) i x (Finsupp.single (SetOperad.map u SetOperad.one) 1)
      = SymOperad.map (R := R)
          ((rightUnitEquiv i).symm.trans (Equiv.sumCongr (Equiv.refl _) u)) x := by
  induction x using Finsupp.induction_linear with
  | zero => simp
  | add x y hx hy => simp only [map_add, LinearMap.add_apply, hx, hy]
  | single s r =>
    show Lin.compL R i (Finsupp.single s r) (Finsupp.single _ 1) = Lin.mapL R _ (Finsupp.single s r)
    rw [Lin.compL_single, Lin.mapL_single, comp_map_one, mul_one]

/-- Composing into the identity, relabelled, is a relabelling, linearly. -/
lemma comp_unit_single {A : Type} [Fintype A] [DecidableEq A] {B : Type} [Fintype B] [DecidableEq B]
    (u : Unit ≃ A) {i : A} (hi : u () = i) (y : FreeBin R G B) :
    SymOperad.comp (R := R) i (Finsupp.single (SetOperad.map u SetOperad.one) 1) y
      = SymOperad.map (R := R) ((leftUnitEquiv B).symm.trans
          ((compEquiv u (Equiv.refl B) ()).trans (slotEquiv hi))) y := by
  induction y using Finsupp.induction_linear with
  | zero => simp
  | add x y hx hy => simp only [map_add, hx, hy]
  | single s r =>
    show Lin.compL R i (Finsupp.single _ 1) (Finsupp.single s r) = Lin.mapL R _ (Finsupp.single s r)
    rw [Lin.compL_single, Lin.mapL_single, map_one_comp u hi, one_mul]

variable (W : Submodule R (FreeBin R G (Fin 3)))

/-- The components of the ideal of `W`: the relabellings of `W` in arity three, nothing below,
everything above. -/
noncomputable def ideal3Sub (A : Type) [Fintype A] [DecidableEq A] : Submodule R (FreeBin R G A) :=
  if Fintype.card A < 3 then ⊥ else ⨅ f : A ≃ Fin 3, W.comap (SymOperad.map (R := R) f)

variable {W}

lemma mem_ideal3Sub {A : Type} [Fintype A] [DecidableEq A] {x : FreeBin R G A} :
    x ∈ ideal3Sub R W A ↔
      (Fintype.card A < 3 → x = 0) ∧ ∀ f : A ≃ Fin 3, SymOperad.map (R := R) f x ∈ W := by
  unfold ideal3Sub
  split_ifs with h
  · rw [Submodule.mem_bot]
    refine ⟨fun hx => ⟨fun _ => hx, fun f => ?_⟩, fun hx => hx.1 h⟩
    have := Fintype.card_congr f
    simp only [Fintype.card_fin] at this
    omega
  · simp only [Submodule.mem_iInf, Submodule.mem_comap]
    exact ⟨fun hx => ⟨fun h' => absurd h' h, hx⟩, fun hx => hx.2⟩

lemma card_target {A B : Type} [Fintype A] [DecidableEq A] [Fintype B] (i : A) :
    Fintype.card (Without A i ⊕ B) = Fintype.card A - 1 + Fintype.card B := by
  rw [Fintype.card_sum, Reg.card_without]

lemma not_equiv_fin3 {A : Type} [Fintype A] (h : Fintype.card A ≠ 3) (f : A ≃ Fin 3) : False := by
  have := Fintype.card_congr f
  simp only [Fintype.card_fin] at this
  exact h this

lemma ideal3_map_mem {A B : Type} [Fintype A] [DecidableEq A] [Fintype B] [DecidableEq B]
    (e : A ≃ B) {x : FreeBin R G A} (hx : x ∈ ideal3Sub R W A) :
    SymOperad.map (R := R) e x ∈ ideal3Sub R W B := by
  rw [mem_ideal3Sub] at hx ⊢
  have hcard := Fintype.card_congr e
  refine ⟨fun h => ?_, fun f => ?_⟩
  · rw [hx.1 (by omega), map_zero]
  · rw [← SymOperad.map_trans]
    exact hx.2 (e.trans f)

lemma ideal3_comp_left {A B : Type} [Fintype A] [DecidableEq A] [Fintype B] [DecidableEq B]
    (i : A) (y : FreeBin R G B) {x : FreeBin R G A} (hx : x ∈ ideal3Sub R W A) :
    SymOperad.comp (R := R) i x y ∈ ideal3Sub R W (Without A i ⊕ B) := by
  rw [mem_ideal3Sub] at hx ⊢
  have hc := card_target (B := B) i
  have hA : 0 < Fintype.card A := Fintype.card_pos_iff.2 ⟨i⟩
  by_cases ha : Fintype.card A < 3
  · rw [hx.1 ha]
    simp only [map_zero, LinearMap.zero_apply, implies_true, true_and]
    exact fun _ => W.zero_mem
  · by_cases hb0 : Fintype.card B = 0
    · rw [freeBin_eq_zero R hb0 y]
      simp only [map_zero, implies_true, true_and]
      exact fun _ => W.zero_mem
    · by_cases hb1 : Fintype.card B = 1
      · obtain ⟨u⟩ : Nonempty (Unit ≃ B) :=
          ⟨Fintype.equivOfCardEq (by rw [Fintype.card_unit, hb1])⟩
        rw [freeBin_eq_smul_single R hb1 (SetOperad.map u SetOperad.one) y, map_smul,
          comp_single_unit]
        refine ⟨fun h => absurd h (by omega), fun f => ?_⟩
        rw [map_smul, ← SymOperad.map_trans]
        exact W.smul_mem _ (hx.2 _)
      · exact ⟨fun h => absurd h (by omega), fun f => (not_equiv_fin3 (by omega) f).elim⟩

lemma ideal3_comp_right {A B : Type} [Fintype A] [DecidableEq A] [Fintype B] [DecidableEq B]
    (i : A) (x : FreeBin R G A) {y : FreeBin R G B} (hy : y ∈ ideal3Sub R W B) :
    SymOperad.comp (R := R) i x y ∈ ideal3Sub R W (Without A i ⊕ B) := by
  rw [mem_ideal3Sub] at hy ⊢
  have hc := card_target (B := B) i
  have hA : 0 < Fintype.card A := Fintype.card_pos_iff.2 ⟨i⟩
  by_cases hb : Fintype.card B < 3
  · rw [hy.1 hb]
    simp only [map_zero, implies_true, true_and]
    exact fun _ => W.zero_mem
  · by_cases ha1 : Fintype.card A = 1
    · obtain ⟨u⟩ : Nonempty (Unit ≃ A) :=
        ⟨Fintype.equivOfCardEq (by rw [Fintype.card_unit, ha1])⟩
      have hi : u () = i := by
        haveI : Subsingleton A := Fintype.card_le_one_iff_subsingleton.1 ha1.le
        exact Subsingleton.elim _ _
      rw [freeBin_eq_smul_single R ha1 (SetOperad.map u SetOperad.one) x, map_smul,
        LinearMap.smul_apply, comp_unit_single R u hi]
      refine ⟨fun h => absurd h (by omega), fun f => ?_⟩
      rw [map_smul, ← SymOperad.map_trans]
      exact W.smul_mem _ (hy.2 _)
    · exact ⟨fun h => absurd h (by omega), fun f => (not_equiv_fin3 (by omega) f).elim⟩

/-- **The ideal of a space `W` of arity-three elements**: the elements of arity three all of whose
relabellings lie in `W`, and everything from arity four on. -/
noncomputable def ideal3 (W : Submodule R (FreeBin R G (Fin 3))) :
    SymOperadIdeal R (FreeBin R G) where
  sub A _ _ := ideal3Sub R W A
  map_mem e _ hx := ideal3_map_mem R e hx
  comp_mem_left i _ y hx := ideal3_comp_left R i y hx
  comp_mem_right i x _ hy := ideal3_comp_right R i x hy

/-- **The relations of arity three of a binary quadratic operad** without relators of arity two:
the span of the relabellings of the relators. -/
theorem span_sub_three (r : Set (FreeBin R G (Fin 3))) :
    (SymOperadIdeal.span R (rel23 (∅ : Set (FreeBin R G (Fin 2))) r)).sub (Fin 3)
      = Submodule.span R (orbit3 R r) := by
  apply le_antisymm
  · have hle : SymOperadIdeal.span R (rel23 (∅ : Set (FreeBin R G (Fin 2))) r)
        ≤ ideal3 R (Submodule.span R (orbit3 R r)) := by
      rw [SymOperadIdeal.span_le]
      intro n x hx
      rcases n with _ | _ | _ | _ | n
      · exact absurd hx (by simp [rel23])
      · exact absurd hx (by simp [rel23])
      · exact absurd hx (by simp [rel23])
      · show x ∈ ideal3Sub R _ (Fin 3)
        rw [mem_ideal3Sub]
        exact ⟨fun h => absurd h (by simp), fun f => Submodule.subset_span ⟨f, x, hx, rfl⟩⟩
      · exact absurd hx (by simp [rel23])
    intro x hx
    have := ((mem_ideal3Sub R).1 (hle (Fin 3) hx)).2 (Equiv.refl _)
    rwa [SymOperad.map_refl] at this
  · rw [Submodule.span_le]
    rintro _ ⟨τ, y, hy, rfl⟩
    exact (SymOperadIdeal.span R _).map_mem τ (SymOperadIdeal.subset_span 3 hy)


end Ideal3

/-! ## The action of `𝔖₃` -/

/-- The action of a permutation on the monomials of arity three: on the relabelling. -/
def act3 (τ : Equiv.Perm (Fin 3)) (m : Mono3 G) : Mono3 G := (m.1, m.2.1, m.2.2.1, τ * m.2.2.2)

/-- **Relabelling a monomial** relabels its inputs. -/
lemma map_mono3 (τ : Equiv.Perm (Fin 3)) (m : Mono3 G) :
    SymOperad.map (R := R) τ (mono3 R m) = mono3 R (act3 τ m) := by
  obtain ⟨s, g, h, σ⟩ := m
  show Lin.mapL R τ (Finsupp.single _ 1) = Finsupp.single _ 1
  rw [Lin.mapL_single]
  congr 1
  cases s
  · show SetOperad.map τ (Pres.mk _) = Pres.mk _
    rw [Pres.map_mk]
    exact Pres.mk_eq_mk (Syn.Rel.symm (Syn.Rel.map_trans (fin3Left.symm.trans σ) τ _))
  · show SetOperad.map τ (Pres.mk _) = Pres.mk _
    rw [Pres.map_mk]
    exact Pres.mk_eq_mk (Syn.Rel.symm (Syn.Rel.map_trans (fin3Right.symm.trans σ) τ _))

lemma act3_injective (τ : Equiv.Perm (Fin 3)) : Function.Injective (act3 (G := G) τ) := by
  rintro ⟨s, g, h, σ⟩ ⟨s', g', h', σ'⟩ heq
  simp only [act3, Prod.mk.injEq, mul_right_inj] at heq
  obtain ⟨rfl, rfl, rfl, rfl⟩ := heq
  rfl

/-- The relations of arity three are closed under relabelling. -/
lemma map_mem_span_orbit3 {r : Set (FreeBin R G (Fin 3))} (τ : Equiv.Perm (Fin 3))
    {x : FreeBin R G (Fin 3)} (hx : x ∈ Submodule.span R (orbit3 R r)) :
    SymOperad.map (R := R) τ x ∈ Submodule.span R (orbit3 R r) := by
  induction hx using Submodule.span_induction with
  | mem y hy =>
    obtain ⟨τ', y, hy, rfl⟩ := hy
    refine Submodule.subset_span ⟨τ * τ', y, hy, ?_⟩
    rw [← SymOperad.map_trans]
    rfl
  | zero => simp
  | add x y _ _ hx hy => rw [map_add]; exact Submodule.add_mem _ hx hy
  | smul c x _ hx => rw [map_smul]; exact Submodule.smul_mem _ c hx

/-- A space closed under relabelling is the span of its relabellings. -/
lemma span_orbit3_eq {W : Submodule R (FreeBin R G (Fin 3))}
    (hW : ∀ τ : Equiv.Perm (Fin 3), ∀ x ∈ W, SymOperad.map (R := R) τ x ∈ W) :
    Submodule.span R (orbit3 R (W : Set (FreeBin R G (Fin 3)))) = W := by
  apply le_antisymm
  · rw [Submodule.span_le]
    rintro _ ⟨τ, y, hy, rfl⟩
    exact hW τ y hy
  · intro x hx
    refine Submodule.subset_span ⟨1, x, hx, ?_⟩
    exact (SymOperad.map_refl x).symm

/-- **Two sets of relators with the same relabellings span** present the same operad. -/
theorem span_eq_of_span_orbit3_eq {r r' : Set (FreeBin R G (Fin 3))}
    (h : Submodule.span R (orbit3 R r) = Submodule.span R (orbit3 R r')) :
    SymOperadIdeal.span R (rel23 (∅ : Set (FreeBin R G (Fin 2))) r)
      = SymOperadIdeal.span R (rel23 (∅ : Set (FreeBin R G (Fin 2))) r') := by
  have key : ∀ r r' : Set (FreeBin R G (Fin 3)),
      Submodule.span R (orbit3 R r) ≤ Submodule.span R (orbit3 R r') →
      SymOperadIdeal.span R (rel23 (∅ : Set (FreeBin R G (Fin 2))) r)
        ≤ SymOperadIdeal.span R (rel23 (∅ : Set (FreeBin R G (Fin 2))) r') := by
    intro r r' hle
    rw [SymOperadIdeal.span_le]
    intro n x hx
    rcases n with _ | _ | _ | _ | n
    · exact absurd hx (by simp [rel23])
    · exact absurd hx (by simp [rel23])
    · exact absurd hx (by simp [rel23])
    · rw [span_sub_three]
      exact hle (Submodule.subset_span ⟨1, x, hx, (SymOperad.map_refl x).symm⟩)
    · exact absurd hx (by simp [rel23])
  exact le_antisymm (key r r' h.le) (key r' r h.ge)

/-! ## The Koszul pairing and the Koszul dual -/

section Koszul

variable [Fintype G] [DecidableEq G] (K : Type u) [Field K]

/-- **The sign of a monomial** in the Koszul pairing: the signature of the relabelling, and `-1`
for the second shape. -/
def sign3 (m : Mono3 G) : K := (if m.1 then -1 else 1) * ((Equiv.Perm.sign m.2.2.2 : ℤ) : K)

omit [Fintype G] [DecidableEq G] in
lemma sign3_ne_zero (m : Mono3 G) : sign3 K m ≠ 0 := by
  unfold sign3
  rcases Int.units_eq_one_or (Equiv.Perm.sign m.2.2.2) with h | h <;> split_ifs <;> simp [h]

omit [Fintype G] [DecidableEq G] in
lemma sign3_act3 (τ : Equiv.Perm (Fin 3)) (m : Mono3 G) :
    sign3 K (act3 τ m) = ((Equiv.Perm.sign τ : ℤ) : K) * sign3 K m := by
  obtain ⟨s, g, h, σ⟩ := m
  cases s <;> simp [sign3, act3, Equiv.Perm.sign_mul]

instance : FiniteDimensional K (FreeBin K G (Fin 3)) :=
  Module.Basis.finiteDimensional_of_finite (basis3 K)

variable (G) in
/-- **The Koszul pairing** on the operations of arity three: the monomials are orthogonal, each
of square its sign. -/
noncomputable def pair3 : LinearMap.BilinForm K (FreeBin K G (Fin 3)) :=
  (basis3 K).constr K fun m => sign3 K m • (basis3 K).coord m

lemma pair3_apply (x y : FreeBin K G (Fin 3)) :
    pair3 G K x y = ∑ m, sign3 K m * (basis3 K).repr x m * (basis3 K).repr y m := by
  rw [pair3, Module.Basis.constr_apply, Finsupp.sum_fintype _ _ (by simp)]
  simp only [LinearMap.coe_sum, Finset.sum_apply, LinearMap.smul_apply, Module.Basis.coord_apply,
    smul_eq_mul]
  refine Finset.sum_congr rfl fun m _ => ?_
  ring

lemma pair3_mono3 (m m' : Mono3 G) :
    pair3 G K (mono3 K m) (mono3 K m') = if m = m' then sign3 K m else 0 := by
  rw [pair3_apply, ← basis3_apply, ← basis3_apply, Module.Basis.repr_self, Module.Basis.repr_self]
  rw [Finset.sum_eq_single m]
  · by_cases h : m = m'
    · subst h
      simp
    · simp [h]
  · intro b _ hb
    simp [Finsupp.single_apply, Ne.symm hb]
  · simp

lemma pair3_comm (x y : FreeBin K G (Fin 3)) : pair3 G K x y = pair3 G K y x := by
  rw [pair3_apply, pair3_apply]
  exact Finset.sum_congr rfl fun m _ => by ring

lemma pair3_isRefl : LinearMap.BilinForm.IsRefl (pair3 G K) := fun x y h => by
  rwa [pair3_comm]

lemma pair3_separatingLeft (x : FreeBin K G (Fin 3)) (hx : ∀ y, pair3 G K x y = 0) : x = 0 := by
  apply (basis3 K).repr.injective
  ext m
  have := hx (mono3 K m)
  rw [pair3_apply, Finset.sum_eq_single m] at this
  · rw [← basis3_apply, Module.Basis.repr_self, Finsupp.single_eq_same, mul_one] at this
    simpa [sign3_ne_zero] using this
  · intro b _ hb
    rw [← basis3_apply, Module.Basis.repr_self, Finsupp.single_eq_of_ne hb, mul_zero]
  · simp

lemma pair3_nondegenerate : LinearMap.BilinForm.Nondegenerate (pair3 G K) :=
  ⟨pair3_separatingLeft K, fun y hy => pair3_separatingLeft K y fun x => by
    rw [pair3_comm]; exact hy x⟩

/-- **The pairing is invariant under relabelling, up to the signature.** -/
lemma pair3_map (τ : Equiv.Perm (Fin 3)) (x y : FreeBin K G (Fin 3)) :
    pair3 G K (SymOperad.map (R := K) τ x) (SymOperad.map (R := K) τ y)
      = ((Equiv.Perm.sign τ : ℤ) : K) * pair3 G K x y := by
  have : (pair3 G K).compl₁₂ (SymOperad.map (R := K) τ) (SymOperad.map (R := K) τ)
      = ((Equiv.Perm.sign τ : ℤ) : K) • pair3 G K := by
    refine (basis3 K).ext fun m => (basis3 K).ext fun m' => ?_
    simp only [LinearMap.compl₁₂_apply, basis3_apply, map_mono3, pair3_mono3,
      LinearMap.smul_apply, smul_eq_mul, (act3_injective τ).eq_iff, sign3_act3]
    split_ifs <;> simp
  exact congrArg (fun B : LinearMap.BilinForm K _ => B x y) this

/-- **The Koszul dual relators**: the orthogonal of the relations of arity three. -/
noncomputable def dualRel (r : Set (FreeBin K G (Fin 3))) : Submodule K (FreeBin K G (Fin 3)) :=
  LinearMap.BilinForm.orthogonal (pair3 G K) (Submodule.span K (orbit3 K r))

/-- The dual relations are closed under relabelling. -/
lemma map_mem_dualRel (r : Set (FreeBin K G (Fin 3))) (τ : Equiv.Perm (Fin 3))
    {x : FreeBin K G (Fin 3)} (hx : x ∈ dualRel K r) :
    SymOperad.map (R := K) τ x ∈ dualRel K r := by
  intro n hn
  have hn' := map_mem_span_orbit3 K τ⁻¹ hn
  have h1 := hx _ hn'
  show pair3 G K n (SymOperad.map (R := K) τ x) = 0
  have h2 := pair3_map K τ (SymOperad.map (R := K) τ⁻¹ n) x
  rw [← SymOperad.map_trans, show τ⁻¹.trans τ = Equiv.refl _ from by ext; simp,
    SymOperad.map_refl] at h2
  rw [h2]
  rw [show pair3 G K _ x = 0 from h1, mul_zero]

lemma span_orbit3_dualRel (r : Set (FreeBin K G (Fin 3))) :
    Submodule.span K (orbit3 K (dualRel K r : Set (FreeBin K G (Fin 3)))) = dualRel K r :=
  span_orbit3_eq K fun τ _ hx => map_mem_dualRel K r τ hx

/-- **The Koszul dual of the Koszul dual**: the relations come back. -/
theorem dualRel_dualRel (r : Set (FreeBin K G (Fin 3))) :
    dualRel K (dualRel K r : Set (FreeBin K G (Fin 3))) = Submodule.span K (orbit3 K r) := by
  rw [dualRel, span_orbit3_dualRel, dualRel,
    LinearMap.BilinForm.orthogonal_orthogonal (pair3_nondegenerate K) (pair3_isRefl K)]

/-- **The dimension of the dual relations**: complementary to that of the relations. -/
theorem finrank_dualRel (r : Set (FreeBin K G (Fin 3))) :
    Module.finrank K (dualRel K r)
      = 12 * Fintype.card G ^ 2 - Module.finrank K (Submodule.span K (orbit3 K r)) := by
  rw [dualRel, LinearMap.BilinForm.finrank_orthogonal (pair3_nondegenerate K),
    Module.finrank_eq_card_basis (basis3 K)]
  congr 1
  simp only [Mono3, Fintype.card_prod, Fintype.card_bool, Fintype.card_perm, Fintype.card_fin,
    show (3 : ℕ).factorial = 6 from rfl]
  ring

/-- **The Koszul dual of a binary quadratic operad** presented by relators of arity three. -/
abbrev BinPres.dual (r : Set (FreeBin K G (Fin 3))) :=
  BinPres K (∅ : Set (FreeBin K G (Fin 2))) (dualRel K r : Set (FreeBin K G (Fin 3)))

/-- **Koszul duality is an involution** on binary quadratic operads. -/
theorem dual_dual (r : Set (FreeBin K G (Fin 3))) :
    SymOperadIdeal.span K (rel23 (∅ : Set (FreeBin K G (Fin 2)))
        (dualRel K (dualRel K r : Set (FreeBin K G (Fin 3))) : Set (FreeBin K G (Fin 3))))
      = SymOperadIdeal.span K (rel23 (∅ : Set (FreeBin K G (Fin 2))) r) := by
  apply span_eq_of_span_orbit3_eq K
  rw [span_orbit3_dualRel, dualRel_dualRel]

end Koszul

/-! ## Recognizing Koszul dual relations -/

section Recognition

variable [Fintype G] [DecidableEq G] (K : Type u) [Field K]

lemma repr_mono3 (m m' : Mono3 G) :
    (basis3 K).repr (mono3 K m) m' = if m = m' then 1 else 0 := by
  rw [← basis3_apply, Module.Basis.repr_self, Finsupp.single_apply]

omit [Fintype G] [DecidableEq G] in
lemma map_binL (τ σ : Equiv.Perm (Fin 3)) (g h : G) :
    SymOperad.map (R := K) τ (binL g h σ) = mono3 K (false, g, h, τ * σ) :=
  map_mono3 K τ (false, g, h, σ)

omit [Fintype G] [DecidableEq G] in
lemma map_binR (τ σ : Equiv.Perm (Fin 3)) (g h : G) :
    SymOperad.map (R := K) τ (binR g h σ) = mono3 K (true, g, h, τ * σ) :=
  map_mono3 K τ (true, g, h, σ)

omit [Fintype G] [DecidableEq G] in
lemma mem_orbit3 {r : Set (FreeBin K G (Fin 3))} {y : FreeBin K G (Fin 3)} (hy : y ∈ r)
    (τ : Equiv.Perm (Fin 3)) : SymOperad.map (R := K) τ y ∈ Submodule.span K (orbit3 K r) :=
  Submodule.subset_span ⟨τ, y, hy, rfl⟩

/-- To be orthogonal to the relations, it suffices to be orthogonal to the relabelled relators. -/
lemma le_dualRel {r s : Set (FreeBin K G (Fin 3))}
    (h : ∀ x ∈ s, ∀ y ∈ r, ∀ σ τ : Equiv.Perm (Fin 3),
      pair3 G K (SymOperad.map (R := K) τ y) (SymOperad.map (R := K) σ x) = 0) :
    Submodule.span K (orbit3 K s) ≤ dualRel K r := by
  rw [Submodule.span_le]
  rintro _ ⟨σ, x, hx, rfl⟩ n hn
  show pair3 G K n (SymOperad.map (R := K) σ x) = 0
  induction hn using Submodule.span_induction with
  | mem y hy =>
    obtain ⟨τ, y, hy, rfl⟩ := hy
    exact h x hx y hy σ τ
  | zero => simp
  | add y z _ _ hy hz => rw [map_add, LinearMap.add_apply, hy, hz, add_zero]
  | smul c y _ hy => rw [map_smul, LinearMap.smul_apply, hy, smul_zero]

/-- **Orthogonal relations of complementary dimensions are Koszul dual to each other.** -/
theorem dualRel_eq_of_orthogonal {r s : Set (FreeBin K G (Fin 3))}
    (h : ∀ x ∈ s, ∀ y ∈ r, ∀ σ τ : Equiv.Perm (Fin 3),
      pair3 G K (SymOperad.map (R := K) τ y) (SymOperad.map (R := K) σ x) = 0)
    (hdim : 12 * Fintype.card G ^ 2 ≤ Module.finrank K (Submodule.span K (orbit3 K s))
      + Module.finrank K (Submodule.span K (orbit3 K r))) :
    dualRel K r = Submodule.span K (orbit3 K s) ∧
      dualRel K s = Submodule.span K (orbit3 K r) := by
  have key : ∀ {r s : Set (FreeBin K G (Fin 3))}, Submodule.span K (orbit3 K s) ≤ dualRel K r →
      12 * Fintype.card G ^ 2 ≤ Module.finrank K (Submodule.span K (orbit3 K s))
        + Module.finrank K (Submodule.span K (orbit3 K r)) →
      dualRel K r = Submodule.span K (orbit3 K s) := fun hle hdim => by
    refine (Submodule.eq_of_le_of_finrank_le hle ?_).symm
    rw [finrank_dualRel]
    omega
  refine ⟨key (le_dualRel K h) hdim, key (le_dualRel K fun y hy x hx τ σ => ?_) (by omega)⟩
  rw [pair3_comm]
  exact h x hx y hy σ τ

/-- **Vectors with private coordinates are independent**: they bound the dimension of any space
containing them. -/
lemma le_finrank_of_private {ι : Type*} [Fintype ι] {W : Submodule K (FreeBin K G (Fin 3))}
    (v : ι → FreeBin K G (Fin 3)) (hv : ∀ i, v i ∈ W) (f : ι → Mono3 G)
    (h : ∀ i j, (basis3 K).repr (v j) (f i) ≠ 0 ↔ j = i) :
    Fintype.card ι ≤ Module.finrank K W := by
  classical
  have hli : LinearIndependent K v := by
    rw [linearIndependent_iff']
    intro t c hc i hi
    have := congrArg (fun x => (basis3 K).repr x (f i)) hc
    simp only [map_sum, map_smul, Finsupp.coe_finsetSum, Finset.sum_apply, Finsupp.coe_smul,
      Pi.smul_apply, smul_eq_mul, map_zero, Finsupp.coe_zero, Pi.zero_apply] at this
    rw [Finset.sum_eq_single i (fun b _ hb => by rw [not_not.1 (mt (h i b).1 hb), mul_zero])
      (fun h' => absurd hi h')] at this
    exact (mul_eq_zero.1 this).resolve_right ((h i i).2 rfl)
  rw [← finrank_span_eq_card hli]
  exact Submodule.finrank_mono (Submodule.span_le.2 (Set.range_subset_iff.2 hv))

/-- **Koszul dual relations present the Koszul dual operad.** -/
theorem BinPres.dual_eq {r s : Set (FreeBin K G (Fin 3))}
    (h : dualRel K r = Submodule.span K (orbit3 K s)) :
    SymOperadIdeal.span K (rel23 (∅ : Set (FreeBin K G (Fin 2))) (dualRel K r : Set _))
      = SymOperadIdeal.span K (rel23 (∅ : Set (FreeBin K G (Fin 2))) s) :=
  span_eq_of_span_orbit3_eq K (by rw [span_orbit3_dualRel, h])

end Recognition

/-! ## Classical Koszul dualities with one generator -/

section OneGenerator

variable (K : Type u) [Field K]

/-- The left and right combs with a given relabelling. -/
noncomputable abbrev cL (σ : Equiv.Perm (Fin 3)) : FreeBin K Unit (Fin 3) :=
  mono3 K (false, (), (), σ)

/-- The right comb with a given relabelling. -/
noncomputable abbrev cR (σ : Equiv.Perm (Fin 3)) : FreeBin K Unit (Fin 3) :=
  mono3 K (true, (), (), σ)

lemma perm3_021_mul_self : perm3 0 2 1 * perm3 0 2 1 = 1 := by decide

lemma sign_perm3_021 : Equiv.Perm.sign (perm3 0 2 1) = -1 := by decide

lemma perm3_021_ne_one : perm3 0 2 1 ≠ 1 := by decide

lemma mul_perm3_021_eq_iff {σ τ : Equiv.Perm (Fin 3)} : σ * perm3 0 2 1 = τ ↔ σ = τ * perm3 0 2 1 :=
  ⟨fun h => by rw [← h, mul_assoc, perm3_021_mul_self, mul_one],
    fun h => by rw [h, mul_assoc, perm3_021_mul_self, mul_one]⟩

lemma mul_perm3_021_mul_self (σ : Equiv.Perm (Fin 3)) :
    σ * perm3 0 2 1 * perm3 0 2 1 = σ := by
  rw [mul_assoc, perm3_021_mul_self, mul_one]

/-- **Representatives of the cosets of `perm3 0 2 1`**: the powers of a three-cycle. -/
noncomputable def cyc3 (k : Fin 3) : Equiv.Perm (Fin 3) := perm3 1 2 0 ^ (k : ℕ)

lemma cyc3_inj (j k : Fin 3) : cyc3 j = cyc3 k ↔ j = k := by
  revert j k; unfold cyc3; decide

lemma cyc3_ne_mul (j k : Fin 3) : cyc3 j ≠ cyc3 k * perm3 0 2 1 := by
  revert j k; unfold cyc3; decide

lemma map_assoc (τ : Equiv.Perm (Fin 3)) :
    SymOperad.map (R := K) τ (BinRel.assoc K ()) = cL K τ - cR K τ := by
  simp only [BinRel.assoc, map_sub, map_binL, map_binR, mul_one]

lemma map_perm (τ : Equiv.Perm (Fin 3)) :
    SymOperad.map (R := K) τ (BinRel.perm K ()) = cR K τ - cR K (τ * perm3 0 2 1) := by
  simp only [BinRel.perm, map_sub, map_binR, mul_one]

lemma map_preLie (τ : Equiv.Perm (Fin 3)) :
    SymOperad.map (R := K) τ (BinRel.preLie K ())
      = cL K τ - cR K τ - (cL K (τ * perm3 0 2 1) - cR K (τ * perm3 0 2 1)) := by
  simp only [BinRel.preLie, map_sub, map_binL, map_binR, mul_one]

lemma map_leib (τ : Equiv.Perm (Fin 3)) :
    SymOperad.map (R := K) τ (BinRel.leib K ())
      = cL K τ - (cL K (τ * perm3 0 2 1) + cR K τ) := by
  simp only [BinRel.leib, map_sub, map_add, map_binL, map_binR, mul_one]

lemma map_zinb (τ : Equiv.Perm (Fin 3)) :
    SymOperad.map (R := K) τ (BinRel.zinb K ())
      = cL K τ - (cR K τ + cR K (τ * perm3 0 2 1)) := by
  simp only [BinRel.zinb, map_sub, map_add, map_binL, map_binR, mul_one]

/-- **The associative operad is Koszul self-dual** at the level of relations. -/
theorem dualRel_assoc :
    dualRel K {BinRel.assoc K ()} = Submodule.span K (orbit3 K {BinRel.assoc K ()}) := by
  have h := le_finrank_of_private K (fun σ => SymOperad.map (R := K) σ (BinRel.assoc K ()))
    (fun σ => mem_orbit3 K (Set.mem_singleton _) σ) (fun σ => (false, (), (), σ)) fun i j => by
      by_cases h : j = i <;> simp [map_assoc, repr_mono3, h]
  refine (dualRel_eq_of_orthogonal K (fun x hx y hy σ τ => ?_) ?_).1
  · rw [Set.mem_singleton_iff] at hx hy
    subst hx hy
    simp only [map_assoc, map_sub, LinearMap.sub_apply, pair3_mono3, Prod.mk.injEq, sign3]
    split_ifs <;> simp_all
  · simp only [Fintype.card_perm, Fintype.card_fin, Fintype.card_unit] at h ⊢
    simp only [show (3 : ℕ).factorial = 6 from rfl] at h
    omega

/-- **The Leibniz and Zinbiel operads are Koszul dual** at the level of relations. -/
theorem dualRel_leib_zinb :
    dualRel K {BinRel.leib K ()} = Submodule.span K (orbit3 K {BinRel.zinb K ()}) ∧
      dualRel K {BinRel.zinb K ()} = Submodule.span K (orbit3 K {BinRel.leib K ()}) := by
  have h₁ := le_finrank_of_private K (fun σ => SymOperad.map (R := K) σ (BinRel.zinb K ()))
    (fun σ => mem_orbit3 K (Set.mem_singleton _) σ) (fun σ => (false, (), (), σ)) fun i j => by
      by_cases h : j = i <;> simp [map_zinb, repr_mono3, h]
  have h₂ := le_finrank_of_private K (fun σ => SymOperad.map (R := K) σ (BinRel.leib K ()))
    (fun σ => mem_orbit3 K (Set.mem_singleton _) σ) (fun σ => (true, (), (), σ)) fun i j => by
      by_cases h : j = i <;> simp [map_leib, repr_mono3, h]
  refine dualRel_eq_of_orthogonal K (fun x hx y hy σ τ => ?_) ?_
  · rw [Set.mem_singleton_iff] at hx hy
    subst hx hy
    simp [map_leib, map_zinb, pair3_mono3, sign3, mul_perm3_021_eq_iff, Equiv.Perm.sign_mul,
      sign_perm3_021]
    split_ifs <;> simp_all
  · simp only [Fintype.card_perm, Fintype.card_fin, Fintype.card_unit] at h₁ h₂ ⊢
    simp only [show (3 : ℕ).factorial = 6 from rfl] at h₁ h₂
    omega

/-- **The pre-Lie and permutative operads are Koszul dual** at the level of relations. -/
theorem dualRel_preLie_perm :
    dualRel K {BinRel.preLie K ()}
        = Submodule.span K (orbit3 K {BinRel.assoc K (), BinRel.perm K ()}) ∧
      dualRel K {BinRel.assoc K (), BinRel.perm K ()}
        = Submodule.span K (orbit3 K {BinRel.preLie K ()}) := by
  have h₁ := le_finrank_of_private K
    (fun k => SymOperad.map (R := K) (cyc3 k) (BinRel.preLie K ()))
    (fun k => mem_orbit3 K (Set.mem_singleton _) _) (fun k => (false, (), (), cyc3 k))
    fun i j => by
      by_cases h : j = i <;>
        simp [map_preLie, repr_mono3, h, mul_perm3_021_eq_iff, cyc3_inj, cyc3_ne_mul,
          perm3_021_ne_one]
  have hA := fun τ => mem_orbit3 K (r := {BinRel.assoc K (), BinRel.perm K ()})
    (Set.mem_insert _ _) τ
  have hP := fun τ => mem_orbit3 K (r := {BinRel.assoc K (), BinRel.perm K ()})
    (Set.mem_insert_of_mem _ (Set.mem_singleton _)) τ
  have h₂ := le_finrank_of_private K
    (fun i : Fin 3 × Fin 3 => ![cL K (cyc3 i.1) - cR K (cyc3 i.1 * perm3 0 2 1),
      cL K (cyc3 i.1 * perm3 0 2 1) - cR K (cyc3 i.1 * perm3 0 2 1),
      cR K (cyc3 i.1) - cR K (cyc3 i.1 * perm3 0 2 1)] i.2)
    (fun i => by
      obtain ⟨k, a⟩ := i
      fin_cases a
      · have := add_mem (hA (cyc3 k)) (hP (cyc3 k))
        rw [map_assoc, map_perm, sub_add_sub_cancel] at this
        exact this
      · have := hA (cyc3 k * perm3 0 2 1)
        rwa [map_assoc] at this
      · have := hP (cyc3 k)
        rwa [map_perm] at this)
    (fun i => ![(false, (), (), cyc3 i.1), (false, (), (), cyc3 i.1 * perm3 0 2 1),
      (true, (), (), cyc3 i.1)] i.2)
    (by
      rintro ⟨k, a⟩ ⟨j, b⟩
      fin_cases a <;> fin_cases b <;> by_cases h : j = k <;>
        simp [h, repr_mono3, mul_perm3_021_eq_iff, cyc3_inj, cyc3_ne_mul, perm3_021_ne_one])
  refine (dualRel_eq_of_orthogonal K (fun x hx y hy σ τ => ?_) ?_)
  · rw [Set.mem_singleton_iff] at hy
    subst hy
    rcases hx with rfl | hx
    · simp [map_preLie, map_assoc, pair3_mono3, sign3, mul_perm3_021_eq_iff,
        Equiv.Perm.sign_mul, sign_perm3_021]
      split_ifs <;> simp_all
    · rw [Set.mem_singleton_iff] at hx
      subst hx
      simp [map_preLie, map_perm, pair3_mono3, sign3, mul_perm3_021_eq_iff,
        Equiv.Perm.sign_mul, sign_perm3_021]
      split_ifs <;> simp_all
  · simp only [Fintype.card_prod, Fintype.card_fin, Fintype.card_unit] at h₁ h₂ ⊢
    omega

end OneGenerator

/-! ## Dendriform and diassociative operads -/

section Dend

variable (K : Type u) [Field K]

instance : Fintype DiOp := ⟨{.left, .right}, fun o => by cases o <;> simp⟩

/-- The dendriform relators. -/
abbrev dendRel : Set (FreeBin K DiOp (Fin 3)) := {BinRel.dend₁ K, BinRel.dend₂ K, BinRel.dend₃ K}

/-- The diassociative relators. -/
abbrev diasRel : Set (FreeBin K DiOp (Fin 3)) :=
  {BinRel.dias₁ K, BinRel.dias₂ K, BinRel.dias₃ K, BinRel.dias₄ K, BinRel.dias₅ K}

lemma finrank_dendRel : 18 ≤ Module.finrank K (Submodule.span K (orbit3 K (dendRel K))) :=
  le_finrank_of_private K
    (fun i : Fin 3 × Equiv.Perm (Fin 3) => SymOperad.map (R := K) i.2
      (![BinRel.dend₁ K, BinRel.dend₂ K, BinRel.dend₃ K] i.1))
    (fun i => mem_orbit3 K (by obtain ⟨k, τ⟩ := i; fin_cases k <;> simp) _)
    (fun i => (![true, false, false] i.1, ![DiOp.left, .left, .right] i.1,
      ![DiOp.right, .right, .left] i.1, i.2))
    (by
      rintro ⟨k, τ⟩ ⟨k', τ'⟩
      fin_cases k <;> fin_cases k' <;> by_cases h : τ' = τ <;>
        simp [h, repr_mono3, BinRel.dend₁, BinRel.dend₂, BinRel.dend₃, map_binL, map_binR])

lemma finrank_diasRel : 30 ≤ Module.finrank K (Submodule.span K (orbit3 K (diasRel K))) :=
  le_finrank_of_private K
    (fun i : Fin 5 × Equiv.Perm (Fin 3) => SymOperad.map (R := K) i.2
      (![BinRel.dias₁ K, BinRel.dias₂ K, BinRel.dias₃ K, BinRel.dias₄ K, BinRel.dias₅ K] i.1))
    (fun i => mem_orbit3 K (by obtain ⟨k, τ⟩ := i; fin_cases k <;> simp) _)
    (fun i => (![true, true, false, false, false] i.1,
      ![DiOp.left, .left, .left, .right, .right] i.1,
      ![DiOp.left, .right, .right, .left, .right] i.1, i.2))
    (by
      rintro ⟨k, τ⟩ ⟨k', τ'⟩
      fin_cases k <;> fin_cases k' <;> by_cases h : τ' = τ <;>
        simp [h, repr_mono3, BinRel.dias₁, BinRel.dias₂, BinRel.dias₃, BinRel.dias₄, BinRel.dias₅,
          map_binL, map_binR])

lemma pair3_dendRel_diasRel : ∀ x ∈ diasRel K, ∀ y ∈ dendRel K, ∀ σ τ : Equiv.Perm (Fin 3),
    pair3 DiOp K (SymOperad.map (R := K) τ y) (SymOperad.map (R := K) σ x) = 0 := by
  intro x hx y hy σ τ
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx hy
  rcases hx with rfl | rfl | rfl | rfl | rfl <;> rcases hy with rfl | rfl | rfl <;>
    simp [BinRel.dend₁, BinRel.dend₂, BinRel.dend₃, BinRel.dias₁, BinRel.dias₂, BinRel.dias₃,
      BinRel.dias₄, BinRel.dias₅, map_binL, map_binR, pair3_mono3, sign3] <;>
    split_ifs <;> simp_all

/-- **The dendriform and diassociative operads are Koszul dual** at the level of relations, with
`≺` paired with `⊣` and `≻` with `⊢`. -/
theorem dualRel_dend_dias :
    dualRel K (dendRel K) = Submodule.span K (orbit3 K (diasRel K)) ∧
      dualRel K (diasRel K) = Submodule.span K (orbit3 K (dendRel K)) := by
  refine dualRel_eq_of_orthogonal K (pair3_dendRel_diasRel K) ?_
  have := finrank_dendRel K
  have := finrank_diasRel K
  rw [show Fintype.card DiOp = 2 from rfl]
  omega

end Dend

end FreeBin

/-! ## The classical Koszul dual operads -/

section Classical

open FreeBin

variable (K : Type u) [Field K]

/-- **`Ass^! = Ass`**: the associative operad is Koszul self-dual. -/
theorem BinAss.dual : BinPres.dual K {BinRel.assoc K ()} = BinAss K :=
  congrArg SymOperadIdeal.Quot (BinPres.dual_eq K (dualRel_assoc K))

/-- **`PreLie^! = Perm`.** -/
theorem PreLie.dual : BinPres.dual K {BinRel.preLie K ()} = BinPerm K :=
  congrArg SymOperadIdeal.Quot (BinPres.dual_eq K (dualRel_preLie_perm K).1)

/-- **`Perm^! = PreLie`.** -/
theorem BinPerm.dual : BinPres.dual K {BinRel.assoc K (), BinRel.perm K ()} = PreLie K :=
  congrArg SymOperadIdeal.Quot (BinPres.dual_eq K (dualRel_preLie_perm K).2)

/-- **`Leib^! = Zinb`.** -/
theorem Leib.dual : BinPres.dual K {BinRel.leib K ()} = Zinb K :=
  congrArg SymOperadIdeal.Quot (BinPres.dual_eq K (dualRel_leib_zinb K).1)

/-- **`Zinb^! = Leib`.** -/
theorem Zinb.dual : BinPres.dual K {BinRel.zinb K ()} = Leib K :=
  congrArg SymOperadIdeal.Quot (BinPres.dual_eq K (dualRel_leib_zinb K).2)

/-- **`Dend^! = Dias`.** -/
theorem Dend.dual : BinPres.dual K (dendRel K) = BinDias K :=
  congrArg SymOperadIdeal.Quot (BinPres.dual_eq K (dualRel_dend_dias K).1)

/-- **`Dias^! = Dend`.** -/
theorem BinDias.dual : BinPres.dual K (diasRel K) = Dend K :=
  congrArg SymOperadIdeal.Quot (BinPres.dual_eq K (dualRel_dend_dias K).2)

end Classical

end Operad
