/-
# The commutative set operad, and generalized associativity and commutativity

`ComSet A` has one element when `A` is nonempty and none otherwise. It is the set operad whose
linearization is `Com`, the operad of commutative associative algebras without unit.

The theorem of this file is that `ComSet` is presented by one binary operation, commutative and
associative (`comPresIso`). Equivalently, a commutative and associative binary element `m` of any
set operad has on every nonempty finite set `A` of inputs a well-defined product `prod A`: the
`m`-product of the inputs, in any order and with any bracketing. These products relabel and
compose as the elements of `ComSet` do (`map_prod`, `comp_prod`), which makes them a morphism of
set operads out of `ComSet` (`ComSet.lift`), and every morphism out of `ComSet` is of this form
(`ComSet.homEquiv`). This is generalized associativity and commutativity: two composites of `m`
with the same inputs are equal.

The products are built on `Fin (n + 1)` as left combs and shown invariant under the symmetric
group, which is generated by transpositions of adjacent inputs
(`Equiv.Perm.mclosure_swap_castSucc_succ`). On an arbitrary `A` the product is transported along
an ordering of `A`, and invariance makes it independent of the ordering.

Through the linearization adjunction the same statement describes morphisms from the
linearization `Lin R ComSet` into an operad in modules (`ComSet.linHomEquiv`).
-/
import Operad.SetBinary
import Mathlib.GroupTheory.Perm.Sign

set_option synthInstance.maxSize 1024

universe u v w

namespace Operad

open Sym

/-- **The commutative set operad**: one operation on each nonempty finite set of inputs. -/
def ComSet : (A : Type) → [Fintype A] → [DecidableEq A] → Type :=
  fun A _ _ => PLift (Nonempty A)

namespace ComSet

instance (A : Type) [Fintype A] [DecidableEq A] : Subsingleton (ComSet A) :=
  inferInstanceAs (Subsingleton (PLift _))

instance instSetOperad : SetOperad ComSet where
  map e x := ⟨x.down.map e⟩
  map_refl _ := Subsingleton.elim _ _
  map_trans _ _ _ := Subsingleton.elim _ _
  one := ⟨⟨()⟩⟩
  comp _ _ y := ⟨y.down.map Sum.inr⟩
  map_comp _ _ _ _ _ := Subsingleton.elim _ _
  comp_one _ _ := Subsingleton.elim _ _
  one_comp _ := Subsingleton.elim _ _
  comp_assoc_seq _ _ _ _ _ := Subsingleton.elim _ _
  comp_assoc_par _ _ _ _ := Subsingleton.elim _ _

/-- The binary operation. -/
def mu : ComSet (Fin 2) := ⟨⟨0⟩⟩

end ComSet

namespace Sym

/-- Adding an input at the end. -/
def snocEquiv (n : ℕ) : Fin n ⊕ Unit ≃ Fin (n + 1) where
  toFun x :=
    match x with
    | Sum.inl k => k.castSucc
    | Sum.inr _ => Fin.last n
  invFun k := if h : (k : ℕ) < n then Sum.inl ⟨k, h⟩ else Sum.inr ()
  left_inv := by
    rintro (k | ⟨⟩)
    · simp [k.isLt]
    · simp
  right_inv := by
    intro k
    by_cases h : (k : ℕ) < n
    · simp [h]
    · simp only [h, ↓reduceDIte]
      ext
      simp only [Fin.val_last]
      omega

@[simp] lemma snocEquiv_inl (n : ℕ) (k : Fin n) : snocEquiv n (Sum.inl k) = k.castSucc := rfl

@[simp] lemma snocEquiv_inr (n : ℕ) (u : Unit) : snocEquiv n (Sum.inr u) = Fin.last n := rfl

@[simp] lemma snocEquiv_symm_castSucc (n : ℕ) (k : Fin n) :
    (snocEquiv n).symm k.castSucc = Sum.inl k :=
  (snocEquiv n).symm_apply_eq.mpr rfl

@[simp] lemma snocEquiv_symm_last (n : ℕ) : (snocEquiv n).symm (Fin.last n) = Sum.inr () :=
  (snocEquiv n).symm_apply_eq.mpr rfl

end Sym

namespace SetOperad

variable {S : (A : Type) → [Fintype A] → [DecidableEq A] → Type v} [SetOperad S]

/-- A binary element is **commutative**: fixed by the transposition of its inputs. -/
def IsComm (m : S (Fin 2)) : Prop := map (Equiv.swap 0 1) m = m

/-- A binary element is **associative**: its two composites with itself agree. -/
def IsAssoc (m : S (Fin 2)) : Prop :=
  map (Equiv.sumAssoc Unit Unit Unit) (bin m (bin m one one) one) = bin m one (bin m one one)

section Comb

variable (m : S (Fin 2))

/-- The left combs: `comb 0` is the identity, and `comb (n + 1)` is `m (comb n, 1)`. -/
def comb : (n : ℕ) → S (Fin (n + 1))
  | 0 => map unitFinOne one
  | n + 1 => map (snocEquiv (n + 1)) (bin m (comb n) one)

lemma comb_succ (n : ℕ) : comb m (n + 1) = map (snocEquiv (n + 1)) (bin m (comb m n) one) := rfl

lemma comb_one :
    comb m 1 = map ((Equiv.sumCongr unitFinOne (Equiv.refl Unit)).trans (snocEquiv 1))
      (bin m one one) := by
  rw [comb_succ, comb, bin_map_left, map_map]

variable {m}

lemma comb_succ_succ (ha : IsAssoc m) (n : ℕ) :
    comb m (n + 2) = map ((Equiv.sumAssoc _ _ _).symm.trans
      ((Equiv.sumCongr (snocEquiv (n + 1)) (Equiv.refl Unit)).trans (snocEquiv (n + 2))))
      (bin m (comb m n) (bin m one one)) := by
  rw [comb_succ, comb_succ, bin_map_left, eq_map_symm_of_map_eq (bin_assoc_of ha _ _ _)]
  simp only [map_map]
  exact map_congr (fun _ => rfl) _

lemma bin_one_one_comm (hc : IsComm m) :
    map (Equiv.sumComm Unit Unit) (bin m one one) = bin m one one :=
  (bin_comm_of hc one one).symm

/-- **The combs are invariant under the symmetric group.** -/
theorem comb_perm (hc : IsComm m) (ha : IsAssoc m) :
    ∀ (n : ℕ) (σ : Equiv.Perm (Fin (n + 1))), map σ (comb m n) = comb m n
  | 0, σ => map_eq_self (fun k => Fin.ext (by have := (σ k).isLt; have := k.isLt; omega)) _
  | n + 1, σ => by
    have key : ∀ i : Fin (n + 1),
        map (Equiv.swap i.castSucc i.succ) (comb m (n + 1)) = comb m (n + 1) := by
      intro i
      by_cases hi : (i : ℕ) < n
      · -- a transposition among the first `n + 1` inputs
        have e : ∀ c, (Equiv.swap i.castSucc i.succ) (snocEquiv (n + 1) c)
            = snocEquiv (n + 1) (Equiv.sumCongr
              (Equiv.swap (⟨i, by omega⟩ : Fin (n + 1)) ⟨i + 1, by omega⟩) (Equiv.refl Unit) c) := by
          have h1 : i.castSucc = (⟨i, by omega⟩ : Fin (n + 1)).castSucc := Fin.ext rfl
          have h2 : i.succ = (⟨i + 1, by omega⟩ : Fin (n + 1)).castSucc := Fin.ext rfl
          rintro (k | ⟨⟩)
          · rw [h1, h2]
            exact (Fin.castSucc_injective _).swap_apply _ _ _
          · refine Equiv.swap_apply_of_ne_of_ne ?_ ?_ <;>
              simp only [snocEquiv_inr, ne_eq, Fin.ext_iff, Fin.val_last, Fin.val_castSucc,
                Fin.val_succ] <;> omega
        rw [comb_succ, map_map, map_congr (f := (Equiv.sumCongr
          (Equiv.swap (⟨i, by omega⟩ : Fin (n + 1)) ⟨i + 1, by omega⟩) (Equiv.refl Unit)).trans
          (snocEquiv (n + 1))) e, ← map_map, ← bin_map_left, comb_perm hc ha n]
      · -- the last two inputs
        rcases n with _ | n
        · obtain rfl : i = 0 := Fin.ext (by have := i.isLt; omega)
          rw [comb_one, map_map]
          conv_rhs => rw [← bin_one_one_comm hc, map_map]
          exact map_congr (fun c => by rcases c with u | u <;> cases u <;> rfl) _
        · obtain rfl : i = Fin.last (n + 1) := Fin.ext (by simp only [Fin.val_last]; omega)
          rw [comb_succ_succ ha, map_map]
          conv_rhs => rw [← bin_one_one_comm hc, bin_map_right, map_map]
          refine map_congr (fun c => ?_) _
          rcases c with k | (⟨⟩ | ⟨⟩)
          · refine Equiv.swap_apply_of_ne_of_ne ?_ ?_ <;>
              simp [snocEquiv, Fin.ext_iff] <;> omega
          · simp [snocEquiv]
          · simp [snocEquiv]
    have hσ : σ ∈ Submonoid.closure
        (Set.range fun i : Fin (n + 1) => Equiv.swap i.castSucc i.succ) := by
      rw [Equiv.Perm.mclosure_swap_castSucc_succ]
      exact Submonoid.mem_top σ
    induction hσ using Submonoid.closure_induction with
    | mem x hx =>
      obtain ⟨i, rfl⟩ := hx
      exact key i
    | one => exact map_refl _
    | mul x y _ _ hx hy => rw [Equiv.Perm.mul_def, map_trans, hy, hx]

/-- Two relabellings of a comb onto the same inputs agree. -/
lemma map_comb_eq (hc : IsComm m) (ha : IsAssoc m) {A : Type} [Fintype A] [DecidableEq A]
    {n : ℕ} (e f : Fin (n + 1) ≃ A) : map e (comb m n) = map f (comb m n) := by
  conv_rhs => rw [← comb_perm hc ha n (e.trans f.symm)]
  rw [map_map]
  exact map_congr (fun k => by simp) _

/-- Relabellings of combs onto the same inputs agree, whatever their lengths. -/
lemma map_comb_eq' (hc : IsComm m) (ha : IsAssoc m) {A : Type} [Fintype A] [DecidableEq A]
    {n n' : ℕ} (e : Fin (n + 1) ≃ A) (f : Fin (n' + 1) ≃ A) :
    map e (comb m n) = map f (comb m n') := by
  obtain rfl : n = n' := by
    have := (Fintype.card_congr e).trans (Fintype.card_congr f).symm
    simp only [Fintype.card_fin, add_left_inj] at this
    exact this
  exact map_comb_eq hc ha e f

end Comb

/-! ## The products -/

section Prod

variable {m : S (Fin 2)} (hc : IsComm m) (ha : IsAssoc m)

lemma exists_equiv_fin {A : Type} [Fintype A] (hA : Nonempty A) :
    ∃ n : ℕ, Nonempty (A ≃ Fin (n + 1)) :=
  ⟨Fintype.card A - 1, ⟨(Fintype.equivFin A).trans (finCongr
    (Nat.sub_add_cancel (Fintype.card_pos_iff.mpr hA)).symm)⟩⟩

/-- **The product of the inputs**, on a nonempty finite set: a comb, relabelled along an ordering
of the inputs. It does not depend on the ordering. -/
def prod (A : Type) [Fintype A] [DecidableEq A] (hA : Nonempty A) : S A :=
  Trunc.lift
    (fun e : A ≃ Fin (Fintype.card A) =>
      map (e.trans (finCongr (Nat.sub_add_cancel (Fintype.card_pos_iff.mpr hA)).symm)).symm
        (comb m (Fintype.card A - 1)))
    (fun _ _ => map_comb_eq hc ha _ _) (Fintype.truncEquivFin A)

variable {hc ha}

/-- The product, along any ordering of the inputs. -/
lemma prod_eq {A : Type} [Fintype A] [DecidableEq A] (hA : Nonempty A) {n : ℕ}
    (e : A ≃ Fin (n + 1)) : prod hc ha A hA = map e.symm (comb m n) := by
  unfold prod
  induction Fintype.truncEquivFin A using Trunc.induction_on with
  | h f => exact map_comb_eq' hc ha _ _

/-- **Products are invariant under relabelling.** -/
lemma map_prod {A A' : Type} [Fintype A] [DecidableEq A] [Fintype A'] [DecidableEq A']
    (hA : Nonempty A) (σ : A ≃ A') :
    map σ (prod hc ha A hA) = prod hc ha A' (hA.map σ) := by
  obtain ⟨n, ⟨e⟩⟩ := exists_equiv_fin hA
  rw [prod_eq hA e, prod_eq _ (σ.symm.trans e), map_map]
  exact map_congr (fun _ => rfl) _

lemma prod_unit : prod hc ha Unit ⟨()⟩ = one := by
  rw [prod_eq _ unitFinOne, comb, map_symm_map]

lemma prod_fin_two : prod hc ha (Fin 2) ⟨0⟩ = m := by
  rw [prod_eq _ (Equiv.refl _), comb_one, bin_one_one, map_map, map_map]
  exact map_eq_self (fun k => by fin_cases k <;> rfl) _

/-- Multiplying by one more input. -/
lemma bin_prod_one {A : Type} [Fintype A] [DecidableEq A] (hA : Nonempty A) :
    bin m (prod hc ha A hA) one = prod hc ha (A ⊕ Unit) (hA.map Sum.inl) := by
  obtain ⟨n, ⟨e⟩⟩ := exists_equiv_fin hA
  rw [prod_eq hA e, prod_eq _ ((Equiv.sumCongr e (Equiv.refl Unit)).trans (snocEquiv (n + 1))),
    comb_succ, bin_map_left, map_map]
  exact map_congr (fun c => by rcases c with a | ⟨⟩ <;> simp) _

/-- **The product of two products** is the product of all the inputs. -/
theorem bin_prod : ∀ (k : ℕ) {B : Type} [Fintype B] [DecidableEq B] (hB : Nonempty B),
    Fintype.card B = k + 1 → ∀ {A : Type} [Fintype A] [DecidableEq A] (hA : Nonempty A),
    bin m (prod hc ha A hA) (prod hc ha B hB) = prod hc ha (A ⊕ B) (hA.map Sum.inl)
  | 0, B, _, _, hB, hcard, A, _, _, hA => by
    obtain ⟨b⟩ := hB
    have e : Unit ≃ B :=
      { toFun := fun _ => b
        invFun := fun _ => ()
        left_inv := fun _ => rfl
        right_inv := fun b' => Fintype.card_le_one_iff.mp hcard.le _ _ }
    rw [← map_prod ⟨()⟩ e, prod_unit, bin_map_right, bin_prod_one, map_prod]
  | k + 1, B, _, _, hB, hcard, A, _, _, hA => by
    obtain ⟨b⟩ := hB
    have hcard' : Fintype.card (Without B b) = k + 1 := by
      have := Fintype.card_congr (rightUnitEquiv b)
      simp only [Fintype.card_sum, Fintype.card_unit, hcard] at this
      omega
    have hB' : Nonempty (Without B b) := Fintype.card_pos_iff.mp (by omega)
    rw [← map_prod (hB'.map Sum.inl) (rightUnitEquiv b), ← bin_prod_one hB', bin_map_right,
      ← bin_assoc_of ha, bin_prod k hB' hcard' hA, bin_prod_one, map_map, map_prod]

/-- **The product of two products** is the product of all the inputs. -/
theorem bin_prod' {A B : Type} [Fintype A] [DecidableEq A] [Fintype B] [DecidableEq B]
    (hA : Nonempty A) (hB : Nonempty B) :
    bin m (prod hc ha A hA) (prod hc ha B hB) = prod hc ha (A ⊕ B) (hA.map Sum.inl) :=
  bin_prod (Fintype.card B - 1) hB (by have := Fintype.card_pos_iff.mpr hB; omega) hA

/-- **Composing products** gives the product. -/
theorem comp_prod {A B : Type} [Fintype A] [DecidableEq A] [Fintype B] [DecidableEq B]
    (hA : Nonempty A) (hB : Nonempty B) (i : A) :
    comp i (prod hc ha A hA) (prod hc ha B hB) = prod hc ha (Without A i ⊕ B) (hB.map Sum.inr) := by
  by_cases h : Nonempty (Without A i)
  · rw [← map_prod (h.map Sum.inl) (rightUnitEquiv i), ← bin_prod_one h,
      comp_map_left_of _ (i := Sum.inr ()) ?h1, comp_inr_bin, one_comp', bin_map_right,
      bin_prod' h hB, map_map, map_map, map_prod]
    · rfl
  · obtain ⟨e, he⟩ : ∃ e : Unit ≃ A, e () = i :=
      ⟨{ toFun := fun _ => i
         invFun := fun _ => ()
         left_inv := fun _ => rfl
         right_inv := fun a => by
           by_contra hne
           exact h ⟨⟨a, fun hai => hne hai.symm⟩⟩ }, rfl⟩
    rw [← map_prod ⟨()⟩ e, prod_unit, comp_map_left_of _ (i := ()) ?h2, one_comp', map_map,
      map_prod]
    · exact he

end Prod

end SetOperad

/-! ## The universal property of `ComSet` -/

namespace ComSet

open SetOperad

variable {S : (A : Type) → [Fintype A] → [DecidableEq A] → Type v} [SetOperad S]

/-- **The morphism out of `ComSet`** defined by a commutative and associative binary element. -/
def lift (m : S (Fin 2)) (hc : IsComm m) (ha : IsAssoc m) : SetOperadHom ComSet S where
  app A _ _ x := prod hc ha A x.down
  app_map e x := (map_prod x.down e).symm
  app_one := prod_unit
  app_comp i x y := (comp_prod x.down y.down i).symm

@[simp] lemma lift_mu (m : S (Fin 2)) (hc : IsComm m) (ha : IsAssoc m) :
    (lift m hc ha).app (Fin 2) mu = m :=
  prod_fin_two (hc := hc) (ha := ha)

lemma isComm_mu : IsComm (S := ComSet) mu := Subsingleton.elim _ _

lemma isAssoc_mu : IsAssoc (S := ComSet) mu := Subsingleton.elim _ _

/-- The image of the binary operation under a morphism is commutative. -/
lemma isComm_app (φ : SetOperadHom ComSet S) : IsComm (φ.app _ mu) := by
  simpa only [IsComm, SetOperadHom.app_map] using congrArg (φ.app _) isComm_mu

/-- The image of the binary operation under a morphism is associative. -/
lemma isAssoc_app (φ : SetOperadHom ComSet S) : IsAssoc (φ.app _ mu) := by
  simpa only [IsAssoc, SetOperadHom.app_map, SetOperadHom.app_bin, SetOperadHom.app_one]
    using congrArg (φ.app _) isAssoc_mu

/-- **Morphisms out of `ComSet` are determined by the binary operation.** -/
theorem hom_ext {φ ψ : SetOperadHom ComSet S} (h : φ.app _ mu = ψ.app _ mu) : φ = ψ := by
  suffices key : ∀ (k : ℕ) (A : Type) [Fintype A] [DecidableEq A], Fintype.card A = k + 1 →
      ∀ x : ComSet A, φ.app A x = ψ.app A x by
    ext A _ _ x
    obtain ⟨n, ⟨e⟩⟩ := exists_equiv_fin x.down
    exact key n A (by simpa using Fintype.card_congr e) x
  intro k
  induction k with
  | zero =>
    intro A _ _ hcard x
    obtain ⟨a⟩ := x.down
    have e : Unit ≃ A :=
      { toFun := fun _ => a
        invFun := fun _ => ()
        left_inv := fun _ => rfl
        right_inv := fun b => Fintype.card_le_one_iff.mp hcard.le _ _ }
    obtain rfl : x = map e one := Subsingleton.elim _ _
    rw [φ.app_map, ψ.app_map, φ.app_one, ψ.app_one]
  | succ k ih =>
    intro A _ _ hcard x
    obtain ⟨a⟩ := x.down
    have hcard' : Fintype.card (Without A a) = k + 1 := by
      have := Fintype.card_congr (rightUnitEquiv a)
      simp only [Fintype.card_sum, Fintype.card_unit, hcard] at this
      omega
    have hA' : Nonempty (Without A a) := Fintype.card_pos_iff.mp (by omega)
    obtain rfl : x = map (rightUnitEquiv a) (bin mu (⟨hA'⟩ : ComSet (Without A a)) one) :=
      Subsingleton.elim _ _
    rw [φ.app_map, ψ.app_map, φ.app_bin, ψ.app_bin, φ.app_one, ψ.app_one, h,
      ih _ hcard' ⟨hA'⟩]

/-- **The universal property of `ComSet`**: morphisms out of it are the commutative and
associative binary elements of the target. -/
def homEquiv : SetOperadHom ComSet S ≃ {m : S (Fin 2) // IsComm m ∧ IsAssoc m} where
  toFun φ := ⟨φ.app _ mu, isComm_app φ, isAssoc_app φ⟩
  invFun m := lift m.1 m.2.1 m.2.2
  left_inv φ := hom_ext (lift_mu (φ.app _ mu) (isComm_app φ) (isAssoc_app φ))
  right_inv m := Subtype.ext (lift_mu m.1 m.2.1 m.2.2)

/-- **The universal property of the linearization of `ComSet`**: morphisms from it into an operad
in modules are the commutative and associative binary elements of the target. -/
noncomputable def linHomEquiv (R : Type u) [CommRing R]
    {Q : (A : Type) → [Fintype A] → [DecidableEq A] → Type w}
    [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (Q A)]
    [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (Q A)] [SymOperad R Q] :
    SymOperadHom R (Lin R ComSet) Q ≃ {m : Und R Q (Fin 2) // IsComm m ∧ IsAssoc m} :=
  (Operad.linHomEquiv R).symm.trans homEquiv

end ComSet

/-! ## The presentation -/

/-- The generator of `ComSet`: one binary operation. -/
inductive ComGen : ℕ → Type
  | mu : ComGen 2

/-- The relations of `ComSet`: commutativity and associativity. -/
inductive ComRel : ∀ {A : Type} [Fintype A] [DecidableEq A], Syn ComGen A → Syn ComGen A → Prop
  | comm : ComRel (.map (Equiv.swap 0 1) (.gen .mu)) (.gen .mu)
  | assoc : ComRel (.map (Equiv.sumAssoc Unit Unit Unit) (Syn.bin (.gen .mu) (Syn.bin (.gen .mu) .one .one) .one))
      (Syn.bin (.gen .mu) .one (Syn.bin (.gen .mu) .one .one))

namespace ComSet

open SetOperad

/-- Generator values respecting commutativity and associativity. -/
lemma respects_iff {S : (A : Type) → [Fintype A] → [DecidableEq A] → Type v} [SetOperad S]
    (f : ∀ n, ComGen n → S (Fin n)) :
    Pres.Respects ComRel f ↔ IsComm (f 2 .mu) ∧ IsAssoc (f 2 .mu) := by
  constructor
  · intro h
    exact ⟨h _ _ .comm, h _ _ .assoc⟩
  · rintro ⟨hc, ha⟩ A _ _ x y hxy
    cases hxy with
    | comm => exact hc
    | assoc => exact ha

/-- The presented operad maps to `ComSet`. -/
def ofPres : SetOperadHom (Pres ComGen ComRel) ComSet :=
  Pres.lift (fun _ g => match g with | .mu => mu) ((respects_iff _).mpr ⟨isComm_mu, isAssoc_mu⟩)

/-- `ComSet` maps to the presented operad. -/
def toPres : SetOperadHom ComSet (Pres ComGen ComRel) :=
  lift (Pres.gen .mu) (Pres.mk_eq_mk_of_rel .comm) (Pres.mk_eq_mk_of_rel .assoc)

/-- **`ComSet` is presented by one commutative associative binary operation.** -/
def comPresIso : SetOperadIso (Pres ComGen ComRel) ComSet where
  hom := ofPres
  inv := toPres
  hom_inv_id := Pres.hom_ext fun n g => by
    cases g
    exact lift_mu (Pres.gen ComGen.mu) (Pres.mk_eq_mk_of_rel ComRel.comm)
      (Pres.mk_eq_mk_of_rel ComRel.assoc)
  inv_hom_id := by
    ext A _ _ x
    exact Subsingleton.elim _ _

end ComSet

end Operad
