/-
# The diamond lemma for free associative algebras

Words over an alphabet `I` with a well-founded linear order, compared degree-lexicographically,
with the contexts `w ↦ u ++ w ++ v` (`Words.ctxOrder`); rules replace a leading word by a
combination of smaller words inside any context, and the free module `List I →₀ R` on the words
modulo the ideal of the rules (`Rules.ideal_eq_span`) is the quotient of the free algebra on `I`
by the two-sided ideal generated by the relations.

**Classification of ambiguities** (`Words.classify`): two occurrences of nonempty leading words in
a word are disjoint, or they overlap or one contains the other, and then the ambiguity factors
through the segment they cover, a **critical ambiguity** (`Words.Critical`): covered by the two
leading words and shorter than their total length. So **Bergman's diamond lemma for free
algebras** (`Words.isCompl_of_critical`): if the critical ambiguities are resolvable, the words
containing no leading word are a basis of the quotient.
-/
import Operad.DiamondCtx
import Operad.ShuffleAnyOrder

namespace Operad

namespace Words

open STree

variable (I : Type*) [LinearOrder I] [WellFoundedLT I]

/-- **Words with their contexts** `w ↦ u ++ w ++ v`, compared degree-lexicographically. -/
def ctxOrder : CtxOrder Unit (fun _ => List I) where
  lt := DegLex
  wf _ := degLex_wf
  trans := DegLex.trans
  IsCtx f := ∃ u v : List I, ∀ w, f w = u ++ w ++ v
  ctx_id _ := ⟨[], [], fun w => by simp⟩
  ctx_comp := by
    rintro _ _ _ f g ⟨u, v, hf⟩ ⟨u', v', hg⟩
    exact ⟨u ++ u', v' ++ v, fun w => by simp [hf, hg]⟩
  lt_ctx := by
    rintro _ _ f ⟨u, v, hf⟩ x y h
    rw [hf, hf]
    simpa only [List.append_assoc] using h.append u v

variable {I} {R : Type*} [CommRing R] {ρ : Type*} (G : Rules R ρ (ctxOrder I))

lemma isCtx_iff {f : List I → List I} :
    (ctxOrder I).IsCtx (a := ()) (b := ()) f ↔ ∃ u v : List I, ∀ w, f w = u ++ w ++ v :=
  Iff.rfl

/-- **A word is normal** if and only if no leading word is a factor of it. -/
lemma normal_iff {w : List I} :
    G.Normal (b := ()) w ↔ ∀ r (u v : List I), u ++ G.lead r ++ v ≠ w := by
  refine ⟨fun h r u v => h r (fun x => u ++ x ++ v) ⟨u, v, fun _ => rfl⟩, ?_⟩
  rintro h r f ⟨u, v, hf⟩
  rw [hf]
  exact h r u v

/-- **A critical ambiguity** of words: the two leading words cover the word, which is shorter
than their total length. -/
def Critical {r₁ r₂ : ρ} (B : G.Amb () r₁ r₂) : Prop :=
  ∃ a₁ b₁ a₂ b₂ : List I, (∀ w, B.f₁ w = a₁ ++ w ++ b₁) ∧ (∀ w, B.f₂ w = a₂ ++ w ++ b₂) ∧
    (a₁ = [] ∨ a₂ = []) ∧ (b₁ = [] ∨ b₂ = []) ∧
    B.top.length < (G.lead r₁).length + (G.lead r₂).length

variable {G}

lemma Critical.swap {r₁ r₂ : ρ} {B : G.Amb () r₁ r₂} (h : Critical G B) :
    Critical G B.swap := by
  obtain ⟨a₁, b₁, a₂, b₂, h₁, h₂, ha, hb, hl⟩ := h
  refine ⟨a₂, b₂, a₁, b₁, h₂, h₁, ha.symm, hb.symm, ?_⟩
  rw [Rules.Amb.swap_top, add_comm]
  exact hl

variable (G)

/-- **Classification**, when the first occurrence does not start after the second. -/
theorem classify_le (hlead : ∀ r, G.lead r ≠ []) {r₁ r₂ : ρ} (A : G.Amb () r₁ r₂)
    {u₁ v₁ u₂ v₂ : List I} (h₁ : ∀ w, A.f₁ w = u₁ ++ w ++ v₁) (h₂ : ∀ w, A.f₂ w = u₂ ++ w ++ v₂)
    (hu : u₁.length ≤ u₂.length) :
    A.IsDisjoint ∨ ∃ B : G.Amb () r₁ r₂, Critical G B ∧ A.FactorsThrough B := by
  have heq : u₁ ++ G.lead r₁ ++ v₁ = u₂ ++ G.lead r₂ ++ v₂ := by
    rw [← h₁, ← h₂]
    exact A.eq
  obtain ⟨s, rfl⟩ : u₁ <+: u₂ := List.prefix_of_prefix_length_le
    ⟨G.lead r₁ ++ v₁, by rw [← List.append_assoc]⟩ ⟨G.lead r₂ ++ v₂, by
      rw [← List.append_assoc, heq]⟩ hu
  simp only [List.append_assoc, List.append_cancel_left_eq] at heq
  by_cases hs : (G.lead r₁).length ≤ s.length
  · -- disjoint occurrences
    obtain ⟨mid, rfl⟩ : G.lead r₁ <+: s := List.prefix_of_prefix_length_le
      ⟨v₁, rfl⟩ ⟨G.lead r₂ ++ v₂, heq.symm⟩ hs
    simp only [List.append_assoc, List.append_cancel_left_eq] at heq
    subst heq
    left
    refine ⟨fun x y => u₁ ++ x ++ (mid ++ y ++ v₂), fun y => ⟨u₁, mid ++ y ++ v₂, fun _ => rfl⟩,
      fun x => ⟨u₁ ++ x ++ mid, v₂, fun _ => by simp⟩, ?_, ?_⟩
    · funext x
      rw [h₁]
      simp
    · funext y
      rw [h₂]
      simp
  · push Not at hs
    obtain ⟨x₀, hx₀⟩ : s <+: G.lead r₁ := List.prefix_of_prefix_length_le
      ⟨G.lead r₂ ++ v₂, heq.symm⟩ ⟨v₁, rfl⟩ hs.le
    have hx₀' : x₀ ++ v₁ = G.lead r₂ ++ v₂ := by
      rw [← hx₀, List.append_assoc] at heq
      exact List.append_cancel_left heq
    have hl₁ : (G.lead r₁).length = s.length + x₀.length := by
      rw [← hx₀, List.length_append]
    by_cases hx : (G.lead r₂).length ≤ x₀.length
    · -- the second leading word inside the first
      obtain ⟨s', rfl⟩ : G.lead r₂ <+: x₀ := List.prefix_of_prefix_length_le
        ⟨v₂, rfl⟩ ⟨v₁, hx₀'⟩ hx
      have hv : v₂ = s' ++ v₁ := by
        rw [List.append_assoc] at hx₀'
        exact (List.append_cancel_left hx₀').symm
      subst hv
      right
      refine ⟨⟨fun w => w, fun w => s ++ w ++ s', ⟨[], [], fun _ => by simp⟩,
        ⟨s, s', fun _ => rfl⟩, by simp only [← hx₀, List.append_assoc]⟩, ?_, ?_⟩
      · refine ⟨[], [], s, s', fun _ => by simp, fun _ => rfl, Or.inl rfl, Or.inl rfl, ?_⟩
        show (G.lead r₁).length < _
        have := List.length_pos_iff.2 (hlead r₂)
        omega
      · refine ⟨fun w => u₁ ++ w ++ v₁, ⟨u₁, v₁, fun _ => rfl⟩, ?_, ?_⟩
        · funext w
          rw [h₁]
          rfl
        · funext w
          rw [h₂]
          simp
    · -- a proper overlap
      push Not at hx
      obtain ⟨y₀, hy₀⟩ : x₀ <+: G.lead r₂ := List.prefix_of_prefix_length_le
        ⟨v₁, rfl⟩ ⟨v₂, hx₀'.symm⟩ hx.le
      have hv : v₁ = y₀ ++ v₂ := by
        rw [← hy₀, List.append_assoc] at hx₀'
        exact List.append_cancel_left hx₀'
      subst hv
      right
      refine ⟨⟨fun w => w ++ y₀, fun w => s ++ w, ⟨[], y₀, fun _ => by simp⟩,
        ⟨s, [], fun _ => by simp⟩, by simp only [← hx₀, ← hy₀, List.append_assoc]⟩, ?_, ?_⟩
      · refine ⟨[], y₀, s, [], fun _ => by simp, fun _ => by simp, Or.inl rfl, Or.inr rfl, ?_⟩
        show (G.lead r₁ ++ y₀).length < _
        have hl₂ : (G.lead r₂).length = x₀.length + y₀.length := by
          rw [← hy₀, List.length_append]
        rw [List.length_append]
        omega
      · refine ⟨fun w => u₁ ++ w ++ v₂, ⟨u₁, v₂, fun _ => rfl⟩, ?_, ?_⟩
        · funext w
          rw [h₁]
          simp
        · funext w
          rw [h₂]
          simp

/-- **Classification of ambiguities of words**: every ambiguity between rules with nonempty
leading words is disjoint or factors through a critical ambiguity. -/
theorem classify (hlead : ∀ r, G.lead r ≠ []) {r₁ r₂ : ρ} (A : G.Amb () r₁ r₂) :
    A.IsDisjoint ∨ ∃ B : G.Amb () r₁ r₂, Critical G B ∧ A.FactorsThrough B := by
  obtain ⟨u₁, v₁, h₁⟩ := A.ctx₁
  obtain ⟨u₂, v₂, h₂⟩ := A.ctx₂
  rcases le_total u₁.length u₂.length with hu | hu
  · exact classify_le G hlead A h₁ h₂ hu
  · rcases classify_le G hlead A.swap h₂ h₁ hu with h | ⟨B, hB, h⟩
    · exact Or.inl (Rules.Amb.IsDisjoint.of_swap h)
    · exact Or.inr ⟨B.swap, hB.swap, Rules.Amb.FactorsThrough.of_swap h⟩

/-- **Bergman's diamond lemma for free algebras**: if the leading words are nonempty and the
critical ambiguities are resolvable, every ambiguity is resolvable. -/
theorem resolvable_of_critical (hlead : ∀ r, G.lead r ≠ [])
    (hcrit : ∀ {r₁ r₂ : ρ} (B : G.Amb () r₁ r₂), Critical G B → B.Res) :
    (G.rw ()).Resolvable :=
  Rules.resolvable_of_crit (fun {_ r₁ r₂} (B : G.Amb () r₁ r₂) => Critical G B)
    (fun B hB => hcrit B hB)
    (fun A => classify G hlead A |>.imp id fun ⟨B, hB, h⟩ => ⟨(), B, hB, h⟩)
    ()

/-- **Bergman's diamond lemma for free algebras**: if the leading words are nonempty and the
critical ambiguities are resolvable, the normal words span a complement of the ideal of the
rules. -/
theorem isCompl_of_critical (hlead : ∀ r, G.lead r ≠ [])
    (hcrit : ∀ {r₁ r₂ : ρ} (B : G.Amb () r₁ r₂), Critical G B → B.Res) :
    IsCompl (Finsupp.supported R R {w : List I | G.Normal (b := ()) w}) (G.rw ()).ideal := by
  rw [← G.irr_eq]
  exact (resolvable_of_critical G hlead hcrit).isCompl

end Words

end Operad
