/-
# Rewriting in contexts and the Buchberger criterion

Monomials come in several types `M a` (arities, for operads), with **contexts**: a class of maps
`M a → M b` containing the identities and closed under composition, and a well-founded order on
each type which every context preserves (`CtxOrder`). **Rules** (`Rules`) are pairs of a
leading monomial and a tail, a combination of smaller monomials of the same type. A monomial is
reduced by applying a rule inside a context, which makes a linear rewriting system in each type
(`Rules.rw`); its ideal is the span of the images of the relations `lead - tail` under the
contexts (`Rules.ideal_eq_span`), and its irreducible monomials are the **normal** ones, in which
no leading monomial occurs (`Rules.mem_irr_iff`).

An **ambiguity** (`Rules.Amb`) is a monomial with two occurrences of leading monomials, given by
two contexts. It is
* **disjoint** (`Rules.Amb.IsDisjoint`) when the two occurrences can be replaced independently:
  both contexts are partial applications of a map `d : M a₁ → M a₂ → M b` whose partial
  applications are all contexts. A disjoint ambiguity is resolvable
  (`Rules.Amb.res_of_isDisjoint`).
* otherwise an overlap, which in practice factors, by a context, through an ambiguity at a
  **small common multiple** of the two leading monomials (`Rules.Amb.FactorsThrough`), and
  resolvability passes from the small ambiguity to the large one (`Rules.Amb.res_of_factors`).

**The Buchberger criterion** (`Rules.resolvable_of_crit`): if every ambiguity is disjoint or
factors through one of a class of critical ambiguities, all of which are resolvable, then in
every type the normal monomials are a basis of the quotient by the ideal generated by the rules
(`Rules.isCompl_of_crit`). Conversely, if they are, every ambiguity is resolvable
(`Rules.Amb.res_of_isCompl`).
-/
import Operad.Diamond

namespace Operad

open Finsupp

/-- **Monomials with contexts and a compatible order**: monomials `M a` of each type `a`, a class
of maps `M a → M b` (the contexts) containing the identities and closed under composition, and
a well-founded transitive relation on each type which the contexts preserve. -/
structure CtxOrder (ι : Type*) (M : ι → Type*) where
  /-- the order on the monomials of each type -/
  lt : ∀ {a}, M a → M a → Prop
  /-- the order is well-founded -/
  wf : ∀ a, WellFounded (@lt a)
  /-- the order is transitive -/
  trans : ∀ {a} {x y z : M a}, lt x y → lt y z → lt x z
  /-- the contexts -/
  IsCtx : ∀ {a b}, (M a → M b) → Prop
  /-- the identity is a context -/
  ctx_id : ∀ a, IsCtx (id : M a → M a)
  /-- contexts compose -/
  ctx_comp : ∀ {a b c} {f : M b → M c} {g : M a → M b}, IsCtx f → IsCtx g → IsCtx (f ∘ g)
  /-- contexts preserve the order -/
  lt_ctx : ∀ {a b} {f : M a → M b}, IsCtx f → ∀ {x y : M a}, lt x y → lt (f x) (f y)

/-- **Rules** indexed by `ρ`: each has a type `src r`, a leading monomial and a tail, a
combination of monomials smaller than the leading one. -/
structure Rules (R : Type*) [CommRing R] {ι : Type*} {M : ι → Type*} (ρ : Type*)
    (O : CtxOrder ι M) where
  /-- the type of a rule -/
  src : ρ → ι
  /-- the leading monomial of a rule -/
  lead : ∀ r, M (src r)
  /-- the tail of a rule -/
  tail : ∀ r, M (src r) →₀ R
  /-- the tail is smaller than the leading monomial -/
  tail_lt : ∀ r, ∀ m ∈ (tail r).support, O.lt m (lead r)

namespace Rules

variable {R : Type*} [CommRing R] {ι : Type*} {M : ι → Type*} {ρ : Type*} {O : CtxOrder ι M}
  (G : Rules R ρ O)

lemma lt_of_mem_mapDomain {a b : ι} {f : M a → M b} (hf : O.IsCtx f) {v : M a →₀ R} {t : M a}
    (hv : ∀ m ∈ v.support, O.lt m t) : ∀ m ∈ (mapDomain f v).support, O.lt m (f t) := by
  classical
  intro m hm
  obtain ⟨m', hm', rfl⟩ := Finset.mem_image.1 (mapDomain_support hm)
  exact O.lt_ctx hf (hv m' hm')

/-- **The rewriting system of the rules** on the monomials of type `b`: a monomial `f (lead r)`,
for a context `f`, reduces to the image `f (tail r)` of the tail. -/
def rw (b : ι) : Rewriting R (M b) where
  lt := O.lt
  wf := O.wf b
  trans := O.trans
  red t := {v | ∃ r, ∃ f : M (G.src r) → M b, O.IsCtx f ∧ f (G.lead r) = t ∧
    v = mapDomain f (G.tail r)}
  red_lt := by
    rintro t v ⟨r, f, hf, rfl, rfl⟩
    exact lt_of_mem_mapDomain hf (G.tail_lt r)

/-- **A normal monomial**: no leading monomial occurs in it. -/
def Normal {b : ι} (t : M b) : Prop :=
  ∀ r, ∀ f : M (G.src r) → M b, O.IsCtx f → f (G.lead r) ≠ t

/-- The irreducible monomials are the normal ones. -/
lemma mem_irr_iff {b : ι} {t : M b} : t ∈ (G.rw b).Irr ↔ G.Normal t := by
  refine ⟨fun h r f hf ht => ?_, fun h => ?_⟩
  · have : mapDomain f (G.tail r) ∈ (G.rw b).red t := ⟨r, f, hf, ht, rfl⟩
    rw [show (G.rw b).red t = ∅ from h] at this
    exact this
  · refine Set.eq_empty_iff_forall_notMem.2 fun v ⟨r, f, hf, ht, _⟩ => h r f hf ht

lemma irr_eq {b : ι} : (G.rw b).Irr = {t | G.Normal t} := Set.ext fun _ => G.mem_irr_iff

/-- **The ideal generated by the rules**: the span of the images of the relations `lead - tail`
under the contexts. -/
theorem ideal_eq_span (b : ι) : (G.rw b).ideal = Submodule.span R
    {x | ∃ r, ∃ f : M (G.src r) → M b, O.IsCtx f ∧
      x = mapDomain f (single (G.lead r) 1 - G.tail r)} := by
  refine le_antisymm (Submodule.span_le.2 ?_) (Submodule.span_le.2 ?_)
  · rintro _ ⟨t, -, v, ⟨r, f, hf, rfl, rfl⟩, rfl⟩
    exact Submodule.subset_span ⟨r, f, hf, by rw [mapDomain_sub, mapDomain_single]⟩
  · rintro _ ⟨r, f, hf, rfl⟩
    rw [mapDomain_sub, mapDomain_single]
    exact (G.rw b).sub_mem_ideal ⟨r, f, hf, rfl, rfl⟩

/-- **Contexts map the ideal below a monomial into the ideal below its image.** -/
theorem mapDomain_mem_idealOn {a b : ι} {g : M a → M b} (hg : O.IsCtx g) {t : M a}
    {v : M a →₀ R} (hv : v ∈ (G.rw a).idealOn ((G.rw a).below t)) :
    mapDomain g v ∈ (G.rw b).idealOn ((G.rw b).below (g t)) := by
  suffices h : (G.rw a).idealOn ((G.rw a).below t) ≤
      ((G.rw b).idealOn ((G.rw b).below (g t))).comap (lmapDomain R R g) from h hv
  refine Submodule.span_le.2 ?_
  rintro _ ⟨m, hm, v, ⟨r, f, hf, rfl, rfl⟩, rfl⟩
  have hlt : O.lt (g (f (G.lead r))) (g t) := O.lt_ctx hg hm
  have hred : mapDomain (g ∘ f) (G.tail r) ∈ (G.rw b).red (g (f (G.lead r))) :=
    ⟨r, g ∘ f, O.ctx_comp hg hf, rfl, rfl⟩
  have key := (G.rw b).sub_mem_idealOn (s := (G.rw b).below (g t)) hlt hred
  rw [SetLike.mem_coe, Submodule.mem_comap, lmapDomain_apply, mapDomain_sub, mapDomain_single,
    ← mapDomain_comp]
  exact key

/-! ## Ambiguities -/

/-- **An ambiguity** of type `b` between the rules `r₁` and `r₂`: a monomial in which the two
leading monomials occur, given by two contexts. -/
structure Amb (b : ι) (r₁ r₂ : ρ) where
  /-- the context of the first occurrence -/
  f₁ : M (G.src r₁) → M b
  /-- the context of the second occurrence -/
  f₂ : M (G.src r₂) → M b
  ctx₁ : O.IsCtx f₁
  ctx₂ : O.IsCtx f₂
  eq : f₁ (G.lead r₁) = f₂ (G.lead r₂)

variable {G}

namespace Amb

variable {b : ι} {r₁ r₂ : ρ} (A : G.Amb b r₁ r₂)

/-- **The monomial of an ambiguity.** -/
def top : M b := A.f₁ (G.lead r₁)

/-- **A resolvable ambiguity**: the two reductions differ by an element of the ideal below the
monomial. -/
def Res : Prop :=
  mapDomain A.f₁ (G.tail r₁) - mapDomain A.f₂ (G.tail r₂) ∈ (G.rw b).idealOn ((G.rw b).below A.top)

/-- **A disjoint ambiguity**: both contexts are partial applications of a map of two variables
all of whose partial applications are contexts. -/
def IsDisjoint : Prop :=
  ∃ d : M (G.src r₁) → M (G.src r₂) → M b, (∀ y, O.IsCtx (d · y)) ∧ (∀ x, O.IsCtx (d x)) ∧
    A.f₁ = (d · (G.lead r₂)) ∧ A.f₂ = d (G.lead r₁)

/-- **An ambiguity factors through another one** by a context `g`. -/
def FactorsThrough {a : ι} (B : G.Amb a r₁ r₂) : Prop :=
  ∃ g : M a → M b, O.IsCtx g ∧ A.f₁ = g ∘ B.f₁ ∧ A.f₂ = g ∘ B.f₂

/-- **The swapped ambiguity.** -/
def swap : G.Amb b r₂ r₁ := ⟨A.f₂, A.f₁, A.ctx₂, A.ctx₁, A.eq.symm⟩

lemma swap_top : A.swap.top = A.top := A.eq.symm

lemma IsDisjoint.of_swap {A : G.Amb b r₁ r₂} (h : A.swap.IsDisjoint) : A.IsDisjoint := by
  obtain ⟨d, hd₁, hd₂, h₁, h₂⟩ := h
  exact ⟨fun x y => d y x, hd₂, hd₁, h₂, h₁⟩

lemma FactorsThrough.of_swap {A : G.Amb b r₁ r₂} {a : ι} {B : G.Amb a r₂ r₁}
    (h : A.swap.FactorsThrough B) : A.FactorsThrough B.swap := by
  obtain ⟨g, hg, h₁, h₂⟩ := h
  exact ⟨g, hg, h₂, h₁⟩

/-- **A disjoint ambiguity is resolvable.** -/
theorem res_of_isDisjoint (h : A.IsDisjoint) : A.Res := by
  obtain ⟨d, hd₁, hd₂, h₁, h₂⟩ := h
  set N := (G.rw b).idealOn ((G.rw b).below A.top)
  have ht : A.top = d (G.lead r₁) (G.lead r₂) := by rw [top, h₁]
  let w := (G.tail r₁).sum fun x c => c • mapDomain (d x) (G.tail r₂)
  have hw : w = (G.tail r₂).sum fun y c => c • mapDomain (d · y) (G.tail r₁) := by
    simp only [w, mapDomain, Finsupp.smul_sum, smul_single, smul_eq_mul]
    rw [Finsupp.sum_comm]
    simp only [mul_comm]
  have e₁ : mapDomain A.f₁ (G.tail r₁) - w = (G.tail r₁).sum fun x c =>
      c • (single (d x (G.lead r₂)) 1 - mapDomain (d x) (G.tail r₂)) := by
    simp only [w, h₁, mapDomain, ← Finsupp.sum_sub, smul_sub, smul_single_one]
  have e₂ : mapDomain A.f₂ (G.tail r₂) - w = (G.tail r₂).sum fun y c =>
      c • (single (d (G.lead r₁) y) 1 - mapDomain (d · y) (G.tail r₁)) := by
    simp only [hw, h₂, mapDomain, ← Finsupp.sum_sub, smul_sub, smul_single_one]
  have m₁ : mapDomain A.f₁ (G.tail r₁) - w ∈ N := by
    rw [e₁]
    refine Submodule.finsuppSum_mem R _ _ _ fun x hx => Submodule.smul_mem _ _ ?_
    refine (G.rw b).sub_mem_idealOn ?_ ⟨r₂, d x, hd₂ x, rfl, rfl⟩
    show O.lt _ _
    rw [ht]
    exact O.lt_ctx (hd₁ _) (G.tail_lt r₁ x (mem_support_iff.2 hx))
  have m₂ : mapDomain A.f₂ (G.tail r₂) - w ∈ N := by
    rw [e₂]
    refine Submodule.finsuppSum_mem R _ _ _ fun y hy => Submodule.smul_mem _ _ ?_
    refine (G.rw b).sub_mem_idealOn ?_ ⟨r₁, (d · y), hd₁ y, rfl, rfl⟩
    show O.lt _ _
    rw [ht]
    exact O.lt_ctx (hd₂ _) (G.tail_lt r₂ y (mem_support_iff.2 hy))
  have := Submodule.sub_mem _ m₁ m₂
  rwa [sub_sub_sub_cancel_right] at this

/-- **Resolvability passes along a factorization** through a context. -/
theorem res_of_factors {a : ι} {B : G.Amb a r₁ r₂} (h : A.FactorsThrough B) (hB : B.Res) :
    A.Res := by
  obtain ⟨g, hg, h₁, h₂⟩ := h
  have := mapDomain_mem_idealOn G hg hB
  rw [mapDomain_sub, ← mapDomain_comp, ← mapDomain_comp] at this
  rw [Res, top, h₁, h₂]
  exact this

/-- **A trivial ambiguity is resolvable**: the same occurrence twice. -/
theorem res_of_eq {r : ρ} (A : G.Amb b r r) (h : A.f₁ = A.f₂) : A.Res := by
  rw [Res, h, sub_self]
  exact Submodule.zero_mem _

end Amb

/-- **Resolvability of the rewriting system is resolvability of all ambiguities.** -/
theorem resolvable_iff {b : ι} :
    (G.rw b).Resolvable ↔ ∀ r₁ r₂ (A : G.Amb b r₁ r₂), A.Res := by
  constructor
  · intro h r₁ r₂ A
    exact h _ _ ⟨r₁, A.f₁, A.ctx₁, rfl, rfl⟩ _ ⟨r₂, A.f₂, A.ctx₂, A.eq.symm, rfl⟩
  · rintro h t _ ⟨r₁, f₁, hf₁, rfl, rfl⟩ _ ⟨r₂, f₂, hf₂, ht, rfl⟩
    exact h r₁ r₂ ⟨f₁, f₂, hf₁, hf₂, ht.symm⟩

/-- **The Buchberger criterion**: if every ambiguity is disjoint or factors through an
ambiguity of a class `P` (the critical ones, at small common multiples), and every ambiguity of
the class `P` is resolvable, then every ambiguity is resolvable. -/
theorem resolvable_of_crit (P : ∀ {a r₁ r₂}, G.Amb a r₁ r₂ → Prop)
    (hP : ∀ {a r₁ r₂} (B : G.Amb a r₁ r₂), P B → B.Res)
    (hcl : ∀ {b r₁ r₂} (A : G.Amb b r₁ r₂),
      A.IsDisjoint ∨ ∃ a, ∃ B : G.Amb a r₁ r₂, P B ∧ A.FactorsThrough B)
    (b : ι) : (G.rw b).Resolvable := by
  refine resolvable_iff.2 fun r₁ r₂ A => ?_
  rcases hcl A with h | ⟨a, B, hB, h⟩
  · exact A.res_of_isDisjoint h
  · exact A.res_of_factors h (hP B hB)

/-- **The Buchberger criterion**, conclusion: the normal monomials span a complement of the
ideal generated by the rules, in every type. -/
theorem isCompl_of_crit (P : ∀ {a r₁ r₂}, G.Amb a r₁ r₂ → Prop)
    (hP : ∀ {a r₁ r₂} (B : G.Amb a r₁ r₂), P B → B.Res)
    (hcl : ∀ {b r₁ r₂} (A : G.Amb b r₁ r₂),
      A.IsDisjoint ∨ ∃ a, ∃ B : G.Amb a r₁ r₂, P B ∧ A.FactorsThrough B)
    (b : ι) : IsCompl (supported R R {t : M b | G.Normal t}) (G.rw b).ideal := by
  rw [← G.irr_eq]
  exact (resolvable_of_crit P hP hcl b).isCompl

/-- **Conversely**, if the normal monomials are independent modulo the ideal, every ambiguity is
resolvable, in particular the critical ones. -/
theorem Amb.res_of_isCompl {b : ι} {r₁ r₂ : ρ} (A : G.Amb b r₁ r₂)
    (h : Disjoint (supported R R {t : M b | G.Normal t}) (G.rw b).ideal) : A.Res := by
  rw [← G.irr_eq] at h
  exact resolvable_iff.1 (Rewriting.resolvable_of_disjoint h) r₁ r₂ A

end Rules

end Operad
