/-
# Grafting is inverse to the root decomposition

For the free graded operad `T(W)` on a graded linear species, **grafting**
`G : W ∘ T(W) → T(W)` (`FreeGrL.graft`) composes the generator at the root with the trees above
it: the total composition after `ι : W → T(W)` (`GrComposite.total`). It commutes with relabelling
and with the right action, `G (ω ◁ᵢ z) = G ω ∘ᵢ z` (`FreeGrL.graft_act`), and sends a corolla
`w ⊗ (1, …, 1)` to `w`.

* **The root decomposition of a grafted tree is its decomposition** (`FreeGrL.root_graft`):
  `ρ ∘ G = 1`, by induction on `W ∘ T(W)` generated by the corollas under the action
  (`GrComposite.induction_act`), and grafted trees have no unit component.
* **Grafting the root decomposition of a tree gives it back**, up to its unit component
  (`FreeGrL.graft_root`): `G ∘ ρ = 1 - ε`, by induction on the operations of `T(W)`
  (`GrSuboperad.mem_of_presGen`).

So `ρ` is an isomorphism from the trees without unit component onto `W ∘ T(W)`.
-/
import Operad.GrTotal
import Operad.GrCompSpan
import Operad.GrSuboperad

universe u v

namespace Operad

open Function Sym GerBV GrComposite

variable {R : Type u} [CommRing R]
  {W : (A : Type) → [Fintype A] → [DecidableEq A] → Type v}
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (W A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (W A)] [GrSpecies R W]

namespace FreeGrL

local notation "𝒥" => GrOperadIdeal.span R (grLinRel R W)

/-- **The generators have no unit component.** -/
lemma unitCoeffL_ι {A : Type} [Fintype A] [DecidableEq A] (w : W A) :
    unitCoeffL R W A ((ι R W).app A w) = 0 := by
  rw [GrSpeciesHom.app_eq_chart (ι R W) (Fintype.equivFin A).symm, ι_app_fin]
  show unitCoeffL R W A (GrOperad.map (R := R) _ ((𝒥).proj _ (FreeGr.gen _) + (𝒥).proj _
    (FreeGr.gen _))) = 0
  rw [unitCoeffL_map, map_add, unitCoeffL_proj, unitCoeffL_proj, unitCoeff_gen, unitCoeff_gen,
    add_zero]

variable (R W) in
/-- **Grafting**: the generator at the root composed with the trees above it. -/
noncomputable def graft (S : Type) [Fintype S] [DecidableEq S] :
    GrComposite R W (FreeGrL R W) S →ₗ[R] FreeGrL R W S :=
  total R (ι R W).toSymSpeciesHom

variable {S : Type} [Fintype S] [DecidableEq S]

lemma graft_act {Y : Type} [Fintype Y] [DecidableEq Y] (i : S) (z : FreeGrL R W Y)
    (ω : GrComposite R W (FreeGrL R W) S) :
    graft R W _ (act R W i z ω) = GrOperad.comp (R := R) i (graft R W S ω) z :=
  total_act R W _ i z ω

lemma graft_map {S' : Type} [Fintype S'] [DecidableEq S'] (σ : S ≃ S')
    (ω : GrComposite R W (FreeGrL R W) S) :
    graft R W S' (map σ ω) = GrOperad.map (R := R) σ (graft R W S ω) :=
  total_map _ σ ω

/-- **Grafting a corolla gives its generator.** -/
@[simp] lemma graft_corolla {A : Type} [Fintype A] [DecidableEq A] (w : W A) :
    graft R W A (corolla R (FreeGrL R W) A w) = (ι R W).app A w := by
  rw [corolla_apply, graft, total_corGen, GrOperad.map_refl]

/-- **The root decomposition of a grafted tree is its decomposition**, and grafted trees have no
unit component. -/
theorem root_graft_and (ω : GrComposite R W (FreeGrL R W) S) :
    root R W S (graft R W S ω) = ω ∧ unitCoeffL R W S (graft R W S ω) = 0 := by
  refine induction_act (fun S _ _ ω => root R W S (graft R W S ω) = ω ∧
      unitCoeffL R W S (graft R W S ω) = 0) (fun S _ _ => by simp only [map_zero, and_self])
    (fun S _ _ x y hx hy => by simp only [map_add, hx.1, hy.1, hx.2, hy.2, add_zero, and_self])
    (fun S _ _ r x hx => by simp only [map_smul, hx.1, hx.2, smul_zero, and_self])
    (fun S S' _ _ _ _ σ x hx => ?_) (fun S Y _ _ _ _ i z x hx => ?_) (fun A _ _ w => ?_) ω
  · beta_reduce at hx ⊢
    rw [graft_map, root_map, hx.1, unitCoeffL_map, hx.2]
    exact ⟨rfl, rfl⟩
  · beta_reduce at hx ⊢
    rw [graft_act, root_comp, hx.1, lact_of_u (aug R W) i (by rw [aug_u, hx.2]),
      LinearMap.zero_apply, add_zero, unitCoeffL_comp, hx.2, zero_mul]
    exact ⟨rfl, rfl⟩
  · beta_reduce
    rw [graft_corolla, root_ι, unitCoeffL_ι]
    exact ⟨rfl, rfl⟩

/-- **`ρ ∘ G = 1`.** -/
theorem root_graft (ω : GrComposite R W (FreeGrL R W) S) : root R W S (graft R W S ω) = ω :=
  (root_graft_and ω).1

/-- **Grafted trees have no unit component.** -/
theorem unitCoeffL_graft (ω : GrComposite R W (FreeGrL R W) S) :
    unitCoeffL R W S (graft R W S ω) = 0 :=
  (root_graft_and ω).2

end FreeGrL

end Operad
