/-
# The free graded operad on a graded linear species

A **graded linear species** is a linear species with parity projections commuting with the
relabellings (`GrSpecies`); every graded operad has an underlying one (`GrOperad.toGrSpecies`).
Its morphisms are the morphisms of linear species commuting with the parity projections
(`GrSpeciesHom`).

* **The skeleton** (`GrSpeciesHom.skeletonEquiv`): a morphism of graded linear species is a family
  of linear maps on the standard finite types commuting with their permutations and the parity
  projections, extended to all finite types through numberings (`GrSpeciesHom.extend`).
* **The free graded operad on a graded linear species** (`FreeGrL`): the free graded operad on the
  homogeneous elements of each `V (Fin n)`, with their parities, modulo the ideal generated by the
  additivity and homogeneity of the generators of each parity and by their equivariance
  (`grLinRel`). The generators form a morphism of graded linear species (`FreeGrL.ι`), and
  **a morphism of graded operads out of `FreeGrL R V` is a morphism of graded linear species out
  of `V`**, by restriction along `ι` (`FreeGrL.homEquiv`, `FreeGrL.homEquiv_apply`,
  `FreeGrL.homEquiv_symm_ι`, `FreeGrL.hom_ext`).
-/
import Operad.GrPresentation
import Operad.SpeciesOp

universe u v w

namespace Operad

/-! ## Graded linear species -/

/-- **A graded linear species**: a linear species with parity projections, complementary
idempotents commuting with the relabellings. -/
class GrSpecies (R : Type u) [CommRing R]
    (V : (A : Type) → [Fintype A] → [DecidableEq A] → Type v)
    [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (V A)]
    [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (V A)] extends SymSpecies R V where
  /-- The parity projections. -/
  par {A : Type} [Fintype A] [DecidableEq A] : Bool → V A →ₗ[R] V A
  /-- Every element is the sum of its even and odd parts. -/
  par_add {A : Type} [Fintype A] [DecidableEq A] (x : V A) : par false x + par true x = x
  /-- The parity projections are complementary idempotents. -/
  par_par {A : Type} [Fintype A] [DecidableEq A] (b b' : Bool) (x : V A) :
    par b (par b' x) = if b = b' then par b' x else 0
  /-- Relabelling preserves parities. -/
  map_par {A B : Type} [Fintype A] [DecidableEq A] [Fintype B] [DecidableEq B] (e : A ≃ B)
    (b : Bool) (x : V A) : map e (par b x) = par b (map e x)

/-- **The underlying graded linear species of a graded operad.** -/
instance (priority := 100) GrOperad.toGrSpecies (R : Type u) [CommRing R]
    (P : (A : Type) → [Fintype A] → [DecidableEq A] → Type v)
    [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (P A)]
    [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (P A)] [GrOperad R P] :
    GrSpecies R P where
  map := GrOperad.map
  map_refl := GrOperad.map_refl
  map_trans := GrOperad.map_trans
  par := GrOperad.par
  par_add := GrOperad.par_add
  par_par := GrOperad.par_par
  map_par := GrOperad.map_par

namespace GrSpecies

variable {R : Type u} [CommRing R] {V : (A : Type) → [Fintype A] → [DecidableEq A] → Type v}
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (V A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (V A)] [GrSpecies R V]
  {A : Type} [Fintype A] [DecidableEq A]

lemma par_par_self (b : Bool) (x : V A) : par (R := R) b (par (R := R) b x) = par (R := R) b x :=
  by rw [par_par, if_pos rfl]

lemma par_par_ne {b b' : Bool} (h : b ≠ b') (x : V A) :
    par (R := R) b (par (R := R) b' x) = 0 := by
  rw [par_par, if_neg h]

end GrSpecies

namespace GrOperad

variable {R : Type u} [CommRing R] {P : (A : Type) → [Fintype A] → [DecidableEq A] → Type v}
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (P A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (P A)] [GrOperad R P]
  {A B : Type} [Fintype A] [DecidableEq A] [Fintype B] [DecidableEq B]

@[simp] lemma toGrSpecies_par (b : Bool) (x : P A) :
    GrSpecies.par (R := R) b x = GrOperad.par (R := R) b x := rfl

@[simp] lemma toGrSpecies_map (e : A ≃ B) (x : P A) :
    SymSpecies.map (R := R) e x = GrOperad.map (R := R) e x := rfl

end GrOperad

/-! ## Morphisms of graded linear species -/

/-- **A morphism of graded linear species**: a morphism of linear species commuting with the
parity projections. -/
structure GrSpeciesHom (R : Type u) [CommRing R]
    (V : (A : Type) → [Fintype A] → [DecidableEq A] → Type v)
    (W : (A : Type) → [Fintype A] → [DecidableEq A] → Type w)
    [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (V A)]
    [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (V A)]
    [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (W A)]
    [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (W A)]
    [GrSpecies R V] [GrSpecies R W] extends SymSpeciesHom R V W where
  app_par {A : Type} [Fintype A] [DecidableEq A] (b : Bool) (x : V A) :
    app A (GrSpecies.par (R := R) b x) = GrSpecies.par (R := R) b (app A x)

/-- The underlying morphism of graded linear species of a morphism of graded operads. -/
def GrOperadHom.toGrSpeciesHom {R : Type u} [CommRing R]
    {P : (A : Type) → [Fintype A] → [DecidableEq A] → Type v}
    {Q : (A : Type) → [Fintype A] → [DecidableEq A] → Type w}
    [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (P A)]
    [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (P A)]
    [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (Q A)]
    [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (Q A)] [GrOperad R P] [GrOperad R Q]
    (φ : GrOperadHom R P Q) : GrSpeciesHom R P Q where
  app := φ.app
  app_map := φ.app_map
  app_par := φ.app_par

namespace GrSpeciesHom

variable {R : Type u} [CommRing R]
  {V : (A : Type) → [Fintype A] → [DecidableEq A] → Type v}
  {W : (A : Type) → [Fintype A] → [DecidableEq A] → Type w}
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (V A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (V A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (W A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (W A)]
  [GrSpecies R V] [GrSpecies R W]

@[ext] lemma ext {φ ψ : GrSpeciesHom R V W}
    (h : ∀ (A : Type) [Fintype A] [DecidableEq A] (x : V A), φ.app A x = ψ.app A x) :
    φ = ψ := by
  obtain ⟨φ', _⟩ := φ
  obtain ⟨ψ', _⟩ := ψ
  have : φ' = ψ' := SymSpeciesHom.ext h
  subst this
  rfl

/-! ### The skeleton -/

/-- A family of linear maps on the standard finite types **commuting with their permutations and
the parity projections**. -/
def Skel (f : ∀ n : ℕ, V (Fin n) →ₗ[R] W (Fin n)) : Prop :=
  (∀ (n : ℕ) (σ : Fin n ≃ Fin n) (x : V (Fin n)),
    f n (SymSpecies.map (R := R) σ x) = SymSpecies.map (R := R) σ (f n x)) ∧
  ∀ (n : ℕ) (b : Bool) (x : V (Fin n)),
    f n (GrSpecies.par (R := R) b x) = GrSpecies.par (R := R) b (f n x)

/-- The component at `A` of the morphism extending `f`, through a chosen numbering of `A`. -/
noncomputable def extendApp (f : ∀ n : ℕ, V (Fin n) →ₗ[R] W (Fin n)) (A : Type) [Fintype A]
    [DecidableEq A] : V A →ₗ[R] W A :=
  SymSpecies.map (R := R) (Fintype.equivFin A).symm ∘ₗ f _ ∘ₗ
    SymSpecies.map (R := R) (Fintype.equivFin A)

/-- **The extension does not depend on the numbering.** -/
lemma extendApp_chart {f : ∀ n : ℕ, V (Fin n) →ₗ[R] W (Fin n)} (hf : Skel f) {A : Type}
    [Fintype A] [DecidableEq A] {n : ℕ} (φ : Fin n ≃ A) (x : V A) :
    extendApp f A x = SymSpecies.map (R := R) φ (f n (SymSpecies.map (R := R) φ.symm x)) := by
  have hn : n = Fintype.card A := by simpa using Fintype.card_congr φ
  subst hn
  set ψ := (Fintype.equivFin A).symm
  have hσ : SymSpecies.map (R := R) ψ.symm x
      = SymSpecies.map (R := R) (φ.trans ψ.symm) (SymSpecies.map (R := R) φ.symm x) := by
    rw [← SymSpecies.map_trans, ← Equiv.trans_assoc, Equiv.symm_trans_self, Equiv.refl_trans]
  show SymSpecies.map (R := R) ψ (f _ (SymSpecies.map (R := R) ψ.symm x)) = _
  rw [hσ, hf.1, ← SymSpecies.map_trans, Equiv.trans_assoc, Equiv.symm_trans_self,
    Equiv.trans_refl]

/-- **The morphism of graded linear species extending a family** of linear maps on the standard
finite types commuting with their permutations and the parity projections. -/
noncomputable def extend (f : ∀ n : ℕ, V (Fin n) →ₗ[R] W (Fin n)) (hf : Skel f) :
    GrSpeciesHom R V W where
  app A _ _ := extendApp f A
  app_map {A B} _ _ _ _ e x := by
    have h1 : SymSpecies.map (R := R) ((Fintype.equivFin A).symm.trans e).symm
        (SymSpecies.map (R := R) e x) = SymSpecies.map (R := R) (Fintype.equivFin A) x := by
      rw [← SymSpecies.map_trans]
      exact congrArg (fun g => SymSpecies.map (R := R) g x) (Equiv.ext fun a => by simp)
    rw [extendApp_chart hf ((Fintype.equivFin A).symm.trans e), h1, SymSpecies.map_trans]
    rfl
  app_par {A} _ _ b x := by
    show SymSpecies.map (R := R) _ (f _ (SymSpecies.map (R := R) _ (GrSpecies.par (R := R) b x)))
      = GrSpecies.par (R := R) b
        (SymSpecies.map (R := R) _ (f _ (SymSpecies.map (R := R) _ x)))
    rw [GrSpecies.map_par, hf.2, GrSpecies.map_par]

@[simp] lemma extend_app_fin {f : ∀ n : ℕ, V (Fin n) →ₗ[R] W (Fin n)} (hf : Skel f) (n : ℕ)
    (x : V (Fin n)) : (extend f hf).app (Fin n) x = f n x := by
  show extendApp f (Fin n) x = f n x
  rw [extendApp_chart hf (Equiv.refl (Fin n)), Equiv.refl_symm, SymSpecies.map_refl,
    SymSpecies.map_refl]

/-- A morphism of graded linear species, computed through a numbering. -/
lemma app_eq_chart (φ : GrSpeciesHom R V W) {A : Type} [Fintype A] [DecidableEq A] {n : ℕ}
    (e : Fin n ≃ A) (x : V A) :
    φ.app A x
      = SymSpecies.map (R := R) e (φ.app (Fin n) (SymSpecies.map (R := R) e.symm x)) := by
  rw [← φ.app_map, ← SymSpecies.map_trans, Equiv.symm_trans_self, SymSpecies.map_refl]

/-- **The skeleton**: morphisms of graded linear species are the families of linear maps on the
standard finite types commuting with their permutations and the parity projections. -/
noncomputable def skeletonEquiv :
    GrSpeciesHom R V W ≃ {f : ∀ n : ℕ, V (Fin n) →ₗ[R] W (Fin n) // Skel f} where
  toFun φ := ⟨fun n => φ.app (Fin n), fun _ σ x => φ.app_map σ x, fun _ b x => φ.app_par b x⟩
  invFun f := extend f.1 f.2
  left_inv φ := by
    ext A _ _ y
    show extendApp _ A y = _
    rw [extendApp_chart ⟨fun _ σ x => φ.app_map σ x, fun _ b x => φ.app_par b x⟩
      (Fintype.equivFin A).symm, ← app_eq_chart]
  right_inv f := Subtype.ext (funext fun n => LinearMap.ext fun x => extend_app_fin f.2 n x)

end GrSpeciesHom

/-! ## The free graded operad on a graded linear species -/

section FreeGrL

variable (R : Type u) [CommRing R] (V : (A : Type) → [Fintype A] → [DecidableEq A] → Type v)
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (V A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (V A)] [GrSpecies R V]

/-- **The generators of the free graded operad on a graded linear species**: in arity `k`, the
elements of `V (Fin k)` homogeneous of a given parity. -/
def GrGen (k : ℕ) : Type v :=
  {p : V (Fin k) × Bool // GrSpecies.par (R := R) p.2 p.1 = p.1}

/-- The parity of a generator. -/
def grGenPar (k : ℕ) (g : GrGen R V k) : Bool := g.1.2

variable {R V}

/-- The part of parity `b` of an element, as a generator. -/
def GrGen.part {k : ℕ} (b : Bool) (v : V (Fin k)) : GrGen R V k :=
  ⟨(GrSpecies.par (R := R) b v, b), GrSpecies.par_par_self b v⟩

/-- A generator, in the free graded operad on the homogeneous elements. -/
noncomputable def lgen {k : ℕ} (v : V (Fin k)) (b : Bool)
    (h : GrSpecies.par (R := R) b v = v) : FreeGr R (grGenPar R V) (Fin k) :=
  FreeGr.gen (⟨(v, b), h⟩ : GrGen R V k)

lemma lgen_congr {k : ℕ} {b : Bool} {v v' : V (Fin k)} (e : v = v')
    (h : GrSpecies.par (R := R) b v = v) (h' : GrSpecies.par (R := R) b v' = v') :
    lgen v b h = lgen v' b h' := by
  subst e
  rfl

variable (R V)

/-- **The linearity relations**: in each parity, the generator of a sum is the sum of the
generators and the generator of a multiple is the multiple of the generator; and relabelling a
generator along a permutation gives the generator of the relabelled element. -/
def grLinRel (n : ℕ) : Set (FreeGr R (grGenPar R V) (Fin n)) :=
  {x | ∃ (b : Bool) (v w : V (Fin n)) (hv : GrSpecies.par (R := R) b v = v)
      (hw : GrSpecies.par (R := R) b w = w),
      x = lgen (v + w) b (by rw [map_add, hv, hw]) - lgen v b hv - lgen w b hw} ∪
  {x | ∃ (b : Bool) (c : R) (v : V (Fin n)) (hv : GrSpecies.par (R := R) b v = v),
      x = lgen (c • v) b (by rw [map_smul, hv]) - c • lgen v b hv} ∪
  {x | ∃ (b : Bool) (σ : Fin n ≃ Fin n) (v : V (Fin n)) (hv : GrSpecies.par (R := R) b v = v),
      x = GrOperad.map (R := R) σ (lgen v b hv)
        - lgen (SymSpecies.map (R := R) σ v) b (by rw [← GrSpecies.map_par, hv])}

/-- **The free graded operad on a graded linear species.** -/
abbrev FreeGrL := (GrOperadIdeal.span R (grLinRel R V)).Quot

namespace FreeGrL

variable {R V} {Q : (A : Type) → [Fintype A] → [DecidableEq A] → Type w}
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (Q A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (Q A)] [GrOperad R Q]

/-- Values on the generators **killing the linearity relations**. -/
def Kills (f : FreeGr.GenVal R (grGenPar R V) Q) : Prop :=
  ∀ n, ∀ x ∈ grLinRel R V n, (FreeGr.homEquiv.symm f).app (Fin n) x = 0

lemma homEquiv_symm_lgen (f : FreeGr.GenVal R (grGenPar R V) Q) {k : ℕ} (v : V (Fin k))
    (b : Bool) (h : GrSpecies.par (R := R) b v = v) :
    (FreeGr.homEquiv.symm f).app (Fin k) (lgen v b h) = f.1 k ⟨(v, b), h⟩ :=
  FreeGr.homEquiv_symm_gen f _

lemma val_congr (f : FreeGr.GenVal R (grGenPar R V) Q) {k : ℕ} {b : Bool} {v v' : V (Fin k)}
    (e : v = v') (h : GrSpecies.par (R := R) b v = v) (h' : GrSpecies.par (R := R) b v' = v') :
    f.1 k ⟨(v, b), h⟩ = f.1 k ⟨(v', b), h'⟩ := by
  subst e
  rfl

/-- A value on a generator has the parity of the generator. -/
lemma par_val (f : FreeGr.GenVal R (grGenPar R V) Q) {k : ℕ} (b' : Bool) (g : GrGen R V k) :
    GrOperad.par (R := R) b' (f.1 k g) = if b' = g.1.2 then f.1 k g else 0 := by
  have h := f.2 k g
  conv_lhs => rw [← h]
  rw [GrOperad.par_par, h]
  rfl

variable {f : FreeGr.GenVal R (grGenPar R V) Q}

lemma Kills.add (hf : Kills f) {n : ℕ} {b : Bool} {v w : V (Fin n)}
    (hv : GrSpecies.par (R := R) b v = v) (hw : GrSpecies.par (R := R) b w = w)
    (h : GrSpecies.par (R := R) b (v + w) = v + w) :
    f.1 n ⟨(v + w, b), h⟩ = f.1 n ⟨(v, b), hv⟩ + f.1 n ⟨(w, b), hw⟩ := by
  have := hf n _ (Or.inl (Or.inl ⟨b, v, w, hv, hw, rfl⟩))
  rwa [map_sub, map_sub, homEquiv_symm_lgen, homEquiv_symm_lgen, homEquiv_symm_lgen, sub_sub,
    sub_eq_zero] at this

lemma Kills.smul (hf : Kills f) {n : ℕ} {b : Bool} (c : R) {v : V (Fin n)}
    (hv : GrSpecies.par (R := R) b v = v) (h : GrSpecies.par (R := R) b (c • v) = c • v) :
    f.1 n ⟨(c • v, b), h⟩ = c • f.1 n ⟨(v, b), hv⟩ := by
  have := hf n _ (Or.inl (Or.inr ⟨b, c, v, hv, rfl⟩))
  rwa [map_sub, map_smul, homEquiv_symm_lgen, homEquiv_symm_lgen, sub_eq_zero] at this

lemma Kills.map (hf : Kills f) {n : ℕ} {b : Bool} (σ : Fin n ≃ Fin n) {v : V (Fin n)}
    (hv : GrSpecies.par (R := R) b v = v)
    (h : GrSpecies.par (R := R) b (SymSpecies.map (R := R) σ v) = SymSpecies.map (R := R) σ v) :
    f.1 n ⟨(SymSpecies.map (R := R) σ v, b), h⟩
      = GrOperad.map (R := R) σ (f.1 n ⟨(v, b), hv⟩) := by
  have := hf n _ (Or.inr ⟨b, σ, v, hv, rfl⟩)
  rw [map_sub, GrOperadHom.app_map, homEquiv_symm_lgen, homEquiv_symm_lgen, sub_eq_zero] at this
  exact this.symm

lemma Kills.zero (hf : Kills f) {n : ℕ} {b : Bool}
    (h : GrSpecies.par (R := R) b (0 : V (Fin n)) = 0) : f.1 n ⟨(0, b), h⟩ = 0 := by
  rw [val_congr f (zero_smul R (0 : V (Fin n))).symm h (by rw [zero_smul]; exact h),
    hf.smul 0 h, zero_smul]

lemma Kills.part_add (hf : Kills f) {n : ℕ} (b : Bool) (v w : V (Fin n)) :
    f.1 n (GrGen.part b (v + w)) = f.1 n (GrGen.part b v) + f.1 n (GrGen.part b w) :=
  (val_congr f (map_add (GrSpecies.par (R := R) b) v w) _
    (by rw [map_add, GrSpecies.par_par_self, GrSpecies.par_par_self])).trans (hf.add _ _ _)

lemma Kills.part_smul (hf : Kills f) {n : ℕ} (b : Bool) (c : R) (v : V (Fin n)) :
    f.1 n (GrGen.part b (c • v)) = c • f.1 n (GrGen.part b v) :=
  (val_congr f (map_smul (GrSpecies.par (R := R) b) c v) _
    (by rw [map_smul, GrSpecies.par_par_self])).trans (hf.smul c _ _)

lemma Kills.part_map (hf : Kills f) {n : ℕ} (b : Bool) (σ : Fin n ≃ Fin n) (v : V (Fin n)) :
    f.1 n (GrGen.part b (SymSpecies.map (R := R) σ v))
      = GrOperad.map (R := R) σ (f.1 n (GrGen.part b v)) :=
  (val_congr f (GrSpecies.map_par σ b v).symm _
    (by rw [GrSpecies.map_par, GrSpecies.par_par_self])).trans (hf.map σ _ _)

lemma Kills.part_par (hf : Kills f) {n : ℕ} (b b' : Bool) (v : V (Fin n)) :
    f.1 n (GrGen.part b (GrSpecies.par (R := R) b' v))
      = if b = b' then f.1 n (GrGen.part b v) else 0 := by
  by_cases hb : b = b'
  · subst hb
    rw [if_pos rfl]
    exact val_congr f (GrSpecies.par_par_self b v) _ _
  · rw [if_neg hb]
    exact (val_congr f (GrSpecies.par_par_ne hb v) _ (map_zero _)).trans (hf.zero _)

/-- The linear map on `V (Fin n)` defined by values on the generators killing the linearity
relations: the sum of the values on the even and the odd part. -/
noncomputable def linOf (f : FreeGr.GenVal R (grGenPar R V) Q) (hf : Kills f) (n : ℕ) :
    V (Fin n) →ₗ[R] Q (Fin n) where
  toFun v := f.1 n (GrGen.part false v) + f.1 n (GrGen.part true v)
  map_add' v w := by
    simp only [hf.part_add]
    abel
  map_smul' c v := by
    simp only [hf.part_smul, smul_add, RingHom.id_apply]

lemma linOf_skel (hf : Kills f) : GrSpeciesHom.Skel (linOf f hf) := by
  refine ⟨fun n σ v => ?_, fun n b v => ?_⟩
  · show f.1 n (GrGen.part false _) + f.1 n (GrGen.part true _)
      = GrOperad.map (R := R) σ (f.1 n (GrGen.part false v) + f.1 n (GrGen.part true v))
    rw [hf.part_map, hf.part_map, map_add]
  · show f.1 n (GrGen.part false _) + f.1 n (GrGen.part true _)
      = GrOperad.par (R := R) b (f.1 n (GrGen.part false v) + f.1 n (GrGen.part true v))
    rw [hf.part_par, hf.part_par, map_add, par_val, par_val]
    cases b <;> simp [GrGen.part]

/-- Values on the generators defined by a family of linear maps. -/
def valOf (F : {F : ∀ n : ℕ, V (Fin n) →ₗ[R] Q (Fin n) // GrSpeciesHom.Skel F}) :
    FreeGr.GenVal R (grGenPar R V) Q :=
  ⟨fun n g => F.1 n g.1.1, fun n g => (F.2.2 n g.1.2 g.1.1).symm.trans (congrArg (F.1 n) g.2)⟩

lemma valOf_kills (F : {F : ∀ n : ℕ, V (Fin n) →ₗ[R] Q (Fin n) // GrSpeciesHom.Skel F}) :
    Kills (valOf F) := by
  rintro n x ((⟨b, v, w, hv, hw, rfl⟩ | ⟨b, c, v, hv, rfl⟩) | ⟨b, σ, v, hv, rfl⟩)
  · rw [map_sub, map_sub, homEquiv_symm_lgen, homEquiv_symm_lgen, homEquiv_symm_lgen]
    show F.1 n (v + w) - F.1 n v - F.1 n w = 0
    rw [map_add, sub_sub, sub_self]
  · rw [map_sub, map_smul, homEquiv_symm_lgen, homEquiv_symm_lgen]
    show F.1 n (c • v) - c • F.1 n v = 0
    rw [map_smul, sub_self]
  · rw [map_sub, GrOperadHom.app_map, homEquiv_symm_lgen, homEquiv_symm_lgen]
    show GrOperad.map (R := R) σ (F.1 n v) - F.1 n (SymSpecies.map (R := R) σ v) = 0
    rw [F.2.1, sub_eq_zero]
    rfl

/-- **Values on the generators killing the linearity relations are families of linear maps
commuting with the permutations and the parity projections.** -/
noncomputable def killsEquiv :
    {f : FreeGr.GenVal R (grGenPar R V) Q // Kills f}
      ≃ {F : ∀ n : ℕ, V (Fin n) →ₗ[R] Q (Fin n) // GrSpeciesHom.Skel F} where
  toFun f := ⟨linOf f.1 f.2, linOf_skel f.2⟩
  invFun F := ⟨valOf F, valOf_kills F⟩
  left_inv f := by
    obtain ⟨f, hf⟩ := f
    refine Subtype.ext (Subtype.ext (funext fun n => funext fun g => ?_))
    obtain ⟨⟨v, b⟩, h⟩ := g
    show f.1 n (GrGen.part false v) + f.1 n (GrGen.part true v) = f.1 n ⟨(v, b), h⟩
    have h0 : ∀ b', b' ≠ b → f.1 n (GrGen.part b' v) = 0 := by
      intro b' hb
      have h' : GrSpecies.par (R := R) b v = v := h
      rw [← h', hf.part_par, if_neg hb]
    have h1 : f.1 n (GrGen.part b v) = f.1 n ⟨(v, b), h⟩ := val_congr f h _ _
    cases b
    · rw [h0 true (by decide), add_zero, h1]
    · rw [h0 false (by decide), zero_add, h1]
  right_inv F := Subtype.ext (funext fun n => LinearMap.ext fun v => by
    show F.1 n (GrSpecies.par (R := R) false v) + F.1 n (GrSpecies.par (R := R) true v) = F.1 n v
    rw [← map_add, GrSpecies.par_add])

/-- **The universal property of the free graded operad on a graded linear species**: a morphism
of graded operads out of `FreeGrL R V` is a morphism of graded linear species out of `V`. -/
noncomputable def homEquiv : GrOperadHom R (FreeGrL R V) Q ≃ GrSpeciesHom R V Q :=
  FreeGr.presHomEquiv.trans (killsEquiv.trans GrSpeciesHom.skeletonEquiv.symm)

/-- The morphism of graded linear species of a morphism out of `FreeGrL R V`, on the standard
finite types: the value on the generators of the even and the odd part. -/
lemma homEquiv_app_fin (φ : GrOperadHom R (FreeGrL R V) Q) {n : ℕ} (v : V (Fin n)) :
    (homEquiv φ).app (Fin n) v = φ.app (Fin n)
      (FreeGr.presGen (grLinRel R V) (GrGen.part false v)
        + FreeGr.presGen (grLinRel R V) (GrGen.part true v)) := by
  rw [map_add]
  exact GrSpeciesHom.extend_app_fin (killsEquiv (FreeGr.presHomEquiv φ)).2 n v

variable (R V) in
/-- **The generators of the free graded operad on a graded linear species**, as a morphism of
graded linear species: the morphism corresponding to the identity. -/
noncomputable def ι : GrSpeciesHom R V (FreeGrL R V) := homEquiv (GrOperadHom.id R _)

lemma ι_app_fin {n : ℕ} (v : V (Fin n)) :
    (ι R V).app (Fin n) v = FreeGr.presGen (grLinRel R V) (GrGen.part false v)
      + FreeGr.presGen (grLinRel R V) (GrGen.part true v) :=
  homEquiv_app_fin _ v

/-- The relators vanish in the free graded operad on a graded linear species. -/
lemma proj_rel {n : ℕ} {x : FreeGr R (grGenPar R V) (Fin n)} (hx : x ∈ grLinRel R V n) :
    (GrOperadIdeal.span R (grLinRel R V)).proj (Fin n) x = 0 :=
  ((GrOperadIdeal.span R _).proj_eq_zero_iff x).2 (GrOperadIdeal.subset_span n hx)

/-- **A homogeneous element is its generator**, in the free graded operad on a graded linear
species. -/
lemma ι_app_hom {n : ℕ} {v : V (Fin n)} {b : Bool} (h : GrSpecies.par (R := R) b v = v) :
    (ι R V).app (Fin n) v = FreeGr.presGen (grLinRel R V) (⟨(v, b), h⟩ : GrGen R V n) := by
  have hz : ∀ (b' : Bool) (h0 : GrSpecies.par (R := R) b' (0 : V (Fin n)) = 0),
      FreeGr.presGen (grLinRel R V) (⟨(0, b'), h0⟩ : GrGen R V n) = 0 := by
    intro b' h0
    have := proj_rel (Or.inl (Or.inl ⟨b', 0, 0, h0, h0, rfl⟩) : _ ∈ grLinRel R V n)
    rw [map_sub, map_sub, lgen_congr (add_zero (0 : V (Fin n))) _ h0, sub_self, zero_sub,
      neg_eq_zero] at this
    exact this
  have hp : ∀ b' : Bool, b' ≠ b → FreeGr.presGen (grLinRel R V) (GrGen.part b' v) = 0 := by
    intro b' hb
    have e : GrGen.part b' v = (⟨(0, b'), map_zero _⟩ : GrGen R V n) :=
      Subtype.ext (Prod.ext (by
        show GrSpecies.par (R := R) b' v = 0
        rw [← h, GrSpecies.par_par_ne hb]) rfl)
    rw [e, hz]
  have e : GrGen.part b v = (⟨(v, b), h⟩ : GrGen R V n) := Subtype.ext (Prod.ext h rfl)
  rw [ι_app_fin]
  cases b
  · rw [hp true (by decide), add_zero, e]
  · rw [hp false (by decide), zero_add, e]

/-- The morphism of graded linear species of a morphism out of the free graded operad is its
restriction along the generators. -/
lemma homEquiv_apply (φ : GrOperadHom R (FreeGrL R V) Q) {A : Type} [Fintype A] [DecidableEq A]
    (v : V A) : (homEquiv φ).app A v = φ.app A ((ι R V).app A v) := by
  rw [GrSpeciesHom.app_eq_chart (homEquiv φ) (Fintype.equivFin A).symm,
    GrSpeciesHom.app_eq_chart (ι R V) (Fintype.equivFin A).symm, homEquiv_app_fin, ι_app_fin]
  show _ = φ.app A (GrOperad.map (R := R) _ _)
  rw [φ.app_map]
  rfl

/-- **The morphism out of the free graded operad extending a morphism of graded linear species**
restricts to it along the generators. -/
@[simp] lemma homEquiv_symm_ι (F : GrSpeciesHom R V Q) {A : Type} [Fintype A] [DecidableEq A]
    (v : V A) : (homEquiv.symm F).app A ((ι R V).app A v) = F.app A v := by
  rw [← homEquiv_apply, Equiv.apply_symm_apply]

/-- **Morphisms out of the free graded operad on a graded linear species agree when they agree on
the generators.** -/
theorem hom_ext {φ ψ : GrOperadHom R (FreeGrL R V) Q}
    (h : ∀ (A : Type) [Fintype A] [DecidableEq A] (v : V A),
      φ.app A ((ι R V).app A v) = ψ.app A ((ι R V).app A v)) : φ = ψ :=
  homEquiv.injective (GrSpeciesHom.ext fun A _ _ v => by
    rw [homEquiv_apply, homEquiv_apply, h])

end FreeGrL

end FreeGrL

end Operad
