/-
# Grafting is inverse to the root decomposition

For the free graded operad `T(W)` on a graded linear species, **grafting**
`G : W ∘ T(W) → T(W)` (`FreeGrL.graft`) composes the generator at the root with the trees above
it: the total composition after `ι : W → T(W)` (`GrComposite.total`). It commutes with relabelling
and with the right action, `G (ω ◁ᵢ z) = G ω ∘ᵢ z` (`FreeGrL.graft_act`), and sends a corolla
`w ⊗ (1, …, 1)` to `w`.

* **The root decomposition of a grafted tree is its decomposition** (`FreeGrL.root_graft`):
  `ρ ∘ G = 1`, by induction on `W ∘ T(W)` generated by the corollas under the action
  (`GrComposite.induction_act`), and grafted trees have no unit component.
* **Grafting the root decomposition of a tree gives it back**, up to its unit component
  (`FreeGrL.graft_root`): `G ∘ ρ = 1 - ε`, by induction on the operations of `T(W)`
  (`GrSuboperad.mem_of_presGen`).

So `ρ` is an isomorphism from the trees without unit component onto `W ∘ T(W)`.
-/
import Operad.GrTotal
import Operad.GrCompSpan
import Operad.GrSuboperad

universe u v

namespace Operad

open Function Sym GerBV GrComposite

variable {R : Type u} [CommRing R]
  {W : (A : Type) → [Fintype A] → [DecidableEq A] → Type v}
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (W A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (W A)] [GrSpecies R W]

namespace FreeGrL

local notation "𝒥" => GrOperadIdeal.span R (grLinRel R W)

/-- **The generators have no unit component.** -/
lemma unitCoeffL_ι {A : Type} [Fintype A] [DecidableEq A] (w : W A) :
    unitCoeffL R W A ((ι R W).app A w) = 0 := by
  rw [GrSpeciesHom.app_eq_chart (ι R W) (Fintype.equivFin A).symm, ι_app_fin]
  show unitCoeffL R W A (GrOperad.map (R := R) _ ((𝒥).proj _ (FreeGr.gen _) + (𝒥).proj _
    (FreeGr.gen _))) = 0
  rw [unitCoeffL_map, map_add, unitCoeffL_proj, unitCoeffL_proj, unitCoeff_gen, unitCoeff_gen,
    add_zero]

variable (R W) in
/-- **Grafting**: the generator at the root composed with the trees above it. -/
noncomputable def graft (S : Type) [Fintype S] [DecidableEq S] :
    GrComposite R W (FreeGrL R W) S →ₗ[R] FreeGrL R W S :=
  total R (ι R W).toSymSpeciesHom

variable {S : Type} [Fintype S] [DecidableEq S]

lemma graft_act {Y : Type} [Fintype Y] [DecidableEq Y] (i : S) (z : FreeGrL R W Y)
    (ω : GrComposite R W (FreeGrL R W) S) :
    graft R W _ (act R W i z ω) = GrOperad.comp (R := R) i (graft R W S ω) z :=
  total_act R W _ i z ω

lemma graft_map {S' : Type} [Fintype S'] [DecidableEq S'] (σ : S ≃ S')
    (ω : GrComposite R W (FreeGrL R W) S) :
    graft R W S' (map σ ω) = GrOperad.map (R := R) σ (graft R W S ω) :=
  total_map _ σ ω

/-- **Grafting a corolla gives its generator.** -/
@[simp] lemma graft_corolla {A : Type} [Fintype A] [DecidableEq A] (w : W A) :
    graft R W A (corolla R (FreeGrL R W) A w) = (ι R W).app A w := by
  rw [corolla_apply, graft, total_corGen, GrOperad.map_refl]

/-- **The root decomposition of a grafted tree is its decomposition**, and grafted trees have no
unit component. -/
theorem root_graft_and (ω : GrComposite R W (FreeGrL R W) S) :
    root R W S (graft R W S ω) = ω ∧ unitCoeffL R W S (graft R W S ω) = 0 := by
  refine induction_act (fun S _ _ ω => root R W S (graft R W S ω) = ω ∧
      unitCoeffL R W S (graft R W S ω) = 0) (fun S _ _ => by simp only [map_zero, and_self])
    (fun S _ _ x y hx hy => by simp only [map_add, hx.1, hy.1, hx.2, hy.2, add_zero, and_self])
    (fun S _ _ r x hx => by simp only [map_smul, hx.1, hx.2, smul_zero, and_self])
    (fun S S' _ _ _ _ σ x hx => ?_) (fun S Y _ _ _ _ i z x hx => ?_) (fun A _ _ w => ?_) ω
  · beta_reduce at hx ⊢
    rw [graft_map, root_map, hx.1, unitCoeffL_map, hx.2]
    exact ⟨rfl, rfl⟩
  · beta_reduce at hx ⊢
    rw [graft_act, root_comp, hx.1, lact_of_u (aug R W) i (by rw [aug_u, hx.2]),
      LinearMap.zero_apply, add_zero, unitCoeffL_comp, hx.2, zero_mul]
    exact ⟨rfl, rfl⟩
  · beta_reduce
    rw [graft_corolla, root_ι, unitCoeffL_ι]
    exact ⟨rfl, rfl⟩

/-- **`ρ ∘ G = 1`.** -/
theorem root_graft (ω : GrComposite R W (FreeGrL R W) S) : root R W S (graft R W S ω) = ω :=
  (root_graft_and ω).1

/-- **Grafted trees have no unit component.** -/
theorem unitCoeffL_graft (ω : GrComposite R W (FreeGrL R W) S) :
    unitCoeffL R W S (graft R W S ω) = 0 :=
  (root_graft_and ω).2

/-! ## Grafting the root decomposition -/

lemma comp_unitL {A B : Type} [Fintype A] [DecidableEq A] [Fintype B] [DecidableEq B] (i : A)
    (y : FreeGrL R W B) :
    GrOperad.comp (R := R) i (unitL R W A) y
      = ∑ e : Unit ≃ A, GrOperad.map (R := R) (unitEquiv e i B).symm y := by
  rw [unitL, map_sum, LinearMap.sum_apply]
  refine Finset.sum_congr rfl fun e _ => ?_
  have hi : e () = i := by rw [← e.apply_symm_apply i]
  have h1 := GrOperad.one_comp (R := R) (P := FreeGrL R W) y
  rw [GrOperad.comp_map_left e () i hi, show GrOperad.comp (R := R) () (GrOperad.one (R := R)) y
      = GrOperad.map (R := R) (leftUnitEquiv B).symm y by
        conv_rhs => rw [← h1]
        rw [← GrOperad.map_trans, Equiv.self_trans_symm, GrOperad.map_refl],
    ← GrOperad.map_trans]
  refine gmap_congr ?_ y
  intro b
  rfl

/-- **Grafting the root decomposition of a composite**, for factors whose root decompositions
graft back. -/
lemma graft_root_comp {A B : Type} [Fintype A] [DecidableEq A] [Fintype B] [DecidableEq B]
    (i : A) {x : FreeGrL R W A} {y : FreeGrL R W B}
    (hx : graft R W A (root R W A x) = secC R W A x)
    (hy : graft R W B (root R W B y) = secC R W B y) :
    graft R W _ (root R W _ (GrOperad.comp (R := R) i x y))
      = secC R W _ (GrOperad.comp (R := R) i x y) := by
  rw [root_comp, map_add, graft_act, hx, secC_apply, map_sub, map_smul, LinearMap.sub_apply,
    LinearMap.smul_apply, comp_unitL, secC_apply, unitCoeffL_comp]
  by_cases hA : Nonempty (Unit ≃ A)
  · obtain ⟨e⟩ := hA
    haveI : Subsingleton (Unit ≃ A) := ⟨fun e₁ e₂ => Equiv.ext fun u => by
      rw [← e.apply_symm_apply (e₁ u), ← e.apply_symm_apply (e₂ u)]⟩
    rw [lact_eq (aug R W) i x e, map_smul, graft_map, hy, secC_apply, Fintype.sum_subsingleton _ e,
      map_sub, map_smul, map_unitL, aug_u, smul_sub, smul_smul, mul_comm]
    abel
  · have hu : unitCoeffL R W A x = 0 := unitCoeffL_eq_zero (not_nonempty_iff.1 hA) x
    rw [lact_of_u (aug R W) i (by rw [aug_u, hu]), LinearMap.zero_apply, map_zero, add_zero, hu,
      zero_smul, sub_zero, zero_mul, zero_smul, sub_zero]

lemma par_comp_eq_sum {A B : Type} [Fintype A] [DecidableEq A] [Fintype B] [DecidableEq B]
    (b : Bool) (i : A) (x : FreeGrL R W A) (y : FreeGrL R W B) :
    GrOperad.par (R := R) b (GrOperad.comp (R := R) i x y)
      = ∑ p : Bool, ∑ q : Bool, if xor p q = b then GrOperad.comp (R := R) i
          (GrOperad.par (R := R) p x) (GrOperad.par (R := R) q y) else 0 := by
  conv_lhs => rw [← GrOperad.par_add (R := R) x, ← GrOperad.par_add (R := R) y]
  simp only [map_add, LinearMap.add_apply, Fintype.sum_bool]
  have h : ∀ p q : Bool, GrOperad.par (R := R) b (GrOperad.comp (R := R) i
      (GrOperad.par (R := R) p x) (GrOperad.par (R := R) q y))
      = if xor p q = b then GrOperad.comp (R := R) i (GrOperad.par (R := R) p x)
          (GrOperad.par (R := R) q y) else 0 := fun p q => by
    rw [← GrOperad.comp_par i p q x y, GrOperad.par_par]
    by_cases h : xor p q = b
    · rw [if_pos h.symm, if_pos h, GrOperad.comp_par]
    · rw [if_neg (Ne.symm h), if_neg h]
  simp only [h]
  abel

variable (R W) in
/-- The operations whose homogeneous parts are grafted back from their root decompositions. -/
noncomputable def graftSub : GrSuboperad R (FreeGrL R W) where
  sub A _ _ := ⨅ b : Bool, (LinearMap.ker ((graft R W A).comp (root R W A) - secC R W A)).comap
    (GrOperad.par (R := R) b)
  par_mem := by
    intro A _ _ b x hx
    simp only [Submodule.mem_iInf, Submodule.mem_comap] at hx ⊢
    intro b'
    rw [GrOperad.par_par]
    split_ifs
    · exact hx b
    · exact zero_mem _
  map_mem := by
    intro A B _ _ _ _ e x hx
    simp only [Submodule.mem_iInf, Submodule.mem_comap, LinearMap.mem_ker, LinearMap.sub_apply,
      LinearMap.comp_apply, sub_eq_zero] at hx ⊢
    intro b
    rw [← GrOperad.map_par, root_map, graft_map, hx b, secC_map]
  one_mem := by
    simp only [Submodule.mem_iInf, Submodule.mem_comap, LinearMap.mem_ker, LinearMap.sub_apply,
      LinearMap.comp_apply, sub_eq_zero]
    intro b
    cases b
    · rw [GrOperad.par_one, root_one, map_zero, ← GrOperad.map_refl (R := R)
        (GrOperad.one (R := R) (P := FreeGrL R W)), secC_unit]
    · rw [← GrOperad.par_one (R := R) (P := FreeGrL R W), GrOperad.par_par, if_neg (by decide),
        map_zero, map_zero, map_zero]
  comp_mem := by
    intro A B _ _ _ _ i x y hx hy
    simp only [Submodule.mem_iInf, Submodule.mem_comap] at hx hy ⊢
    intro b
    rw [par_comp_eq_sum]
    refine Submodule.sum_mem _ fun p _ => Submodule.sum_mem _ fun q _ => ?_
    split_ifs
    · have hx' := hx p
      have hy' := hy q
      simp only [LinearMap.mem_ker, LinearMap.sub_apply, LinearMap.comp_apply, sub_eq_zero]
        at hx' hy' ⊢
      exact graft_root_comp i hx' hy'
    · exact zero_mem _

/-- **`G ∘ ρ = 1 - ε`**: grafting the root decomposition of an operation gives it back, without its
unit component. -/
theorem graft_root {A : Type} [Fintype A] [DecidableEq A] (x : FreeGrL R W A) :
    graft R W A (root R W A x) = secC R W A x := by
  have hx := FreeGr.mem_of_presGen (graftSub R W) (fun k e => by
    obtain ⟨⟨v, b⟩, hv⟩ := e
    rw [← ι_app_hom hv]
    simp only [graftSub, Submodule.mem_iInf, Submodule.mem_comap, LinearMap.mem_ker,
      LinearMap.sub_apply, LinearMap.comp_apply, sub_eq_zero]
    intro b'
    rw [show GrOperad.par (R := R) b' ((ι R W).app (Fin k) v)
        = (ι R W).app (Fin k) (GrSpecies.par (R := R) b' v) from ((ι R W).app_par b' v).symm,
      root_ι, graft_corolla,
      secC_of_unitCoeff (unitCoeffL_ι _)]) x
  simp only [graftSub, Submodule.mem_iInf, Submodule.mem_comap, LinearMap.mem_ker,
    LinearMap.sub_apply, LinearMap.comp_apply, sub_eq_zero] at hx
  rw [← GrOperad.par_add (R := R) x, map_add, map_add, map_add, hx false, hx true]

end FreeGrL

end Operad
