/-
# The free operad on a species

The free operad on a species `X` has the elements of `X` as generators, relabelled as in `X`.
It is presented by generators and relations (`Operad.SetPresentation`): the generators in arity
`n` are the elements of `X (Fin n)`, and the relations say that relabelling a generator along a
permutation of `Fin n` is the generator relabelled in `X` (`spRel`).

* **The free set operad on a set species** (`FreeSp`), with the generators as a morphism of species
  (`FreeSp.ι`), and **its universal property** (`FreeSp.homEquiv`): a morphism of set operads out
  of `FreeSp X` is the same as a morphism of species out of `X`, by restriction along `ι`
  (`FreeSp.homEquiv_apply`, `FreeSp.homEquiv_symm_ι`).
* **The free operad in modules on a linear species** (`FreeL`): the linearization of the free set
  operad on the underlying set species, modulo the ideal generated by the linearity of the
  generators (`linRel`), with the generators as a morphism of linear species (`FreeL.ι`), and
  **its universal property** (`FreeL.homEquiv`): a morphism of operads in modules out of
  `FreeL R V` is the same as a morphism of linear species out of `V`, by restriction along `ι`
  (`FreeL.homEquiv_apply'`, `FreeL.homEquiv_symm_ι`, `FreeL.hom_ext`).
-/
import Operad.SpeciesOp
import Operad.SymPresentation

universe u v w

namespace Operad

open Sym

/-! ## The free set operad on a set species -/

section SetFree

variable (X : (A : Type) → [Fintype A] → [DecidableEq A] → Type v) [SetSpecies X]

/-- The generators of the free operad on `X`: the elements of `X (Fin n)`, in arity `n`. -/
abbrev SpGen (n : ℕ) : Type v := X (Fin n)

/-- **The relations of the free operad on a species**: relabelling a generator along a
permutation is the relabelled generator. -/
def spRel :
    ∀ {A : Type} [Fintype A] [DecidableEq A], Syn (SpGen X) A → Syn (SpGen X) A → Prop :=
  fun {A} _ _ x y => ∃ (n : ℕ) (σ : Fin n ≃ Fin n) (e : Fin n ≃ A) (g : X (Fin n)),
    x = Syn.map e (Syn.map σ (Syn.gen g)) ∧ y = Syn.map e (Syn.gen (SetSpecies.map σ g))

/-- **The free set operad on a set species.** -/
abbrev FreeSp : (A : Type) → [Fintype A] → [DecidableEq A] → Type (max 1 v) :=
  Pres (SpGen X) (spRel X)

variable {X}

/-- Generator values respect the relations exactly when they are equivariant. -/
lemma respects_spRel_iff {S : (A : Type) → [Fintype A] → [DecidableEq A] → Type w}
    [SetOperad S] (f : ∀ n, SpGen X n → S (Fin n)) :
    Pres.Respects (spRel X) f ↔ SetSpeciesHom.Equivariant (Y := S) f := by
  constructor
  · intro h n σ g
    have := h _ _ ⟨n, σ, Equiv.refl _, g, rfl, rfl⟩
    simp only [Syn.eval_map, Syn.eval_gen, SetOperad.map_refl] at this
    exact this.symm
  · rintro h A _ _ x y ⟨n, σ, e, g, rfl, rfl⟩
    simp only [Syn.eval_map, Syn.eval_gen]
    exact congrArg (SetOperad.map e) (h n σ g).symm

namespace FreeSp

/-- The generators are equivariant. -/
lemma gen_equivariant : SetSpeciesHom.Equivariant (X := X) (Y := FreeSp X)
    (fun _ g => Pres.gen g) := by
  intro n σ g
  have h := Pres.mk_eq_mk_of_rel (ρ := spRel X)
    (show spRel X (Syn.map (Equiv.refl _) (Syn.map σ (Syn.gen g)))
      (Syn.map (Equiv.refl _) (Syn.gen (SetSpecies.map σ g))) from
      ⟨n, σ, Equiv.refl _, g, rfl, rfl⟩)
  simp only [← Pres.map_mk, SetOperad.map_refl] at h
  exact h.symm

/-- **The generators, as a morphism of species.** -/
noncomputable def ι : SetSpeciesHom X (FreeSp X) :=
  SetSpeciesHom.extend (fun _ g => Pres.gen g) gen_equivariant

@[simp] lemma ι_app_fin (n : ℕ) (g : X (Fin n)) : ι.app (Fin n) g = Pres.gen g :=
  SetSpeciesHom.extend_app_fin gen_equivariant n g

variable {S : (A : Type) → [Fintype A] → [DecidableEq A] → Type w} [SetOperad S]

/-- **The universal property of the free set operad on a set species**: a morphism of set operads
out of `FreeSp X` is a morphism of species out of `X`. -/
noncomputable def homEquiv : SetOperadHom (FreeSp X) S ≃ SetSpeciesHom X S :=
  Pres.homEquiv.trans ((Equiv.subtypeEquivRight respects_spRel_iff).trans
    SetSpeciesHom.skeletonEquiv.symm)

lemma homEquiv_app_fin (φ : SetOperadHom (FreeSp X) S) (n : ℕ) (g : X (Fin n)) :
    (homEquiv φ).app (Fin n) g = φ.app (Fin n) (Pres.gen g) :=
  SetSpeciesHom.extend_app_fin ((respects_spRel_iff _).1 (Pres.respects_app φ)) n g

/-- The morphism of species of a morphism out of the free operad is its restriction along the
generators. -/
lemma homEquiv_apply (φ : SetOperadHom (FreeSp X) S) {A : Type} [Fintype A] [DecidableEq A]
    (x : X A) : (homEquiv φ).app A x = φ.app A (ι.app A x) := by
  rw [SetSpeciesHom.app_eq_chart (homEquiv φ) (Fintype.equivFin A).symm,
    SetSpeciesHom.app_eq_chart (ι (X := X)) (Fintype.equivFin A).symm, ι_app_fin,
    homEquiv_app_fin]
  show _ = φ.app A (SetOperad.map _ _)
  rw [φ.app_map]
  rfl

/-- **The morphism out of the free operad extending a morphism of species** restricts to it
along the generators. -/
@[simp] lemma homEquiv_symm_ι (f : SetSpeciesHom X S) {A : Type} [Fintype A] [DecidableEq A]
    (x : X A) : (homEquiv.symm f).app A (ι.app A x) = f.app A x := by
  rw [← homEquiv_apply, Equiv.apply_symm_apply]

/-- **Morphisms out of the free operad agree when they agree on the generators.** -/
theorem hom_ext {φ ψ : SetOperadHom (FreeSp X) S}
    (h : ∀ (A : Type) [Fintype A] [DecidableEq A] (x : X A),
      φ.app A (ι.app A x) = ψ.app A (ι.app A x)) : φ = ψ :=
  homEquiv.injective (SetSpeciesHom.ext fun A _ _ x => by
    rw [homEquiv_apply, homEquiv_apply, h])

end FreeSp

end SetFree

/-! ## The free operad in modules on a linear species -/

section LinFree

variable (R : Type u) [CommRing R] (V : (A : Type) → [Fintype A] → [DecidableEq A] → Type v)
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (V A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (V A)] [SymSpecies R V]

/-- A generator of the free operad on a linear species, in its linearization. -/
noncomputable def linGen {n : ℕ} (v : V (Fin n)) : Lin R (FreeSp (UndSp R V)) (Fin n) :=
  Finsupp.single (Pres.gen (UndSp.of R V v)) 1

/-- **The linearity relations**: the generator of a sum is the sum of the generators, and the
generator of a multiple the multiple of the generator. -/
def linRel (n : ℕ) : Set (Lin R (FreeSp (UndSp R V)) (Fin n)) :=
  {x | ∃ v w : V (Fin n), x = linGen R V (v + w) - linGen R V v - linGen R V w} ∪
    {x | ∃ (c : R) (v : V (Fin n)), x = linGen R V (c • v) - c • linGen R V v}

/-- **The free operad in modules on a linear species.** -/
abbrev FreeL := (SymOperadIdeal.span R (linRel R V)).Quot

namespace FreeL

variable {R V} {Q : (A : Type) → [Fintype A] → [DecidableEq A] → Type w}
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (Q A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (Q A)] [SymOperad R Q]

/-- A morphism of set species into the underlying set operad of `Q` that is **linear on the
standard finite types**. -/
def LinFin (F : SetSpeciesHom (UndSp R V) (Und R Q)) : Prop :=
  ∀ n : ℕ,
    (∀ v w : V (Fin n), (Und.of R Q).symm (F.app (Fin n) (UndSp.of R V (v + w)))
      = (Und.of R Q).symm (F.app _ (UndSp.of R V v)) + (Und.of R Q).symm (F.app _ (UndSp.of R V w)))
    ∧ ∀ (c : R) (v : V (Fin n)), (Und.of R Q).symm (F.app (Fin n) (UndSp.of R V (c • v)))
      = c • (Und.of R Q).symm (F.app _ (UndSp.of R V v))

/-- The linear extension of a morphism out of the free set operad kills the linearity relations
exactly when the corresponding morphism of species is linear on the standard finite types. -/
lemma kills_iff (ψ : SetOperadHom (FreeSp (UndSp R V)) (Und R Q)) :
    (∀ n, ∀ x ∈ linRel R V n, (linHomEquiv R ψ).app (Fin n) x = 0)
      ↔ LinFin (FreeSp.homEquiv ψ) := by
  have hgen : ∀ n (v : V (Fin n)), (linHomEquiv R ψ).app (Fin n) (linGen R V v)
      = (Und.of R Q).symm ((FreeSp.homEquiv ψ).app (Fin n) (UndSp.of R V v)) := by
    intro n v
    rw [FreeSp.homEquiv_app_fin]
    show Finsupp.lift (Q _) R _ _ (Finsupp.single _ 1) = _
    simp
  simp only [linRel, Set.mem_union, Set.mem_setOf_eq]
  constructor
  · intro h n
    refine ⟨fun v w => ?_, fun c v => ?_⟩
    · have := h n _ (Or.inl ⟨v, w, rfl⟩)
      rw [map_sub, map_sub, hgen, hgen, hgen, sub_sub, sub_eq_zero] at this
      exact this
    · have := h n _ (Or.inr ⟨c, v, rfl⟩)
      rw [map_sub, map_smul, hgen, hgen, sub_eq_zero] at this
      exact this
  · rintro h n x (⟨v, w, rfl⟩ | ⟨c, v, rfl⟩)
    · rw [map_sub, map_sub, hgen, hgen, hgen, sub_sub, sub_eq_zero]
      exact (h n).1 v w
    · rw [map_sub, map_smul, hgen, hgen, sub_eq_zero]
      exact (h n).2 c v

/-- Morphisms into the underlying set operad of `Q`, as morphisms into the underlying set species
of `Q`. -/
def undSpEquiv :
    SetSpeciesHom (UndSp R V) (Und R Q) ≃ SetSpeciesHom (UndSp R V) (UndSp R Q) where
  toFun F := ⟨F.app, F.app_map⟩
  invFun F := ⟨F.app, F.app_map⟩
  left_inv _ := rfl
  right_inv _ := rfl

/-- **Linearity on the standard finite types is linearity**, through numberings. -/
lemma isLinear_iff (F : SetSpeciesHom (UndSp R V) (Und R Q)) :
    SymSpeciesHom.IsLinear (undSpEquiv F) ↔ LinFin F := by
  constructor
  · intro h n
    exact ⟨(h (Fin n)).1, (h (Fin n)).2⟩
  · intro h A _ _
    have key : ∀ z : V A, (Und.of R Q).symm (F.app A (UndSp.of R V z))
        = SymOperad.map (R := R) (Fintype.equivFin A).symm ((Und.of R Q).symm (F.app _
          (UndSp.of R V (SymSpecies.map (R := R) (Fintype.equivFin A) z)))) := fun z =>
      congrArg (Und.of R Q).symm
        (SetSpeciesHom.app_eq_chart F (Fintype.equivFin A).symm (UndSp.of R V z))
    refine ⟨fun v w => ?_, fun c v => ?_⟩
    · apply (Und.of R Q).symm.injective
      show (Und.of R Q).symm (F.app A (UndSp.of R V (v + w)))
        = (Und.of R Q).symm (F.app A (UndSp.of R V v))
          + (Und.of R Q).symm (F.app A (UndSp.of R V w))
      rw [key, key v, key w, map_add, (h _).1, map_add]
    · apply (Und.of R Q).symm.injective
      show (Und.of R Q).symm (F.app A (UndSp.of R V (c • v)))
        = c • (Und.of R Q).symm (F.app A (UndSp.of R V v))
      rw [key, key v, map_smul, (h _).2, map_smul]

/-- **The universal property of the free operad in modules on a linear species**: a morphism of
operads in modules out of `FreeL R V` is a morphism of linear species out of `V`. -/
noncomputable def homEquiv : SymOperadHom R (FreeL R V) Q ≃ SymSpeciesHom R V Q :=
  SymOperadIdeal.presHomEquiv.trans <|
    ((linHomEquiv R).symm.subtypeEquiv fun φ => by rw [Equiv.apply_symm_apply]).trans <|
    (FreeSp.homEquiv.subtypeEquiv fun ψ => kills_iff ψ).trans <|
    (undSpEquiv.subtypeEquiv fun F => (isLinear_iff F).symm).trans
      SymSpeciesHom.undEquiv.symm

lemma homEquiv_apply (φ : SymOperadHom R (FreeL R V) Q) {A : Type} [Fintype A] [DecidableEq A]
    (v : V A) : (homEquiv φ).app A v = φ.app A ((SymOperadIdeal.span R (linRel R V)).proj A
      (Finsupp.single (FreeSp.ι.app A (UndSp.of R V v)) 1)) := by
  show (Und.of R Q).symm ((FreeSp.homEquiv _).app A (UndSp.of R V v)) = _
  rw [FreeSp.homEquiv_apply]
  rfl

variable (R V) in
/-- **The generators of the free operad on a linear species**, as a morphism of linear species:
the morphism corresponding to the identity. -/
noncomputable def ι : SymSpeciesHom R V (FreeL R V) := homEquiv (SymOperadHom.id)

lemma ι_app {A : Type} [Fintype A] [DecidableEq A] (v : V A) :
    (ι R V).app A v = (SymOperadIdeal.span R (linRel R V)).proj A
      (Finsupp.single (FreeSp.ι.app A (UndSp.of R V v)) 1) :=
  homEquiv_apply _ v

/-- The morphism of species of a morphism out of the free operad is its restriction along the
generators. -/
lemma homEquiv_apply' (φ : SymOperadHom R (FreeL R V) Q) {A : Type} [Fintype A] [DecidableEq A]
    (v : V A) : (homEquiv φ).app A v = φ.app A ((ι R V).app A v) := by
  rw [homEquiv_apply, ι_app]

/-- **The morphism out of the free operad extending a morphism of linear species** restricts to
it along the generators. -/
@[simp] lemma homEquiv_symm_ι (f : SymSpeciesHom R V Q) {A : Type} [Fintype A] [DecidableEq A]
    (v : V A) : (homEquiv.symm f).app A ((ι R V).app A v) = f.app A v := by
  rw [← homEquiv_apply', Equiv.apply_symm_apply]

/-- **Morphisms out of the free operad on a linear species agree when they agree on the
generators.** -/
theorem hom_ext {φ ψ : SymOperadHom R (FreeL R V) Q}
    (h : ∀ (A : Type) [Fintype A] [DecidableEq A] (v : V A),
      φ.app A ((ι R V).app A v) = ψ.app A ((ι R V).app A v)) : φ = ψ :=
  homEquiv.injective (SymSpeciesHom.ext fun A _ _ v => by
    rw [homEquiv_apply', homEquiv_apply', h])

end FreeL

end LinFree

end Operad
