/-
# Graded composites are generated by corollas under the right action

For a graded operad `C`, the graded composite `V ∘ C` is spanned by the corollas `w ⊗ (1, …, 1)`
(`GrComposite.corolla`) under relabelling and the right action of `C`
(`GrComposite.induction_act`): an inner operation is the result of composing it into a unit
(`GrComposite.map_act_ext`), the other inner operations moving across it with the Koszul sign.
-/
import Operad.FreeGrRoot

universe u v w

namespace Operad

open Function Sym GerBV

namespace GrComposite

/-! ## Replacing a fibre by a single input -/

section Ext

variable {S A : Type} [DecidableEq S] [DecidableEq A] (f : S → A) (a₀ : A)

/-- **The inputs not owned by `a₀`, and one input owned by `a₀`.** -/
abbrev Ext : Type := {s : S // f s ≠ a₀} ⊕ Unit

/-- The owners of the inputs of `Ext f a₀`. -/
def extOwner : Ext f a₀ → A := Sum.elim (fun s => f s.1) fun _ => a₀

/-- The single input owned by `a₀`. -/
def extUnit {a : A} (h : a₀ = a) : Unit ≃ Fib (extOwner f a₀) a where
  toFun _ := ⟨Sum.inr (), h⟩
  invFun _ := ()
  left_inv _ := rfl
  right_inv := by
    rintro ⟨⟨s, hs⟩ | ⟨⟩, h'⟩
    · exact absurd (h'.trans h.symm) hs
    · rfl

/-- The inputs owned by another input of the outer operation are unchanged. -/
def extIncl {a : A} (h : a₀ ≠ a) : Fib f a ≃ Fib (extOwner f a₀) a where
  toFun s := ⟨Sum.inl ⟨s.1, fun e => h (e.symm.trans s.2)⟩, s.2⟩
  invFun s := match s with
    | ⟨Sum.inl t, ht⟩ => ⟨t.1, ht⟩
    | ⟨Sum.inr _, ht⟩ => absurd ht (Ne.symm h).symm
  left_inv _ := rfl
  right_inv := by
    rintro ⟨t | ⟨⟩, ht⟩
    · rfl
    · exact absurd ht h

/-- **After composing at the new input, the inputs are those of `S`.** -/
def extEquiv : Without (Ext f a₀) (Sum.inr ()) ⊕ Fib f a₀ ≃ S where
  toFun x := match x with
    | Sum.inl ⟨Sum.inl s, _⟩ => s.1
    | Sum.inl ⟨Sum.inr (), h⟩ => absurd rfl h
    | Sum.inr t => t.1
  invFun s := if h : f s = a₀ then Sum.inr ⟨s, h⟩ else Sum.inl ⟨Sum.inl ⟨s, h⟩, Sum.inl_ne_inr⟩
  left_inv := by
    rintro (⟨⟨s, hs⟩ | ⟨⟩, h⟩ | ⟨t, ht⟩)
    · simp [hs]
    · exact absurd rfl h
    · simp [ht]
  right_inv s := by
    by_cases h : f s = a₀ <;> simp [h]

lemma extOwner_extEquiv :
    actOwner (Y := Fib f a₀) (extOwner f a₀) (Sum.inr ()) ∘ (extEquiv f a₀).symm = f := by
  funext s
  by_cases h : f s = a₀
  · simp [extEquiv, h, actOwner, extOwner]
  · simp [extEquiv, h, actOwner, extOwner]

end Ext

variable {R : Type u} [CommRing R]
  {V : (A : Type) → [Fintype A] → [DecidableEq A] → Type v}
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (V A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (V A)] [GrSpecies R V]
  {C : (A : Type) → [Fintype A] → [DecidableEq A] → Type w}
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (C A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (C A)] [GrOperad R C]

/-! ## Composing into a unit -/

section ActExt

variable {S A : Type} [Fintype S] [DecidableEq S] [Fintype A] [DecidableEq A]

/-- The inner operations with the unit at `a₀`. -/
noncomputable def extY (f : S → A) (yy : ∀ a, C (Fib f a)) (a₀ : A) (a : A) :
    C (Fib (extOwner f a₀) a) :=
  if h : a₀ = a then GrOperad.map (R := R) (extUnit f a₀ h) (GrOperad.one (R := R))
  else GrOperad.map (R := R) (extIncl f a₀ h) (yy a)

/-- **Composing an inner operation into a unit** gives it back, the inner operations read after
it moving across it. -/
lemma map_act_ext (L : LinOrd A) (w : V A) (f : S → A) (yy : ∀ a, C (Fib f a)) (c : A → Bool)
    (hyy : ∀ a, GrOperad.par (R := R) (c a) (yy a) = yy a) (a₀ : A) :
    map (extEquiv f a₀) (act R V (Sum.inr ()) (yy a₀)
        (mk R (ownGen L w (extOwner f a₀) (extY (R := R) f yy a₀))))
      = (∏ a, σ R ((c a₀ && ltB L a₀ a) && c a)) • mk R (ownGen L w f yy) := by
  rw [act_mk_ownGen, actOwn_hom L w _ _ _ (yy a₀) (hyy a₀), map_mk_ownGen,
    mk_ownGen_congr _ w (extOwner_extEquiv f a₀)]
  have hS := (mkY (R := R) (ownGen L w f yy)).map_smul_univ
    (fun a => σ R ((c a₀ && ltB L a₀ a) && c a)) yy
  refine Eq.trans ?_ hS
  show mk R (ownGen L w f _) = mk R (ownGen L w f fun a => _ • yy a)
  congr 2
  funext a
  show GrOperad.map (R := R) _ (GrOperad.map (R := R) _ (actLin (R := R) L (extOwner f a₀)
      (Sum.inr ()) (yy a₀) (c a₀) a (extY (R := R) f yy a₀ a))) = _
  by_cases h : a₀ = a
  · subst h
    have h1 := GrOperad.one_comp (R := R) (yy a₀)
    rw [actLin_eq L (extOwner f a₀) (Sum.inr ()) (yy a₀) (c a₀) a₀ rfl, extY, dif_pos rfl,
      GrOperad.comp_map_left (extUnit f a₀ rfl) () ⟨Sum.inr (), rfl⟩ rfl,
      show GrOperad.comp (R := R) () (GrOperad.one (R := R)) (yy a₀)
        = GrOperad.map (R := R) (leftUnitEquiv (Fib f a₀)).symm (yy a₀) by
          conv_rhs => rw [← h1]
          rw [← GrOperad.map_trans, Equiv.self_trans_symm, GrOperad.map_refl],
      ltB_self, Bool.and_false, Bool.false_and, σ_false, one_smul]
    simp only [← GrOperad.map_trans]
    refine (gmap_congr (e' := Equiv.refl _) ?_ _).trans (GrOperad.map_refl _)
    intro t
    exact Subtype.ext rfl
  · have hv : GrOperad.par (R := R) (c a) (GrOperad.map (R := R) (actNe (Y := Fib f a₀)
        (extOwner f a₀) (Sum.inr ()) a h) (GrOperad.map (R := R) (extIncl f a₀ h) (yy a)))
        = GrOperad.map (R := R) (actNe (Y := Fib f a₀) (extOwner f a₀) (Sum.inr ()) a h)
          (GrOperad.map (R := R) (extIncl f a₀ h) (yy a)) := by
      rw [← GrOperad.map_par, ← GrOperad.map_par, hyy]
    rw [actLin_ne L (extOwner f a₀) (Sum.inr ()) (yy a₀) (c a₀) a h, extY, dif_neg h,
      GrOperad.tw_hom _ hv, map_smul, map_smul]
    congr 1
    simp only [← GrOperad.map_trans]
    refine (gmap_congr (e' := Equiv.refl _) ?_ _).trans (GrOperad.map_refl _)
    intro t
    exact Subtype.ext rfl

end ActExt

end GrComposite

end Operad
