/-
# The Koszul dual cooperad of quadratic data with generators of any arity

Generators `E`, a graded linear species, and relators `r` in the free graded operad
`T(E) = FreeGrL R E` present the graded operad `P = T(E)/(r)` (`Koszul.Pres`). The cut cooperad
`T^c(sE)` on the parity shift of the generators carries the **desuspension map**
`κ_T : T^c(sE) → T(E)` (`Koszul.kapT`), the weight one component desuspended: the morphism of
graded operads `T(sE) → T(E) ⊕ εT(E)` into the square-zero extension by an odd parameter sending
a generator `sv` to `εv` (`Koszul.epsHom`) has as its `ε`-part the weight one component of a
tree. Its convolution square `κ_T ⋆ κ_T` reads a tree with two vertices as the composite of their
desuspensions, and vanishes on the other trees.

* **The Koszul dual cooperad** `P^¡` (`Koszul.Dual`) is the largest subcooperad of `T^c(sE)` on
  which `κ_T ⋆ κ_T` lands in the ideal generated by the relators (`Koszul.dualSub`): for quadratic
  relators `R`, the cooperad `C(sE, s²R)` cogenerated by `sE` with corelations `s²R`. Over a field
  it is a coaugmented graded cooperad.
* **The Koszul twisting morphism** `κ : P^¡ → P` (`Koszul.kappa`): `κ_T` restricted to `P^¡` and
  followed by the projection onto `P`. It satisfies the Maurer–Cartan equation since `κ ⋆ κ` is
  the projection of `κ_T ⋆ κ_T` (`Koszul.twisting`).
* By the cobar adjunction it is **a morphism of dg operads `ΩP^¡ → P`** (`Koszul.cobarMor`), and
  `P` is **Koszul** when it is a quasi-isomorphism (`Koszul.IsKoszul`).

Graded operads are dg operads with the zero differential (`ZeroDG`).
-/
import Operad.GrSubCooperad
import Operad.Twisting
import Operad.CofreeGrL

universe u v w

namespace Operad

open Sym GerBV
open scoped TensorProduct

/-! ## Graded operads with the zero differential -/

section ZeroDG

variable (R : Type u) [CommRing R] (P : (A : Type) → [Fintype A] → [DecidableEq A] → Type w)
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (P A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (P A)]

set_option linter.unusedVariables false in
/-- **A graded operad with the zero differential.** -/
@[nolint unusedArguments]
def ZeroDG (R : Type u) [CommRing R] (P : (A : Type) → [Fintype A] → [DecidableEq A] → Type w)
    (A : Type) [Fintype A] [DecidableEq A] : Type w := P A

instance (A : Type) [Fintype A] [DecidableEq A] : AddCommGroup (ZeroDG R P A) :=
  inferInstanceAs (AddCommGroup (P A))

instance (A : Type) [Fintype A] [DecidableEq A] : Module R (ZeroDG R P A) :=
  inferInstanceAs (Module R (P A))

variable [GrOperad R P]

/-- **A graded operad is a dg operad with the zero differential.** -/
instance ZeroDG.instDGOperad : DGOperad R (ZeroDG R P) where
  toGrOperad := inferInstanceAs (GrOperad R P)
  d := 0
  d_d _ := rfl
  d_par _ _ := by simp
  map_d _ _ := by simp
  d_one := rfl
  d_comp _ _ _ := by simp

variable {R P}

/-- A morphism of graded operads into `P`, into `P` with the zero differential. -/
def GrOperadHom.toZeroDG {Q : (A : Type) → [Fintype A] → [DecidableEq A] → Type v}
    [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (Q A)]
    [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (Q A)] [GrOperad R Q]
    (φ : GrOperadHom R Q P) : GrOperadHom R Q (ZeroDG R P) where
  app A _ _ := φ.app A
  app_par := φ.app_par
  app_map := φ.app_map
  app_one := φ.app_one
  app_comp := φ.app_comp

end ZeroDG

/-! ## The convolution square of a family vanishing on the coaugmentation -/

section StarUnit

variable {R : Type u} [CommRing R] {C : (A : Type) → [Fintype A] → [DecidableEq A] → Type v}
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (C A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (C A)] [GrCooperad R C]
  [GrCooperad.Coaug R C]
  {P : (A : Type) → [Fintype A] → [DecidableEq A] → Type w}
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (P A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (P A)] [GrOperad R P]

/-- A tensor whose second factor is a relabelling of `1` is killed by `f ⊗ g`, for `g` vanishing
on the coaugmentation. -/
lemma kap_unit {A D : Type} [Fintype A] [DecidableEq A] [Fintype D] [DecidableEq D]
    (f : ConvOp R C P D) {g : ConvOp R C P A}
    (hg : ∀ x ∈ GrCooperad.unitSpan R C A, ConvOp.toLin g x = 0)
    (a : C D) {b : C A} (hb : b ∈ GrCooperad.unitSpan R C A) :
    ConvOp.kap f g (a ⊗ₜ b) = 0 := by
  simp only [ConvOp.kap, LinearMap.coe_sum, Finset.sum_apply, TensorProduct.map_tmul]
  refine Finset.sum_eq_zero fun q _ => ?_
  rw [ConvOp.parC_apply]
  have : ∀ c : Bool, ConvOp.toLin g (GrSpecies.par (R := R) c b) = 0 := fun c =>
    hg _ (GrCooperad.unitSpan_le_comap_par c hb)
  simp [this]

/-- **The convolution product with a family vanishing on the coaugmentation vanishes on the
coaugmentation.** -/
lemma star_unit (α β : GrOperad.Inv R (ConvOp R C P)) (hβ : KillsUnit R C P β)
    {A : Type} [Fintype A] [DecidableEq A] {x : C A} (hx : x ∈ GrCooperad.unitSpan R C A) :
    ConvOp.toLin ((GrOperad.Inv.star R _ α β).1 A) x = 0 := by
  rw [GrOperad.Inv.star_apply, ConvOp.toLin_sum, LinearMap.coe_sum, Finset.sum_apply]
  refine Finset.sum_eq_zero fun S _ => ?_
  show ConvOp.toLin (ConvOp.mapC (splitEquiv S)
    (ConvOp.compC none (α.1 (SOut S)) (β.1 (SIn S)))) x = 0
  rw [ConvOp.mapC_apply, ConvOp.toLin_compC, LinearMap.comp_apply, LinearMap.comp_apply]
  have hmem : GrCooperad.decomp (R := R) (C := C) (none : SOut S)
      (SymSpecies.map (R := R) (splitEquiv S).symm x)
      ∈ Submodule.map₂ (TensorProduct.mk R (C (SOut S)) (C (SIn S)))
          (GrCooperad.unitSpan R C (SOut S)) (GrCooperad.unitSpan R C (SIn S)) := by
    have hx' := GrCooperad.unitSpan_le_comap_map (R := R) (C := C) (splitEquiv S).symm hx
    have key : GrCooperad.unitSpan R C (Without (SOut S) none ⊕ SIn S)
        ≤ Submodule.comap (GrCooperad.decomp (R := R) (C := C) (none : SOut S))
          (Submodule.map₂ (TensorProduct.mk R (C (SOut S)) (C (SIn S)))
            (GrCooperad.unitSpan R C (SOut S)) (GrCooperad.unitSpan R C (SIn S))) := by
      rw [GrCooperad.unitSpan, GrCooperad.unitSpanOf, Submodule.span_le]
      rintro _ ⟨e, rfl⟩
      exact GrCooperad.Coaug.decomp_mem none e
    exact key hx'
  have hk : ∀ t ∈ Submodule.map₂ (TensorProduct.mk R (C (SOut S)) (C (SIn S)))
      (GrCooperad.unitSpan R C (SOut S)) (GrCooperad.unitSpan R C (SIn S)),
      ConvOp.kap (α.1 (SOut S)) (β.1 (SIn S)) t = 0 := by
    intro t ht
    refine (Submodule.map₂_le.2 ?_ : Submodule.map₂ _ _ _ ≤ LinearMap.ker
      (ConvOp.kap (α.1 (SOut S)) (β.1 (SIn S)))) ht
    intro a _ b hb
    exact kap_unit _ (fun y hy => hβ _ y hy) a hb
  rw [hk _ hmem, map_zero, map_zero]

end StarUnit

/-! ## Trees with at most one vertex -/

section WeightOne

variable {R : Type u} [CommRing R]
  {A B : Type} [Fintype A] [DecidableEq A] [Fintype B] [DecidableEq B]

/-- The image of `p ⊗ q` under `f ⊗ g` lies in the image of `f(p) ⊗ g(q)`. -/
lemma map_range_map_subtype_le {M M' N N' : Type*} [AddCommGroup M] [Module R M]
    [AddCommGroup M'] [Module R M'] [AddCommGroup N] [Module R N] [AddCommGroup N']
    [Module R N'] (f : M →ₗ[R] M') (g : N →ₗ[R] N') (p : Submodule R M) (q : Submodule R N) :
    (LinearMap.range (TensorProduct.map p.subtype q.subtype)).map (TensorProduct.map f g)
      ≤ LinearMap.range (TensorProduct.map (p.map f).subtype (q.map g).subtype) := by
  rintro _ ⟨_, ⟨t, rfl⟩, rfl⟩
  refine ⟨TensorProduct.map (f.submoduleMap p) (g.submoduleMap q) t, ?_⟩
  rw [← LinearMap.comp_apply (TensorProduct.map _ _), ← TensorProduct.map_comp,
    ← LinearMap.comp_apply (TensorProduct.map f g), ← TensorProduct.map_comp]
  rfl

namespace FreeGr

variable {T : ℕ → Type v} {gp : ∀ k, T k → Bool}

/-- The number of vertices of a tree. -/
abbrev vtx (x : Reg (TreeOfArity T) A) : ℕ := FreeReg.cntR (fun _ _ => 1) x

lemma eq_leaf_of_vtx {x : Reg (TreeOfArity T) A} (h : vtx x = 0) : treeOf x = .leaf := by
  unfold vtx FreeReg.cntR at h
  revert h
  cases treeOf x with
  | leaf => exact fun _ => rfl
  | node e fo =>
    intro h
    simp only [Tree.cnt_node] at h
    omega

variable (R gp) in
/-- The span of the trees with at most one vertex. -/
noncomputable def wtOne (A : Type) [Fintype A] [DecidableEq A] : Submodule R (FreeGr R gp A) :=
  Submodule.span R {z | ∃ x : Reg (TreeOfArity T) A, vtx x ≤ 1 ∧ SgnLin.bas (treeSgn gp) R x = z}

variable (R gp) in
/-- The span of the trees without vertices. -/
noncomputable def wtZero (A : Type) [Fintype A] [DecidableEq A] : Submodule R (FreeGr R gp A) :=
  Submodule.span R {z | ∃ x : Reg (TreeOfArity T) A, vtx x = 0 ∧ SgnLin.bas (treeSgn gp) R x = z}

lemma wtZero_le_wtOne : wtZero R gp A ≤ wtOne R gp A :=
  Submodule.span_mono fun _ ⟨x, hx, h⟩ => ⟨x, by omega, h⟩

/-- The trees without vertices are the relabellings of the unit. -/
lemma wtZero_le_unitSpan : wtZero R gp A ≤ GrCooperad.unitSpan R (FreeGr R gp) A := by
  rw [wtZero, Submodule.span_le]
  rintro _ ⟨x, hx, rfl⟩
  obtain ⟨e, rfl⟩ := eq_map_one_of_leaf x (eq_leaf_of_vtx hx)
  rw [← SgnLin.map_bas]
  exact GrCooperad.map_one_mem (R := R) (C := FreeGr R gp) e

lemma par_mem_wtOne (b : Bool) {z : FreeGr R gp A} (hz : z ∈ wtOne R gp A) :
    GrOperad.par (R := R) b z ∈ wtOne R gp A := by
  refine (Submodule.span_le (p := (wtOne R gp A).comap (GrOperad.par (R := R) b))).2 ?_ hz
  rintro _ ⟨x, hx, rfl⟩
  rw [SetLike.mem_coe, Submodule.mem_comap, par_bas_eq]
  split_ifs
  · exact Submodule.subset_span ⟨x, hx, rfl⟩
  · exact zero_mem _

lemma map_mem_wtOne (e : A ≃ B) {z : FreeGr R gp A} (hz : z ∈ wtOne R gp A) :
    GrOperad.map (R := R) e z ∈ wtOne R gp B := by
  refine (Submodule.span_le (p := (wtOne R gp B).comap (GrOperad.map (R := R) e))).2 ?_ hz
  rintro _ ⟨x, hx, rfl⟩
  rw [SetLike.mem_coe, Submodule.mem_comap, SgnLin.map_bas]
  exact Submodule.subset_span ⟨_, by rw [vtx, FreeReg.cntR_map]; exact hx, rfl⟩

/-- The decomposition of a tree with at most one vertex. -/
lemma decomp_bas_mem_wtOne (i : A) (x : Reg (TreeOfArity T) (Without A i ⊕ B))
    (hx : vtx x ≤ 1) :
    GrCooperad.decomp (R := R) (C := FreeGr R gp) i (SgnLin.bas (treeSgn gp) R x)
      ∈ LinearMap.range (TensorProduct.map (wtZero R gp A).subtype (wtOne R gp B).subtype)
        ⊔ LinearMap.range (TensorProduct.map (wtOne R gp A).subtype (wtZero R gp B).subtype) := by
  have e : GrCooperad.decomp (R := R) (C := FreeGr R gp) i (SgnLin.bas (treeSgn gp) R x)
      = ∑ pq ∈ (SetOperad.FiniteFact.finite i x).toFinset,
          σ R (SgnData.sgn i ((treeSgn gp).app A pq.1) ((treeSgn gp).app B pq.2)) •
            ((SgnLin.bas (treeSgn gp) R pq.1 : FreeGr R gp A) ⊗ₜ[R]
              (SgnLin.bas (treeSgn gp) R pq.2 : FreeGr R gp B)) := by
    have h := SgnLin.decompT_single (R := R) (δ := treeSgn gp) i x 1
    simp only [mul_one] at h
    exact h
  rw [e]
  refine Submodule.sum_mem _ fun pq hpq => Submodule.smul_mem _ _ ?_
  have h := (SgnLin.mem_fact_iff i x pq).1 hpq
  have hv : vtx pq.1 + vtx pq.2 ≤ 1 := by
    rw [vtx, vtx, ← FreeReg.cntR_comp, h]
    exact hx
  rcases Nat.eq_zero_or_pos (vtx pq.1) with h1 | h1
  · exact Submodule.mem_sup_left ⟨⟨_, Submodule.subset_span ⟨pq.1, h1, rfl⟩⟩ ⊗ₜ
      ⟨_, Submodule.subset_span ⟨pq.2, by omega, rfl⟩⟩, rfl⟩
  · exact Submodule.mem_sup_right ⟨⟨_, Submodule.subset_span ⟨pq.1, by omega, rfl⟩⟩ ⊗ₜ
      ⟨_, Submodule.subset_span ⟨pq.2, by omega, rfl⟩⟩, rfl⟩

/-- **The decomposition of a tree with at most one vertex**: in every cut, one part has no
vertex. -/
lemma decomp_mem_wtOne (i : A) {z : FreeGr R gp (Without A i ⊕ B)}
    (hz : z ∈ wtOne R gp (Without A i ⊕ B)) :
    GrCooperad.decomp (R := R) (C := FreeGr R gp) i z
      ∈ LinearMap.range (TensorProduct.map (wtZero R gp A).subtype (wtOne R gp B).subtype)
        ⊔ LinearMap.range (TensorProduct.map (wtOne R gp A).subtype (wtZero R gp B).subtype) := by
  have key : wtOne R gp (Without A i ⊕ B)
      ≤ Submodule.comap (GrCooperad.decomp (R := R) (C := FreeGr R gp) i)
        (LinearMap.range (TensorProduct.map (wtZero R gp A).subtype (wtOne R gp B).subtype)
          ⊔ LinearMap.range (TensorProduct.map (wtOne R gp A).subtype
            (wtZero R gp B).subtype)) := by
    rw [wtOne, Submodule.span_le]
    rintro _ ⟨x, hx, rfl⟩
    exact decomp_bas_mem_wtOne i x hx
  exact key hz

end FreeGr

namespace FreeGrL

variable {V : (A : Type) → [Fintype A] → [DecidableEq A] → Type v}
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (V A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (V A)] [GrSpecies R V]

variable (R V) in
/-- The trees with at most one vertex, in the cut cooperad. -/
noncomputable def wtOneL (A : Type) [Fintype A] [DecidableEq A] : Submodule R (FreeGrL R V A) :=
  (FreeGr.wtOne R (grGenPar R V) A).map ((GrOperadIdeal.span R (grLinRel R V)).proj A)

variable (R V) in
/-- The trees without vertices, in the cut cooperad. -/
noncomputable def wtZeroL (A : Type) [Fintype A] [DecidableEq A] : Submodule R (FreeGrL R V A) :=
  (FreeGr.wtZero R (grGenPar R V) A).map ((GrOperadIdeal.span R (grLinRel R V)).proj A)

lemma wtZeroL_le_wtOneL : wtZeroL R V A ≤ wtOneL R V A :=
  Submodule.map_mono FreeGr.wtZero_le_wtOne

lemma wtZeroL_le_unitSpan : wtZeroL R V A ≤ GrCooperad.unitSpan R (FreeGrL R V) A :=
  (Submodule.map_mono FreeGr.wtZero_le_unitSpan).trans ((linCoideal R V).proj_unitSpan_le)

lemma decomp_mem_wtOneL (i : A) {y : FreeGrL R V (Without A i ⊕ B)}
    (hy : y ∈ wtOneL R V (Without A i ⊕ B)) :
    GrCooperad.decomp (R := R) (C := FreeGrL R V) i y
      ∈ LinearMap.range (TensorProduct.map (wtZeroL R V A).subtype (wtOneL R V B).subtype)
        ⊔ LinearMap.range (TensorProduct.map (wtOneL R V A).subtype (wtZeroL R V B).subtype) := by
  obtain ⟨z, hz, rfl⟩ := hy
  have h := FreeGr.decomp_mem_wtOne i hz
  have hm := Submodule.mem_map_of_mem (f := TensorProduct.map
    ((GrOperadIdeal.span R (grLinRel R V)).proj A) ((GrOperadIdeal.span R (grLinRel R V)).proj B)) h
  rw [Submodule.map_sup] at hm
  have hle := sup_le_sup
    (map_range_map_subtype_le ((GrOperadIdeal.span R (grLinRel R V)).proj A)
      ((GrOperadIdeal.span R (grLinRel R V)).proj B) (FreeGr.wtZero R (grGenPar R V) A)
      (FreeGr.wtOne R (grGenPar R V) B))
    (map_range_map_subtype_le ((GrOperadIdeal.span R (grLinRel R V)).proj A)
      ((GrOperadIdeal.span R (grLinRel R V)).proj B) (FreeGr.wtOne R (grGenPar R V) A)
      (FreeGr.wtZero R (grGenPar R V) B))
  exact hle hm

variable (R V) in
/-- **The trees with at most one vertex form a subcooperad of the cut cooperad.** -/
noncomputable def wtOneSub : GrSubCooperad R (FreeGrL R V) where
  sub A _ _ := wtOneL R V A
  par_mem := by
    rintro A _ _ b _ ⟨z, hz, rfl⟩
    exact ⟨_, FreeGr.par_mem_wtOne b hz, rfl⟩
  map_mem := by
    rintro A B _ _ _ _ e _ ⟨z, hz, rfl⟩
    exact ⟨_, FreeGr.map_mem_wtOne e hz, rfl⟩
  decomp_mem := by
    intro A B _ _ _ _ i y hy
    have h1 := GrSubCooperad.range_map_subtype_mono (C := FreeGrL R V)
      (wtZeroL_le_wtOneL (R := R) (V := V) (A := A)) (le_refl (wtOneL R V B))
    have h2 := GrSubCooperad.range_map_subtype_mono (C := FreeGrL R V)
      (le_refl (wtOneL R V A)) (wtZeroL_le_wtOneL (R := R) (V := V) (A := B))
    exact sup_le h1 h2 (decomp_mem_wtOneL i hy)

/-- **The generators are trees with one vertex.** -/
lemma ι_mem_wtOneL (w : V A) : (ι R V).app A w ∈ wtOneL R V A := by
  have h : ∀ n (v : V (Fin n)), (ι R V).app (Fin n) v ∈ wtOneL R V (Fin n) := by
    intro n v
    rw [ι_app_fin]
    refine add_mem ⟨_, Submodule.subset_span ⟨_, ?_, rfl⟩, rfl⟩
      ⟨_, Submodule.subset_span ⟨_, ?_, rfl⟩, rfl⟩ <;>
    · rw [FreeGr.vtx, FreeReg.cntR_std]
  have e := Fintype.equivFin A
  have hw : w = SymSpecies.map (R := R) e.symm (SymSpecies.map (R := R) e w) := by
    rw [SymSpecies.map_symm_map]
  rw [hw, (ι R V).app_map]
  obtain ⟨z, hz, hz'⟩ := h _ (SymSpecies.map (R := R) e w)
  rw [← hz']
  exact ⟨_, FreeGr.map_mem_wtOne e.symm hz, rfl⟩

end FreeGrL

end WeightOne

/-! ## The Koszul dual cooperad -/

section Koszul

variable (R : Type u) [Field R] (E : (A : Type) → [Fintype A] → [DecidableEq A] → Type v)
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (E A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (E A)] [GrSpecies R E]

namespace Koszul

/-- The cut cooperad `T^c(sE)` on the parity shift of the generators. -/
abbrev Cut := FreeGrL R (GrSpecies.Shift E R)

/-- The generators `sv ↦ εv`, into the square-zero extension of `T(E)` by an odd parameter. -/
noncomputable def epsGen :
    GrSpeciesHom R (GrSpecies.Shift E R) (DualExt R (FreeGrL R E) true) where
  app A _ _ :=
    { toFun := fun w => DualExt.mk 0 ((FreeGrL.ι R E).app A w)
      map_add' := fun w w' => Prod.ext (add_zero 0).symm (map_add _ w w')
      map_smul' := fun a w => Prod.ext (smul_zero a).symm (map_smul _ a w) }
  app_map e w := Prod.ext (by
    show (0 : FreeGrL R E _) = GrOperad.map (R := R) e 0
    rw [map_zero]) ((FreeGrL.ι R E).app_map e w)
  app_par c w := Prod.ext (by
    show (0 : FreeGrL R E _) = GrOperad.par (R := R) c 0
    rw [map_zero]) (by
    show (FreeGrL.ι R E).app _ (GrSpecies.par (R := R) (!c) w)
      = GrOperad.par (R := R) (xor c true) ((FreeGrL.ι R E).app _ w)
    rw [(FreeGrL.ι R E).app_par, Bool.xor_true]
    rfl)

/-- **The morphism `T(sE) → T(E) ⊕ εT(E)`**, `sv ↦ εv`. -/
noncomputable def epsHom :
    GrOperadHom R (Cut R E) (DualExt R (FreeGrL R E) true) :=
  FreeGrL.homEquiv.symm (epsGen R E)

/-- **The desuspension map** `κ_T : T^c(sE) → T(E)`: the `ε`-part of `epsHom`, the weight one
component of a tree, desuspended. -/
noncomputable def kapL (A : Type) [Fintype A] [DecidableEq A] :
    Cut R E A →ₗ[R] FreeGrL R E A :=
  DualExt.snd ∘ₗ (epsHom R E).app A

variable {R E}

lemma kapL_ι {A : Type} [Fintype A] [DecidableEq A] (w : E A) :
    kapL R E A ((FreeGrL.ι R (GrSpecies.Shift E R)).app A (GrSpecies.Shift.of A w))
      = (FreeGrL.ι R E).app A w := by
  rw [kapL, LinearMap.comp_apply, epsHom, FreeGrL.homEquiv_symm_ι]
  exact rfl

lemma kapL_map {A B : Type} [Fintype A] [DecidableEq A] [Fintype B] [DecidableEq B] (e : A ≃ B)
    (x : Cut R E A) :
    kapL R E B (GrOperad.map (R := R) e x) = GrOperad.map (R := R) e (kapL R E A x) := by
  rw [kapL, LinearMap.comp_apply, (epsHom R E).app_map]
  rfl

lemma kapL_par {A : Type} [Fintype A] [DecidableEq A] (c : Bool) (x : Cut R E A) :
    kapL R E A (GrOperad.par (R := R) c x) = GrOperad.par (R := R) (!c) (kapL R E A x) := by
  rw [kapL, LinearMap.comp_apply, (epsHom R E).app_par, ← Bool.xor_true]
  rfl

lemma kapL_one : kapL R E Unit (GrOperad.one (R := R)) = 0 := by
  rw [kapL, LinearMap.comp_apply, (epsHom R E).app_one]
  rfl

variable (R E) in
/-- **The desuspension map**, an invariant family of the convolution operad of `T^c(sE)` and
`T(E)`. -/
noncomputable def kapT : GrOperad.Inv R (ConvOp R (Cut R E) (FreeGrL R E)) :=
  ⟨fun A _ _ => ConvOp.of (kapL R E A), fun A B _ _ _ _ e => by
    show ConvOp.mapC e (ConvOp.of (kapL R E A)) = ConvOp.of (kapL R E B)
    ext x
    rw [ConvOp.mapC_apply, ConvOp.toLin_of, ConvOp.toLin_of]
    show GrOperad.map (R := R) e (kapL R E A (GrOperad.map (R := R) e.symm x)) = _
    rw [kapL_map, ← GrOperad.map_trans, Equiv.symm_trans_self, GrOperad.map_refl]⟩

lemma kapT_apply (A : Type) [Fintype A] [DecidableEq A] :
    (kapT R E).1 A = ConvOp.of (kapL R E A) := rfl

/-- **The desuspension map is odd.** -/
lemma isPar_kapT : GrOperad.Inv.IsPar true (kapT R E) := by
  intro A _ _
  show ConvOp.parC true (ConvOp.of (kapL R E A)) = ConvOp.of (kapL R E A)
  rw [ConvOp.parC_eq_self_iff]
  intro c x
  rw [ConvOp.toLin_of, Bool.xor_true]
  exact kapL_par c x

/-- **The desuspension map vanishes on the coaugmentation.** -/
lemma killsUnit_kapT : KillsUnit R (Cut R E) (FreeGrL R E) (kapT R E) := by
  intro A _ _ x hx
  rw [kapT_apply, ConvOp.toLin_of]
  refine Submodule.span_induction (p := fun x _ => kapL R E A x = 0) ?_ (map_zero _) ?_ ?_ hx
  · rintro _ ⟨e, rfl⟩
    show kapL R E A (GrOperad.map (R := R) e (GrOperad.one (R := R))) = 0
    rw [kapL_map, kapL_one, map_zero]
  · intro x y _ _ hx hy
    beta_reduce at hx hy ⊢
    rw [map_add, hx, hy, add_zero]
  · intro a x _ hx
    beta_reduce at hx ⊢
    rw [map_smul, hx, smul_zero]

variable (r : ∀ n : ℕ, Set (FreeGrL R E (Fin n)))

variable (R E) in
/-- **The presented graded operad** `P = T(E)/(r)`. -/
abbrev Pres := (GrOperadIdeal.span R r).Quot

variable (R E) in
/-- The submodules of `T^c(sE)` on which the convolution square `κ_T ⋆ κ_T` lands in the ideal
generated by the relators. -/
noncomputable def admissible (A : Type) [Fintype A] [DecidableEq A] : Submodule R (Cut R E A) :=
  ((GrOperadIdeal.span R r).sub A).comap
    (ConvOp.toLin ((GrOperad.Inv.star R _ (kapT R E) (kapT R E)).1 A))

variable (R E) in
/-- **The Koszul dual cooperad**, as a subcooperad of the cut cooperad: the largest subcooperad on
which `κ_T ⋆ κ_T` lands in the ideal generated by the relators. -/
noncomputable def dualSub : GrSubCooperad R (Cut R E) :=
  GrSubCooperad.cogen (admissible R E r)

variable (R E) in
/-- **The Koszul dual cooperad** `P^¡`. -/
abbrev Dual := (dualSub R E r).Sub

/-- **The Koszul dual cooperad contains the coaugmentation.** -/
lemma unitSub_le : GrSubCooperad.unitSub R (Cut R E) ≤ dualSub R E r :=
  GrSubCooperad.le_cogen _ fun A _ _ x hx => by
    show ConvOp.toLin ((GrOperad.Inv.star R _ (kapT R E) (kapT R E)).1 A) x
      ∈ (GrOperadIdeal.span R r).sub A
    rw [star_unit _ _ killsUnit_kapT hx]
    exact zero_mem _

/-- **The Koszul dual cooperad is coaugmented.** -/
noncomputable instance instCoaug : GrCooperad.Coaug R (Dual R E r) :=
  (dualSub R E r).coaug (unitSub_le r)

/-- **The universal property of the Koszul dual cooperad**: a subcooperad of `T^c(sE)` on which
`κ_T ⋆ κ_T` lands in the ideal of the relators lies in the Koszul dual cooperad. -/
lemma le_dualSub {K : GrSubCooperad R (Cut R E)}
    (hK : ∀ (A : Type) [Fintype A] [DecidableEq A] (x : Cut R E A), x ∈ K.sub A →
      ConvOp.toLin ((GrOperad.Inv.star R _ (kapT R E) (kapT R E)).1 A) x
        ∈ (GrOperadIdeal.span R r).sub A) :
    K ≤ dualSub R E r :=
  GrSubCooperad.le_cogen _ fun A _ _ x hx => hK A x hx

/-! ### The Koszul twisting morphism -/

variable (R E) in
/-- **The Koszul twisting morphism** `κ : P^¡ → P`: the desuspension map, restricted to the
Koszul dual cooperad and projected onto `P`. -/
noncomputable def kappa :
    GrOperad.Inv R (ConvOp R (Dual R E r) (ZeroDG R (Pres R E r))) :=
  GrOperad.Inv.appHom (ConvOp.postHom (C := Dual R E r)
      (GrOperadHom.toZeroDG (GrOperadIdeal.span R r).projHom))
    (GrOperad.Inv.appHom (ConvOp.preHom (P := FreeGrL R E) (dualSub R E r).inclHom) (kapT R E))

lemma kappa_apply {A : Type} [Fintype A] [DecidableEq A] (x : Dual R E r A) :
    ConvOp.toLin ((kappa R E r).1 A) x
      = (GrOperadIdeal.span R r).proj A (kapL R E A ((dualSub R E r).incl A x)) := rfl

/-- **The Koszul twisting morphism is odd.** -/
lemma isPar_kappa : GrOperad.Inv.IsPar true (kappa R E r) := by
  intro A _ _
  show GrOperad.par (R := R) true ((ConvOp.postHom (C := Dual R E r)
      (GrOperadHom.toZeroDG (GrOperadIdeal.span R r).projHom)).app A
      ((ConvOp.preHom (P := FreeGrL R E) (dualSub R E r).inclHom).app A ((kapT R E).1 A))) = _
  rw [← GrOperadHom.app_par, ← GrOperadHom.app_par, isPar_kapT A]
  rfl

/-- The inclusion of the Koszul dual cooperad maps the coaugmentation into the coaugmentation. -/
lemma incl_unitSpan {A : Type} [Fintype A] [DecidableEq A] {x : Dual R E r A}
    (hx : x ∈ GrCooperad.unitSpan R (Dual R E r) A) :
    (dualSub R E r).incl A x ∈ GrCooperad.unitSpan R (Cut R E) A := by
  refine Submodule.span_induction (p := fun x _ => (dualSub R E r).incl A x
      ∈ GrCooperad.unitSpan R (Cut R E) A) ?_ ?_ ?_ ?_ hx
  · rintro _ ⟨e, rfl⟩
    exact GrCooperad.map_one_mem (R := R) (C := Cut R E) e
  · beta_reduce
    rw [map_zero]
    exact zero_mem _
  · intro x y _ _ hx hy
    beta_reduce at hx hy ⊢
    rw [map_add]
    exact add_mem hx hy
  · intro a x _ hx
    beta_reduce at hx ⊢
    rw [map_smul]
    exact Submodule.smul_mem _ a hx

/-- **The Koszul twisting morphism vanishes on the coaugmentation.** -/
lemma killsUnit_kappa : KillsUnit R (Dual R E r) (ZeroDG R (Pres R E r)) (kappa R E r) := by
  intro A _ _ x hx
  rw [kappa_apply]
  have h := killsUnit_kapT (R := R) (E := E) A _ (incl_unitSpan r hx)
  rw [kapT_apply, ConvOp.toLin_of] at h
  rw [h, map_zero]
  rfl

/-- **The Koszul twisting morphism satisfies the Maurer–Cartan equation**: `κ ⋆ κ` is the
projection of `κ_T ⋆ κ_T`, which lands in the ideal of the relators on `P^¡`, and `P` has the zero
differential. -/
theorem mc_kappa :
    GrOperad.Inv.appDer (ConvOp.postDer (C := Dual R E r)
        (DGOperad.toDer (R := R) (P := ZeroDG R (Pres R E r)))) (kappa R E r)
      + GrOperad.Inv.star R _ (kappa R E r) (kappa R E r) = 0 := by
  have h1 : GrOperad.Inv.appDer (ConvOp.postDer (C := Dual R E r)
      (DGOperad.toDer (R := R) (P := ZeroDG R (Pres R E r)))) (kappa R E r) = 0 :=
    Subtype.ext (funext fun A => funext fun _ => funext fun _ => ConvOp.ext fun x => by
      rw [ConvOp.appDer_postDer_apply]
      exact LinearMap.zero_apply _)
  have h2 : GrOperad.Inv.star R _ (kappa R E r) (kappa R E r) = 0 := by
    have e1 := GrOperad.Inv.appHom_star
      (ConvOp.preHom (P := FreeGrL R E) (dualSub R E r).inclHom) (kapT R E) (kapT R E)
    have e2 := GrOperad.Inv.appHom_star (ConvOp.postHom (C := Dual R E r)
      (GrOperadHom.toZeroDG (GrOperadIdeal.span R r).projHom))
      (GrOperad.Inv.appHom (ConvOp.preHom (P := FreeGrL R E) (dualSub R E r).inclHom)
        (kapT R E))
      (GrOperad.Inv.appHom (ConvOp.preHom (P := FreeGrL R E) (dualSub R E r).inclHom)
        (kapT R E))
    refine (e2.symm.trans ?_)
    rw [← e1]
    refine Subtype.ext (funext fun A => funext fun _ => funext fun _ => ConvOp.ext fun x => ?_)
    show (GrOperadIdeal.span R r).proj A (ConvOp.toLin
      ((GrOperad.Inv.star R _ (kapT R E) (kapT R E)).1 A) ((dualSub R E r).incl A x)) = 0
    rw [GrOperadIdeal.proj_eq_zero_iff]
    exact GrSubCooperad.cogen_le (admissible R E r) A x.2
  exact (congrArg₂ (· + ·) h1 h2).trans (add_zero 0)

variable (R E) in
/-- **The Koszul twisting morphism**, a twisting morphism `P^¡ → P`. -/
noncomputable def twisting : Twisting R (Dual R E r) (ZeroDG R (Pres R E r)) :=
  ⟨kappa R E r, isPar_kappa r, killsUnit_kappa r, mc_kappa r⟩

variable (R E) in
/-- **The morphism of dg operads `ΩP^¡ → P`**, by the cobar adjunction. -/
noncomputable def cobarMor : CobarHom R (Dual R E r) (ZeroDG R (Pres R E r)) :=
  (Cobar.homEquiv (R := R) (C := Dual R E r) (P := ZeroDG R (Pres R E r))).symm
    (twisting R E r)

variable (R E) in
/-- **Koszulness**: the morphism `ΩP^¡ → P` induces isomorphisms on homology. -/
def IsKoszul : Prop :=
  ∀ (A : Type) [Fintype A] [DecidableEq A],
    Function.Bijective (Homology.map (dV := (Cobar.d R (Dual R E r)).app A)
      (dW := DGOperad.d (R := R) (P := ZeroDG R (Pres R E r)) (A := A))
      ((cobarMor R E r).1.app A) ((cobarMor R E r).2 A))

/-! ### The generators -/

lemma kap_unit_left {A D : Type} [Fintype A] [DecidableEq A] [Fintype D] [DecidableEq D]
    {f : ConvOp R (Cut R E) (FreeGrL R E) D}
    (hf : ∀ x ∈ GrCooperad.unitSpan R (Cut R E) D, ConvOp.toLin f x = 0)
    (g : ConvOp R (Cut R E) (FreeGrL R E) A) {a : Cut R E D}
    (ha : a ∈ GrCooperad.unitSpan R (Cut R E) D) (b : Cut R E A) :
    ConvOp.kap f g (a ⊗ₜ b) = 0 := by
  simp only [ConvOp.kap, LinearMap.coe_sum, Finset.sum_apply, TensorProduct.map_tmul]
  refine Finset.sum_eq_zero fun q _ => ?_
  rw [LinearMap.comp_apply, hf, TensorProduct.zero_tmul]
  rw [GrSpecies.tw_apply]
  exact add_mem (GrCooperad.unitSpan_le_comap_par false ha)
    (Submodule.smul_mem _ _ (GrCooperad.unitSpan_le_comap_par true ha))

/-- **`κ_T ⋆ κ_T` vanishes on the trees with at most one vertex.** -/
lemma star_wtOne {A : Type} [Fintype A] [DecidableEq A] {x : Cut R E A}
    (hx : x ∈ FreeGrL.wtOneL R (GrSpecies.Shift E R) A) :
    ConvOp.toLin ((GrOperad.Inv.star R _ (kapT R E) (kapT R E)).1 A) x = 0 := by
  rw [GrOperad.Inv.star_apply, ConvOp.toLin_sum, LinearMap.coe_sum, Finset.sum_apply]
  refine Finset.sum_eq_zero fun S _ => ?_
  show ConvOp.toLin (ConvOp.mapC (splitEquiv S)
    (ConvOp.compC none ((kapT R E).1 (SOut S)) ((kapT R E).1 (SIn S)))) x = 0
  rw [ConvOp.mapC_apply, ConvOp.toLin_compC, LinearMap.comp_apply, LinearMap.comp_apply]
  have hx' : SymSpecies.map (R := R) (splitEquiv S).symm x
      ∈ FreeGrL.wtOneL R (GrSpecies.Shift E R) _ :=
    (FreeGrL.wtOneSub R (GrSpecies.Shift E R)).map_mem _ hx
  have hk := FreeGrL.decomp_mem_wtOneL (none : SOut S) hx'
  have h1 : LinearMap.range (TensorProduct.map
      (FreeGrL.wtZeroL R (GrSpecies.Shift E R) (SOut S)).subtype
      (FreeGrL.wtOneL R (GrSpecies.Shift E R) (SIn S)).subtype) ≤ LinearMap.ker (ConvOp.kap
      ((kapT R E).1 (SOut S)) ((kapT R E).1 (SIn S))) := by
    rintro _ ⟨t, rfl⟩
    induction t using TensorProduct.induction_on with
    | zero => simp
    | tmul a b =>
      rw [LinearMap.mem_ker, TensorProduct.map_tmul]
      exact kap_unit_left (fun y hy => killsUnit_kapT _ y hy) _
        (FreeGrL.wtZeroL_le_unitSpan a.2) _
    | add t t' ht ht' =>
      rw [LinearMap.mem_ker, map_add, map_add]
      rw [LinearMap.mem_ker] at ht ht'
      rw [ht, ht', add_zero]
  have h2 : LinearMap.range (TensorProduct.map
      (FreeGrL.wtOneL R (GrSpecies.Shift E R) (SOut S)).subtype
      (FreeGrL.wtZeroL R (GrSpecies.Shift E R) (SIn S)).subtype) ≤ LinearMap.ker (ConvOp.kap
      ((kapT R E).1 (SOut S)) ((kapT R E).1 (SIn S))) := by
    rintro _ ⟨t, rfl⟩
    induction t using TensorProduct.induction_on with
    | zero => simp
    | tmul a b =>
      rw [LinearMap.mem_ker, TensorProduct.map_tmul]
      exact kap_unit _ (fun y hy => killsUnit_kapT _ y hy) _ (FreeGrL.wtZeroL_le_unitSpan b.2)
    | add t t' ht ht' =>
      rw [LinearMap.mem_ker, map_add, map_add]
      rw [LinearMap.mem_ker] at ht ht'
      rw [ht, ht', add_zero]
  rw [LinearMap.mem_ker.1 (sup_le h1 h2 hk), map_zero, map_zero]

/-- **The trees with at most one vertex lie in the Koszul dual cooperad.** -/
lemma wtOneSub_le : FreeGrL.wtOneSub R (GrSpecies.Shift E R) ≤ dualSub R E r :=
  le_dualSub r fun A _ _ x hx => by
    rw [star_wtOne hx]
    exact zero_mem _

/-- **The generators `sE` lie in the Koszul dual cooperad.** -/
theorem ι_mem_dual {A : Type} [Fintype A] [DecidableEq A] (w : E A) :
    (FreeGrL.ι R (GrSpecies.Shift E R)).app A (GrSpecies.Shift.of A w)
      ∈ (dualSub R E r).sub A :=
  wtOneSub_le r A (FreeGrL.ι_mem_wtOneL _)

end Koszul

end Koszul

end Operad
