/-
# Ideals, quotients and presentations of graded operads

An **ideal** of a graded operad is a family of submodules stable under the parity projections, the
relabellings, and composition on either side (`GrOperadIdeal`); the kernel of a morphism of graded
operads is one (`GrOperadHom.ker`). **The quotient by an ideal is a graded operad**
(`GrOperadIdeal.instGrOperad`): parallel associativity descends through homogeneous
representatives, which exist because the ideal is stable under the parity projections. The
quotient map is the universal morphism killing the ideal (`GrOperadIdeal.liftHom`,
`GrOperadIdeal.liftHom_unique`), and a morphism factors injectively through the quotient by its
kernel (`GrOperadHom.kerLift_injective`).

The **ideal generated by relators** is the smallest one containing them (`GrOperadIdeal.span`).
A morphism out of the quotient is a morphism killing the relators (`GrOperadIdeal.presHomEquiv`),
and for the free graded operad, **a morphism out of a presented graded operad is a choice of an
operation of the right parity for each generator, on which the relators vanish**
(`FreeGr.presHomEquiv`).
-/
import Operad.FreeGraded
import Mathlib.LinearAlgebra.Quotient.Basic

universe u v w x

namespace Operad

open Sym GerBV

/-! ## Composition of morphisms -/

namespace GrOperadHom

variable {R : Type u} [CommRing R]
  {P : (A : Type) → [Fintype A] → [DecidableEq A] → Type v}
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (P A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (P A)] [GrOperad R P]
  {Q : (A : Type) → [Fintype A] → [DecidableEq A] → Type w}
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (Q A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (Q A)] [GrOperad R Q]
  {S : (A : Type) → [Fintype A] → [DecidableEq A] → Type x}
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (S A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (S A)] [GrOperad R S]

variable (R P) in
/-- The identity morphism. -/
def id : GrOperadHom R P P where
  app _ _ _ := LinearMap.id
  app_par _ _ := rfl
  app_map _ _ := rfl
  app_one := rfl
  app_comp _ _ _ := rfl

/-- The composite of two morphisms. -/
def comp (ψ : GrOperadHom R Q S) (φ : GrOperadHom R P Q) : GrOperadHom R P S where
  app A _ _ := ψ.app A ∘ₗ φ.app A
  app_par b x := by simp only [LinearMap.comp_apply, φ.app_par, ψ.app_par]
  app_map e x := by simp only [LinearMap.comp_apply, φ.app_map, ψ.app_map]
  app_one := by simp only [LinearMap.comp_apply, φ.app_one, ψ.app_one]
  app_comp i x y := by simp only [LinearMap.comp_apply, φ.app_comp, ψ.app_comp]

@[simp] lemma comp_app (ψ : GrOperadHom R Q S) (φ : GrOperadHom R P Q) {A : Type} [Fintype A]
    [DecidableEq A] (x : P A) : (ψ.comp φ).app A x = ψ.app A (φ.app A x) := rfl

end GrOperadHom

/-! ## Ideals -/

/-- **An ideal of a graded operad**: submodules stable under the parity projections, the
relabellings, and composition on either side. -/
structure GrOperadIdeal (R : Type u) [CommRing R]
    (P : (A : Type) → [Fintype A] → [DecidableEq A] → Type v)
    [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (P A)]
    [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (P A)] [GrOperad R P] where
  /-- The component at a finite input set. -/
  sub (A : Type) [Fintype A] [DecidableEq A] : Submodule R (P A)
  par_mem {A : Type} [Fintype A] [DecidableEq A] (b : Bool) {x : P A} :
    x ∈ sub A → GrOperad.par (R := R) b x ∈ sub A
  map_mem {A B : Type} [Fintype A] [DecidableEq A] [Fintype B] [DecidableEq B] (e : A ≃ B)
    {x : P A} : x ∈ sub A → GrOperad.map (R := R) e x ∈ sub B
  comp_mem_left {A B : Type} [Fintype A] [DecidableEq A] [Fintype B] [DecidableEq B] (i : A)
    {x : P A} (y : P B) : x ∈ sub A → GrOperad.comp (R := R) i x y ∈ sub (Without A i ⊕ B)
  comp_mem_right {A B : Type} [Fintype A] [DecidableEq A] [Fintype B] [DecidableEq B] (i : A)
    (x : P A) {y : P B} : y ∈ sub B → GrOperad.comp (R := R) i x y ∈ sub (Without A i ⊕ B)

variable {R : Type u} [CommRing R]
  {P : (A : Type) → [Fintype A] → [DecidableEq A] → Type v}
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (P A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (P A)] [GrOperad R P]
  {Q : (A : Type) → [Fintype A] → [DecidableEq A] → Type w}
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (Q A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (Q A)] [GrOperad R Q]

/-- **The kernel of a morphism of graded operads is an ideal.** -/
def GrOperadHom.ker (f : GrOperadHom R P Q) : GrOperadIdeal R P where
  sub A _ _ := LinearMap.ker (f.app A)
  par_mem := by
    intro A _ _ b x hx
    rw [LinearMap.mem_ker] at hx ⊢
    rw [f.app_par, hx, map_zero]
  map_mem := by
    intro A B _ _ _ _ e x hx
    rw [LinearMap.mem_ker] at hx ⊢
    rw [f.app_map, hx, map_zero]
  comp_mem_left := by
    intro A B _ _ _ _ i x y hx
    rw [LinearMap.mem_ker] at hx ⊢
    rw [f.app_comp, hx, map_zero, LinearMap.zero_apply]
  comp_mem_right := by
    intro A B _ _ _ _ i x y hy
    rw [LinearMap.mem_ker] at hy ⊢
    rw [f.app_comp, hy, map_zero]

@[simp] lemma GrOperadHom.mem_ker (f : GrOperadHom R P Q) {A : Type} [Fintype A]
    [DecidableEq A] (x : P A) : x ∈ f.ker.sub A ↔ f.app A x = 0 :=
  LinearMap.mem_ker

/-! ## Quotients -/

namespace GrOperadIdeal

variable (I : GrOperadIdeal R P)

/-- **The quotient of a graded operad by an ideal**, input set by input set. -/
def Quot (A : Type) [Fintype A] [DecidableEq A] : Type v := P A ⧸ I.sub A

instance (A : Type) [Fintype A] [DecidableEq A] : AddCommGroup (I.Quot A) :=
  inferInstanceAs (AddCommGroup (_ ⧸ _))

instance (A : Type) [Fintype A] [DecidableEq A] : Module R (I.Quot A) :=
  inferInstanceAs (Module R (_ ⧸ _))

variable {A B : Type} [Fintype A] [DecidableEq A] [Fintype B] [DecidableEq B]

/-- The quotient map. -/
def proj (A : Type) [Fintype A] [DecidableEq A] : P A →ₗ[R] I.Quot A := (I.sub A).mkQ

lemma proj_surjective (A : Type) [Fintype A] [DecidableEq A] : Function.Surjective (I.proj A) :=
  Submodule.mkQ_surjective _

lemma proj_eq_zero_iff (x : P A) : I.proj A x = 0 ↔ x ∈ I.sub A :=
  Submodule.Quotient.mk_eq_zero _

/-- The parity projections, descended to the quotient. -/
def parQ (b : Bool) : I.Quot A →ₗ[R] I.Quot A :=
  Submodule.mapQ _ _ (GrOperad.par (R := R) b) fun _ hx => I.par_mem b hx

/-- Relabelling, descended to the quotient. -/
def mapQ (e : A ≃ B) : I.Quot A →ₗ[R] I.Quot B :=
  Submodule.mapQ _ _ (GrOperad.map (R := R) e) fun _ hx => I.map_mem e hx

/-- Composition with a fixed outer operation, descended to the quotient. -/
def compRight (i : A) (x : P A) : I.Quot B →ₗ[R] I.Quot (Without A i ⊕ B) :=
  Submodule.mapQ _ _ (GrOperad.comp (R := R) i x) fun _ hy => I.comp_mem_right i x hy

lemma compRight_proj (i : A) (x : P A) (y : P B) :
    I.compRight i x (I.proj B y) = I.proj _ (GrOperad.comp (R := R) i x y) := rfl

/-- Composition on the quotient. -/
def compQ (i : A) : I.Quot A →ₗ[R] I.Quot B →ₗ[R] I.Quot (Without A i ⊕ B) :=
  Submodule.liftQ _
    { toFun := fun x => I.compRight i x
      map_add' := fun x x' => by
        refine LinearMap.ext fun z => ?_
        obtain ⟨y, rfl⟩ := I.proj_surjective B z
        simp only [compRight_proj, LinearMap.add_apply, map_add]
      map_smul' := fun r x => by
        refine LinearMap.ext fun z => ?_
        obtain ⟨y, rfl⟩ := I.proj_surjective B z
        simp only [compRight_proj, LinearMap.smul_apply, RingHom.id_apply, map_smul] }
    (by
      intro x hx
      refine LinearMap.ext fun z => ?_
      obtain ⟨y, rfl⟩ := I.proj_surjective B z
      show I.proj _ (GrOperad.comp (R := R) i x y) = 0
      exact (I.proj_eq_zero_iff _).2 (I.comp_mem_left i y hx))

lemma compQ_proj (i : A) (x : P A) (y : P B) :
    I.compQ i (I.proj A x) (I.proj B y) = I.proj _ (GrOperad.comp (R := R) i x y) := rfl

/-- **The quotient of a graded operad by an ideal is a graded operad.** -/
instance instGrOperad : GrOperad R I.Quot where
  par b := I.parQ b
  par_add X := by
    obtain ⟨x, rfl⟩ := I.proj_surjective _ X
    exact (map_add (I.proj _) _ _).symm.trans (congrArg (I.proj _) (GrOperad.par_add x))
  par_par b b' X := by
    obtain ⟨x, rfl⟩ := I.proj_surjective _ X
    show I.proj _ (GrOperad.par (R := R) b (GrOperad.par (R := R) b' x)) = _
    rw [GrOperad.par_par]
    split_ifs
    · rfl
    · exact map_zero _
  map e := I.mapQ e
  map_refl X := by
    obtain ⟨x, rfl⟩ := I.proj_surjective _ X
    exact congrArg (I.proj _) (GrOperad.map_refl (R := R) x)
  map_trans e f X := by
    obtain ⟨x, rfl⟩ := I.proj_surjective _ X
    exact congrArg (I.proj _) (GrOperad.map_trans (R := R) e f x)
  map_par e b X := by
    obtain ⟨x, rfl⟩ := I.proj_surjective _ X
    exact congrArg (I.proj _) (GrOperad.map_par (R := R) e b x)
  one := I.proj Unit (GrOperad.one (R := R) (P := P))
  par_one := congrArg (I.proj _) GrOperad.par_one
  comp i := I.compQ i
  comp_par i p q X Y := by
    obtain ⟨x, rfl⟩ := I.proj_surjective _ X
    obtain ⟨y, rfl⟩ := I.proj_surjective _ Y
    exact congrArg (I.proj _) (GrOperad.comp_par (R := R) i p q x y)
  map_comp σ' τ i X Y := by
    obtain ⟨x, rfl⟩ := I.proj_surjective _ X
    obtain ⟨y, rfl⟩ := I.proj_surjective _ Y
    exact congrArg (I.proj _) (GrOperad.map_comp (R := R) σ' τ i x y)
  comp_one i X := by
    obtain ⟨x, rfl⟩ := I.proj_surjective _ X
    exact congrArg (I.proj _) (GrOperad.comp_one (R := R) i x)
  one_comp Y := by
    obtain ⟨y, rfl⟩ := I.proj_surjective _ Y
    exact congrArg (I.proj _) (GrOperad.one_comp (R := R) y)
  comp_assoc_seq i j X Y Z := by
    obtain ⟨x, rfl⟩ := I.proj_surjective _ X
    obtain ⟨y, rfl⟩ := I.proj_surjective _ Y
    obtain ⟨z, rfl⟩ := I.proj_surjective _ Z
    exact congrArg (I.proj _) (GrOperad.comp_assoc_seq (R := R) i j x y z)
  comp_assoc_par {A B D} _ _ _ _ _ _ i k hik X q r Y Z hY hZ := by
    obtain ⟨x, rfl⟩ := I.proj_surjective _ X
    obtain ⟨y, rfl⟩ := I.proj_surjective _ Y
    obtain ⟨z, rfl⟩ := I.proj_surjective _ Z
    -- homogeneous representatives
    rw [← hY, ← hZ]
    exact (congrArg (I.proj _) (GrOperad.comp_assoc_par (R := R) hik x
      (y := GrOperad.par (R := R) q y) (z := GrOperad.par (R := R) r z)
      (by rw [GrOperad.par_par, if_pos rfl]) (by rw [GrOperad.par_par, if_pos rfl]))).trans
      (map_smul (I.proj _) _ _)

/-- **The quotient map is a morphism of graded operads.** -/
def projHom : GrOperadHom R P I.Quot where
  app A _ _ := I.proj A
  app_par _ _ := rfl
  app_map _ _ := rfl
  app_one := rfl
  app_comp _ _ _ := rfl

@[simp] lemma projHom_app (x : P A) : I.projHom.app A x = I.proj A x := rfl

/-- **The kernel of the quotient map is the ideal.** -/
lemma mem_ker_projHom (x : P A) : x ∈ I.projHom.ker.sub A ↔ x ∈ I.sub A := by
  rw [GrOperadHom.mem_ker, projHom_app, proj_eq_zero_iff]

/-- **The universal property of the quotient**: a morphism vanishing on the ideal factors through
the quotient. -/
def liftHom (φ : GrOperadHom R P Q)
    (h : ∀ (A : Type) [Fintype A] [DecidableEq A], ∀ x ∈ I.sub A, φ.app A x = 0) :
    GrOperadHom R I.Quot Q where
  app A _ _ := Submodule.liftQ (I.sub A) (φ.app A) fun x hx => h A x hx
  app_par b X := by
    obtain ⟨x, rfl⟩ := I.proj_surjective _ X
    exact φ.app_par b x
  app_map e X := by
    obtain ⟨x, rfl⟩ := I.proj_surjective _ X
    exact φ.app_map e x
  app_one := φ.app_one
  app_comp i X Y := by
    obtain ⟨x, rfl⟩ := I.proj_surjective _ X
    obtain ⟨y, rfl⟩ := I.proj_surjective _ Y
    exact φ.app_comp i x y

lemma liftHom_proj (φ : GrOperadHom R P Q)
    (h : ∀ (A : Type) [Fintype A] [DecidableEq A], ∀ x ∈ I.sub A, φ.app A x = 0) (x : P A) :
    (I.liftHom φ h).app A (I.proj A x) = φ.app A x := rfl

/-- The factorization through the quotient composes back to the morphism. -/
lemma liftHom_comp_projHom (φ : GrOperadHom R P Q)
    (h : ∀ (A : Type) [Fintype A] [DecidableEq A], ∀ x ∈ I.sub A, φ.app A x = 0) :
    (I.liftHom φ h).comp I.projHom = φ :=
  GrOperadHom.ext fun _ _ _ _ => rfl

/-- **The factorization is unique.** -/
lemma liftHom_unique (φ : GrOperadHom R P Q)
    (h : ∀ (A : Type) [Fintype A] [DecidableEq A], ∀ x ∈ I.sub A, φ.app A x = 0)
    (ψ : GrOperadHom R I.Quot Q) (hψ : ψ.comp I.projHom = φ) : ψ = I.liftHom φ h := by
  refine GrOperadHom.ext fun A _ _ X => ?_
  obtain ⟨x, rfl⟩ := I.proj_surjective _ X
  rw [liftHom_proj, ← hψ]
  rfl

end GrOperadIdeal

namespace GrOperadHom

/-- **A morphism factors through the quotient by its kernel.** -/
def kerLift (φ : GrOperadHom R P Q) : GrOperadHom R φ.ker.Quot Q :=
  φ.ker.liftHom φ fun _ _ _ _ hx => hx

lemma kerLift_proj (φ : GrOperadHom R P Q) {A : Type} [Fintype A] [DecidableEq A]
    (x : P A) : φ.kerLift.app A (φ.ker.proj A x) = φ.app A x := rfl

/-- **The factorization through the kernel is injective.** -/
lemma kerLift_injective (φ : GrOperadHom R P Q) (A : Type) [Fintype A] [DecidableEq A] :
    Function.Injective (φ.kerLift.app A) := by
  rw [← LinearMap.ker_eq_bot, Submodule.eq_bot_iff]
  intro z hz
  obtain ⟨x, rfl⟩ := φ.ker.proj_surjective _ z
  rw [LinearMap.mem_ker, kerLift_proj] at hz
  exact (φ.ker.proj_eq_zero_iff x).2 hz

end GrOperadHom

/-! ## Generated ideals and presentations -/

namespace GrOperadIdeal

lemma ext {I J : GrOperadIdeal R P}
    (h : ∀ (A : Type) [Fintype A] [DecidableEq A], I.sub A = J.sub A) : I = J := by
  obtain ⟨I, _, _, _, _⟩ := I
  obtain ⟨J, _, _, _, _⟩ := J
  have : @I = @J := by
    funext A _ _
    exact h A
  subst this
  rfl

/-- **Ideals are ordered by inclusion**, input set by input set. -/
instance : PartialOrder (GrOperadIdeal R P) where
  le I J := ∀ (A : Type) [Fintype A] [DecidableEq A], I.sub A ≤ J.sub A
  le_refl _ _ _ _ := le_rfl
  le_trans _ _ _ hIJ hJK A _ _ := (hIJ A).trans (hJK A)
  le_antisymm _ _ hIJ hJI := ext fun A _ _ => le_antisymm (hIJ A) (hJI A)

/-- **The intersection of a set of ideals is an ideal.** -/
def sInf (S : Set (GrOperadIdeal R P)) : GrOperadIdeal R P where
  sub A _ _ := ⨅ I ∈ S, I.sub A
  par_mem := by
    intro A _ _ b x hx
    simp only [Submodule.mem_iInf] at hx ⊢
    exact fun I hI => I.par_mem b (hx I hI)
  map_mem := by
    intro A B _ _ _ _ e x hx
    simp only [Submodule.mem_iInf] at hx ⊢
    exact fun I hI => I.map_mem e (hx I hI)
  comp_mem_left := by
    intro A B _ _ _ _ i x y hx
    simp only [Submodule.mem_iInf] at hx ⊢
    exact fun I hI => I.comp_mem_left i y (hx I hI)
  comp_mem_right := by
    intro A B _ _ _ _ i x y hy
    simp only [Submodule.mem_iInf] at hy ⊢
    exact fun I hI => I.comp_mem_right i x (hy I hI)

lemma mem_sInf {S : Set (GrOperadIdeal R P)} {A : Type} [Fintype A] [DecidableEq A] {x : P A} :
    x ∈ (sInf S).sub A ↔ ∀ I ∈ S, x ∈ I.sub A := by
  simp only [sInf, Submodule.mem_iInf]

lemma sInf_le {S : Set (GrOperadIdeal R P)} {I : GrOperadIdeal R P} (h : I ∈ S) :
    sInf S ≤ I :=
  fun _ _ _ _ hx => mem_sInf.1 hx I h

variable (R) in
/-- **The ideal generated by relators** `r n ⊆ P (Fin n)`: the smallest ideal containing them. -/
def span (r : ∀ n : ℕ, Set (P (Fin n))) : GrOperadIdeal R P :=
  sInf {I | ∀ n, r n ⊆ I.sub (Fin n)}

variable {r : ∀ n : ℕ, Set (P (Fin n))}

lemma subset_span (n : ℕ) : r n ⊆ (span R r).sub (Fin n) :=
  fun _ hx => mem_sInf.2 fun _ hI => hI n hx

/-- **The generated ideal lies in an ideal exactly when the relators do.** -/
lemma span_le {I : GrOperadIdeal R P} : span R r ≤ I ↔ ∀ n, r n ⊆ I.sub (Fin n) :=
  ⟨fun h n _ hx => h _ (subset_span n hx), fun h => sInf_le h⟩

/-- A morphism killing the relators kills every element of the generated ideal. -/
lemma app_eq_zero_of_mem_span (φ : GrOperadHom R P Q)
    (hφ : ∀ n, ∀ x ∈ r n, φ.app (Fin n) x = 0) {A : Type} [Fintype A] [DecidableEq A] {x : P A}
    (hx : x ∈ (span R r).sub A) : φ.app A x = 0 :=
  (GrOperadHom.mem_ker φ x).1 (span_le.2 (fun n y hy => (GrOperadHom.mem_ker φ y).2 (hφ n y hy))
    A hx)

/-- **The universal property of a presented graded operad**: a morphism out of the quotient by
the ideal generated by `r` is a morphism out of `P` killing `r`. -/
def presHomEquiv :
    GrOperadHom R (span R r).Quot Q
      ≃ {φ : GrOperadHom R P Q // ∀ n, ∀ x ∈ r n, φ.app (Fin n) x = 0} where
  toFun ψ := ⟨ψ.comp (span R r).projHom, fun n x hx => by
    show ψ.app _ ((span R r).proj _ x) = 0
    rw [((span R r).proj_eq_zero_iff x).2 (subset_span n hx), map_zero]⟩
  invFun φ := (span R r).liftHom φ.1 fun _ _ _ _ hx => app_eq_zero_of_mem_span φ.1 φ.2 hx
  left_inv ψ := ((span R r).liftHom_unique _ _ ψ rfl).symm
  right_inv φ := Subtype.ext ((span R r).liftHom_comp_projHom _ _)

lemma presHomEquiv_symm_proj (φ : {φ : GrOperadHom R P Q // ∀ n, ∀ x ∈ r n,
    φ.app (Fin n) x = 0}) {A : Type} [Fintype A] [DecidableEq A] (x : P A) :
    (presHomEquiv.symm φ).app A ((span R r).proj A x) = φ.1.app A x := rfl

end GrOperadIdeal

/-! ## Presented graded operads -/

namespace FreeGr

variable {T : ℕ → Type v} {gp : ∀ k, T k → Bool}
  {r : ∀ n : ℕ, Set (FreeGr R gp (Fin n))}

/-- **The universal property of a presented graded operad**: a morphism out of the free graded
operad modulo the ideal generated by relators is an operation of the right parity for each
generator, such that the morphism they define kills the relators. -/
noncomputable def presHomEquiv :
    GrOperadHom R (GrOperadIdeal.span R r).Quot Q
      ≃ {f : GenVal R gp Q // ∀ n, ∀ x ∈ r n, (homEquiv.symm f).app (Fin n) x = 0} :=
  GrOperadIdeal.presHomEquiv.trans (homEquiv.subtypeEquiv fun φ => by
    rw [Equiv.symm_apply_apply])

/-- The generators, in a presented graded operad. -/
noncomputable def presGen (r : ∀ n : ℕ, Set (FreeGr R gp (Fin n))) {k : ℕ} (e : T k) :
    (GrOperadIdeal.span R r).Quot (Fin k) :=
  (GrOperadIdeal.span R r).proj (Fin k) (gen e)

@[simp] lemma presHomEquiv_symm_gen
    (f : {f : GenVal R gp Q // ∀ n, ∀ x ∈ r n, (homEquiv.symm f).app (Fin n) x = 0}) {k : ℕ}
    (e : T k) : (presHomEquiv.symm f).app (Fin k) (presGen r e) = f.1.1 k e :=
  homEquiv_symm_gen f.1 e

/-- **Morphisms out of a presented graded operad agree when they agree on the generators.** -/
theorem pres_hom_ext {φ ψ : GrOperadHom R (GrOperadIdeal.span R r).Quot Q}
    (h : ∀ k (e : T k), φ.app (Fin k) (presGen r e) = ψ.app (Fin k) (presGen r e)) : φ = ψ :=
  presHomEquiv.injective (Subtype.ext (congrArg homEquiv (hom_ext fun k e => h k e)))

end FreeGr

end Operad
