/-
# The hypercommutative operad

**The hypercommutative operad** `HyperCom` (Getzler; the homology of the moduli spaces `M̄₀,ₙ₊₁`
of stable curves of genus zero, with `n` inputs and one output) is generated by one totally
symmetric operation `mₙ` in each arity `n ≥ 2`, subject to the **WDVV relations**: for distinct
inputs `i, j, k` among `n`,

  `∑_{i, j ∈ S, k ∉ S} m(m(x_S), x_{Sᶜ}) = ∑_{i, k ∈ S, j ∉ S} m(m(x_S), x_{Sᶜ})`,

the sums running over the sets `S` of inputs, and `m(m(x_S), x_{Sᶜ})` being `m_{|Sᶜ| + 1}` with
`m_{|S|}` of the inputs in `S` in its first input and the inputs in `Sᶜ` in the others. The
generator `mₙ` has degree `2 (n - 2)`, so the operad is concentrated in even degrees and lives
among ungraded operads.

* `HCGen` and `FreeHC`: the generators and the free operad on them; `HyperCom R` is the operad
  presented by the symmetry relators of the generators and the WDVV relators (`hcRel`).
* **Algebras over `HyperCom` are hypercommutative algebras** (`HyperCom.algebraEquiv`): families of
  totally symmetric multilinear operations `μₙ`, `n ≥ 2`, satisfying the WDVV identities
  (`HCAlg`).
* In arity three the WDVV identity is associativity: the binary operation of a hypercommutative
  algebra is commutative and associative (`HCAlg.mul_comm`, `HCAlg.mul_assoc`), and **commutative
  algebras are hypercommutative**, with no operations of arity at least three (`HCAlg.ofComm`).
-/
import Operad.BinaryQuadratic

universe u v

namespace Operad

open Sym SetOperad Finset

/-! ## Generators and relators -/

/-- **The generators of the hypercommutative operad**: one operation in each arity `n ≥ 2`. -/
@[nolint structureInType]
structure HCGen (n : ℕ) : Type where
  /-- The arity is at least two. -/
  two_le : 2 ≤ n

variable (R : Type u) [CommRing R]

/-- **The free operad on the hypercommutative generators**, in `R`-modules. -/
abbrev FreeHC := Lin R (FreeSet HCGen)

namespace HyperCom

/-- The expression of the generator `mₙ`. -/
def gen (n : ℕ) (h : 2 ≤ n) : Syn HCGen (Fin n) := .gen ⟨h⟩

variable {R}

/-- **The relabelled generator** `mₙ(x_{σ 0}, …, x_{σ (n-1)})`. -/
noncomputable def mono (n : ℕ) (h : 2 ≤ n) (σ : Equiv.Perm (Fin n)) : FreeHC R (Fin n) :=
  Finsupp.single (Pres.mk (.map σ (gen n h))) 1

/-- The inputs of an operation of arity `c + 1` other than the first. -/
def withoutZero (c : ℕ) : Without (Fin (c + 1)) 0 ≃ Fin c where
  toFun x := x.1.pred x.2
  invFun k := ⟨k.succ, Fin.succ_ne_zero k⟩
  left_inv x := Subtype.ext (Fin.succ_pred x.1 x.2)
  right_inv k := Fin.pred_succ k

/-- **The relabelling of a WDVV composite**: the other inputs of the outer operation go to `Sᶜ`
and the inputs of the inner one to `S`, both in increasing order. -/
noncomputable def wEquiv {n : ℕ} (S : Finset (Fin n)) :
    Without (Fin (Sᶜ.card + 1)) 0 ⊕ Fin S.card ≃ Fin n :=
  (Equiv.sumCongr ((withoutZero _).trans ((Sᶜ.orderIsoOfFin rfl).toEquiv.trans
      (Equiv.subtypeEquivRight fun _ => Finset.mem_compl)))
    (S.orderIsoOfFin rfl).toEquiv).trans
    ((Equiv.sumComm _ _).trans (Equiv.sumCompl fun a => a ∈ S))

@[simp] lemma wEquiv_inr {n : ℕ} (S : Finset (Fin n)) (t : Fin S.card) :
    wEquiv S (Sum.inr t) = S.orderEmbOfFin rfl t := by
  simp [wEquiv, Finset.coe_orderIsoOfFin_apply]

@[simp] lemma wEquiv_inl {n : ℕ} (S : Finset (Fin n)) (x : Without (Fin (Sᶜ.card + 1)) 0) :
    wEquiv S (Sum.inl x) = Sᶜ.orderEmbOfFin rfl (withoutZero _ x) := by
  simp [wEquiv, Finset.coe_orderIsoOfFin_apply]

/-- **The WDVV composite** `m(m(x_S), x_{Sᶜ})`, zero unless `S` has at least two elements and
misses one. -/
noncomputable def wTerm {n : ℕ} (S : Finset (Fin n)) : FreeHC R (Fin n) :=
  if h : 2 ≤ S.card ∧ 1 ≤ Sᶜ.card then
    Finsupp.single (Pres.mk (.map (wEquiv S)
      (.comp 0 (gen (Sᶜ.card + 1) (by omega)) (gen S.card h.1)))) 1
  else 0

/-- **The WDVV relator** for distinct inputs `i, j, k`. -/
noncomputable def wdvv {n : ℕ} (i j k : Fin n) : FreeHC R (Fin n) :=
  ∑ S ∈ univ.filter (fun S => i ∈ S ∧ j ∈ S ∧ k ∉ S), wTerm S -
    ∑ S ∈ univ.filter (fun S => i ∈ S ∧ k ∈ S ∧ j ∉ S), wTerm S

variable (R) in
/-- **The relators of the hypercommutative operad**: the generators are totally symmetric, and the
WDVV relators. -/
def hcRel (n : ℕ) : Set (FreeHC R (Fin n)) :=
  {x | ∃ (h : 2 ≤ n) (σ : Equiv.Perm (Fin n)), x = mono n h σ - mono n h 1} ∪
    {x | ∃ i j k : Fin n, i ≠ j ∧ i ≠ k ∧ j ≠ k ∧ x = wdvv i j k}

end HyperCom

/-- **The hypercommutative operad**, presented by totally symmetric generators `mₙ` (`n ≥ 2`) and
the WDVV relations. -/
abbrev HyperComOp := (SymOperadIdeal.span R (HyperCom.hcRel R)).Quot

/-! ## Hypercommutative algebras -/

section Algebra

variable {R} (V : Type v) [AddCommGroup V] [Module R V]

namespace HyperCom

/-- **The WDVV composite of operations** `μ_{|Sᶜ|+1}(μ_{|S|}(v_S), v_{Sᶜ})`, the inputs in `S` and
in `Sᶜ` in increasing order, zero unless `S` has at least two elements and misses one. -/
def wVal (μ : ∀ n, 2 ≤ n → EndOp R V (Fin n)) {n : ℕ} (S : Finset (Fin n)) (v : Fin n → V) : V :=
  if h : 2 ≤ S.card ∧ 1 ≤ Sᶜ.card then
    μ (Sᶜ.card + 1) (by omega)
      (Fin.cons (μ S.card h.1 fun t => v (S.orderEmbOfFin rfl t))
        fun t => v (Sᶜ.orderEmbOfFin rfl t))
  else 0

end HyperCom

open HyperCom

variable (R) in
/-- The conditions on a family of operations to make a hypercommutative algebra: total symmetry and
the WDVV identities. -/
def IsHC (μ : ∀ n, 2 ≤ n → EndOp R V (Fin n)) : Prop :=
  (∀ n (h : 2 ≤ n) (σ : Equiv.Perm (Fin n)) (v : Fin n → V),
    μ n h (fun a => v (σ a)) = μ n h v) ∧
  (∀ n (i j k : Fin n), i ≠ j → i ≠ k → j ≠ k → ∀ v : Fin n → V,
    ∑ S ∈ univ.filter (fun S => i ∈ S ∧ j ∈ S ∧ k ∉ S), wVal V μ S v
      = ∑ S ∈ univ.filter (fun S => i ∈ S ∧ k ∈ S ∧ j ∉ S), wVal V μ S v)

variable (R) in
/-- **A hypercommutative algebra**: totally symmetric multilinear operations `μₙ` in every arity
`n ≥ 2`, satisfying the WDVV identities: for distinct inputs `i, j, k`,
`∑_{i, j ∈ S, k ∉ S} μ(μ(v_S), v_{Sᶜ}) = ∑_{i, k ∈ S, j ∉ S} μ(μ(v_S), v_{Sᶜ})`. -/
structure HCAlg where
  /-- The operations. -/
  μ : ∀ n, 2 ≤ n → EndOp R V (Fin n)
  /-- The operations are totally symmetric. -/
  symm : ∀ n (h : 2 ≤ n) (σ : Equiv.Perm (Fin n)) (v : Fin n → V),
    μ n h (fun a => v (σ a)) = μ n h v
  /-- The WDVV identities. -/
  wdvv : ∀ n (i j k : Fin n), i ≠ j → i ≠ k → j ≠ k → ∀ v : Fin n → V,
    ∑ S ∈ univ.filter (fun S => i ∈ S ∧ j ∈ S ∧ k ∉ S), wVal V μ S v
      = ∑ S ∈ univ.filter (fun S => i ∈ S ∧ k ∈ S ∧ j ∉ S), wVal V μ S v

namespace HyperCom

/-- The generator values given by a family of operations. -/
def hcVal (μ : ∀ n, 2 ≤ n → EndOp R V (Fin n)) : ∀ n, HCGen n → Und R (EndOp R V) (Fin n) :=
  fun n g => Und.of R (EndOp R V) (μ n g.two_le)

/-- **The algebra over the free operad given by a family of operations.** -/
noncomputable def hcHom (μ : ∀ n, 2 ≤ n → EndOp R V (Fin n)) : SymAlgebra R (FreeHC R) V :=
  linHomEquiv R (FreeSet.homEquiv.symm (hcVal V μ))

/-- Generator values are families of operations. -/
def hcValEquiv :
    (∀ n, HCGen n → Und R (EndOp R V) (Fin n)) ≃ (∀ n, 2 ≤ n → EndOp R V (Fin n)) where
  toFun f n h := (Und.of R (EndOp R V)).symm (f n ⟨h⟩)
  invFun := hcVal V
  left_inv _ := rfl
  right_inv _ := rfl

/-- **Algebras over the free operad** on the hypercommutative generators are families of
operations. -/
noncomputable def freeHCEquiv : SymAlgebra R (FreeHC R) V ≃ (∀ n, 2 ≤ n → EndOp R V (Fin n)) :=
  (linHomEquiv R).symm.trans (FreeSet.homEquiv.trans (hcValEquiv V))

lemma freeHCEquiv_symm (μ : ∀ n, 2 ≤ n → EndOp R V (Fin n)) :
    (freeHCEquiv V).symm μ = hcHom V μ :=
  rfl

variable {V}

lemma hcHom_single (μ : ∀ n, 2 ≤ n → EndOp R V (Fin n)) {A : Type} [Fintype A] [DecidableEq A]
    (x : Syn HCGen A) :
    (hcHom V μ).app A (Finsupp.single (Pres.mk x) 1)
      = (Und.of R (EndOp R V)).symm (Syn.eval (hcVal V μ) x) := by
  show Finsupp.lift (EndOp R V A) R (FreeSet HCGen A) _ (Finsupp.single (Pres.mk x) 1) = _
  simp
  rfl

/-- The value of a relabelled generator. -/
lemma hcHom_mono (μ : ∀ n, 2 ≤ n → EndOp R V (Fin n)) {n : ℕ} (h : 2 ≤ n)
    (σ : Equiv.Perm (Fin n)) (v : Fin n → V) :
    (hcHom V μ).app (Fin n) (mono n h σ) v = μ n h fun a => v (σ a) := by
  rw [mono, hcHom_single]
  rfl

/-- The value of a WDVV composite. -/
lemma hcHom_wTerm (μ : ∀ n, 2 ≤ n → EndOp R V (Fin n)) {n : ℕ} (S : Finset (Fin n))
    (v : Fin n → V) : (hcHom V μ).app (Fin n) (wTerm S) v = wVal V μ S v := by
  unfold wTerm wVal
  split_ifs with h
  · rw [hcHom_single]
    show EndOp.ap (map (wEquiv S) (comp 0 (Und.of R (EndOp R V) (μ _ _))
      (Und.of R (EndOp R V) (μ _ _)))) v = _
    rw [EndOp.ap_map, EndOp.ap_comp]
    show μ _ _ _ = μ _ _ _
    congr 1
    funext t
    refine Fin.cases ?_ (fun t => ?_) t
    · rw [feed_self, Fin.cons_zero]
      show μ _ _ _ = μ _ _ _
      congr 1
    · rw [feed_of_ne (Fin.succ_ne_zero t), Fin.cons_succ, wEquiv_inl]
      rfl
  · rfl

/-- **The relators vanish exactly on hypercommutative algebras.** -/
lemma rel_iff (μ : ∀ n, 2 ≤ n → EndOp R V (Fin n)) :
    (∀ n, ∀ x ∈ hcRel R n, (hcHom V μ).app (Fin n) x = 0) ↔ IsHC R V μ := by
  have hsym : ∀ n (h : 2 ≤ n) (σ : Equiv.Perm (Fin n)),
      (hcHom V μ).app (Fin n) (mono n h σ - mono n h 1) = 0 ↔
        ∀ v : Fin n → V, μ n h (fun a => v (σ a)) = μ n h v := by
    intro n h σ
    rw [map_sub, sub_eq_zero]
    refine ⟨fun H v => ?_, fun H => MultilinearMap.ext fun v => ?_⟩
    · have := congrArg (fun F : EndOp R V (Fin n) => F v) H
      simpa only [hcHom_mono, Equiv.Perm.one_apply] using this
    · rw [hcHom_mono, hcHom_mono, H]
      rfl
  have hw : ∀ n (i j k : Fin n), (hcHom V μ).app (Fin n) (wdvv i j k) = 0 ↔
      ∀ v : Fin n → V, ∑ S ∈ univ.filter (fun S => i ∈ S ∧ j ∈ S ∧ k ∉ S), wVal V μ S v
        = ∑ S ∈ univ.filter (fun S => i ∈ S ∧ k ∈ S ∧ j ∉ S), wVal V μ S v := by
    intro n i j k
    rw [wdvv, map_sub, sub_eq_zero]
    refine ⟨fun H v => ?_, fun H => MultilinearMap.ext fun v => ?_⟩
    · have := congrArg (fun F : EndOp R V (Fin n) => F v) H
      simpa only [map_sum, MultilinearMap.sum_apply, hcHom_wTerm] using this
    · simp only [map_sum, MultilinearMap.sum_apply, hcHom_wTerm]
      exact H v
  constructor
  · intro H
    refine ⟨fun n h σ => (hsym n h σ).1 (H n _ (Or.inl ⟨h, σ, rfl⟩)),
      fun n i j k hij hik hjk => (hw n i j k).1 (H n _ (Or.inr ⟨i, j, k, hij, hik, hjk, rfl⟩))⟩
  · rintro ⟨H₁, H₂⟩ n x (⟨h, σ, rfl⟩ | ⟨i, j, k, hij, hik, hjk, rfl⟩)
    · exact (hsym n h σ).2 (H₁ n h σ)
    · exact (hw n i j k).2 (H₂ n i j k hij hik hjk)

end HyperCom

open HyperCom

variable (R) in
/-- **Algebras over the hypercommutative operad are hypercommutative algebras.** -/
noncomputable def HyperComOp.algebraEquiv : SymAlgebra R (HyperComOp R) V ≃ HCAlg R V :=
  SymOperadIdeal.presHomEquiv.trans <|
    ((freeHCEquiv V).subtypeEquiv (p := fun φ => ∀ n, ∀ x ∈ hcRel R n, φ.app (Fin n) x = 0)
      (q := IsHC R V) fun φ => by
        have h := rel_iff (freeHCEquiv V φ)
        rw [← freeHCEquiv_symm, Equiv.symm_apply_apply] at h
        exact h).trans
    { toFun := fun μ => ⟨μ.1, μ.2.1, μ.2.2⟩
      invFun := fun a => ⟨a.μ, a.symm, a.wdvv⟩
      left_inv := fun _ => rfl
      right_inv := fun _ => rfl }

namespace HyperCom

variable {V}

/-- Operations of equal arities agree on corresponding inputs. -/
lemma μ_congr (μ : ∀ n, 2 ≤ n → EndOp R V (Fin n)) {m m' : ℕ} (h : m = m') (hm : 2 ≤ m)
    (hm' : 2 ≤ m') {w : Fin m → V} {w' : Fin m' → V} (hw : ∀ i, w i = w' (Fin.cast h i)) :
    μ m hm w = μ m' hm' w' := by
  subst h
  congr 1
  funext i
  exact hw i

lemma min'_pair {p q : Fin 3} {S : Finset (Fin 3)} (hS : S = {p, q}) (hpq : p < q)
    (hne : S.Nonempty) : S.min' hne = p :=
  le_antisymm (Finset.min'_le S p (by rw [hS]; simp)) (Finset.le_min' S hne p fun y hy => by
    rw [hS] at hy
    simp only [Finset.mem_insert, Finset.mem_singleton] at hy
    rcases hy with rfl | rfl
    exacts [le_rfl, hpq.le])

lemma max'_pair {p q : Fin 3} {S : Finset (Fin 3)} (hS : S = {p, q}) (hpq : p < q)
    (hne : S.Nonempty) : S.max' hne = q :=
  le_antisymm (Finset.max'_le S hne q fun y hy => by
    rw [hS] at hy
    simp only [Finset.mem_insert, Finset.mem_singleton] at hy
    rcases hy with rfl | rfl
    exacts [hpq.le, le_rfl]) (Finset.le_max' S q (by rw [hS]; simp))

/-- **A WDVV composite in arity three** is a binary operation inserted into another one. -/
lemma wVal_pair (μ : ∀ n, 2 ≤ n → EndOp R V (Fin n)) (v : Fin 3 → V) {S : Finset (Fin 3)}
    {p q r : Fin 3} (hS : S = {p, q}) (hpq : p < q) (hr : Sᶜ = {r}) :
    wVal V μ S v = μ 2 le_rfl ![μ 2 le_rfl ![v p, v q], v r] := by
  have hc : S.card = 2 := by rw [hS]; exact Finset.card_pair hpq.ne
  have hc' : Sᶜ.card = 1 := by rw [hr]; rfl
  unfold wVal
  rw [dif_pos ⟨hc.ge, hc'.ge⟩]
  refine μ_congr μ (by omega) _ _ fun t => ?_
  refine Fin.cases ?_ (fun t => ?_) t
  · rw [Fin.cons_zero]
    refine (μ_congr μ hc _ _ fun s => ?_).trans rfl
    obtain ⟨s, hs⟩ := s
    have hs' : s = 0 ∨ s = 1 := by omega
    rcases hs' with rfl | rfl
    · rw [Finset.orderEmbOfFin_zero rfl (by omega), min'_pair hS hpq]
      rfl
    · have h1 : (⟨1, hs⟩ : Fin S.card) = ⟨S.card - 1, by omega⟩ := Fin.ext (by simp; omega)
      rw [h1, Finset.orderEmbOfFin_last rfl (by omega), max'_pair hS hpq,
        show Fin.cast hc (⟨S.card - 1, by omega⟩ : Fin S.card) = 1 from Fin.ext (by simp; omega)]
      rfl
  · rw [Fin.cons_succ]
    obtain ⟨t, ht⟩ := t
    obtain rfl : t = 0 := by omega
    rw [Finset.orderEmbOfFin_zero rfl (by omega)]
    have hm : Sᶜ.min' (Finset.card_pos.mp (by omega)) = r := by
      have hall : ∀ y ∈ Sᶜ, y = r := fun y hy => by
        rw [hr] at hy
        exact Finset.mem_singleton.mp hy
      exact hall _ (Finset.min'_mem _ _)
    rw [hm]
    rfl

end HyperCom

namespace HCAlg

variable {V} (a : HCAlg R V)

/-- **The binary product** of a hypercommutative algebra. -/
def mul (x y : V) : V := a.μ 2 le_rfl ![x, y]

/-- **The product is commutative.** -/
theorem mul_comm (x y : V) : a.mul x y = a.mul y x := by
  have h := a.symm 2 le_rfl (Equiv.swap 0 1) ![x, y]
  rw [EndOp.vec_swap] at h
  exact h.symm

lemma wdvv_three (x y z : V) : a.mul (a.mul x y) z = a.mul (a.mul x z) y := by
  have h := a.wdvv 3 0 1 2 (by decide) (by decide) (by decide) ![x, y, z]
  rw [show (univ.filter fun S : Finset (Fin 3) => 0 ∈ S ∧ 1 ∈ S ∧ 2 ∉ S) = {{0, 1}} by decide,
    show (univ.filter fun S : Finset (Fin 3) => 0 ∈ S ∧ 2 ∈ S ∧ 1 ∉ S) = {{0, 2}} by decide,
    Finset.sum_singleton, Finset.sum_singleton,
    wVal_pair (p := 0) (q := 1) (r := 2) _ _ rfl (by decide) (by decide),
    wVal_pair (p := 0) (q := 2) (r := 1) _ _ rfl (by decide) (by decide)] at h
  exact h

/-- **The product is associative**: in arity three, the WDVV identity is associativity. -/
theorem mul_assoc (x y z : V) : a.mul (a.mul x y) z = a.mul x (a.mul y z) := by
  rw [a.mul_comm x (a.mul y z), a.wdvv_three y z x, a.mul_comm y x]

end HCAlg

/-! ## Commutative algebras -/

namespace HCAlg

variable (R) (A : Type v) [CommRing A] [Algebra R A]

/-- The operations of a commutative algebra: the product in arity two, zero in higher arities. -/
@[nolint unusedArguments]
noncomputable def comOps (n : ℕ) (_ : 2 ≤ n) : EndOp R A (Fin n) :=
  if n = 2 then MultilinearMap.mkPiAlgebra R (Fin n) A else 0

lemma comOps_two (v : Fin 2 → A) : comOps R A 2 le_rfl v = v 0 * v 1 := by
  simp [comOps, MultilinearMap.mkPiAlgebra_apply, Fin.prod_univ_two]

lemma comOps_of_ne {n : ℕ} (h : 2 ≤ n) (hn : n ≠ 2) : comOps R A n h = 0 := if_neg hn

lemma wVal_comOps_eq_zero {n : ℕ} (hn : 4 ≤ n) (S : Finset (Fin n)) (v : Fin n → A) :
    wVal A (comOps R A) S v = 0 := by
  unfold wVal
  split_ifs with h
  · by_cases hc : Sᶜ.card + 1 = 2
    · have hS : S.card ≠ 2 := by
        have := Finset.card_add_card_compl S
        simp only [Fintype.card_fin] at this
        omega
      rw [comOps_of_ne R A h.1 hS]
      exact MultilinearMap.map_coord_zero _ 0 (by rw [Fin.cons_zero]; rfl)
    · rw [comOps_of_ne R A _ hc]
      rfl
  · rfl

/-- **A commutative algebra is hypercommutative**, with no operations of arity at least three. -/
noncomputable def ofComm : HCAlg R A where
  μ := comOps R A
  symm n h σ v := by
    unfold comOps
    split_ifs
    · simp only [MultilinearMap.mkPiAlgebra_apply]
      exact Equiv.prod_comp σ v
    · rfl
  wdvv n i j k hij hik hjk v := by
    rcases lt_or_ge n 4 with hn | hn
    · have h3 : n = 3 := by
        have := Fintype.card_le_of_injective ![i, j, k] (by
          intro a b hab
          fin_cases a <;> fin_cases b <;> simp_all [eq_comm])
        simp only [Fintype.card_fin] at this
        omega
      subst h3
      have hcompl : ∀ p q r : Fin 3, p ≠ q → p ≠ r → q ≠ r → ({p, q} : Finset (Fin 3))ᶜ = {r} := by
        decide
      have key : ∀ (p q r : Fin 3), p ≠ q → p ≠ r → q ≠ r →
          wVal A (comOps R A) {p, q} v = v p * v q * v r := by
        intro p q r hpq hpr hqr
        rcases lt_or_gt_of_ne hpq with h | h
        · rw [wVal_pair _ _ rfl h (hcompl p q r hpq hpr hqr)]
          simp only [comOps_two, Matrix.cons_val_zero, Matrix.cons_val_one]
        · rw [Finset.pair_comm,
            wVal_pair _ _ rfl h (hcompl q p r (Ne.symm hpq) hqr hpr)]
          simp only [comOps_two, Matrix.cons_val_zero, Matrix.cons_val_one]
          ring
      have hf : ∀ (p q r : Fin 3), p ≠ q → p ≠ r → q ≠ r →
          univ.filter (fun S : Finset (Fin 3) => p ∈ S ∧ q ∈ S ∧ r ∉ S) = {{p, q}} := by
        decide
      rw [hf i j k hij hik hjk, hf i k j hik hij (Ne.symm hjk), Finset.sum_singleton,
        Finset.sum_singleton, key i j k hij hik hjk, key i k j hik hij (Ne.symm hjk)]
      ring
    · rw [Finset.sum_eq_zero fun S _ => wVal_comOps_eq_zero R A hn S v,
        Finset.sum_eq_zero fun S _ => wVal_comOps_eq_zero R A hn S v]

end HCAlg

end Algebra

end Operad
