/-
# Non-symmetric set operads by generators and relations

The planar counterpart of `Operad.SetPresentation`. `NSSyn T n` is the syntax of planar operad
expressions of arity `n` in generators `T`; `NSPres T ρ` is its quotient by the congruence
generated by the axioms of `NSSetOperad` and the relations `ρ`, and it is the non-symmetric set
operad presented by `T` and `ρ` (`NSPres.homEquiv`). Its linearization is described by the same
data (`NSPres.linHomEquiv`).
-/
import Operad.NSSet

universe u v w

namespace Operad

/-- **Planar operad expressions** in generators `T`, indexed by arity. -/
inductive NSSyn (T : ℕ → Type w) : ℕ → Type w where
  /-- The identity operation. -/
  | one : NSSyn T 1
  /-- A generator. -/
  | gen {n : ℕ} (g : T n) : NSSyn T n
  /-- Positional partial composition. -/
  | comp (a b : ℕ) {n : ℕ} (x : NSSyn T (a + 1 + b)) (y : NSSyn T n) : NSSyn T (a + n + b)

namespace NSSyn

variable {T : ℕ → Type w}

/-- **The congruence generated by the axioms and the relations `ρ`.** -/
inductive Rel (ρ : ∀ n : ℕ, NSSyn T n → NSSyn T n → Prop) : {n : ℕ} → NSSyn T n → NSSyn T n → Prop
  | of {n : ℕ} {x y : NSSyn T n} : ρ n x y → Rel ρ x y
  | refl {n : ℕ} (x : NSSyn T n) : Rel ρ x x
  | symm {n : ℕ} {x y : NSSyn T n} : Rel ρ x y → Rel ρ y x
  | trans {n : ℕ} {x y z : NSSyn T n} : Rel ρ x y → Rel ρ y z → Rel ρ x z
  | comp (a b : ℕ) {n : ℕ} {x x' : NSSyn T (a + 1 + b)} {y y' : NSSyn T n} :
      Rel ρ x x' → Rel ρ y y' → Rel ρ (comp a b x y) (comp a b x' y')
  | comp_one_right (a b : ℕ) (x : NSSyn T (a + 1 + b)) : Rel ρ (comp a b x one) x
  | comp_one_left {n : ℕ} (x : NSSyn T n) :
      Rel ρ (reindexS (NSSyn T) (by omega) (comp 0 0 one x)) x
  | assoc_seq (a b c d : ℕ) {p : ℕ} (x : NSSyn T (a + 1 + b)) (y : NSSyn T (c + 1 + d))
      (z : NSSyn T p) :
      Rel ρ (reindexS (NSSyn T) (by omega)
          (comp (a + c) (d + b) (reindexS (NSSyn T) (by omega) (comp a b x y)) z))
        (comp a b x (comp c d y z))
  | assoc_par (a b c : ℕ) {n p : ℕ} (x : NSSyn T (a + 1 + b + 1 + c)) (y : NSSyn T n)
      (z : NSSyn T p) :
      Rel ρ (reindexS (NSSyn T) (by omega)
          (comp (a + n + b) c
            (reindexS (NSSyn T) (by omega)
              (comp a (b + 1 + c) (reindexS (NSSyn T) (by omega) x) y)) z))
        (comp a (b + p + c) (reindexS (NSSyn T) (by omega) (comp (a + 1 + b) c x z)) y)

lemma Rel.reindexS {ρ : ∀ n : ℕ, NSSyn T n → NSSyn T n → Prop} {m n : ℕ} (h : m = n)
    {x y : NSSyn T m} (hxy : Rel ρ x y) :
    Rel ρ (reindexS (NSSyn T) h x) (reindexS (NSSyn T) h y) := by
  subst h
  exact hxy

variable {S : ℕ → Type v} [NSSetOperad S]

/-- **Evaluate an expression** in a non-symmetric set operad. -/
def eval (f : ∀ n, T n → S n) : {n : ℕ} → NSSyn T n → S n
  | _, .one => NSSetOperad.one
  | _, .gen g => f _ g
  | _, .comp a b x y => NSSetOperad.comp a b (eval f x) (eval f y)

variable (f : ∀ n, T n → S n)

@[simp] lemma eval_one : eval f (one : NSSyn T 1) = NSSetOperad.one := rfl

@[simp] lemma eval_gen {n : ℕ} (g : T n) : eval f (gen g) = f n g := rfl

@[simp] lemma eval_comp (a b : ℕ) {n : ℕ} (x : NSSyn T (a + 1 + b)) (y : NSSyn T n) :
    eval f (comp a b x y) = NSSetOperad.comp a b (eval f x) (eval f y) := rfl

lemma eval_reindexS {m n : ℕ} (h : m = n) (x : NSSyn T m) :
    eval f (reindexS (NSSyn T) h x) = reindexS S h (eval f x) := by
  subst h
  rfl

/-- Evaluation respects the axioms, and every relation it respects. -/
theorem eval_eq_of_rel {ρ : ∀ n : ℕ, NSSyn T n → NSSyn T n → Prop}
    (hf : ∀ {n : ℕ} (x y : NSSyn T n), ρ n x y → eval f x = eval f y)
    {n : ℕ} {x y : NSSyn T n} (h : Rel ρ x y) : eval f x = eval f y := by
  induction h with
  | of h => exact hf _ _ h
  | refl => rfl
  | symm _ ih => exact ih.symm
  | trans _ _ ih ih' => exact ih.trans ih'
  | comp a b _ _ ih ih' => simp only [eval_comp, ih, ih']
  | comp_one_right a b x => exact NSSetOperad.comp_one_right a b (eval f x)
  | comp_one_left x =>
    rw [eval_reindexS]
    exact NSSetOperad.comp_one_left (eval f x)
  | assoc_seq a b c d x y z =>
    simp only [eval_reindexS, eval_comp]
    exact NSSetOperad.comp_assoc_seq a b c d (eval f x) (eval f y) (eval f z)
  | assoc_par a b c x y z =>
    simp only [eval_reindexS, eval_comp]
    exact NSSetOperad.comp_assoc_par a b c (eval f x) (eval f y) (eval f z)

end NSSyn

/-! ## The presented operad -/

/-- **The non-symmetric set operad presented by `T` and `ρ`.** -/
def NSPres (T : ℕ → Type w) (ρ : ∀ n : ℕ, NSSyn T n → NSSyn T n → Prop) : ℕ → Type w :=
  fun n => Quot (NSSyn.Rel ρ (n := n))

namespace NSPres

variable {T : ℕ → Type w} {ρ : ∀ n : ℕ, NSSyn T n → NSSyn T n → Prop}

/-- The class of an expression. -/
abbrev mk {n : ℕ} (x : NSSyn T n) : NSPres T ρ n := Quot.mk _ x

lemma mk_surjective {n : ℕ} : Function.Surjective (mk (ρ := ρ) (n := n)) := Quot.exists_rep

/-- A relation holds in the presented operad. -/
lemma mk_eq_mk_of_rel {n : ℕ} {x y : NSSyn T n} (h : ρ n x y) : mk (ρ := ρ) x = mk y :=
  Quot.sound (.of h)

lemma reindexS_mk {m n : ℕ} (h : m = n) (x : NSSyn T m) :
    reindexS (NSPres T ρ) h (mk x) = mk (reindexS (NSSyn T) h x) := by
  subst h
  rfl

/-- Composition of classes. -/
def compFn (a b : ℕ) {n : ℕ} : NSPres T ρ (a + 1 + b) → NSPres T ρ n → NSPres T ρ (a + n + b) :=
  Quot.map₂ (NSSyn.comp a b) (fun x _ _ h => .comp a b (.refl x) h)
    (fun _ _ y h => .comp a b h (.refl y))

@[simp] lemma compFn_mk (a b : ℕ) {n : ℕ} (x : NSSyn T (a + 1 + b)) (y : NSSyn T n) :
    compFn (ρ := ρ) a b (mk x) (mk y) = mk (.comp a b x y) := rfl

instance instNSSetOperad : NSSetOperad (NSPres T ρ) where
  one := mk .one
  comp a b _ := compFn a b
  comp_one_right a b := by
    rintro ⟨x⟩
    exact Quot.sound (.comp_one_right a b x)
  comp_one_left := by
    rintro _ ⟨x⟩
    exact (reindexS_mk _ _).trans (Quot.sound (NSSyn.Rel.comp_one_left x))
  comp_assoc_seq a b c d _ := by
    rintro ⟨x⟩ ⟨y⟩ ⟨z⟩
    show reindexS _ _ (compFn _ _ (reindexS _ _ (mk (NSSyn.comp a b x y))) (mk z)) = _
    rw [reindexS_mk]
    exact (reindexS_mk _ _).trans (Quot.sound (NSSyn.Rel.assoc_seq a b c d x y z))
  comp_assoc_par a b c _ _ := by
    rintro ⟨x⟩ ⟨y⟩ ⟨z⟩
    simp only [reindexS_mk, compFn_mk]
    exact Quot.sound (NSSyn.Rel.assoc_par a b c x y z)

@[simp] lemma comp_mk (a b : ℕ) {n : ℕ} (x : NSSyn T (a + 1 + b)) (y : NSSyn T n) :
    NSSetOperad.comp a b (mk (ρ := ρ) x) (mk y) = mk (.comp a b x y) := rfl

/-- A generator, in the presented operad. -/
def gen {n : ℕ} (g : T n) : NSPres T ρ n := mk (.gen g)

variable {S : ℕ → Type v} [NSSetOperad S]

/-- The condition for generator values to define a morphism out of `NSPres T ρ`. -/
def Respects (ρ : ∀ n : ℕ, NSSyn T n → NSSyn T n → Prop) (f : ∀ n, T n → S n) : Prop :=
  ∀ {n : ℕ} (x y : NSSyn T n), ρ n x y → NSSyn.eval f x = NSSyn.eval f y

/-- **The morphism defined by generator values that respect the relations.** -/
def lift (f : ∀ n, T n → S n) (hf : Respects ρ f) : NSSetOperadHom (NSPres T ρ) S where
  app _ := Quot.lift (NSSyn.eval f) (fun _ _ h => NSSyn.eval_eq_of_rel f hf h)
  app_one := rfl
  app_comp _ _ _ x y := Quot.inductionOn x fun _ => Quot.inductionOn y fun _ => rfl

@[simp] lemma lift_mk (f : ∀ n, T n → S n) (hf : Respects ρ f) {n : ℕ} (x : NSSyn T n) :
    (lift f hf).app n (mk x) = NSSyn.eval f x := rfl

@[simp] lemma lift_gen (f : ∀ n, T n → S n) (hf : Respects ρ f) {n : ℕ} (g : T n) :
    (lift f hf).app n (gen g) = f n g := rfl

/-- A morphism out of `NSPres T ρ` is its values on generators, extended. -/
lemma app_mk (φ : NSSetOperadHom (NSPres T ρ) S) {n : ℕ} (x : NSSyn T n) :
    φ.app n (mk x) = NSSyn.eval (fun _ g => φ.app _ (gen g)) x := by
  induction x with
  | one => exact φ.app_one
  | gen g => rfl
  | comp a b x y ihx ihy => rw [NSSyn.eval_comp, ← ihx, ← ihy, ← φ.app_comp]; rfl

/-- **Morphisms out of a presented operad are determined by the generators.** -/
theorem hom_ext {φ ψ : NSSetOperadHom (NSPres T ρ) S}
    (h : ∀ (n : ℕ) (g : T n), φ.app _ (gen g) = ψ.app _ (gen g)) : φ = ψ := by
  ext n x
  obtain ⟨x, rfl⟩ := mk_surjective x
  rw [app_mk, app_mk]
  congr 1
  funext n g
  exact h n g

/-- The generator values of a morphism respect the relations. -/
lemma respects_app (φ : NSSetOperadHom (NSPres T ρ) S) :
    Respects ρ (fun _ g => φ.app _ (gen g)) := by
  intro n x y h
  rw [← app_mk, ← app_mk, mk_eq_mk_of_rel h]

/-- **The universal property of a presented non-symmetric set operad.** -/
def homEquiv : NSSetOperadHom (NSPres T ρ) S ≃ {f : ∀ n, T n → S n // Respects ρ f} where
  toFun φ := ⟨fun _ g => φ.app _ (gen g), respects_app φ⟩
  invFun f := lift f.1 f.2
  left_inv _ := hom_ext fun _ _ => rfl
  right_inv _ := rfl

end NSPres

end Operad
