/-
# The presentation of `Perm`

Chapoton's operad `Perm` of permutative algebras is the linearization of the set operad of pointed
inputs (`PointedSet.linPermIso`). This file proves that it is presented by one binary operation
`ν`, without symmetries, and the two permutative relations

  `ν(ν(x, y), z) = ν(x, ν(y, z))`,   `ν(x, ν(y, z)) = ν(x, ν(z, y))`

(`PermElt`): in any set operad such a `ν` extends uniquely to a morphism out of the pointed sets
(`PermElt.lift`, `PointedSet.homEquiv`), and in any operad in modules to a morphism out of `Perm`
(`Perm.homEquiv`).

The extension sends the point `a` of `A` to the input `a` with every other input adjoined through
`ν`, `ν(⋯ν(ν(1, x), y)⋯, z)` (`PermElt.psi`). Its well-definedness is the adjoining calculus:

* **adjoining does not depend on the order** (`PermElt.adj_perm`): two inputs adjoined through `ν`
  commute, `ν(ν(Y, a), b) = ν(ν(Y, b), a)` (`PermElt.nu_nu_comm`), and the symmetric group is
  generated by adjacent transpositions, so `adjN X N` adjoins a finite set `N`;
* adjoining is compatible with relabelling, with adjoining in batches, with composing into the
  inputs of `X`, and `ν` passes through it (`adjN_adjN`, `comp_inl_adjN`, `bin_nu_adjN`).

The composition law (`PermElt.psi_comp`) then has two cases: composing at the point replaces it by
the normal form composed in, and composing at an adjoined input adjoins the inputs composed in.
-/
import Operad.SetHadamard
import Operad.ComSet

universe u w

namespace Operad

open Sym SetOperad

/-! ## A permutative binary element, and adjoining inputs through it -/

/-- **A permutative binary element**: `ν(ν(x, y), z) = ν(x, ν(y, z))` and
`ν(x, ν(y, z)) = ν(x, ν(z, y))`. -/
structure PermElt (S : (A : Type) → [Fintype A] → [DecidableEq A] → Type*) [SetOperad S] where
  /-- The binary element. -/
  nu : S (Fin 2)
  r2a : IsAssoc nu
  r2b : bin nu one (bin nu one one) = bin nu one (bin (map (Equiv.swap 0 1) nu) one one)

namespace PermElt

section Equivs

variable {C : Type}

/-- The relabelling exchanging the two adjoined inputs. -/
def swapEquiv (C A B : Type) : (C ⊕ B) ⊕ A ≃ (C ⊕ A) ⊕ B where
  toFun x :=
    match x with
    | Sum.inl (Sum.inl c) => Sum.inl (Sum.inl c)
    | Sum.inl (Sum.inr b) => Sum.inr b
    | Sum.inr a => Sum.inl (Sum.inr a)
  invFun x :=
    match x with
    | Sum.inl (Sum.inl c) => Sum.inl (Sum.inl c)
    | Sum.inl (Sum.inr a) => Sum.inr a
    | Sum.inr b => Sum.inl (Sum.inr b)
  left_inv := by rintro ((c | b) | a) <;> rfl
  right_inv := by rintro ((c | a) | b) <;> rfl

/-- The relabelling adding one more adjoined input. -/
def snocAdj (C : Type) (k : ℕ) : (C ⊕ Fin k) ⊕ Unit ≃ C ⊕ Fin (k + 1) :=
  (Equiv.sumAssoc C (Fin k) Unit).trans (Equiv.sumCongr (Equiv.refl C) (snocEquiv k))

@[simp] lemma snocAdj_inl_inl (k : ℕ) (c : C) :
    snocAdj C k (Sum.inl (Sum.inl c)) = Sum.inl c := rfl

@[simp] lemma snocAdj_inl_inr (k : ℕ) (j : Fin k) :
    snocAdj C k (Sum.inl (Sum.inr j)) = Sum.inr j.castSucc := rfl

@[simp] lemma snocAdj_inr (k : ℕ) (u : Unit) :
    snocAdj C k (Sum.inr u) = Sum.inr (Fin.last k) := rfl

/-- The relabelling adjoining `k` and then `l` inputs. -/
def addEquiv (C : Type) (k l : ℕ) : (C ⊕ Fin k) ⊕ Fin l ≃ C ⊕ Fin (k + l) :=
  (Equiv.sumAssoc C (Fin k) (Fin l)).trans (Equiv.sumCongr (Equiv.refl C) finSumFinEquiv)

end Equivs

variable {S : (A : Type) → [Fintype A] → [DecidableEq A] → Type*} [SetOperad S] (P : PermElt S)
  {A B C D : Type} [Fintype A] [DecidableEq A] [Fintype B] [DecidableEq B] [Fintype C]
  [DecidableEq C] [Fintype D] [DecidableEq D]

lemma nu_assoc (x : S A) (y : S B) (z : S C) :
    bin P.nu (bin P.nu x y) z = map (Equiv.sumAssoc A B C).symm (bin P.nu x (bin P.nu y z)) :=
  eq_map_symm_of_map_eq (bin_assoc_of P.r2a x y z)

lemma nu_swap (x : S A) (y : S B) (z : S C) :
    bin P.nu x (bin P.nu y z)
      = map (Equiv.sumCongr (Equiv.refl A) (Equiv.sumComm C B)) (bin P.nu x (bin P.nu z y)) := by
  rw [bin_right_of P.r2b x y z, bin_swap, bin_map_right]

/-- **Two inputs adjoined through `ν` commute**: `ν(ν(Y, a), b) = ν(ν(Y, b), a)`. -/
lemma nu_nu_comm (Y : S C) (a : S A) (b : S B) :
    bin P.nu (bin P.nu Y a) b = map (swapEquiv C A B) (bin P.nu (bin P.nu Y b) a) := by
  rw [P.nu_assoc Y a b, P.nu_swap Y a b, P.nu_assoc Y b a]
  simp only [map_map]
  refine map_congr (fun x => ?_) _
  rcases x with c | (b | a) <;> rfl

/-- **Adjoin `k` inputs through `ν`**: `ν(⋯ν(ν(X, 1), 1)⋯, 1)`. -/
def adj (X : S C) : (k : ℕ) → S (C ⊕ Fin k)
  | 0 => map (Equiv.sumEmpty C (Fin 0)).symm X
  | k + 1 => map (snocAdj C k) (bin P.nu (adj X k) one)

lemma adj_zero (X : S C) : P.adj X 0 = map (Equiv.sumEmpty C (Fin 0)).symm X := rfl

lemma adj_succ (X : S C) (k : ℕ) :
    P.adj X (k + 1) = map (snocAdj C k) (bin P.nu (P.adj X k) one) := rfl

/-- Exchanging the last two adjoined inputs. -/
lemma adj_swap_last (X : S C) (k : ℕ) :
    map (Equiv.sumCongr (Equiv.refl C) (Equiv.swap (Fin.last k).castSucc (Fin.last (k + 1))))
      (P.adj X (k + 2)) = P.adj X (k + 2) := by
  rw [adj_succ, adj_succ, bin_map_left]
  conv_lhs => rw [P.nu_nu_comm]
  simp only [map_map]
  refine map_congr (fun x => ?_) _
  rcases x with ((c | j) | ⟨⟩) | ⟨⟩
  · rfl
  · show Sum.inr (Equiv.swap _ _ j.castSucc.castSucc) = Sum.inr j.castSucc.castSucc
    rw [Equiv.swap_apply_of_ne_of_ne]
    · simp [Fin.ext_iff]
      omega
    · simp [Fin.ext_iff]
      omega
  · show Sum.inr (Equiv.swap _ _ (Fin.last (k + 1))) = Sum.inr (Fin.last k).castSucc
    rw [Equiv.swap_apply_right]
  · show Sum.inr (Equiv.swap _ _ (Fin.last k).castSucc) = Sum.inr (Fin.last (k + 1))
    rw [Equiv.swap_apply_left]

/-- **The adjoined inputs can be permuted**: adjoining does not depend on the order. -/
theorem adj_perm (X : S C) : ∀ (k : ℕ) (σ : Equiv.Perm (Fin k)),
    map (Equiv.sumCongr (Equiv.refl C) σ) (P.adj X k) = P.adj X k
  | 0, σ => map_eq_self (fun x => by rcases x with c | j; rfl; exact j.elim0) _
  | k + 1, σ => by
    have key : ∀ i : Fin k, map (Equiv.sumCongr (Equiv.refl C) (Equiv.swap i.castSucc i.succ))
        (P.adj X (k + 1)) = P.adj X (k + 1) := by
      intro i
      by_cases hi : (i : ℕ) + 1 < k
      · have e : ∀ x, (Equiv.sumCongr (Equiv.refl C) (Equiv.swap i.castSucc i.succ))
            (snocAdj C k x) = snocAdj C k (Equiv.sumCongr (Equiv.sumCongr (Equiv.refl C)
              (Equiv.swap (⟨i, by omega⟩ : Fin k) ⟨i + 1, hi⟩)) (Equiv.refl Unit) x) := by
          have h1 : i.castSucc = (⟨i, by omega⟩ : Fin k).castSucc := Fin.ext rfl
          have h2 : i.succ = (⟨i + 1, hi⟩ : Fin k).castSucc := Fin.ext rfl
          rintro ((c | j) | ⟨⟩)
          · rfl
          · show Sum.inr (Equiv.swap _ _ j.castSucc) = Sum.inr (Equiv.swap _ _ j).castSucc
            rw [h1, h2]
            exact congrArg Sum.inr ((Fin.castSucc_injective _).swap_apply _ _ _)
          · show Sum.inr (Equiv.swap _ _ (Fin.last k)) = Sum.inr (Fin.last k)
            rw [Equiv.swap_apply_of_ne_of_ne] <;>
              simp only [ne_eq, Fin.ext_iff, Fin.val_last, Fin.val_castSucc, Fin.val_succ] <;>
              omega
        rw [adj_succ, map_map, map_congr (f := (Equiv.sumCongr (Equiv.sumCongr (Equiv.refl C)
          (Equiv.swap (⟨i, by omega⟩ : Fin k) ⟨i + 1, hi⟩)) (Equiv.refl Unit)).trans
          (snocAdj C k)) e, ← map_map, ← bin_map_left, adj_perm X k]
      · obtain ⟨m, rfl⟩ : ∃ m, k = m + 1 := ⟨k - 1, by have := i.isLt; omega⟩
        obtain rfl : i = Fin.last m := Fin.ext (by simp only [Fin.val_last]; omega)
        exact P.adj_swap_last X m
    have hσ : σ ∈ Submonoid.closure
        (Set.range fun i : Fin k => Equiv.swap i.castSucc i.succ) := by
      rw [Equiv.Perm.mclosure_swap_castSucc_succ]
      exact Submonoid.mem_top σ
    induction hσ using Submonoid.closure_induction with
    | mem x hx =>
      obtain ⟨i, rfl⟩ := hx
      exact key i
    | one => exact map_eq_self (fun x => by rcases x with c | j <;> rfl) _
    | mul x y _ _ hx hy =>
      rw [show Equiv.sumCongr (Equiv.refl C) (x * y)
          = (Equiv.sumCongr (Equiv.refl C) y).trans (Equiv.sumCongr (Equiv.refl C) x) by
        ext z; rcases z with c | j <;> rfl, map_trans, hy, hx]

/-! ### Adjoining a finite set of inputs -/

/-- **Adjoin the inputs `N` through `ν`**, in any order (`adjN_eq`). -/
def adjN (X : S C) (N : Type) [Fintype N] [DecidableEq N] : S (C ⊕ N) :=
  Trunc.lift (fun e : N ≃ Fin (Fintype.card N) =>
      map (Equiv.sumCongr (Equiv.refl C) e.symm) (P.adj X (Fintype.card N)))
    (fun e f => by
      dsimp only
      conv_rhs => rw [← P.adj_perm X _ (e.symm.trans f)]
      rw [map_map]
      exact map_congr (fun x => by rcases x with c | j <;> simp) _)
    (Fintype.truncEquivFin N)

/-- `adjN`, along any ordering of the adjoined inputs. -/
lemma adjN_eq (X : S C) {N : Type} [Fintype N] [DecidableEq N] {k : ℕ} (e : N ≃ Fin k) :
    P.adjN X N = map (Equiv.sumCongr (Equiv.refl C) e.symm) (P.adj X k) := by
  obtain rfl : k = Fintype.card N := by simpa using (Fintype.card_congr e).symm
  unfold adjN
  induction Fintype.truncEquivFin N using Trunc.induction_on with
  | h f =>
    show map (Equiv.sumCongr (Equiv.refl C) f.symm) (P.adj X _) = _
    conv_rhs => rw [← P.adj_perm X _ (f.symm.trans e)]
    rw [map_map]
    exact map_congr (fun x => by rcases x with c | j <;> simp) _

lemma adj_map_left {C' : Type} [Fintype C'] [DecidableEq C'] (σ : C ≃ C') (X : S C) :
    ∀ k, P.adj (map σ X) k = map (Equiv.sumCongr σ (Equiv.refl (Fin k))) (P.adj X k)
  | 0 => by
    rw [adj_zero, adj_zero, map_map, map_map]
    exact map_congr (fun c => by rfl) _
  | k + 1 => by
    rw [adj_succ, adj_succ, adj_map_left σ X k, bin_map_left, map_map, map_map]
    exact map_congr (fun x => by rcases x with (c | j) | ⟨⟩ <;> rfl) _

/-- Relabelling the inputs of `X`. -/
lemma adjN_map_left {C' : Type} [Fintype C'] [DecidableEq C'] (σ : C ≃ C') (X : S C)
    (N : Type) [Fintype N] [DecidableEq N] :
    P.adjN (map σ X) N = map (Equiv.sumCongr σ (Equiv.refl N)) (P.adjN X N) := by
  rw [P.adjN_eq _ (Fintype.equivFin N), P.adjN_eq _ (Fintype.equivFin N), adj_map_left,
    map_map, map_map]
  exact map_congr (fun x => by rcases x with c | j <;> rfl) _

/-- Relabelling the adjoined inputs. -/
lemma map_adjN_right (X : S C) {N N' : Type} [Fintype N] [DecidableEq N] [Fintype N']
    [DecidableEq N'] (τ : N ≃ N') :
    map (Equiv.sumCongr (Equiv.refl C) τ) (P.adjN X N) = P.adjN X N' := by
  rw [P.adjN_eq _ (Fintype.equivFin N), P.adjN_eq _ (τ.symm.trans (Fintype.equivFin N)),
    map_map]
  exact map_congr (fun x => by rcases x with c | j <;> simp) _

/-- Adjoining nothing. -/
lemma adjN_isEmpty (X : S C) (N : Type) [Fintype N] [DecidableEq N] [IsEmpty N] :
    P.adjN X N = map (Equiv.sumEmpty C N).symm X := by
  rw [P.adjN_eq _ (Equiv.equivOfIsEmpty N (Fin 0)), adj_zero, map_map]
  exact map_congr (fun c => by rfl) _

/-- Adjoining one input. -/
lemma adjN_unit (X : S C) : P.adjN X Unit = bin P.nu X one := by
  rw [P.adjN_eq _ unitFinOne, adj_succ, adj_zero, bin_map_left, map_map, map_map]
  exact map_eq_self (fun x => by rcases x with c | ⟨⟩ <;> rfl) _

lemma adj_add (X : S C) (k : ℕ) :
    ∀ l, P.adj X (k + l) = map (addEquiv C k l) (P.adj (P.adj X k) l)
  | 0 => by
    rw [adj_zero, map_map]
    exact (map_eq_self (fun x => by
      rcases x with c | j
      · rfl
      · exact congrArg Sum.inr (Fin.ext rfl)) _).symm
  | l + 1 => by
    show P.adj X (k + l + 1) = _
    rw [adj_succ, adj_add X k l, adj_succ, bin_map_left, map_map, map_map]
    refine map_congr (fun x => ?_) _
    rcases x with ((c | j) | j) | ⟨⟩
    · rfl
    · exact congrArg Sum.inr (Fin.ext (by simp))
    · exact congrArg Sum.inr (Fin.ext (by simp))
    · exact congrArg Sum.inr (Fin.ext (by simp))

/-- **Adjoining in two batches.** -/
lemma adjN_sum (X : S C) (N M : Type) [Fintype N] [DecidableEq N] [Fintype M] [DecidableEq M] :
    P.adjN X (N ⊕ M) = map (Equiv.sumAssoc C N M) (P.adjN (P.adjN X N) M) := by
  rw [P.adjN_eq _ ((Equiv.sumCongr (Fintype.equivFin N) (Fintype.equivFin M)).trans
      finSumFinEquiv), P.adjN_eq _ (Fintype.equivFin M), P.adjN_eq _ (Fintype.equivFin N),
    adj_map_left, adj_add, map_map, map_map, map_map]
  refine map_congr (fun x => ?_) _
  rcases x with (c | j) | j
  · rfl
  · simp [addEquiv]
  · simp [addEquiv]

lemma adjN_adjN (X : S C) (N M : Type) [Fintype N] [DecidableEq N] [Fintype M]
    [DecidableEq M] :
    P.adjN (P.adjN X N) M = map (Equiv.sumAssoc C N M).symm (P.adjN X (N ⊕ M)) :=
  eq_map_symm_of_map_eq (P.adjN_sum X N M).symm

/-- Adjoining all inputs but one, then that one. -/
lemma adjN_split (X : S C) {N : Type} [Fintype N] [DecidableEq N] (n : N) :
    P.adjN X N = map ((Equiv.sumAssoc C (Without N n) Unit).trans
      (Equiv.sumCongr (Equiv.refl C) (rightUnitEquiv n)))
      (bin P.nu (P.adjN X (Without N n)) one) := by
  rw [← P.map_adjN_right X (rightUnitEquiv n), P.adjN_sum, P.adjN_unit, map_map]

/-! ### Composing into an adjoined form -/

/-- **Composing into an input of `X`**, after adjoining. -/
lemma comp_inl_adj (c : C) (X : S C) (y : S B) :
    ∀ k, comp (Sum.inl c) (P.adj X k) y = map (binLeftEquiv c) (P.adj (comp c X y) k)
  | 0 => by
    rw [adj_zero, adj_zero, comp_map_left_of _ (i := c) ?h0, map_map]
    · exact map_congr (fun x => by rcases x with a | b <;> rfl) _
    · rfl
  | k + 1 => by
    rw [adj_succ, adj_succ, comp_map_left_of _ (i := Sum.inl (Sum.inl c)) ?h1, comp_inl_bin,
      comp_inl_adj c X y k, bin_map_left]
    · simp only [map_map]
      refine map_congr (fun x => ?_) _
      rcases x with ((a | b) | j) | ⟨⟩ <;> rfl
    · rfl

lemma comp_inl_adjN (c : C) (X : S C) (y : S B) (N : Type) [Fintype N] [DecidableEq N] :
    comp (Sum.inl c) (P.adjN X N) y = map (binLeftEquiv c) (P.adjN (comp c X y) N) := by
  rw [P.adjN_eq _ (Fintype.equivFin N), P.adjN_eq _ (Fintype.equivFin N),
    comp_map_left_of _ (i := Sum.inl c) ?h, comp_inl_adj, map_map, map_map]
  · exact map_congr (fun x => by rcases x with (a | b) | j <;> rfl) _
  · rfl

/-- **Absorption into the adjoining**: a binary element `g` with `ν(g(x, y), z) = g(x, ν(y, z))`
passes through the adjoined inputs. -/
lemma bin_adj_of {g : S (Fin 2)}
    (hg : map (Equiv.sumAssoc Unit Unit Unit) (bin P.nu (bin g one one) one)
      = bin g one (bin P.nu one one)) (Y : S D) (W : S C) :
    ∀ k, bin g Y (P.adj W k) = map (Equiv.sumAssoc D C (Fin k)) (P.adj (bin g Y W) k)
  | 0 => by
    rw [adj_zero, adj_zero, bin_map_right, map_map]
    exact map_congr (fun x => by rcases x with a | c <;> rfl) _
  | k + 1 => by
    rw [adj_succ, adj_succ, bin_map_right, ← bin_assoc_of hg Y (P.adj W k) one,
      bin_adj_of hg Y W k, bin_map_left]
    simp only [map_map]
    refine map_congr (fun x => ?_) _
    rcases x with ((d | c) | j) | ⟨⟩ <;> rfl

lemma bin_adjN_of {g : S (Fin 2)}
    (hg : map (Equiv.sumAssoc Unit Unit Unit) (bin P.nu (bin g one one) one)
      = bin g one (bin P.nu one one)) (Y : S D) (W : S C) (N : Type) [Fintype N]
    [DecidableEq N] :
    bin g Y (P.adjN W N) = map (Equiv.sumAssoc D C N) (P.adjN (bin g Y W) N) := by
  rw [P.adjN_eq _ (Fintype.equivFin N), P.adjN_eq _ (Fintype.equivFin N), bin_map_right,
    P.bin_adj_of hg, map_map, map_map]
  exact map_congr (fun x => by rcases x with (d | c) | j <;> rfl) _

/-- `ν` passes through the adjoining. -/
lemma bin_nu_adjN (Y : S D) (W : S C) (N : Type) [Fintype N] [DecidableEq N] :
    bin P.nu Y (P.adjN W N) = map (Equiv.sumAssoc D C N) (P.adjN (bin P.nu Y W) N) :=
  P.bin_adjN_of P.r2a Y W N

/-! ### Transport along morphisms -/

variable {T : (A : Type) → [Fintype A] → [DecidableEq A] → Type*} [SetOperad T]

/-- Transport along a morphism. -/
def map (φ : SetOperadHom S T) : PermElt T where
  nu := φ.app _ P.nu
  r2a := isAssoc_app P.r2a φ
  r2b := by
    simpa only [SetOperadHom.app_map, SetOperadHom.app_bin, SetOperadHom.app_one]
      using congrArg (φ.app _) P.r2b

lemma app_adj (φ : SetOperadHom S T) (X : S C) :
    ∀ k, φ.app _ (P.adj X k) = (P.map φ).adj (φ.app _ X) k
  | 0 => by rw [adj_zero, adj_zero, φ.app_map]
  | k + 1 => by
    rw [adj_succ, adj_succ, φ.app_map, φ.app_bin, φ.app_one, app_adj φ X k]
    rfl

/-- **Morphisms carry adjoined forms to adjoined forms.** -/
lemma app_adjN (φ : SetOperadHom S T) (X : S C) (N : Type) [Fintype N] [DecidableEq N] :
    φ.app _ (P.adjN X N) = (P.map φ).adjN (φ.app _ X) N := by
  rw [P.adjN_eq _ (Fintype.equivFin N), (P.map φ).adjN_eq _ (Fintype.equivFin N), φ.app_map,
    app_adj]

end PermElt

/-! ## The universal property of the pointed sets -/

namespace PermElt

/-- The inputs of `A`: the point `a`, then the others. -/
def pointEquiv {A : Type} [DecidableEq A] (a : A) : Unit ⊕ Without A a ≃ A :=
  (Equiv.sumComm Unit (Without A a)).trans (rightUnitEquiv a)

@[simp] lemma pointEquiv_inl {A : Type} [DecidableEq A] (a : A) (u : Unit) :
    pointEquiv a (Sum.inl u) = a := rfl

@[simp] lemma pointEquiv_inr {A : Type} [DecidableEq A] (a : A) (b : Without A a) :
    pointEquiv a (Sum.inr b) = b.1 := rfl

variable {S : (A : Type) → [Fintype A] → [DecidableEq A] → Type*} [SetOperad S] (P : PermElt S)
  {A B : Type} [Fintype A] [DecidableEq A] [Fintype B] [DecidableEq B]

/-- **The normal form of the point `a`**: the input `a`, with the other inputs adjoined through
`ν`. -/
def psi (A : Type) [Fintype A] [DecidableEq A] (a : A) : S A :=
  SetOperad.map (pointEquiv a) (P.adjN one (Without A a))

/-- **The normal form**, along any decomposition of the inputs into the point and the others. -/
theorem psi_eq {N : Type} [Fintype N] [DecidableEq N] (a : A) (E : Unit ⊕ N ≃ A)
    (hE : E (Sum.inl ()) = a) : P.psi A a = SetOperad.map E (P.adjN one N) := by
  have hne : ∀ n, E (Sum.inr n) ≠ a := fun n h => by
    rw [← hE] at h
    exact Sum.inr_ne_inl (E.injective h)
  let τ : N ≃ Without A a := Equiv.ofBijective (fun n => ⟨E (Sum.inr n), hne n⟩)
    ⟨fun n m h => Sum.inr_injective (E.injective (congrArg Subtype.val h)), fun ⟨x, hx⟩ => by
      rcases hy : E.symm x with u | n
      · exact absurd (show x = a by rw [← hE, ← hy, Equiv.apply_symm_apply]) hx
      · exact ⟨n, Subtype.ext (show E (Sum.inr n) = x by rw [← hy, Equiv.apply_symm_apply])⟩⟩
  rw [psi, ← P.map_adjN_right one τ, map_map]
  refine map_congr (fun x => ?_) _
  rcases x with ⟨⟩ | n
  · exact hE.symm
  · rfl

/-- **The normal forms are invariant under relabelling.** -/
theorem psi_map {A' : Type} [Fintype A'] [DecidableEq A'] (e : A ≃ A') (a : A) :
    P.psi A' (e a) = SetOperad.map e (P.psi A a) := by
  rw [P.psi_eq (e a) ((pointEquiv a).trans e) rfl, psi, map_map]

lemma psi_one : P.psi Unit () = one := by
  rw [P.psi_eq () (Equiv.sumEmpty Unit Empty) rfl, P.adjN_isEmpty, map_map]
  exact map_eq_self (fun _ => rfl) _

lemma psi_nu : P.psi (Fin 2) 0 = P.nu := by
  rw [P.psi_eq 0 finTwoSum.symm rfl, P.adjN_unit, bin_one_one, map_map]
  exact map_eq_self (fun k => by fin_cases k <;> rfl) _

/-- **The composition law**: composing at the point replaces it by the normal form composed in,
and composing at another input adjoins the inputs composed in. -/
theorem psi_comp (i : A) (a : A) (b : B) :
    P.psi _ (PointedSet.comp i a b) = comp i (P.psi A a) (P.psi B b) := by
  symm
  by_cases h : a = i
  · subst h
    rw [PointedSet.comp_self, psi, comp_map_left_of _ (i := Sum.inl ()) ?h, P.comp_inl_adjN,
      one_comp', psi, P.adjN_map_left, P.adjN_map_left, P.adjN_adjN]
    case h => rfl
    simp only [map_map]
    exact (P.psi_eq _ _ rfl).symm
  · rw [PointedSet.comp_of_ne h, psi, P.adjN_split _ ⟨i, Ne.symm h⟩, map_map,
      comp_map_left_of _ (i := Sum.inr ()) ?h, comp_inr_bin, one_comp', bin_map_right, psi,
      bin_map_right, P.bin_nu_adjN, ← P.adjN_unit, P.adjN_adjN, P.adjN_adjN]
    case h => rfl
    simp only [map_map]
    exact (P.psi_eq _ _ rfl).symm

/-- **The morphism out of the pointed sets** defined by a permutative element: the point `a` goes
to its normal form. -/
def lift : SetOperadHom PointedSet S where
  app A _ _ a := P.psi A a
  app_map e a := P.psi_map e a
  app_one := P.psi_one
  app_comp i a b := P.psi_comp i a b

@[simp] lemma lift_app (a : A) : P.lift.app A a = P.psi A a := rfl

lemma lift_nu : P.lift.app (Fin 2) 0 = P.nu := P.psi_nu

end PermElt

namespace PointedSet

/-- **The pointed sets are permutative**: `ν` is the first input of two. -/
def permElt : PermElt PointedSet where
  nu := (0 : Fin 2)
  r2a := rfl
  r2b := rfl

variable {S : (A : Type) → [Fintype A] → [DecidableEq A] → Type*} [SetOperad S]
  {A : Type} [Fintype A] [DecidableEq A]

lemma bin_zero {B C : Type} [Fintype B] [DecidableEq B] [Fintype C] [DecidableEq C] (x : B)
    (y : C) : bin (S := PointedSet) (0 : Fin 2) x y = Sum.inl x := rfl

lemma permElt_adj {C : Type} [Fintype C] [DecidableEq C] (x : C) :
    ∀ k, permElt.adj (S := PointedSet) x k = Sum.inl x
  | 0 => rfl
  | k + 1 => by
    rw [PermElt.adj_succ, permElt_adj x k]
    rfl

lemma permElt_adjN {C : Type} [Fintype C] [DecidableEq C] (x : C) (N : Type) [Fintype N]
    [DecidableEq N] : permElt.adjN (S := PointedSet) x N = Sum.inl x := by
  rw [PermElt.adjN_eq _ _ (Fintype.equivFin N), permElt_adj]
  rfl

/-- **Every point is its own normal form.** -/
lemma permElt_psi (a : A) : permElt.psi A a = a := by
  rw [PermElt.psi, permElt_adjN]
  rfl

/-- **Morphisms out of the pointed sets are determined by the image of `ν`.** -/
theorem hom_ext {φ ψ : SetOperadHom PointedSet S}
    (h : φ.app (Fin 2) (0 : Fin 2) = ψ.app (Fin 2) (0 : Fin 2)) : φ = ψ := by
  ext A _ _ a
  rw [← permElt_psi a, PermElt.psi, φ.app_map, ψ.app_map, PermElt.app_adjN, PermElt.app_adjN,
    φ.app_one, ψ.app_one]
  have hP : permElt.map φ = permElt.map ψ := by
    cases hφ : permElt.map φ
    cases hψ : permElt.map ψ
    simp only [PermElt.map, PermElt.mk.injEq] at hφ hψ ⊢
    rw [← hφ, ← hψ]
    exact h
  rw [hP]

/-- **The universal property of the pointed sets**: a morphism of set operads out of them is a
permutative binary element. -/
def homEquiv : SetOperadHom PointedSet S ≃ PermElt S where
  toFun φ := permElt.map φ
  invFun P := P.lift
  left_inv φ := hom_ext (by rw [PermElt.lift_nu]; rfl)
  right_inv P := by
    obtain ⟨nu, r2a, r2b⟩ := P
    simp only [PermElt.map]
    congr 1
    exact PermElt.lift_nu ⟨nu, r2a, r2b⟩

end PointedSet

namespace SymOperadIso

variable {R : Type u} [CommRing R]
  {P : (A : Type) → [Fintype A] → [DecidableEq A] → Type*}
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (P A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (P A)] [SymOperad R P]
  {P' : (A : Type) → [Fintype A] → [DecidableEq A] → Type*}
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (P' A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (P' A)] [SymOperad R P']
  {Q : (A : Type) → [Fintype A] → [DecidableEq A] → Type*}
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (Q A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (Q A)] [SymOperad R Q]

/-- **Precomposition with an isomorphism**: morphisms out of `P'` are morphisms out of `P`. -/
def precompEquiv (e : SymOperadIso R P P') : SymOperadHom R P' Q ≃ SymOperadHom R P Q where
  toFun φ := φ.comp e.hom
  invFun ψ := ψ.comp e.inv
  left_inv φ := SymOperadHom.ext fun A _ _ x => by
    show φ.app A (e.hom.app A (e.inv.app A x)) = φ.app A x
    rw [e.hom_inv_apply]
  right_inv ψ := SymOperadHom.ext fun A _ _ x => by
    show ψ.app A (e.inv.app A (e.hom.app A x)) = ψ.app A x
    rw [e.inv_hom_apply]

end SymOperadIso

namespace Perm

variable (R : Type u) [CommRing R] {Q : (A : Type) → [Fintype A] → [DecidableEq A] → Type w}
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (Q A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (Q A)] [SymOperad R Q]

/-- **The presentation of `Perm`**: a morphism of operads in `R`-modules out of `Perm` is a binary
operation `ν`, in the underlying set operad, with
`ν(ν(x, y), z) = ν(x, ν(y, z)) = ν(x, ν(z, y))`. -/
noncomputable def homEquiv : SymOperadHom R (Sym.Perm R) Q ≃ PermElt (Und R Q) :=
  (PointedSet.linPermIso R).precompEquiv.trans ((linHomEquiv R).symm.trans PointedSet.homEquiv)

end Perm

end Operad
