/-
# Homotopy algebras over a quadratic operad

For quadratic data `(E, r)` presenting `P = T(E)/(r)`, **a `P∞`-algebra** on a dg super module
`V` is an algebra over the cobar construction `ΩP^¡` of the Koszul dual cooperad
(`Koszul.PInfAlgebra`): a morphism of dg operads `ΩP^¡ → End_V`, equivalently a twisting morphism
`P^¡ → End_V` (`HoAlgebra.equivTwisting`). When `P` is Koszul, `ΩP^¡` is the minimal model of `P`
(`Koszul.IsKoszul`, `Koszul.isKoszul_iff`).

* **A dg `P`-algebra** (`Koszul.DGAlgebra`) is a morphism of graded operads `P → End_V` whose
  operations are chain maps: `P` has the zero differential, so its image consists of cycles of
  `End_V`.
* **Every dg `P`-algebra is a `P∞`-algebra** (`Koszul.DGAlgebra.toPInf`), by restriction along the
  morphism `ΩP^¡ → P`. Its twisting morphism is `φ ∘ κ` (`Koszul.DGAlgebra.toPInf_twisting`): it
  sends a generator `sv` of `P^¡` to the operation `φ(v)` (`Koszul.DGAlgebra.toPInf_gen`), and
  **this is faithful** (`Koszul.DGAlgebra.toPInf_injective`): a `P`-algebra structure is determined
  by its `P∞`-structure, as `P` is generated by `E`.
-/
import Operad.InnerDer
import Operad.GrKoszulDual

universe u v v' w

namespace Operad

open Sym GerBV

/-! ## Post-composition with morphisms of dg operads -/

section PostComp

variable {R : Type u} [CommRing R] {C : (A : Type) → [Fintype A] → [DecidableEq A] → Type v}
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (C A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (C A)] [GrCooperad R C]
  [GrCooperad.Coaug R C] {P : (A : Type) → [Fintype A] → [DecidableEq A] → Type v'}
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (P A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (P A)]
  {Q : (A : Type) → [Fintype A] → [DecidableEq A] → Type w}
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (Q A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (Q A)]

/-- **A morphism out of the cobar construction followed by a morphism of dg operads.** -/
noncomputable def CobarHom.postcomp [DGOperad R P] [DGOperad R Q] (φ : CobarHom R C P)
    (ψ : GrOperadHom R P Q) (hψ : ∀ (A : Type) [Fintype A] [DecidableEq A] (x : P A),
      ψ.app A (DGOperad.d (R := R) x) = DGOperad.d (R := R) (ψ.app A x)) : CobarHom R C Q :=
  ⟨ψ.comp φ.1, fun A _ _ y => by rw [GrOperadHom.comp_app, GrOperadHom.comp_app, φ.2, hψ]⟩

lemma CobarHom.postcomp_app [DGOperad R P] [DGOperad R Q] (φ : CobarHom R C P)
    (ψ : GrOperadHom R P Q) (hψ : ∀ (A : Type) [Fintype A] [DecidableEq A] (x : P A),
      ψ.app A (DGOperad.d (R := R) x) = DGOperad.d (R := R) (ψ.app A x))
    {A : Type} [Fintype A] [DecidableEq A] (y : CobarGr R C A) :
    (CobarHom.postcomp φ ψ hψ).1.app A y = ψ.app A (φ.1.app A y) := rfl

/-- **The twisting morphism of the composite is the composite of the twisting morphism.** -/
lemma CobarHom.postcomp_twisting [DGOperad R P] [DGOperad R Q] (φ : CobarHom R C P)
    (ψ : GrOperadHom R P Q) (hψ : ∀ (A : Type) [Fintype A] [DecidableEq A] (x : P A),
      ψ.app A (DGOperad.d (R := R) x) = DGOperad.d (R := R) (ψ.app A x))
    {A : Type} [Fintype A] [DecidableEq A] (x : C A) :
    ConvOp.toLin ((Cobar.homEquiv (CobarHom.postcomp φ ψ hψ)).1.1 A) x
      = ψ.app A (ConvOp.toLin ((Cobar.homEquiv φ).1.1 A) x) := rfl

variable [GrOperad R P]

/-- A morphism of graded operads out of `P`, out of `P` with the zero differential. -/
def GrOperadHom.ofZeroDG [GrOperad R Q] (φ : GrOperadHom R P Q) :
    GrOperadHom R (ZeroDG R P) Q where
  app A _ _ := φ.app A
  app_par := φ.app_par
  app_map := φ.app_map
  app_one := φ.app_one
  app_comp := φ.app_comp

lemma GrOperadHom.ofZeroDG_app [GrOperad R Q] (φ : GrOperadHom R P Q) {A : Type} [Fintype A]
    [DecidableEq A] (x : P A) : φ.ofZeroDG.app A x = φ.app A x := rfl

/-- The zero differential. -/
lemma ZeroDG.d_apply {A : Type} [Fintype A] [DecidableEq A] (x : ZeroDG R P A) :
    DGOperad.d (R := R) (P := ZeroDG R P) x = 0 := rfl

/-- A morphism of graded operads into a dg operad landing in the cycles is a morphism of dg
operads out of the zero differential. -/
lemma GrOperadHom.ofZeroDG_d [DGOperad R Q] (φ : GrOperadHom R P Q)
    (hφ : ∀ (A : Type) [Fintype A] [DecidableEq A] (x : P A), DGOperad.d (R := R) (φ.app A x) = 0)
    (A : Type) [Fintype A] [DecidableEq A] (x : ZeroDG R P A) :
    φ.ofZeroDG.app A (DGOperad.d (R := R) x) = DGOperad.d (R := R) (φ.ofZeroDG.app A x) := by
  rw [ZeroDG.d_apply, map_zero]
  exact (hφ A x).symm

end PostComp

namespace Koszul

variable (R : Type u) [Field R] (E : (A : Type) → [Fintype A] → [DecidableEq A] → Type u)
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (E A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (E A)] [GrSpecies R E]
  (r : ∀ n : ℕ, Set (FreeGrL R E (Fin n)))
  (V : Type w) [AddCommGroup V] [Module R V] [SuperMod R V] [DGSuperMod R V]

/-- **`P∞`-algebras**: the algebras over the cobar construction of the Koszul dual cooperad, the
morphisms of dg operads `ΩP^¡ → End_V`. -/
abbrev PInfAlgebra : Type _ := HoAlgebra R (Dual R E r) V

/-- **dg `P`-algebras**: the morphisms of graded operads `P → End_V` whose operations are chain
maps, the cycles of `End_V`. -/
def DGAlgebra : Type _ :=
  {φ : GrOperadHom R (Pres R E r) (EndGr R V) // ∀ (A : Type) [Fintype A] [DecidableEq A]
    (x : Pres R E r A), DGOperad.d (R := R) (P := EndGr R V) (φ.app A x) = 0}

variable {R E r V}

namespace DGAlgebra

/-- **Every dg `P`-algebra is a `P∞`-algebra**, by restriction along `ΩP^¡ → P`. -/
noncomputable def toPInf (φ : DGAlgebra R E r V) : PInfAlgebra R E r V :=
  CobarHom.postcomp (cobarMor R E r) φ.1.ofZeroDG (GrOperadHom.ofZeroDG_d φ.1 φ.2)

lemma toPInf_app (φ : DGAlgebra R E r V) {A : Type} [Fintype A] [DecidableEq A]
    (y : CobarGr R (Dual R E r) A) :
    (toPInf φ).1.app A y = φ.1.app A ((cobarMor R E r).1.app A y) := rfl

/-- **The twisting morphism of a dg `P`-algebra is `φ ∘ κ`.** -/
theorem toPInf_twisting (φ : DGAlgebra R E r V) {A : Type} [Fintype A] [DecidableEq A]
    (x : Dual R E r A) :
    ConvOp.toLin ((HoAlgebra.equivTwisting (toPInf φ)).1.1 A) x
      = φ.1.app A ((GrOperadIdeal.span R r).proj A (kapL R E A ((dualSub R E r).incl A x))) :=
  (CobarHom.postcomp_twisting _ _ _ x).trans
    (congrArg (φ.1.app A) ((Cobar.homOf_ιL _ _ _ x).trans (kappa_apply r x)))

/-- The generator `sv` of `P^¡`. -/
noncomputable def gen {A : Type} [Fintype A] [DecidableEq A] (w : E A) : Dual R E r A :=
  ⟨(FreeGrL.ι R (GrSpecies.Shift E R)).app A (GrSpecies.Shift.of A w), ι_mem_dual r w⟩

/-- **The twisting morphism of a dg `P`-algebra sends a generator `sv` to the operation `φ(v)`.** -/
theorem toPInf_gen (φ : DGAlgebra R E r V) {A : Type} [Fintype A] [DecidableEq A] (w : E A) :
    ConvOp.toLin ((HoAlgebra.equivTwisting (toPInf φ)).1.1 A) (gen (r := r) w)
      = φ.1.app A ((GrOperadIdeal.span R r).proj A ((FreeGrL.ι R E).app A w)) :=
  (toPInf_twisting φ _).trans (congrArg (fun z => φ.1.app A ((GrOperadIdeal.span R r).proj A z))
    (kapL_ι w))

/-- **A dg `P`-algebra is determined by its `P∞`-structure.** -/
theorem toPInf_injective :
    Function.Injective (toPInf : DGAlgebra R E r V → PInfAlgebra R E r V) := by
  intro φ ψ h
  have hgen : ∀ (A : Type) [Fintype A] [DecidableEq A] (w : E A),
      φ.1.app A ((GrOperadIdeal.span R r).proj A ((FreeGrL.ι R E).app A w))
        = ψ.1.app A ((GrOperadIdeal.span R r).proj A ((FreeGrL.ι R E).app A w)) :=
    fun A _ _ w => (toPInf_gen φ w).symm.trans ((congrArg (fun χ : PInfAlgebra R E r V =>
      ConvOp.toLin ((HoAlgebra.equivTwisting χ).1.1 A) (gen (r := r) w)) h).trans
        (toPInf_gen ψ w))
  have hc : φ.1.comp (GrOperadIdeal.span R r).projHom
      = ψ.1.comp (GrOperadIdeal.span R r).projHom :=
    FreeGrL.hom_ext fun A _ _ w => hgen A w
  refine Subtype.ext (GrOperadHom.ext fun A _ _ x => ?_)
  obtain ⟨y, rfl⟩ := (GrOperadIdeal.span R r).proj_surjective A x
  exact congrArg (fun χ : GrOperadHom R (FreeGrL R E) (EndGr R V) => χ.app A y) hc

end DGAlgebra

end Koszul

end Operad
