/-
# Operads by generators and relations

`Free` builds the free non-symmetric operad on a collection of generators, with its universal
property; `Ideal` builds the quotient by an ideal, with its universal property. This file is the
packaging that makes the two usable together: a `Presentation` is a collection of generators plus
a family of relations, and `Presentation.Op` is the operad it presents.

The point is `Presentation.lift`. Mapping *out* of a presented operad should require exactly what
the mathematics requires — a choice of image for each generator, and a proof that the relations go
to zero — and nothing else. Without this packaging every such map is assembled by hand out of
`extendHom`, `liftHom` and `apply_eq_zero_of_isGenerated`, which is how `assPresToAss` in
`Magmatic.lean` was written before this file existed. The last section rebuilds that map from the
API and checks the two agree.

`lift_gen` and `hom_ext` are the two halves of the universal property. Uniqueness goes through the
free operad: two morphisms out of `Op` that agree on generators agree after precomposition with the
projection, which is `extendHom_unique`, and the projection is surjective.
-/
import Operad.Free
import Operad.FreeUniversal
import Operad.Ideal
import Operad.Magmatic

universe u v w

namespace Operad

open NSOperad

/-! ## 1. Presentations -/

/-- A presentation of a non-symmetric operad: a collection `E` of generators, and for each arity a
set of relations among the trees built from them. -/
structure Presentation (R : Type u) [CommRing R] (E : ℕ → Type v) where
  /-- The relations, as a family of subsets of the free operad. -/
  rel : ∀ n, Set (Free R E n)

namespace Presentation

variable {R : Type u} [CommRing R] {E : ℕ → Type v}

/-- The ideal generated by the relations. -/
noncomputable def ideal (p : Presentation R E) : OperadIdeal R (Free R E) :=
  generated p.rel

/-- **The operad presented by `p`**: the free operad on the generators, modulo the ideal generated
by the relations. -/
noncomputable abbrev Op (p : Presentation R E) : ℕ → Type (max u v) := p.ideal.Quot

noncomputable example (p : Presentation R E) : NSOperad R p.Op := inferInstance

/-- The projection from the free operad onto the presented one. -/
noncomputable def proj (p : Presentation R E) : NSOperadHom R (Free R E) p.Op :=
  p.ideal.projHom

@[simp] lemma proj_app (p : Presentation R E) (n : ℕ) (x : Free R E n) :
    p.proj.app n x = p.ideal.proj n x := rfl

/-- A generator, viewed in the presented operad. -/
noncomputable def gen (p : Presentation R E) {k : ℕ} (e : E k) : p.Op k :=
  p.ideal.proj k (genOf e)

lemma gen_def (p : Presentation R E) {k : ℕ} (e : E k) :
    p.gen e = p.ideal.proj k (genOf (R := R) e) := rfl

/-- **The relations hold in the presented operad**, which is the point of imposing them. -/
theorem rel_eq_zero (p : Presentation R E) {n : ℕ} {x : Free R E n} (hx : x ∈ p.rel n) :
    p.ideal.proj n x = 0 :=
  (Submodule.Quotient.mk_eq_zero _).2 (subset_generated _ hx)

/-! ## 2. The universal property -/

/-- A choice of image for each generator which kills every relation.  This is exactly the data that
a morphism out of a presented operad amounts to. -/
structure Rep (p : Presentation R E) (Q : ℕ → Type w) [∀ n, AddCommGroup (Q n)]
    [∀ n, Module R (Q n)] [NSOperad R Q] where
  /-- Where each generator goes. -/
  toFun : ∀ k, E k → Q k
  /-- Every relation is sent to zero. -/
  kills : ∀ (n : ℕ), ∀ x ∈ p.rel n, (extendHom (R := R) toFun).app n x = 0

variable {Q : ℕ → Type w} [∀ n, AddCommGroup (Q n)] [∀ n, Module R (Q n)] [NSOperad R Q]

/-- The morphism out of the *free* operad determined by a representation. -/
noncomputable def Rep.free {p : Presentation R E} (ρ : p.Rep Q) :
    NSOperadHom R (Free R E) Q :=
  extendHom ρ.toFun

/-- **The universal property of a presentation.**  A representation extends to a morphism out of
the presented operad. -/
noncomputable def lift {p : Presentation R E} (ρ : p.Rep Q) : NSOperadHom R p.Op Q :=
  p.ideal.liftHom ρ.free (fun _ _ hx => apply_eq_zero_of_isGenerated ρ.free p.rel ρ.kills hx)

lemma lift_proj {p : Presentation R E} (ρ : p.Rep Q) (n : ℕ) (x : Free R E n) :
    (lift ρ).app n (p.ideal.proj n x) = ρ.free.app n x := rfl

@[simp] lemma lift_mk {p : Presentation R E} (ρ : p.Rep Q) (n : ℕ) (x : Free R E n) :
    (lift ρ).app n (Submodule.Quotient.mk x) = ρ.free.app n x := rfl

/-- The lift does on generators what it was asked to do. -/
@[simp] theorem lift_gen {p : Presentation R E} (ρ : p.Rep Q) {k : ℕ} (e : E k) :
    (lift ρ).app k (p.gen e) = ρ.toFun k e := by
  show (lift ρ).app k (p.ideal.proj k (genOf e)) = ρ.toFun k e
  rw [lift_proj]
  show (extendHom (R := R) ρ.toFun).app k (genOf e) = ρ.toFun k e
  rw [genOf_def, extendHom_corolla]

/-- **Two morphisms out of a presented operad agreeing on generators are equal.**

Precomposing with the projection lands in the free operad, where `extendHom_unique` applies; and
the projection is surjective, so agreement there is agreement everywhere. -/
theorem hom_ext {p : Presentation R E} (φ ψ : NSOperadHom R p.Op Q)
    (h : ∀ (k : ℕ) (e : E k), φ.app k (p.gen e) = ψ.app k (p.gen e)) :
    φ = ψ := by
  have key : ∀ σ : NSOperadHom R p.Op Q,
      (∀ (k : ℕ) (e : E k), σ.app k (p.gen e) = ψ.app k (p.gen e)) →
      σ.comp p.proj = extendHom (R := R) (fun k (e : E k) => ψ.app k (p.gen e)) := by
    intro σ hσ
    refine extendHom_unique _ _ fun k e => ?_
    rw [NSOperadHom.comp_app]
    exact hσ k e
  have h1 := key φ h
  have h2 := key ψ (fun _ _ => rfl)
  refine NSOperadHom.ext fun n => ?_
  refine LinearMap.ext fun x => ?_
  obtain ⟨y, rfl⟩ := p.ideal.proj_surjective n x
  have e1 : φ.app n (p.ideal.proj n y)
      = (extendHom (R := R) (fun k (e : E k) => ψ.app k (p.gen e))).app n y := by
    have := congrArg (fun σ => σ.app n y) h1
    simpa using this
  have e2 : ψ.app n (p.ideal.proj n y)
      = (extendHom (R := R) (fun k (e : E k) => ψ.app k (p.gen e))).app n y := by
    have := congrArg (fun σ => σ.app n y) h2
    simpa using this
  rw [e1, e2]

/-- **Uniqueness.**  A morphism out of a presented operad is determined by where it sends the
generators. -/
theorem lift_unique {p : Presentation R E} (ρ : p.Rep Q) (φ : NSOperadHom R p.Op Q)
    (hφ : ∀ (k : ℕ) (e : E k), φ.app k (p.gen e) = ρ.toFun k e) :
    φ = lift ρ :=
  hom_ext φ (lift ρ) fun k e => by rw [hφ k e, lift_gen]

end Presentation

/-! ## 3. The associative operad, through the API

`Magmatic.lean` presents `Ass` by one binary generator modulo associativity, and builds the
comparison map to the hand-built `Ass` by unfolding all three universal properties.  Here is the
same map from `Presentation.lift`, and the check that it is the same map. -/

/-- The presentation of the associative operad: one binary generator, one ternary relation. -/
noncomputable def assPresentation (R : Type u) [CommRing R] : Presentation R MagGen :=
  ⟨assocRels R⟩

/-- The presented operad is the one `Magmatic.lean` already built. -/
example (R : Type u) [CommRing R] : (assPresentation R).Op = AssPres R := rfl

/-- Sending the binary generator to the product of `Ass` kills the associator. -/
noncomputable def assRep (R : Type u) [CommRing R] : (assPresentation R).Rep (Ass R) where
  toFun := magToAss R
  kills := by
    intro n x hx
    match n, x, hx with
    | 0, x, hx => exact absurd hx (by simp [assPresentation, assocRels])
    | 1, x, hx => exact absurd hx (by simp [assPresentation, assocRels])
    | 2, x, hx => exact absurd hx (by simp [assPresentation, assocRels])
    | 3, x, hx =>
        rw [show x = assocRel R from by simpa [assPresentation, assocRels] using hx]
        exact extendHom_assocRel R
    | (k + 4), x, hx => exact absurd hx (by simp [assPresentation, assocRels])

/-- The comparison map, rebuilt from the presentation API in one line.

The type is written as `(assPresentation R).Op` rather than the definitionally equal `AssPres R`:
ascribing the latter makes the elaborator unify `Presentation.ideal ⟨assocRels R⟩` with
`generated (assocRels R)` while `p` is still a metavariable, and it does not terminate. -/
noncomputable def assPresToAssOfRep (R : Type u) [CommRing R] :
    NSOperadHom R (assPresentation R).Op (Ass R) :=
  Presentation.lift (p := assPresentation R) (assRep R)

/-- **The API reproduces the hand-built map.**  This is the encoding check for this file: a wrong
`lift` would still typecheck, and would still send the generator to the right place, but it would
not be the map `Magmatic.lean` built by unfolding the two universal properties by hand. -/
theorem assPresToAssOfRep_eq (R : Type u) [CommRing R] :
    assPresToAssOfRep R = assPresToAss R := by
  refine Presentation.hom_ext (p := assPresentation R) _ _ fun k e => ?_
  have hL : (assPresToAssOfRep R).app k ((assPresentation R).gen e) = magToAss R k e := by
    show (Presentation.lift (p := assPresentation R) (assRep R)).app k
      ((assPresentation R).gen e) = _
    rw [Presentation.lift_gen]
    rfl
  have hR : (assPresToAss R).app k ((assPresentation R).gen e) = magToAss R k e := by
    show (assPresToAss R).app k ((generated (R := R) (assocRels R)).proj k (genOf e)) = _
    rw [assPresToAss, OperadIdeal.liftHom_proj]
    show (extendHom (R := R) (magToAss R)).app k (genOf e) = _
    rw [genOf_def, extendHom_corolla]
  exact hL.trans hR.symm

end Operad
