/-
# Set operads by generators and relations

`Syn T A` is the type of operad expressions in generators `T` with inputs `A`: generators, the
identity, relabellings and partial compositions, kept as syntax. `Pres T ρ` is its quotient by the
congruence generated by the operad axioms and the relations `ρ`. It is a set operad, and it is the
set operad *presented* by `T` and `ρ`: a morphism out of it is exactly an assignment of values to
the generators under which the relations evaluate to equalities (`Pres.homEquiv`). With no
relations it is the free set operad on `T` (`FreeSet`).

Taking the quotient of the syntax, rather than an explicit combinatorial model, makes the universal
property immediate. It costs nothing downstream: a normal-form theorem, that the presented operad
is isomorphic to a given one, is proved by exhibiting the inverse morphism, and never needs normal
forms in the free operad itself.

The generators are indexed by arity and carry no symmetry. A generator with symmetries is a
generator together with relations: a commutative binary operation is a binary generator `g` with
the relation `map swap g = g`.

Through the linearization adjunction the same presentation describes morphisms into operads in
`R`-modules (`Pres.linHomEquiv`): relations that are equalities of monomials present a linear
operad whose relations are the corresponding differences.
-/
import Operad.SetOperad

universe u v w

namespace Operad

open Sym

/-- **Operad expressions** in generators `T` (those of arity `n` in `T n`), indexed by their input
type. -/
inductive Syn (T : ℕ → Type w) : (A : Type) → [Fintype A] → [DecidableEq A] → Type (max 1 w) where
  /-- The identity operation. -/
  | one : Syn T Unit
  /-- A generator, with inputs `Fin n`. -/
  | gen {n : ℕ} (g : T n) : Syn T (Fin n)
  /-- Relabel the inputs along a bijection. -/
  | map {A B : Type} [Fintype A] [DecidableEq A] [Fintype B] [DecidableEq B] (e : A ≃ B)
      (x : Syn T A) : Syn T B
  /-- Partial composition at the input `i`. -/
  | comp {A B : Type} [Fintype A] [DecidableEq A] [Fintype B] [DecidableEq B] (i : A)
      (x : Syn T A) (y : Syn T B) : Syn T (Without A i ⊕ B)

namespace Syn

variable {T : ℕ → Type w}

/-- **The congruence generated by the operad axioms and the relations `ρ`.** -/
inductive Rel (ρ : ∀ {A : Type} [Fintype A] [DecidableEq A], Syn T A → Syn T A → Prop) :
    {A : Type} → [Fintype A] → [DecidableEq A] → Syn T A → Syn T A → Prop where
  | of {A : Type} [Fintype A] [DecidableEq A] {x y : Syn T A} : ρ x y → Rel ρ x y
  | refl {A : Type} [Fintype A] [DecidableEq A] (x : Syn T A) : Rel ρ x x
  | symm {A : Type} [Fintype A] [DecidableEq A] {x y : Syn T A} : Rel ρ x y → Rel ρ y x
  | trans {A : Type} [Fintype A] [DecidableEq A] {x y z : Syn T A} :
      Rel ρ x y → Rel ρ y z → Rel ρ x z
  | map {A B : Type} [Fintype A] [DecidableEq A] [Fintype B] [DecidableEq B] (e : A ≃ B)
      {x y : Syn T A} : Rel ρ x y → Rel ρ (map e x) (map e y)
  | comp {A B : Type} [Fintype A] [DecidableEq A] [Fintype B] [DecidableEq B] (i : A)
      {x x' : Syn T A} {y y' : Syn T B} :
      Rel ρ x x' → Rel ρ y y' → Rel ρ (comp i x y) (comp i x' y')
  | map_refl {A : Type} [Fintype A] [DecidableEq A] (x : Syn T A) :
      Rel ρ (map (Equiv.refl A) x) x
  | map_trans {A B C : Type} [Fintype A] [DecidableEq A] [Fintype B] [DecidableEq B]
      [Fintype C] [DecidableEq C] (e : A ≃ B) (f : B ≃ C) (x : Syn T A) :
      Rel ρ (map (e.trans f) x) (map f (map e x))
  | map_comp {A A' B B' : Type} [Fintype A] [DecidableEq A] [Fintype A'] [DecidableEq A']
      [Fintype B] [DecidableEq B] [Fintype B'] [DecidableEq B'] (σ : A ≃ A') (τ : B ≃ B')
      (i : A) (x : Syn T A) (y : Syn T B) :
      Rel ρ (map (compEquiv σ τ i) (comp i x y)) (comp (σ i) (map σ x) (map τ y))
  | comp_one {A : Type} [Fintype A] [DecidableEq A] (i : A) (x : Syn T A) :
      Rel ρ (map (rightUnitEquiv i) (comp i x one)) x
  | one_comp {B : Type} [Fintype B] [DecidableEq B] (y : Syn T B) :
      Rel ρ (map (leftUnitEquiv B) (comp () one y)) y
  | assoc_seq {A B D : Type} [Fintype A] [DecidableEq A] [Fintype B] [DecidableEq B]
      [Fintype D] [DecidableEq D] (i : A) (j : B) (x : Syn T A) (y : Syn T B) (z : Syn T D) :
      Rel ρ (map (seqEquiv i j D) (comp (Sum.inr j) (comp i x y) z)) (comp i x (comp j y z))
  | assoc_par {A B D : Type} [Fintype A] [DecidableEq A] [Fintype B] [DecidableEq B]
      [Fintype D] [DecidableEq D] {i k : A} (hik : i ≠ k) (x : Syn T A) (y : Syn T B)
      (z : Syn T D) :
      Rel ρ (map (parEquiv hik B D) (comp (Sum.inl ⟨k, Ne.symm hik⟩) (comp i x y) z))
        (comp (Sum.inl ⟨i, hik⟩) (comp k x z) y)

variable {S : (A : Type) → [Fintype A] → [DecidableEq A] → Type v} [SetOperad S]

/-- **Evaluate an expression** in a set operad, given values for the generators. -/
def eval (f : ∀ n, T n → S (Fin n)) :
    {A : Type} → [Fintype A] → [DecidableEq A] → Syn T A → S A
  | _, _, _, .one => SetOperad.one
  | _, _, _, .gen g => f _ g
  | _, _, _, @Syn.map _ _ _ _ _ _ _ e x => SetOperad.map e (eval f x)
  | _, _, _, @Syn.comp _ _ _ _ _ _ _ i x y => SetOperad.comp i (eval f x) (eval f y)

variable (f : ∀ n, T n → S (Fin n))

@[simp] lemma eval_one : eval f (one : Syn T Unit) = SetOperad.one := rfl

@[simp] lemma eval_gen {n : ℕ} (g : T n) : eval f (gen g) = f n g := rfl

@[simp] lemma eval_map {A B : Type} [Fintype A] [DecidableEq A] [Fintype B] [DecidableEq B]
    (e : A ≃ B) (x : Syn T A) : eval f (map e x) = SetOperad.map e (eval f x) := rfl

@[simp] lemma eval_comp {A B : Type} [Fintype A] [DecidableEq A] [Fintype B] [DecidableEq B]
    (i : A) (x : Syn T A) (y : Syn T B) :
    eval f (comp i x y) = SetOperad.comp i (eval f x) (eval f y) := rfl

/-- Evaluation respects the operad axioms, and every relation it respects. -/
theorem eval_eq_of_rel {ρ : ∀ {A : Type} [Fintype A] [DecidableEq A], Syn T A → Syn T A → Prop}
    (hf : ∀ {A : Type} [Fintype A] [DecidableEq A] (x y : Syn T A), ρ x y → eval f x = eval f y)
    {A : Type} [Fintype A] [DecidableEq A] {x y : Syn T A} (h : Rel ρ x y) :
    eval f x = eval f y := by
  induction h with
  | of h => exact hf _ _ h
  | refl => rfl
  | symm _ ih => exact ih.symm
  | trans _ _ ih ih' => exact ih.trans ih'
  | map e _ ih => simp only [eval_map, ih]
  | comp i _ _ ih ih' => simp only [eval_comp, ih, ih']
  | map_refl x => exact SetOperad.map_refl (eval f x)
  | map_trans e e' x => exact SetOperad.map_trans e e' (eval f x)
  | map_comp σ τ i x y => exact SetOperad.map_comp σ τ i (eval f x) (eval f y)
  | comp_one i x => exact SetOperad.comp_one i (eval f x)
  | one_comp y => exact SetOperad.one_comp (eval f y)
  | assoc_seq i j x y z => exact SetOperad.comp_assoc_seq i j (eval f x) (eval f y) (eval f z)
  | assoc_par hik x y z => exact SetOperad.comp_assoc_par hik (eval f x) (eval f y) (eval f z)

end Syn

/-! ## The presented set operad -/

/-- **The set operad presented by generators `T` and relations `ρ`.** -/
def Pres (T : ℕ → Type w) (ρ : ∀ {A : Type} [Fintype A] [DecidableEq A], Syn T A → Syn T A → Prop) :
    (A : Type) → [Fintype A] → [DecidableEq A] → Type (max 1 w) :=
  fun A _ _ => Quot (Syn.Rel ρ (A := A))

namespace Pres

variable {T : ℕ → Type w} {ρ : ∀ {A : Type} [Fintype A] [DecidableEq A], Syn T A → Syn T A → Prop}

/-- The class of an expression. -/
def mk {A : Type} [Fintype A] [DecidableEq A] (x : Syn T A) : Pres T ρ A := Quot.mk _ x

lemma mk_surjective {A : Type} [Fintype A] [DecidableEq A] :
    Function.Surjective (mk (ρ := ρ) (A := A)) := Quot.exists_rep

lemma mk_eq_mk {A : Type} [Fintype A] [DecidableEq A] {x y : Syn T A} (h : Syn.Rel ρ x y) :
    mk (ρ := ρ) x = mk y := Quot.sound h

/-- A relation holds in the presented operad. -/
lemma mk_eq_mk_of_rel {A : Type} [Fintype A] [DecidableEq A] {x y : Syn T A} (h : ρ x y) :
    mk (ρ := ρ) x = mk y := Quot.sound (.of h)

instance instSetOperad : SetOperad (Pres T ρ) where
  map e := Quot.map (Syn.map e) (fun _ _ h => .map e h)
  map_refl := by
    rintro _ _ _ ⟨x⟩
    exact Quot.sound (.map_refl x)
  map_trans e f := by
    rintro ⟨x⟩
    exact Quot.sound (.map_trans e f x)
  one := mk .one
  comp i := Quot.map₂ (Syn.comp i) (fun x _ _ h => .comp i (.refl x) h)
    (fun _ _ y h => .comp i h (.refl y))
  map_comp σ τ i := by
    rintro ⟨x⟩ ⟨y⟩
    exact Quot.sound (.map_comp σ τ i x y)
  comp_one i := by
    rintro ⟨x⟩
    exact Quot.sound (.comp_one i x)
  one_comp := by
    rintro _ _ _ ⟨y⟩
    exact Quot.sound (.one_comp y)
  comp_assoc_seq i j := by
    rintro ⟨x⟩ ⟨y⟩ ⟨z⟩
    exact Quot.sound (.assoc_seq i j x y z)
  comp_assoc_par hik := by
    rintro ⟨x⟩ ⟨y⟩ ⟨z⟩
    exact Quot.sound (.assoc_par hik x y z)

@[simp] lemma map_mk {A B : Type} [Fintype A] [DecidableEq A] [Fintype B] [DecidableEq B]
    (e : A ≃ B) (x : Syn T A) : SetOperad.map e (mk (ρ := ρ) x) = mk (.map e x) := rfl

@[simp] lemma comp_mk {A B : Type} [Fintype A] [DecidableEq A] [Fintype B] [DecidableEq B]
    (i : A) (x : Syn T A) (y : Syn T B) :
    SetOperad.comp i (mk (ρ := ρ) x) (mk y) = mk (.comp i x y) := rfl

lemma one_eq : (SetOperad.one : Pres T ρ Unit) = mk .one := rfl

/-- A generator, in the presented operad. -/
def gen {n : ℕ} (g : T n) : Pres T ρ (Fin n) := mk (.gen g)

/-- Every element is the class of the evaluation of an expression at the generators. -/
lemma mk_eq_eval {A : Type} [Fintype A] [DecidableEq A] (x : Syn T A) :
    mk (ρ := ρ) x = Syn.eval (fun _ g => gen g) x := by
  induction x with
  | one => rfl
  | gen g => rfl
  | map e x ih => rw [Syn.eval_map, ← ih]; rfl
  | comp i x y ihx ihy => rw [Syn.eval_comp, ← ihx, ← ihy]; rfl

variable {S : (A : Type) → [Fintype A] → [DecidableEq A] → Type v} [SetOperad S]

/-- The condition for generator values to define a morphism out of `Pres T ρ`. -/
def Respects (ρ : ∀ {A : Type} [Fintype A] [DecidableEq A], Syn T A → Syn T A → Prop)
    (f : ∀ n, T n → S (Fin n)) : Prop :=
  ∀ {A : Type} [Fintype A] [DecidableEq A] (x y : Syn T A), ρ x y → Syn.eval f x = Syn.eval f y

/-- **The morphism defined by generator values that respect the relations.** -/
def lift (f : ∀ n, T n → S (Fin n)) (hf : Respects ρ f) : SetOperadHom (Pres T ρ) S where
  app _ _ _ := Quot.lift (Syn.eval f) (fun _ _ h => Syn.eval_eq_of_rel f hf h)
  app_map _ x := Quot.inductionOn x fun _ => rfl
  app_one := rfl
  app_comp _ x y := Quot.inductionOn x fun _ => Quot.inductionOn y fun _ => rfl

@[simp] lemma lift_mk (f : ∀ n, T n → S (Fin n)) (hf : Respects ρ f) {A : Type} [Fintype A]
    [DecidableEq A] (x : Syn T A) : (lift f hf).app A (mk x) = Syn.eval f x := rfl

@[simp] lemma lift_gen (f : ∀ n, T n → S (Fin n)) (hf : Respects ρ f) {n : ℕ} (g : T n) :
    (lift f hf).app (Fin n) (gen g) = f n g := rfl

/-- A morphism out of `Pres T ρ` is its values on generators, extended. -/
lemma app_mk (φ : SetOperadHom (Pres T ρ) S) {A : Type} [Fintype A] [DecidableEq A]
    (x : Syn T A) : φ.app A (mk x) = Syn.eval (fun _ g => φ.app _ (gen g)) x := by
  induction x with
  | one => exact φ.app_one
  | gen g => rfl
  | map e x ih => rw [Syn.eval_map, ← ih, ← φ.app_map]; rfl
  | comp i x y ihx ihy => rw [Syn.eval_comp, ← ihx, ← ihy, ← φ.app_comp]; rfl

/-- **Morphisms out of a presented operad are determined by the generators.** -/
theorem hom_ext {φ ψ : SetOperadHom (Pres T ρ) S}
    (h : ∀ (n : ℕ) (g : T n), φ.app _ (gen g) = ψ.app _ (gen g)) : φ = ψ := by
  ext A _ _ x
  obtain ⟨x, rfl⟩ := mk_surjective x
  rw [app_mk, app_mk]
  congr 1
  funext n g
  exact h n g

/-- The generator values of a morphism respect the relations. -/
lemma respects_app (φ : SetOperadHom (Pres T ρ) S) :
    Respects ρ (fun _ g => φ.app _ (gen g)) := by
  intro A _ _ x y h
  rw [← app_mk, ← app_mk, mk_eq_mk_of_rel h]

/-- **The universal property of a presented set operad**: morphisms out of `Pres T ρ` are
generator values respecting the relations. -/
def homEquiv : SetOperadHom (Pres T ρ) S ≃ {f : ∀ n, T n → S (Fin n) // Respects ρ f} where
  toFun φ := ⟨fun _ g => φ.app _ (gen g), respects_app φ⟩
  invFun f := lift f.1 f.2
  left_inv _ := hom_ext fun _ _ => rfl
  right_inv _ := rfl

/-! ### Into operads in modules -/

variable (R : Type u) [CommRing R] {Q : (A : Type) → [Fintype A] → [DecidableEq A] → Type w}
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (Q A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (Q A)] [SymOperad R Q]

/-- **The universal property of the linearization of a presented set operad**: morphisms of
operads in `R`-modules out of `Lin R (Pres T ρ)` are generator values in `Q` under which the
relations evaluate to equalities. -/
noncomputable def linHomEquiv :
    SymOperadHom R (Lin R (Pres T ρ)) Q ≃ {f : ∀ n, T n → Und R Q (Fin n) // Respects ρ f} :=
  (Operad.linHomEquiv R).symm.trans homEquiv

end Pres

/-- **The free set operad** on generators `T`. -/
abbrev FreeSet (T : ℕ → Type w) : (A : Type) → [Fintype A] → [DecidableEq A] → Type (max 1 w) :=
  Pres T (fun _ _ => False)

namespace FreeSet

variable {T : ℕ → Type w} {S : (A : Type) → [Fintype A] → [DecidableEq A] → Type v} [SetOperad S]

/-- **The universal property of the free set operad.** -/
def homEquiv : SetOperadHom (FreeSet T) S ≃ (∀ n, T n → S (Fin n)) :=
  Pres.homEquiv.trans
    { toFun := fun f => f.1
      invFun := fun f => ⟨f, fun _ _ h => h.elim⟩
      left_inv := fun _ => rfl
      right_inv := fun _ => rfl }

end FreeSet

end Operad
