/-
# Symmetric presentations as presentations of the free shuffle operad

For generators `T` without operations of arity zero, the free symmetric operad is the free shuffle
operad on the relabelled generators (`Operad.FreeSet.shuffleEquiv`), and this transports
presentations.

* `Operad.ShuffleOperadIdeal.comap`: the preimage of an ideal along a morphism of shuffle operads;
  `Operad.ShuffleOperadIdeal.quotHom`: the morphism of quotients induced by a morphism mapping one
  ideal into another.
* **A symmetric presentation as a presentation of the free shuffle operad**
  (`Operad.FreeSet.presToSh`, `Operad.FreeSet.presEquiv`): the underlying shuffle operad of the
  operad presented by relators `r` is the free shuffle operad on the relabelled generators modulo
  the ideal generated by the sorted relabellings of the relators (`Operad.FreeSet.shuffleRel`).
* **PBW bases of symmetric operads** (`Operad.FreeSet.presBasis`, Dotsenko–Khoroshkin): when the
  sorted relabellings of the relators generate the ideal of a resolvable set of rules — for rules
  on the positions `0, …, n - 1`, the shuffle ideal generated by their relations
  (`Operad.Rules.shuffleIdeal_eq_span`) — the normal monomials are a basis of the symmetric operad
  on every finite linear order.
-/
import Operad.ShuffleFreeSym
import Operad.ShufflePresUniv

universe u v w

namespace Operad

namespace ShuffleOperadIdeal

variable {R : Type u} [CommRing R]
  {P : (A : Type) → [Fintype A] → [LinearOrder A] → Type v}
  [∀ (A : Type) [Fintype A] [LinearOrder A], AddCommGroup (P A)]
  [∀ (A : Type) [Fintype A] [LinearOrder A], Module R (P A)] [ShuffleOperad R P]
  {Q : (A : Type) → [Fintype A] → [LinearOrder A] → Type w}
  [∀ (A : Type) [Fintype A] [LinearOrder A], AddCommGroup (Q A)]
  [∀ (A : Type) [Fintype A] [LinearOrder A], Module R (Q A)] [ShuffleOperad R Q]

/-- **The preimage of an ideal** along a morphism of shuffle operads. -/
def comap (ψ : ShuffleOperadHom R Q P) (I : ShuffleOperadIdeal R P) : ShuffleOperadIdeal R Q where
  sub A _ _ := (I.sub A).comap (ψ.app A)
  map_mem e := fun {x} hx => by
    show ψ.app _ (ShuffleOperad.map (R := R) e x) ∈ I.sub _
    rw [ψ.app_map]
    exact I.map_mem e hx
  comp_mem_left i e he := fun {x} y hx => by
    show ψ.app _ (ShuffleOperad.comp (R := R) i e he x y) ∈ I.sub _
    rw [ψ.app_comp]
    exact I.comp_mem_left i e he _ hx
  comp_mem_right i e he := fun x {y} hy => by
    show ψ.app _ (ShuffleOperad.comp (R := R) i e he x y) ∈ I.sub _
    rw [ψ.app_comp]
    exact I.comp_mem_right i e he _ hy

@[simp] lemma mem_comap (ψ : ShuffleOperadHom R Q P) (I : ShuffleOperadIdeal R P) {A : Type}
    [Fintype A] [LinearOrder A] {x : Q A} : x ∈ (I.comap ψ).sub A ↔ ψ.app A x ∈ I.sub A :=
  Iff.rfl

/-- **The morphism of quotients** induced by a morphism mapping an ideal into another. -/
noncomputable def quotHom (φ : ShuffleOperadHom R P Q) (I : ShuffleOperadIdeal R P)
    (J : ShuffleOperadIdeal R Q) (h : I ≤ J.comap φ) : ShuffleOperadHom R I.Quot J.Quot :=
  I.liftHom (J.projHom.comp φ) fun A _ _ _ hx => (Submodule.Quotient.mk_eq_zero _).2 (h A hx)

@[simp] lemma quotHom_proj (φ : ShuffleOperadHom R P Q) (I : ShuffleOperadIdeal R P)
    (J : ShuffleOperadIdeal R Q) (h : I ≤ J.comap φ) (A : Type) [Fintype A] [LinearOrder A]
    (x : P A) : (quotHom φ I J h).app A (I.proj A x) = J.proj A (φ.app A x) := rfl

end ShuffleOperadIdeal

namespace FreeSet

open STree

variable (R : Type u) [CommRing R] {T : ℕ → Type v} [IsEmpty (T 0)]
  (r : ∀ n : ℕ, Set (Lin R (FreeSet T) (Fin n)))

/-- **The shuffle relators of a symmetric presentation**: the sorted relabellings of the
relators. -/
def shuffleRel (A : Type) [Fintype A] [LinearOrder A] : Set (FreeSh R (SGen T) A) :=
  (toSh R T).app A '' SymOperadIdeal.relabelSet (R := R) r A

lemma span_relabel_le : ShuffleOperadIdeal.span R (SymOperadIdeal.relabelSet (R := R) r) ≤
    (ShuffleOperadIdeal.span R (shuffleRel R r)).comap (toSh R T) :=
  ShuffleOperadIdeal.span_le.2 fun A _ _ x hx => ShuffleOperadIdeal.subset_span A ⟨x, hx, rfl⟩

lemma span_shuffleRel_le : ShuffleOperadIdeal.span R (shuffleRel R r) ≤
    (ShuffleOperadIdeal.span R (SymOperadIdeal.relabelSet (R := R) r)).comap (fromSh R T) :=
  ShuffleOperadIdeal.span_le.2 fun A _ _ y hy => by
    obtain ⟨x, hx, rfl⟩ := hy
    show (fromSh R T).app A ((toSh R T).app A x) ∈
      (ShuffleOperadIdeal.span R (SymOperadIdeal.relabelSet (R := R) r)).sub A
    rw [fromSh_toSh]
    exact ShuffleOperadIdeal.subset_span A hx

/-- **A symmetric presentation as a presentation of the free shuffle operad**: the morphism from
the underlying shuffle operad of the operad presented by relators to the free shuffle operad on
the relabelled generators modulo the sorted relabellings of the relators, sorting. -/
noncomputable def presToSh : ShuffleOperadHom R (Shuf (SymOperadIdeal.span R r).Quot)
    (ShuffleOperadIdeal.span R (shuffleRel R r)).Quot :=
  (ShuffleOperadIdeal.quotHom (toSh R T) _ _ (span_relabel_le R r)).comp
    (SymOperadIdeal.toShuffleSpanQuot r)

lemma presToSh_proj (A : Type) [Fintype A] [LinearOrder A] (x : Lin R (FreeSet T) A) :
    (presToSh R r).app A ((SymOperadIdeal.span R r).proj A x) =
      (ShuffleOperadIdeal.span R (shuffleRel R r)).proj A ((toSh R T).app A x) := rfl

omit [IsEmpty (T 0)] in
lemma sub_eq_relabel (A : Type) [Fintype A] [LinearOrder A] :
    (SymOperadIdeal.span R r).sub A =
      (ShuffleOperadIdeal.span R (SymOperadIdeal.relabelSet (R := R) r)).sub A := by
  rw [← SymOperadIdeal.toShuffle_span r]
  rfl

lemma map_shuffleEquiv (A : Type) [Fintype A] [LinearOrder A] :
    ((ShuffleOperadIdeal.span R (SymOperadIdeal.relabelSet (R := R) r)).sub A).map
      ((shuffleEquiv R A : Lin R (FreeSet T) A ≃ₗ[R] FreeSh R (SGen T) A) :
        Lin R (FreeSet T) A →ₗ[R] FreeSh R (SGen T) A) =
      (ShuffleOperadIdeal.span R (shuffleRel R r)).sub A := by
  refine le_antisymm (Submodule.map_le_iff_le_comap.2 fun x hx => span_relabel_le R r A hx)
    fun y hy => ⟨(fromSh R T).app A y, span_shuffleRel_le R r A hy, toSh_fromSh R A y⟩

/-- **The components of a symmetric presentation as a shuffle presentation are isomorphisms.** -/
noncomputable def presEquiv (A : Type) [Fintype A] [LinearOrder A] :
    (SymOperadIdeal.span R r).Quot A ≃ₗ[R] (ShuffleOperadIdeal.span R (shuffleRel R r)).Quot A :=
  (Submodule.quotEquivOfEq _ _ (sub_eq_relabel R r A)).trans
    (Submodule.Quotient.equiv _ _ (shuffleEquiv R A) (map_shuffleEquiv R r A))

lemma presEquiv_apply (A : Type) [Fintype A] [LinearOrder A] (q : (SymOperadIdeal.span R r).Quot A) :
    presEquiv R r A q = (presToSh R r).app A q := by
  obtain ⟨x, rfl⟩ := (SymOperadIdeal.span R r).proj_surjective A q
  rfl

/-- **PBW bases of symmetric operads** (Dotsenko–Khoroshkin): when the sorted relabellings of the
relators generate the ideal of a resolvable set of rules, the normal monomials are a basis of the
symmetric operad presented by the relators, on every finite linear order. -/
noncomputable def presBasis {ρ : Type*} {O : AdmOrder (SGen T)} (G : Rules R ρ O.toCtxOrder)
    (hG : ShuffleOperadIdeal.span R (shuffleRel R r) = G.shuffleIdeal)
    (hres : ∀ C, (G.rw C).Resolvable) (A : Type) [Fintype A] [LinearOrder A] :
    Module.Basis (G.rw (Finset.range (Fintype.card A))).Irr R
      ((SymOperadIdeal.span R r).Quot A) :=
  (G.presentedBasis hres A).map ((presEquiv R r A).trans
    (Submodule.quotEquivOfEq _ _ (by rw [hG]))).symm

/-- The basis element of a normal monomial is the class of its symmetric operation. -/
theorem presBasis_apply {ρ : Type*} {O : AdmOrder (SGen T)} (G : Rules R ρ O.toCtxOrder)
    (hG : ShuffleOperadIdeal.span R (shuffleRel R r) = G.shuffleIdeal)
    (hres : ∀ C, (G.rw C).Resolvable) (A : Type) [Fintype A] [LinearOrder A]
    (m : (G.rw (Finset.range (Fintype.card A))).Irr) :
    presBasis R r G hG hres A m =
      (SymOperadIdeal.span R r).proj A ((fromSh R T).app A (Finsupp.single (m : SMono _ _) 1)) := by
  have key : ((presEquiv R r A).trans (Submodule.quotEquivOfEq _ _ (by rw [hG])))
      ((SymOperadIdeal.span R r).proj A ((fromSh R T).app A (Finsupp.single (m : SMono _ _) 1))) =
      G.presentedBasis hres A m := by
    rw [Rules.presentedBasis_apply, LinearEquiv.trans_apply, presEquiv_apply, presToSh_proj,
      toSh_fromSh]
    rfl
  rw [presBasis, Module.Basis.map_apply, ← key]
  exact LinearEquiv.symm_apply_apply _ _

end FreeSet

end Operad
