/-
# Generated ideals of shuffle operads, and presentations transported

* `ShuffleOperadIdeal.span`: **the shuffle ideal generated** by elements of the components, the
  smallest ideal containing them (`subset_span`, `span_le`).
* **Sorting** (`exists_sort`, `exists_shuffle`): every bijection `Without A i ⊕ B ≃ D` onto an
  ordered set becomes a shuffle once `A` and `B` are numbered suitably: `B` in the order of its
  image, and `A` in the order of the images of `Without A i`, with `i` at the place of the least
  image of `B`.
* So **a relabelled partial composite in a symmetric operad is a shuffle composite of relabelled
  operations** (`SymOperad.map_comp_eq_shuffle`).
* **The forgetful image of a generated ideal is the shuffle ideal generated by all relabellings of
  the relators** (`SymOperadIdeal.toShuffle_span`): the shuffle ideal generated by relators
  closed under relabelling is closed under all bijections, not only the increasing ones
  (`ShuffleOperadIdeal.map_mem_span_relabel`). Hence **the forgetful image of the operad presented
  by relators is the shuffle operad presented by their relabellings**
  (`SymOperadIdeal.toShuffleSpanQuot`).
* **Generation**: the underlying shuffle operad of a presented operad in modules is generated by
  the relabellings of its generators, so a morphism of shuffle operads out of it is determined by
  their values (`Pres.shuffle_hom_ext`, and for quotients `SymOperadIdeal.shuffle_hom_ext`).
-/
import Operad.ShuffleOperad
import Operad.SymPresentation
import Mathlib.Data.Finset.Sort
import Mathlib.Order.WithBot

universe u v w

namespace Operad

open Sym

/-! ## Generated shuffle ideals -/

namespace ShuffleOperadIdeal

variable {R : Type u} [CommRing R]
  {P : (A : Type) → [Fintype A] → [LinearOrder A] → Type v}
  [∀ (A : Type) [Fintype A] [LinearOrder A], AddCommGroup (P A)]
  [∀ (A : Type) [Fintype A] [LinearOrder A], Module R (P A)] [ShuffleOperad R P]

@[ext] lemma ext {I J : ShuffleOperadIdeal R P}
    (h : ∀ (A : Type) [Fintype A] [LinearOrder A], I.sub A = J.sub A) : I = J := by
  obtain ⟨I, _, _, _⟩ := I
  obtain ⟨J, _, _, _⟩ := J
  have : @I = @J := by
    funext A _ _
    exact h A
  subst this
  rfl

/-- **Shuffle ideals are ordered by inclusion**, input set by input set. -/
instance : PartialOrder (ShuffleOperadIdeal R P) where
  le I J := ∀ (A : Type) [Fintype A] [LinearOrder A], I.sub A ≤ J.sub A
  le_refl _ _ _ _ := le_rfl
  le_trans _ _ _ hIJ hJK A _ _ := (hIJ A).trans (hJK A)
  le_antisymm _ _ hIJ hJI := ext fun A _ _ => le_antisymm (hIJ A) (hJI A)

/-- **The intersection of a set of shuffle ideals is a shuffle ideal.** -/
def sInf (S : Set (ShuffleOperadIdeal R P)) : ShuffleOperadIdeal R P where
  sub A _ _ := ⨅ I ∈ S, I.sub A
  map_mem := by
    intro A B _ _ _ _ e x hx
    simp only [Submodule.mem_iInf] at hx ⊢
    exact fun I hI => I.map_mem e (hx I hI)
  comp_mem_left := by
    intro A B C _ _ _ _ _ _ i e he x y hx
    simp only [Submodule.mem_iInf] at hx ⊢
    exact fun I hI => I.comp_mem_left i e he y (hx I hI)
  comp_mem_right := by
    intro A B C _ _ _ _ _ _ i e he x y hy
    simp only [Submodule.mem_iInf] at hy ⊢
    exact fun I hI => I.comp_mem_right i e he x (hy I hI)

lemma mem_sInf {S : Set (ShuffleOperadIdeal R P)} {A : Type} [Fintype A] [LinearOrder A]
    {x : P A} : x ∈ (sInf S).sub A ↔ ∀ I ∈ S, x ∈ I.sub A := by
  simp only [sInf, Submodule.mem_iInf]

variable (R) in
/-- **The shuffle ideal generated** by elements `r A ⊆ P A`: the smallest ideal containing
them. -/
def span (r : ∀ (A : Type) [Fintype A] [LinearOrder A], Set (P A)) : ShuffleOperadIdeal R P :=
  sInf {I | ∀ (A : Type) [Fintype A] [LinearOrder A], r A ⊆ I.sub A}

variable {r : ∀ (A : Type) [Fintype A] [LinearOrder A], Set (P A)}

lemma subset_span (A : Type) [Fintype A] [LinearOrder A] : r A ⊆ (span R r).sub A :=
  fun _ hx => mem_sInf.2 fun _ hI => hI A hx

/-- **The generated ideal lies in an ideal exactly when the generators do.** -/
lemma span_le {I : ShuffleOperadIdeal R P} :
    span R r ≤ I ↔ ∀ (A : Type) [Fintype A] [LinearOrder A], r A ⊆ I.sub A :=
  ⟨fun h A _ _ _ hx => h A (subset_span A hx), fun h _ _ _ _ hx => mem_sInf.1 hx I h⟩

end ShuffleOperadIdeal

/-! ## Sorting -/

/-- **Sorting a finite type along an injective map into an ordered type.** -/
lemma exists_sort {A D : Type} [Fintype A] [LinearOrder D] (key : A → D)
    (hkey : Function.Injective key) :
    ∃ α : A ≃ Fin (Fintype.card A), StrictMono fun k => key (α.symm k) := by
  classical
  let s : Finset D := Finset.univ.image key
  have hs : s.card = Fintype.card A := by
    rw [Finset.card_image_of_injective _ hkey, Finset.card_univ]
  let φ : A ≃ s := Equiv.ofBijective
    (fun a => ⟨key a, Finset.mem_image_of_mem key (Finset.mem_univ a)⟩)
    ⟨fun a b h => hkey (congrArg Subtype.val h), fun ⟨d, hd⟩ => by
      obtain ⟨a, _, rfl⟩ := Finset.mem_image.1 hd
      exact ⟨a, rfl⟩⟩
  have hφ : ∀ y : s, key (φ.symm y) = y.1 := fun y =>
    congrArg Subtype.val (φ.apply_symm_apply y)
  refine ⟨φ.trans (s.orderIsoOfFin hs).symm.toEquiv, fun k l hkl => ?_⟩
  show key (φ.symm ((s.orderIsoOfFin hs) k)) < key (φ.symm ((s.orderIsoOfFin hs) l))
  rw [hφ, hφ]
  exact (s.orderIsoOfFin hs).strictMono hkl

/-- **Every bijection onto an ordered set is a shuffle once the inputs are numbered suitably.** -/
lemma exists_shuffle {A B D : Type} [Fintype A] [DecidableEq A] [Fintype B] [DecidableEq B]
    [LinearOrder D] (i : A) (h : Without A i ⊕ B ≃ D) :
    ∃ (α : A ≃ Fin (Fintype.card A)) (β : B ≃ Fin (Fintype.card B)),
      IsShuffle (α i) ((compEquiv α β i).symm.trans h) := by
  classical
  obtain ⟨β, hβ⟩ := exists_sort (fun b => h (Sum.inr b))
    fun b b' e => Sum.inr_injective (h.injective e)
  let m : WithTop D := Finset.univ.inf fun b => ((h (Sum.inr b) : D) : WithTop D)
  have hm : ∀ a : Without A i, m ≠ ((h (Sum.inl a) : D) : WithTop D) := by
    intro a hma
    rcases isEmpty_or_nonempty B with hB | hB
    · have : m = ⊤ := by
        simp only [m, Finset.univ_eq_empty, Finset.inf_empty]
      rw [this] at hma
      exact WithTop.top_ne_coe hma
    · obtain ⟨b, -, hb⟩ := Finset.exists_mem_eq_inf (Finset.univ : Finset B) Finset.univ_nonempty
        fun b => ((h (Sum.inr b) : D) : WithTop D)
      rw [show m = _ from hb] at hma
      exact Sum.inr_ne_inl (h.injective (WithTop.coe_injective hma))
  let key : A → WithTop D := fun a =>
    if ha : a = i then m else ((h (Sum.inl ⟨a, ha⟩) : D) : WithTop D)
  have key_ne : ∀ (a : A) (ha : a ≠ i), key a = ((h (Sum.inl ⟨a, ha⟩) : D) : WithTop D) :=
    fun a ha => dif_neg ha
  have key_i : key i = m := dif_pos rfl
  have hkey : Function.Injective key := by
    intro a a' haa
    by_cases ha : a = i <;> by_cases ha' : a' = i
    · rw [ha, ha']
    · rw [ha, key_i, key_ne a' ha'] at haa
      exact absurd haa (hm _)
    · rw [ha', key_i, key_ne a ha] at haa
      exact absurd haa.symm (hm _)
    · rw [key_ne a ha, key_ne a' ha'] at haa
      exact congrArg Subtype.val (Sum.inl_injective (h.injective (WithTop.coe_injective haa)))
  obtain ⟨α, hα⟩ := exists_sort key hkey
  refine ⟨α, β, ⟨fun a a' haa => ?_, fun b b' hbb => hβ hbb, fun a b hb => ?_⟩⟩
  · have h1 := hα haa
    dsimp only at h1
    rw [key_ne _ (fun e => a.2 (α.symm_apply_eq.mp e)),
      key_ne _ (fun e => a'.2 (α.symm_apply_eq.mp e))] at h1
    exact WithTop.coe_lt_coe.1 h1
  · have hmin : m = ((h (Sum.inr (β.symm b)) : D) : WithTop D) := by
      refine le_antisymm (Finset.inf_le (Finset.mem_univ _)) (Finset.le_inf fun b' _ => ?_)
      refine WithTop.coe_le_coe.2 ?_
      have hbb : b ≤ β b' := hb (β b')
      rcases hbb.lt_or_eq with hlt | heq
      · have := hβ hlt
        simp only [Equiv.symm_apply_apply] at this
        exact this.le
      · rw [heq, Equiv.symm_apply_apply]
    have hlt : a.1 < α i ↔ key (α.symm a.1) < key (α.symm (α i)) :=
      (hα.lt_iff_lt (a := a.1) (b := α i)).symm
    rw [Equiv.symm_apply_apply, key_i, hmin,
      key_ne _ (fun e => a.2 (α.symm_apply_eq.mp e)), WithTop.coe_lt_coe] at hlt
    exact hlt

/-! ## Relabelled composites are shuffle composites -/

namespace SymOperad

variable {R : Type u} [CommRing R]
  {P : (A : Type) → [Fintype A] → [DecidableEq A] → Type v}
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (P A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (P A)] [SymOperad R P]

/-- **A relabelled partial composite is a shuffle composite of relabelled operations.** -/
lemma map_comp_eq_shuffle {A B D : Type} [Fintype A] [DecidableEq A] [Fintype B] [DecidableEq B]
    [Fintype D] [LinearOrder D] (i : A) (h : Without A i ⊕ B ≃ D) (x : P A) (y : P B) :
    ∃ (α : A ≃ Fin (Fintype.card A)) (β : B ≃ Fin (Fintype.card B))
      (hs : IsShuffle (α i) ((compEquiv α β i).symm.trans h)),
      map (R := R) h (comp (R := R) i x y)
        = ShuffleOperad.comp (R := R) (P := Shuf P) (α i) _ hs (map (R := R) α x)
            (map (R := R) β y) := by
  obtain ⟨α, β, hs⟩ := exists_shuffle i h
  refine ⟨α, β, hs, ?_⟩
  rw [toShuffle_comp, ← map_comp, map_map']
  exact map_congr' (fun c => by simp) _

end SymOperad

/-! ## Generated ideals transported -/

namespace SymOperadIdeal

variable {R : Type u} [CommRing R]
  {P : (A : Type) → [Fintype A] → [DecidableEq A] → Type v}
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (P A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (P A)] [SymOperad R P]

/-- **All relabellings of relators**, on ordered input sets. -/
def relabelSet (r : ∀ n : ℕ, Set (P (Fin n))) (A : Type) [Fintype A] [LinearOrder A] :
    Set (Shuf P A) :=
  {x | ∃ (n : ℕ) (e : Fin n ≃ A) (y : P (Fin n)), y ∈ r n ∧ x = SymOperad.map (R := R) e y}

variable (r : ∀ n : ℕ, Set (P (Fin n)))

/-- The elements of the shuffle ideal generated by the relabellings of relators all of whose
relabellings stay in it: an ideal. -/
def stableSpan : ShuffleOperadIdeal R (Shuf P) where
  sub A _ _ :=
    { carrier := {x | ∀ (B : Type) [Fintype B] [LinearOrder B] (e : A ≃ B),
        SymOperad.map (R := R) e x ∈ (ShuffleOperadIdeal.span R (relabelSet (R := R) r)).sub B}
      add_mem' := fun {a b} hx hy B _ _ e => by
        convert Submodule.add_mem _ (hx B e) (hy B e) using 1
        exact map_add (SymOperad.map (R := R) e) a b
      zero_mem' := fun B _ _ e => by
        convert Submodule.zero_mem ((ShuffleOperadIdeal.span R (relabelSet (R := R) r)).sub B)
          using 1
        exact map_zero (SymOperad.map (R := R) (P := P) e)
      smul_mem' := fun c x hx B _ _ e => by
        convert Submodule.smul_mem _ c (hx B e) using 1
        exact map_smul (SymOperad.map (R := R) e) c x }
  map_mem := by
    intro A A' _ _ _ _ σ x hx B _ _ e
    show SymOperad.map (R := R) e (SymOperad.map (R := R) σ.toEquiv x) ∈ _
    rw [SymOperad.map_map']
    exact hx B _
  comp_mem_left := by
    intro A B' C _ _ _ _ _ _ i e₀ he₀ x y hx D _ _ f
    show SymOperad.map (R := R) f (SymOperad.map (R := R) e₀ (SymOperad.comp (R := R) i x y)) ∈ _
    rw [SymOperad.map_map']
    obtain ⟨α, β, hs, heq⟩ := SymOperad.map_comp_eq_shuffle (R := R) i (e₀.trans f) x y
    rw [heq]
    exact ShuffleOperadIdeal.comp_mem_left _ _ _ hs _ (hx _ α)
  comp_mem_right := by
    intro A B' C _ _ _ _ _ _ i e₀ he₀ x y hy D _ _ f
    show SymOperad.map (R := R) f (SymOperad.map (R := R) e₀ (SymOperad.comp (R := R) i x y)) ∈ _
    rw [SymOperad.map_map']
    obtain ⟨α, β, hs, heq⟩ := SymOperad.map_comp_eq_shuffle (R := R) i (e₀.trans f) x y
    rw [heq]
    exact ShuffleOperadIdeal.comp_mem_right _ _ _ hs _ (hy _ β)

/-- **The shuffle ideal generated by the relabellings of relators is stable under all
bijections**, not only the increasing ones. -/
lemma map_mem_span_relabel {A B : Type} [Fintype A] [LinearOrder A] [Fintype B] [LinearOrder B]
    (e : A ≃ B) {x : P A}
    (hx : x ∈ (ShuffleOperadIdeal.span R (relabelSet (R := R) r)).sub A) :
    SymOperad.map (R := R) e x ∈ (ShuffleOperadIdeal.span R (relabelSet (R := R) r)).sub B := by
  have hle : ShuffleOperadIdeal.span R (relabelSet (R := R) r) ≤ stableSpan r := by
    refine ShuffleOperadIdeal.span_le.2 fun A _ _ x hx B _ _ e => ?_
    obtain ⟨n, e', y, hy, rfl⟩ := hx
    rw [SymOperad.map_map']
    exact ShuffleOperadIdeal.subset_span B ⟨n, e'.trans e, y, hy, rfl⟩
  exact hle A hx B e

/-- The symmetric ideal of the operations whose standard numbering lies in the shuffle ideal
generated by the relabellings of the relators. -/
noncomputable def numbered : SymOperadIdeal R P where
  sub A _ _ :=
    (ShuffleOperadIdeal.span R (relabelSet (R := R) r)).sub (Fin (Fintype.card A)) |>.comap
      (SymOperad.map (R := R) (Fintype.equivFin A))
  map_mem := by
    intro A B _ _ _ _ e x hx
    simp only [Submodule.mem_comap] at hx ⊢
    rw [show SymOperad.map (R := R) (Fintype.equivFin B) (SymOperad.map (R := R) e x)
      = SymOperad.map (R := R) (((Fintype.equivFin A).symm.trans e).trans (Fintype.equivFin B))
          (SymOperad.map (R := R) (Fintype.equivFin A) x) by
        rw [SymOperad.map_map', SymOperad.map_map']
        exact SymOperad.map_congr' (fun a => by simp) _]
    exact map_mem_span_relabel r _ hx
  comp_mem_left := by
    intro A B _ _ _ _ i x y hx
    simp only [Submodule.mem_comap] at hx ⊢
    obtain ⟨α, β, hs, heq⟩ := SymOperad.map_comp_eq_shuffle (R := R) i
      (Fintype.equivFin (Without A i ⊕ B)) x y
    rw [heq]
    refine ShuffleOperadIdeal.comp_mem_left _ _ _ hs _ ?_
    rw [show SymOperad.map (R := R) α x = SymOperad.map (R := R) ((Fintype.equivFin A).symm.trans α)
        (SymOperad.map (R := R) (Fintype.equivFin A) x) by
      rw [SymOperad.map_map']
      exact SymOperad.map_congr' (fun a => by simp) _]
    exact map_mem_span_relabel r _ hx
  comp_mem_right := by
    intro A B _ _ _ _ i x y hy
    simp only [Submodule.mem_comap] at hy ⊢
    obtain ⟨α, β, hs, heq⟩ := SymOperad.map_comp_eq_shuffle (R := R) i
      (Fintype.equivFin (Without A i ⊕ B)) x y
    rw [heq]
    refine ShuffleOperadIdeal.comp_mem_right _ _ _ hs _ ?_
    rw [show SymOperad.map (R := R) β y = SymOperad.map (R := R) ((Fintype.equivFin B).symm.trans β)
        (SymOperad.map (R := R) (Fintype.equivFin B) y) by
      rw [SymOperad.map_map']
      exact SymOperad.map_congr' (fun a => by simp) _]
    exact map_mem_span_relabel r _ hy

/-- **The forgetful image of the ideal generated by relators is the shuffle ideal generated by
all their relabellings.** -/
theorem toShuffle_span :
    (span R r).toShuffle = ShuffleOperadIdeal.span R (relabelSet (R := R) r) := by
  refine le_antisymm ?_ (ShuffleOperadIdeal.span_le.2 ?_)
  · intro A _ _ x hx
    have hle : span R r ≤ numbered r := by
      refine span_le.2 fun n y hy => ?_
      simp only [numbered]
      exact ShuffleOperadIdeal.subset_span _ ⟨n, Fintype.equivFin (Fin n), y, hy, rfl⟩
    have h := hle A hx
    simp only [numbered, Submodule.mem_comap] at h
    have := map_mem_span_relabel r (Fintype.equivFin A).symm h
    rwa [SymOperad.map_map', Equiv.self_trans_symm, SymOperad.map_refl] at this
  · intro A _ _ x hx
    obtain ⟨n, e, y, hy, rfl⟩ := hx
    exact map_mem_span e hy

/-- **Presentations are transported**: the underlying shuffle operad of the operad presented by
relators is the shuffle operad presented by all their relabellings, by the identity maps of the
components. -/
noncomputable def toShuffleSpanQuot :
    ShuffleOperadHom R (Shuf (span R r).Quot)
      (ShuffleOperadIdeal.span R (relabelSet (R := R) r)).Quot where
  app A _ _ := (Submodule.quotEquivOfEq _ _ (by
    rw [← toShuffle_span r]
    rfl)).toLinearMap
  app_map e q := by
    obtain ⟨x, rfl⟩ := (span R r).proj_surjective _ q
    rfl
  app_one := rfl
  app_comp i e he p q := by
    obtain ⟨x, rfl⟩ := (span R r).proj_surjective _ p
    obtain ⟨y, rfl⟩ := (span R r).proj_surjective _ q
    rfl

lemma toShuffleSpanQuot_bijective (A : Type) [Fintype A] [LinearOrder A] :
    Function.Bijective ((toShuffleSpanQuot (R := R) r).app A) :=
  LinearEquiv.bijective _

end SymOperadIdeal

/-! ## Generation by the relabelled generators -/

namespace ShuffleOperadHom

variable {R : Type u} [CommRing R]
  {P : (A : Type) → [Fintype A] → [LinearOrder A] → Type v}
  [∀ (A : Type) [Fintype A] [LinearOrder A], AddCommGroup (P A)]
  [∀ (A : Type) [Fintype A] [LinearOrder A], Module R (P A)] [ShuffleOperad R P]
  {Q : (A : Type) → [Fintype A] → [LinearOrder A] → Type w}
  [∀ (A : Type) [Fintype A] [LinearOrder A], AddCommGroup (Q A)]
  [∀ (A : Type) [Fintype A] [LinearOrder A], Module R (Q A)] [ShuffleOperad R Q]

/-- Two morphisms with the same components are equal. -/
@[ext] lemma ext {φ ψ : ShuffleOperadHom R P Q}
    (h : ∀ (A : Type) [Fintype A] [LinearOrder A] (x : P A), φ.app A x = ψ.app A x) :
    φ = ψ := by
  obtain ⟨φa, _, _, _⟩ := φ
  obtain ⟨ψa, _, _, _⟩ := ψ
  have : @φa = @ψa := by
    funext A _ _
    exact LinearMap.ext (h A)
  subst this
  rfl

/-- The composite of morphisms. -/
def comp {P' : (A : Type) → [Fintype A] → [LinearOrder A] → Type v}
    [∀ (A : Type) [Fintype A] [LinearOrder A], AddCommGroup (P' A)]
    [∀ (A : Type) [Fintype A] [LinearOrder A], Module R (P' A)] [ShuffleOperad R P']
    (ψ : ShuffleOperadHom R P Q) (φ : ShuffleOperadHom R P' P) : ShuffleOperadHom R P' Q where
  app A _ _ := ψ.app A ∘ₗ φ.app A
  app_map e x := by simp [φ.app_map, ψ.app_map]
  app_one := by simp [φ.app_one, ψ.app_one]
  app_comp i e he x y := by simp [φ.app_comp, ψ.app_comp]

end ShuffleOperadHom

/-- An order isomorphism between ordered sets with at most one element. -/
def orderIsoOfSubsingleton {A B : Type} [LinearOrder A] [LinearOrder B] [Subsingleton A]
    (e : A ≃ B) : A ≃o B :=
  ⟨e, fun {a b} => by
    rw [Subsingleton.elim a b]
    simp⟩

namespace Pres

variable {R : Type u} [CommRing R] {T : ℕ → Type w}
  {ρ : ∀ {A : Type} [Fintype A] [DecidableEq A], Syn T A → Syn T A → Prop}
  {Q : (A : Type) → [Fintype A] → [LinearOrder A] → Type v}
  [∀ (A : Type) [Fintype A] [LinearOrder A], AddCommGroup (Q A)]
  [∀ (A : Type) [Fintype A] [LinearOrder A], Module R (Q A)] [ShuffleOperad R Q]

/-- **The underlying shuffle operad of a presented operad is generated by the relabelled
generators**: two morphisms of shuffle operads agreeing on them agree. -/
theorem shuffle_hom_ext {φ ψ : ShuffleOperadHom R (Shuf (Lin R (Pres T ρ))) Q}
    (h : ∀ (n : ℕ) (g : T n) (σ : Equiv.Perm (Fin n)),
      φ.app (Fin n) (Finsupp.single (SetOperad.map σ (gen g)) 1)
        = ψ.app (Fin n) (Finsupp.single (SetOperad.map σ (gen g)) 1)) : φ = ψ := by
  have key : ∀ {A : Type} [Fintype A] [DecidableEq A] (x : Syn T A) (B : Type) [Fintype B]
      [LinearOrder B] (e : A ≃ B),
      φ.app B (Finsupp.single (SetOperad.map e (mk (ρ := ρ) x)) 1)
        = ψ.app B (Finsupp.single (SetOperad.map e (mk (ρ := ρ) x)) 1) := by
    intro A _ _ x
    induction x with
    | one =>
      intro B _ _ e
      have hsub : Subsingleton B := e.symm.subsingleton
      let o : Unit ≃o B := orderIsoOfSubsingleton e
      have hx : (Finsupp.single (SetOperad.map e (mk (ρ := ρ) Syn.one)) (1 : R)
          : Shuf (Lin R (Pres T ρ)) B)
          = ShuffleOperad.map (R := R) (P := Shuf (Lin R (Pres T ρ))) o
              (ShuffleOperad.one R) := by
        show _ = Finsupp.mapDomain _ (Finsupp.single _ 1)
        rw [Finsupp.mapDomain_single]
        rfl
      rw [hx, φ.app_map, ψ.app_map, φ.app_one, ψ.app_one]
    | @gen n g =>
      intro B _ _ e
      let o : Fin n ≃o B := Fintype.orderIsoFinOfCardEq B (by
        rw [← Fintype.card_fin n, Fintype.card_congr e])
      have hx : (Finsupp.single (SetOperad.map e (mk (ρ := ρ) (Syn.gen g))) (1 : R)
          : Shuf (Lin R (Pres T ρ)) B)
          = ShuffleOperad.map (R := R) (P := Shuf (Lin R (Pres T ρ))) o
              (Finsupp.single (SetOperad.map (e.trans o.symm.toEquiv) (gen g)) 1) := by
        show _ = Finsupp.mapDomain _ (Finsupp.single _ 1)
        rw [Finsupp.mapDomain_single, ← SetOperad.map_trans]
        congr 2
        exact Equiv.ext fun k => by simp
      rw [hx, φ.app_map, ψ.app_map]
      exact congrArg _ (h n g _)
    | @map A' A _ _ _ _ f x ih =>
      intro B _ _ e
      rw [show (mk (ρ := ρ) (Syn.map f x) : Pres T ρ A) = SetOperad.map f (mk x) from rfl,
        ← SetOperad.map_trans]
      exact ih B (f.trans e)
    | @comp A₁ A₂ _ _ _ _ i x y ihx ihy =>
      intro B _ _ e
      have hx : (Finsupp.single (SetOperad.map e (mk (ρ := ρ) (Syn.comp i x y))) (1 : R)
          : Lin R (Pres T ρ) B)
          = SymOperad.map (R := R) (P := Lin R (Pres T ρ)) e (SymOperad.comp (R := R) i
              (Finsupp.single (mk (ρ := ρ) x) 1) (Finsupp.single (mk (ρ := ρ) y) 1)) := by
        show _ = Lin.mapL R e (Lin.compL R i _ _)
        rw [Lin.compL_single, Lin.mapL_single, mul_one]
        rfl
      obtain ⟨α, β, hs, heq⟩ := SymOperad.map_comp_eq_shuffle (R := R) (P := Lin R (Pres T ρ)) i e
        (Finsupp.single (mk (ρ := ρ) x) 1) (Finsupp.single (mk (ρ := ρ) y) 1)
      rw [hx, heq, φ.app_comp, ψ.app_comp]
      have e1 : (SymOperad.map (R := R) α (Finsupp.single (mk (ρ := ρ) x) (1 : R))
          : Lin R (Pres T ρ) _) = Finsupp.single (SetOperad.map α (mk x)) 1 :=
        Lin.mapL_single α _ 1
      have e2 : (SymOperad.map (R := R) β (Finsupp.single (mk (ρ := ρ) y) (1 : R))
          : Lin R (Pres T ρ) _) = Finsupp.single (SetOperad.map β (mk y)) 1 :=
        Lin.mapL_single β _ 1
      rw [e1, e2, ihx _ α, ihy _ β]
  refine ShuffleOperadHom.ext fun A _ _ z => ?_
  refine Lin.induction₁ (φ.app A) (ψ.app A) (fun s => ?_) z
  obtain ⟨x, rfl⟩ := mk_surjective s
  have := key x A (Equiv.refl A)
  rwa [SetOperad.map_refl] at this

end Pres

namespace SymOperadIdeal

variable {R : Type u} [CommRing R] {T : ℕ → Type w}
  {ρ : ∀ {A : Type} [Fintype A] [DecidableEq A], Syn T A → Syn T A → Prop}
  (I : SymOperadIdeal R (Lin R (Pres T ρ)))
  {Q : (A : Type) → [Fintype A] → [LinearOrder A] → Type v}
  [∀ (A : Type) [Fintype A] [LinearOrder A], AddCommGroup (Q A)]
  [∀ (A : Type) [Fintype A] [LinearOrder A], Module R (Q A)] [ShuffleOperad R Q]

/-- The projection onto a quotient, as a morphism of the underlying shuffle operads. -/
noncomputable def projShuffle : ShuffleOperadHom R (Shuf (Lin R (Pres T ρ))) (Shuf I.Quot) :=
  I.projHom.toShuffle

/-- **The underlying shuffle operad of an operad presented by generators and linear relators is
generated by the relabelled generators.** -/
theorem shuffle_hom_ext {φ ψ : ShuffleOperadHom R (Shuf I.Quot) Q}
    (h : ∀ (n : ℕ) (g : T n) (σ : Equiv.Perm (Fin n)),
      φ.app (Fin n) (I.proj _ (Finsupp.single (SetOperad.map σ (Pres.gen g)) 1))
        = ψ.app (Fin n) (I.proj _ (Finsupp.single (SetOperad.map σ (Pres.gen g)) 1))) :
    φ = ψ := by
  have := Pres.shuffle_hom_ext (φ := φ.comp (projShuffle I)) (ψ := ψ.comp (projShuffle I)) h
  refine ShuffleOperadHom.ext fun A _ _ q => ?_
  obtain ⟨x, rfl⟩ := I.proj_surjective A q
  exact congrArg (fun F : ShuffleOperadHom R (Shuf (Lin R (Pres T ρ))) Q => F.app A x) this

end SymOperadIdeal

end Operad
