/-
# Substitution at a window of a shuffle monomial

The ideal of a free shuffle operad generated by relators of arity three is spanned by the
monomials in which one window has been replaced by a relator. This file has the substitution and
its compatibility with the path-lexicographic order, which is what the division algorithm needs.

* `LTree.subtreeAt`, `LTree.replaceAt`: the subtree at a path from the root (`false` for the
  first slot), and its replacement.
* `LTree.plug ins m`: the trees `ins k` grafted onto the leaves `k` of `m`.
* **The edges** of a monomial are the pairs `(p, s)` of a vertex, at the path `p`, and a slot `s`
  holding a vertex (`IsEdge`); `windowAt t p s` is the window of that edge, and every window of
  `t` is one of those (`mem_windows_iff`).
* **Substitution** `t.substAt p s m` replaces the window of the edge by the arity-three monomial
  `m`, the three inputs of the window grafted onto the leaves `0, 1, 2` of `m` in the order of
  their least labels (`winIns`). It gives back `t` for the window itself (`substAt_windowAt`),
  and a shuffle monomial on the same labels for any shuffle monomial `m` on `0, 1, 2`
  (`isShuffle_substAt`, `perm_labels_substAt`).
* **Compatibility with the order** (`pathKey_substAt_lt`): substituting a monomial with a smaller
  path-lexicographic key gives a monomial with a smaller key. The path of a leaf below the window
  is the path to the window, followed by the path in `m` to the input containing it, followed by
  the path inside that input (`path_substAt_of_mem`); the leaf with the least label in the first
  input whose path changes is where the two keys first differ.
-/
import Operad.ShuffleTree
import Mathlib.Tactic.IntervalCases

universe v

namespace Operad

namespace LTree

variable {E : Type v}

/-! ## Lexicographic order on lists -/

section Lex

variable {α : Type*} [LinearOrder α]

lemma cons_lt_cons_self_iff (c : α) (x y : List α) : c :: x < c :: y ↔ x < y := by
  rw [List.cons_lt_cons_iff]
  simp

lemma append_lt_append_left_iff (c x y : List α) : c ++ x < c ++ y ↔ x < y := by
  induction c with
  | nil => rfl
  | cons a c ih => rw [List.cons_append, List.cons_append, cons_lt_cons_self_iff, ih]

/-- Comparing two lists of the same length decides the comparison of any extensions. -/
lemma append_lt_append_of_length_eq {x y : List α} (hxy : x.length = y.length) (h : x < y)
    (u v : List α) : x ++ u < y ++ v := by
  induction x generalizing y with
  | nil =>
    cases y with
    | nil => exact absurd h (lt_irrefl _)
    | cons => simp at hxy
  | cons a x ih =>
    cases y with
    | nil => simp at hxy
    | cons b y =>
      rw [List.cons_lt_cons_iff] at h
      rw [List.cons_append, List.cons_append, List.cons_lt_cons_iff]
      rcases h with h | ⟨rfl, h⟩
      · exact Or.inl h
      · exact Or.inr ⟨rfl, ih (by simpa using hxy) h⟩

/-- **Lists of values on `0, …, n - 1`** are compared at the first index where they differ. -/
lemma map_range_lt_iff (f g : ℕ → α) (n : ℕ) :
    (List.range n).map f < (List.range n).map g ↔
      ∃ i < n, (∀ j < i, f j = g j) ∧ f i < g i := by
  induction n generalizing f g with
  | zero => simp
  | succ n ih =>
    rw [List.range_succ_eq_map, List.map_cons, List.map_cons, List.map_map, List.map_map,
      List.cons_lt_cons_iff, ih]
    constructor
    · rintro (h | ⟨h0, i, hi, hlt, h⟩)
      · exact ⟨0, n.succ_pos, fun j hj => absurd hj (Nat.not_lt_zero j), h⟩
      · refine ⟨i + 1, by omega, fun j hj => ?_, h⟩
        rcases j with _ | j
        · exact h0
        · exact hlt j (by omega)
    · rintro ⟨i, hi, hlt, h⟩
      rcases i with _ | i
      · exact Or.inl h
      · exact Or.inr ⟨hlt 0 (by omega), i, by omega, fun j hj => hlt (j + 1) (by omega), h⟩

/-- A list is **length-coded** when its head is the length of its tail. -/
def LengthCoded (x : List ℕ) : Prop := ∃ y, x = y.length :: y

/-- Two different length-coded lists compare like any extensions of them. -/
lemma append_lt_append_of_lengthCoded {x y : List ℕ} (hx : LengthCoded x) (hy : LengthCoded y)
    (h : x < y) (u v : List ℕ) : x ++ u < y ++ v := by
  obtain ⟨x, rfl⟩ := hx
  obtain ⟨y, rfl⟩ := hy
  rw [List.cons_lt_cons_iff] at h
  rw [List.cons_append, List.cons_append, List.cons_lt_cons_iff]
  rcases h with h | ⟨hl, h⟩
  · exact Or.inl h
  · exact Or.inr ⟨hl, append_lt_append_of_length_eq hl h u v⟩

/-- **Concatenations of length-coded lists** compare like the lists of lists. -/
lemma flatten_lt_flatten_iff {a b : List (List ℕ)} (hab : a.length = b.length)
    (ha : ∀ x ∈ a, LengthCoded x) (hb : ∀ x ∈ b, LengthCoded x) :
    a.flatten < b.flatten ↔ a < b := by
  induction a generalizing b with
  | nil =>
    cases b with
    | nil => simp
    | cons => simp at hab
  | cons x a ih =>
    cases b with
    | nil => simp at hab
    | cons y b =>
      have ha' : ∀ z ∈ a, LengthCoded z := fun z hz => ha z (List.mem_cons_of_mem _ hz)
      have hb' : ∀ z ∈ b, LengthCoded z := fun z hz => hb z (List.mem_cons_of_mem _ hz)
      have hab' : a.length = b.length := by simpa using hab
      rw [List.flatten_cons, List.flatten_cons, List.cons_lt_cons_iff]
      rcases lt_trichotomy x y with hxy | rfl | hxy
      · simp only [hxy, true_or, iff_true]
        exact append_lt_append_of_lengthCoded (ha x (by simp)) (hb y (by simp)) hxy _ _
      · rw [append_lt_append_left_iff, ih hab' ha' hb']
        simp
      · simp only [not_lt_of_gt hxy, false_or, ne_of_gt hxy, false_and, iff_false]
        exact not_lt_of_gt
          (append_lt_append_of_lengthCoded (hb y (by simp)) (ha x (by simp)) hxy _ _)

end Lex

/-! ## Subtrees, replacement and grafting -/

/-- **The subtree at a path** from the root, `false` for the first slot. -/
def subtreeAt : LTree E → List Bool → LTree E
  | t, [] => t
  | leaf a, _ :: _ => leaf a
  | node _ l _, false :: p => l.subtreeAt p
  | node _ _ r, true :: p => r.subtreeAt p

/-- **Replace the subtree at a path.** -/
def replaceAt : LTree E → List Bool → LTree E → LTree E
  | _, [], u => u
  | leaf a, _ :: _, _ => leaf a
  | node e l r, false :: p, u => node e (l.replaceAt p u) r
  | node e l r, true :: p, u => node e l (r.replaceAt p u)

/-- The decorations on a path from the root, the vertex at its end excluded. -/
def decAt : LTree E → List Bool → List E
  | _, [] => []
  | leaf _, _ :: _ => []
  | node e l _, false :: p => e :: l.decAt p
  | node e _ r, true :: p => e :: r.decAt p

/-- **Graft trees onto the leaves**: the leaf `k` becomes `ins k`. -/
def plug (ins : ℕ → LTree E) : LTree E → LTree E
  | leaf a => ins a
  | node e l r => node e (l.plug ins) (r.plug ins)

@[simp] lemma subtreeAt_nil (t : LTree E) : t.subtreeAt [] = t := by cases t <;> rfl

@[simp] lemma replaceAt_nil (t u : LTree E) : t.replaceAt [] u = u := by cases t <;> rfl

lemma replaceAt_subtreeAt : ∀ (t : LTree E) (p : List Bool), t.replaceAt p (t.subtreeAt p) = t
  | leaf _, [] => rfl
  | leaf _, _ :: _ => rfl
  | node _ _ _, [] => rfl
  | node e l r, false :: p => by
    simp only [replaceAt, subtreeAt, replaceAt_subtreeAt l p]
  | node e l r, true :: p => by
    simp only [replaceAt, subtreeAt, replaceAt_subtreeAt r p]

/-- A vertex sits at the end of a path only if the path stays inside the tree. -/
lemma labels_replaceAt_perm : ∀ (t : LTree E) (p : List Bool) (u : LTree E),
    (∃ e l r, t.subtreeAt p = node e l r) → u.labels.Perm (t.subtreeAt p).labels →
    (t.replaceAt p u).labels.Perm t.labels
  | leaf _, [], _, _, h => by simpa using h
  | leaf _, _ :: _, _, ⟨_, _, _, h⟩, _ => by simp [subtreeAt] at h
  | node _ _ _, [], _, _, h => by simpa using h
  | node e l r, false :: p, u, hv, h => by
    simp only [replaceAt, labels_node]
    exact (labels_replaceAt_perm l p u hv h).append_right _
  | node e l r, true :: p, u, hv, h => by
    simp only [replaceAt, labels_node]
    exact (labels_replaceAt_perm r p u hv h).append_left _

lemma labels_subtreeAt_subset : ∀ (t : LTree E) (p : List Bool),
    (t.subtreeAt p).labels ⊆ t.labels
  | leaf _, [] => fun _ h => h
  | leaf _, _ :: _ => fun _ h => h
  | node _ _ _, [] => fun _ h => h
  | node _ l _, false :: p => fun _ h => by
    simp only [labels_node, List.mem_append]
    exact Or.inl (labels_subtreeAt_subset l p h)
  | node _ _ r, true :: p => fun _ h => by
    simp only [labels_node, List.mem_append]
    exact Or.inr (labels_subtreeAt_subset r p h)

/-- **The path to a leaf below a vertex** goes through the vertex. -/
lemma path_of_mem_subtreeAt {i : ℕ} : ∀ (t : LTree E) (p : List Bool), t.labels.Nodup →
    i ∈ (t.subtreeAt p).labels → t.path i = t.decAt p ++ (t.subtreeAt p).path i
  | leaf _, [], _, _ => rfl
  | leaf _, _ :: _, _, _ => rfl
  | node _ _ _, [], _, _ => rfl
  | node e l r, false :: p, hnd, hi => by
    have hl : i ∈ l.labels := labels_subtreeAt_subset l p hi
    simp only [path, subtreeAt, decAt, hl, if_true, List.cons_append]
    rw [path_of_mem_subtreeAt l p (List.nodup_append.1 hnd).1 hi]
  | node e l r, true :: p, hnd, hi => by
    have hr : i ∈ r.labels := labels_subtreeAt_subset r p hi
    have hl : i ∉ l.labels := fun hl => (List.nodup_append.1 hnd).2.2 i hl i hr rfl
    simp only [path, subtreeAt, decAt, hl, if_false, List.cons_append]
    rw [path_of_mem_subtreeAt r p (List.nodup_append.1 hnd).2.1 hi]

/-- The path to a leaf of the replacing tree. -/
lemma path_replaceAt_of_mem {i : ℕ} : ∀ (t : LTree E) (p : List Bool) (u : LTree E),
    t.labels.Nodup → (∃ e l r, t.subtreeAt p = node e l r) →
    u.labels.Perm (t.subtreeAt p).labels → i ∈ u.labels →
    (t.replaceAt p u).path i = t.decAt p ++ u.path i
  | leaf _, [], _, _, _, _, _ => rfl
  | leaf _, _ :: _, _, _, ⟨_, _, _, h⟩, _, _ => by simp [subtreeAt] at h
  | node _ _ _, [], _, _, _, _, _ => rfl
  | node e l r, false :: p, u, hnd, hv, hu, hi => by
    have hl : i ∈ (l.replaceAt p u).labels :=
      (labels_replaceAt_perm l p u hv hu).symm.subset (labels_subtreeAt_subset l p (hu.subset hi))
    simp only [replaceAt, path, decAt, hl, if_true, List.cons_append]
    rw [path_replaceAt_of_mem l p u (List.nodup_append.1 hnd).1 hv hu hi]
  | node e l r, true :: p, u, hnd, hv, hu, hi => by
    have hr : i ∈ r.labels := labels_subtreeAt_subset r p (hu.subset hi)
    have hl : i ∉ l.labels := fun hl => (List.nodup_append.1 hnd).2.2 i hl i hr rfl
    simp only [replaceAt, path, decAt, hl, if_false, List.cons_append]
    rw [path_replaceAt_of_mem r p u (List.nodup_append.1 hnd).2.1 hv hu hi]

/-- The path to a leaf away from the replaced subtree is unchanged. -/
lemma path_replaceAt_of_not_mem {i : ℕ} : ∀ (t : LTree E) (p : List Bool) (u : LTree E),
    t.labels.Nodup → (∃ e l r, t.subtreeAt p = node e l r) →
    u.labels.Perm (t.subtreeAt p).labels → i ∈ t.labels → i ∉ (t.subtreeAt p).labels →
    (t.replaceAt p u).path i = t.path i
  | leaf _, [], _, _, _, _, hi, hi' => absurd hi hi'
  | leaf _, _ :: _, _, _, ⟨_, _, _, h⟩, _, _, _ => by simp [subtreeAt] at h
  | node _ _ _, [], _, _, _, _, hi, hi' => absurd hi hi'
  | node e l r, false :: p, u, hnd, hv, hu, hi, hi' => by
    have hp := labels_replaceAt_perm l p u hv hu
    simp only [replaceAt, path]
    by_cases hl : i ∈ l.labels
    · simp only [hp.mem_iff, hl, if_true]
      rw [path_replaceAt_of_not_mem l p u (List.nodup_append.1 hnd).1 hv hu hl hi']
    · simp only [hp.mem_iff, hl, if_false]
  | node e l r, true :: p, u, hnd, hv, hu, hi, hi' => by
    simp only [replaceAt, path]
    by_cases hl : i ∈ l.labels
    · simp only [hl, if_true]
    · have hr : i ∈ r.labels := by
        simp only [labels_node, List.mem_append, hl, false_or] at hi
        exact hi
      simp only [hl, if_false]
      rw [path_replaceAt_of_not_mem r p u (List.nodup_append.1 hnd).2.1 hv hu hr hi']

lemma labels_plug (ins : ℕ → LTree E) :
    ∀ m : LTree E, (m.plug ins).labels = m.labels.flatMap fun k => (ins k).labels
  | leaf a => by simp [plug]
  | node e l r => by
    simp only [plug, labels_node, List.flatMap_append, labels_plug ins l, labels_plug ins r]

/-- **The path to a leaf of a grafted tree**: through the leaf it is grafted on. -/
lemma path_plug (ins : ℕ → LTree E) {N : ℕ}
    (hdisj : ∀ k < N, ∀ k' < N, k ≠ k' → ∀ i ∈ (ins k).labels, i ∉ (ins k').labels) {i k : ℕ}
    (hk : k < N) (hi : i ∈ (ins k).labels) :
    ∀ m : LTree E, (∀ a ∈ m.labels, a < N) → m.labels.Nodup → k ∈ m.labels →
      (m.plug ins).path i = m.path k ++ (ins k).path i
  | leaf a, _, _, hkm => by
    simp only [labels_leaf, List.mem_singleton] at hkm
    subst hkm
    rfl
  | node e l r, hN, hnd, hkm => by
    have hNl : ∀ a ∈ l.labels, a < N := fun a ha => hN a (by simp [ha])
    have hNr : ∀ a ∈ r.labels, a < N := fun a ha => hN a (by simp [ha])
    have hiff : i ∈ (l.plug ins).labels ↔ k ∈ l.labels := by
      rw [labels_plug, List.mem_flatMap]
      constructor
      · rintro ⟨k', hk', hik'⟩
        by_cases hkk : k = k'
        · exact hkk ▸ hk'
        · exact absurd hik' (hdisj k hk k' (hNl k' hk') hkk i hi)
      · exact fun hk => ⟨k, hk, hi⟩
    simp only [plug, path, hiff]
    by_cases hkl : k ∈ l.labels
    · simp only [hkl, if_true, List.cons_append]
      rw [path_plug ins hdisj hk hi l hNl (List.nodup_append.1 hnd).1 hkl]
    · have hkr : k ∈ r.labels := by
        simp only [labels_node, List.mem_append, hkl, false_or] at hkm
        exact hkm
      simp only [hkl, if_false, List.cons_append]
      rw [path_plug ins hdisj hk hi r hNr (List.nodup_append.1 hnd).2.1 hkr]

/-! ## Edges and windows -/

/-- The root of a tree has an edge into the slot `s`: that slot holds a vertex. -/
def IsEdgeRoot : LTree E → Bool → Prop
  | node _ (node _ _ _) _, false => True
  | node _ _ (node _ _ _), true => True
  | _, _ => False

/-- The window of the edge into the slot `s` of the root (a leaf when there is none). -/
def windowRoot : LTree E → Bool → LTree E
  | node e (node f a b) c, false => window e f false a.minLabel b.minLabel c.minLabel
  | node e c (node f a b), true => window e f true a.minLabel b.minLabel c.minLabel
  | _, _ => leaf 0

/-- **An edge** of a tree: a vertex, at the path `p`, whose slot `s` holds a vertex. -/
def IsEdge (t : LTree E) (p : List Bool) (s : Bool) : Prop := (t.subtreeAt p).IsEdgeRoot s

/-- **The window of an edge.** -/
def windowAt (t : LTree E) (p : List Bool) (s : Bool) : LTree E := (t.subtreeAt p).windowRoot s

lemma IsEdge.exists_node {t : LTree E} {p : List Bool} {s : Bool} (h : t.IsEdge p s) :
    ∃ e l r, t.subtreeAt p = node e l r := by
  unfold IsEdge at h
  generalize t.subtreeAt p = u at h
  match u, s, h with
  | node e l r, _, _ => exact ⟨e, l, r, rfl⟩

/-- **The windows of a tree are those of its edges.** -/
theorem mem_windows_iff {w : LTree E} :
    ∀ t : LTree E, w ∈ t.windows ↔ ∃ p s, t.IsEdge p s ∧ t.windowAt p s = w
  | leaf a => by
    simp only [windows, List.not_mem_nil, false_iff, not_exists, not_and]
    intro p s h
    cases p <;> cases s <;> simp [IsEdge, IsEdgeRoot, subtreeAt] at h
  | node e l r => by
    constructor
    · intro hw
      simp only [windows, List.mem_append] at hw
      rcases hw with ((hw | hw) | hw) | hw
      · match l, hw with
        | node f a b, hw =>
          refine ⟨[], false, trivial, ?_⟩
          simp only [List.mem_singleton] at hw
          simp [windowAt, windowRoot, hw]
      · match r, hw with
        | node f a b, hw =>
          refine ⟨[], true, ?_, ?_⟩
          · show IsEdgeRoot (node e l (node f a b)) true
            cases l <;> trivial
          · show windowRoot (node e l (node f a b)) true = w
            simp only [List.mem_singleton] at hw
            cases l <;> simp [windowRoot, hw]
      · obtain ⟨p, s, hp, rfl⟩ := (mem_windows_iff l).1 hw
        exact ⟨false :: p, s, hp, rfl⟩
      · obtain ⟨p, s, hp, rfl⟩ := (mem_windows_iff r).1 hw
        exact ⟨true :: p, s, hp, rfl⟩
    · rintro ⟨p, s, hp, rfl⟩
      simp only [windows, List.mem_append]
      rcases p with _ | ⟨_ | _, p⟩
      · rcases s with _ | _
        · match l, hp with
          | leaf _, hp => simp [IsEdge, IsEdgeRoot] at hp
          | node f a b, _ => simp [windowAt, windowRoot]
        · match r, hp with
          | leaf _, hp => cases l <;> simp [IsEdge, IsEdgeRoot] at hp
          | node f a b, _ =>
            left; left; right
            cases l <;> simp [windowAt, windowRoot]
      · exact Or.inl (Or.inr ((mem_windows_iff l).2 ⟨p, s, hp, rfl⟩))
      · exact Or.inr ((mem_windows_iff r).2 ⟨p, s, hp, rfl⟩)

/-! ## Substitution -/

/-- Three trees, at `0`, `1` and `2`. -/
def ins3 (x y z : LTree E) (k : ℕ) : LTree E := if k = 0 then x else if k = 1 then y else z

/-- **The inputs of the window** of the edge into the slot `s` of the root, in the order of their
least labels on a shuffle monomial: the two inputs of the lower vertex and the other input of the
upper one. -/
def winInputs : LTree E → Bool → LTree E × LTree E × LTree E
  | node _ (node _ a b) c, false => if b.minLabel < c.minLabel then (a, b, c) else (a, c, b)
  | node _ c (node _ a b), true => (c, a, b)
  | t, _ => (t, t, t)

/-- The inputs of the window, at `0, 1, 2`. -/
def winIns (u : LTree E) (s : Bool) : ℕ → LTree E :=
  ins3 (u.winInputs s).1 (u.winInputs s).2.1 (u.winInputs s).2.2

/-- **Substitution at a window**: the window of the edge `(p, s)` replaced by `m`, the inputs of
the window grafted onto the leaves `0, 1, 2` of `m`. -/
def substAt (t : LTree E) (p : List Bool) (s : Bool) (m : LTree E) : LTree E :=
  t.replaceAt p (m.plug ((t.subtreeAt p).winIns s))

lemma minLabel_eq_of_perm {t u : LTree E} (h : t.labels.Perm u.labels) :
    t.minLabel = u.minLabel :=
  le_antisymm (minLabel_le_of_mem t (h.symm.subset (minLabel_mem u)))
    (minLabel_le_of_mem u (h.subset (minLabel_mem t)))

lemma ne_of_nodup_append {l₁ l₂ : List ℕ} (h : (l₁ ++ l₂).Nodup) {a b : ℕ} (ha : a ∈ l₁)
    (hb : b ∈ l₂) : a ≠ b :=
  fun hab => (List.nodup_append.1 h).2.2 a ha b hb hab

/-- The facts about the inputs of a window that substitution needs: they are shuffle monomials,
in increasing order of least labels, and their labels are those of the vertex. -/
structure WinSpec (u : LTree E) (s : Bool) : Prop where
  shuffle : ∀ k, (u.winIns s k).IsShuffle
  lt01 : (u.winIns s 0).minLabel < (u.winIns s 1).minLabel
  lt12 : (u.winIns s 1).minLabel < (u.winIns s 2).minLabel
  perm : u.labels.Perm ((u.winIns s 0).labels ++ (u.winIns s 1).labels ++ (u.winIns s 2).labels)
  window : (u.windowRoot s).plug (u.winIns s) = u

lemma ins3_eq_of_ne {x y z : LTree E} {k : ℕ} (h0 : k ≠ 0) (h1 : k ≠ 1) : ins3 x y z k = z := by
  simp [ins3, h0, h1]

theorem winSpec {u : LTree E} {s : Bool} (he : u.IsEdgeRoot s) (hs : u.IsShuffle)
    (hnd : u.labels.Nodup) : u.WinSpec s := by
  match u, s, he with
  | node e (node f a b) c, false, _ =>
    obtain ⟨h1, ⟨h2, ha, hb⟩, hc⟩ := hs
    simp only [minLabel_node] at h1
    have hab : a.minLabel < b.minLabel := h2
    have hac : a.minLabel < c.minLabel := by
      rw [min_eq_left hab.le] at h1
      exact h1
    have hbc : b.minLabel ≠ c.minLabel := by
      simp only [labels_node] at hnd
      exact ne_of_nodup_append hnd (List.mem_append.2 (Or.inr (minLabel_mem b))) (minLabel_mem c)
    have e0 : rank3 a.minLabel b.minLabel c.minLabel a.minLabel = 0 := by
      simp only [rank3]
      split_ifs <;> omega
    by_cases hbc' : b.minLabel < c.minLabel
    · have e1 : rank3 a.minLabel b.minLabel c.minLabel b.minLabel = 1 := by
        simp only [rank3]
        split_ifs <;> omega
      have e2 : rank3 a.minLabel b.minLabel c.minLabel c.minLabel = 2 := by
        simp only [rank3]
        split_ifs <;> omega
      refine ⟨fun k => ?_, ?_, ?_, ?_, ?_⟩
      · simp only [winIns, winInputs, hbc', if_true, ins3]
        split_ifs
        exacts [ha, hb, hc]
      · simpa [winIns, winInputs, hbc', ins3] using hab
      · simp [winIns, winInputs, hbc', ins3]
      · simp [winIns, winInputs, hbc', ins3, List.append_assoc]
      · simp [windowRoot, window, winIns, winInputs, hbc', ins3, plug, e0, e1, e2]
    · have hcb : c.minLabel < b.minLabel := lt_of_le_of_ne (not_lt.1 hbc') (Ne.symm hbc)
      have e1 : rank3 a.minLabel b.minLabel c.minLabel b.minLabel = 2 := by
        simp only [rank3]
        split_ifs <;> omega
      have e2 : rank3 a.minLabel b.minLabel c.minLabel c.minLabel = 1 := by
        simp only [rank3]
        split_ifs <;> omega
      refine ⟨fun k => ?_, ?_, ?_, ?_, ?_⟩
      · simp only [winIns, winInputs, hbc', if_false, ins3]
        split_ifs
        exacts [ha, hc, hb]
      · simpa [winIns, winInputs, hbc', ins3] using hac
      · simpa [winIns, winInputs, hbc', ins3] using hcb
      · simp only [winIns, winInputs, hbc', if_false, ins3, labels_node, if_true,
          one_ne_zero, OfNat.ofNat_ne_zero, OfNat.ofNat_ne_one, List.append_assoc]
        exact List.Perm.append_left _ List.perm_append_comm
      · simp [windowRoot, window, winIns, winInputs, hbc', ins3, plug, e0, e1, e2]
  | node e c (node f a b), true, _ =>
    obtain ⟨h1, hc, ⟨h2, ha, hb⟩⟩ := hs
    simp only [minLabel_node] at h1
    have hab : a.minLabel < b.minLabel := h2
    rw [min_eq_left hab.le] at h1
    have e0 : rank3 a.minLabel b.minLabel c.minLabel c.minLabel = 0 := by
      simp only [rank3]
      split_ifs <;> omega
    have e1 : rank3 a.minLabel b.minLabel c.minLabel a.minLabel = 1 := by
      simp only [rank3]
      split_ifs <;> omega
    have e2 : rank3 a.minLabel b.minLabel c.minLabel b.minLabel = 2 := by
      simp only [rank3]
      split_ifs <;> omega
    have hw : winInputs (node e c (node f a b)) true = (c, a, b) := by
      cases c <;> rfl
    have hwr : windowRoot (node e c (node f a b)) true
        = window e f true a.minLabel b.minLabel c.minLabel := by
      cases c <;> rfl
    refine ⟨fun k => ?_, ?_, ?_, ?_, ?_⟩
    · simp only [winIns, hw, ins3]
      split_ifs
      exacts [hc, ha, hb]
    · simpa [winIns, hw, ins3] using h1
    · simpa [winIns, hw, ins3] using hab
    · simp [winIns, hw, ins3, List.append_assoc]
    · rw [hwr]
      simp [window, winIns, hw, ins3, plug, e0, e1, e2]

/-! ## Labels and the shuffle condition -/

lemma perm_labels_plug {m : LTree E} (hm : m.labels.Perm (List.range 3)) (ins : ℕ → LTree E) :
    (m.plug ins).labels.Perm ((ins 0).labels ++ (ins 1).labels ++ (ins 2).labels) := by
  rw [labels_plug]
  refine (hm.flatMap_right _).trans ?_
  simp [List.range_succ, List.append_assoc]

lemma lt_three_of_perm {m : LTree E} (hm : m.labels.Perm (List.range 3)) :
    ∀ a ∈ m.labels, a < 3 := fun _ ha => List.mem_range.1 (hm.subset ha)

lemma minLabel_plug {ins : ℕ → LTree E}
    (hmono : ∀ j k, j < k → k < 3 → (ins j).minLabel < (ins k).minLabel) :
    ∀ m : LTree E, (∀ a ∈ m.labels, a < 3) → (m.plug ins).minLabel = (ins m.minLabel).minLabel
  | leaf _, _ => rfl
  | node e l r, h3 => by
    have hl := minLabel_plug hmono l fun a ha => h3 a (by simp [ha])
    have hr := minLabel_plug hmono r fun a ha => h3 a (by simp [ha])
    have hl3 : l.minLabel < 3 := h3 _ (by simp [minLabel_mem l])
    have hr3 : r.minLabel < 3 := h3 _ (by simp [minLabel_mem r])
    simp only [plug, minLabel_node, hl, hr]
    rcases lt_trichotomy l.minLabel r.minLabel with h | h | h
    · rw [min_eq_left h.le, min_eq_left (hmono _ _ h hr3).le]
    · rw [h, min_self, min_self]
    · rw [min_eq_right h.le, min_eq_right (hmono _ _ h hl3).le]

lemma isShuffle_plug {ins : ℕ → LTree E}
    (hmono : ∀ j k, j < k → k < 3 → (ins j).minLabel < (ins k).minLabel)
    (hs : ∀ k < 3, (ins k).IsShuffle) :
    ∀ m : LTree E, m.IsShuffle → (∀ a ∈ m.labels, a < 3) → (m.plug ins).IsShuffle
  | leaf a, _, h3 => hs a (h3 a (by simp))
  | node e l r, ⟨hlr, hl, hr⟩, h3 => by
    have h3l : ∀ a ∈ l.labels, a < 3 := fun a ha => h3 a (by simp [ha])
    have h3r : ∀ a ∈ r.labels, a < 3 := fun a ha => h3 a (by simp [ha])
    refine ⟨?_, isShuffle_plug hmono hs l hl h3l, isShuffle_plug hmono hs r hr h3r⟩
    rw [minLabel_plug hmono l h3l, minLabel_plug hmono r h3r]
    exact hmono _ _ hlr (h3r _ (minLabel_mem r))

lemma isShuffle_subtreeAt : ∀ (t : LTree E) (p : List Bool), t.IsShuffle →
    (t.subtreeAt p).IsShuffle
  | leaf _, [], h => h
  | leaf _, _ :: _, h => h
  | node _ _ _, [], h => h
  | node _ l _, false :: p, h => isShuffle_subtreeAt l p h.2.1
  | node _ _ r, true :: p, h => isShuffle_subtreeAt r p h.2.2

lemma nodup_subtreeAt : ∀ (t : LTree E) (p : List Bool), t.labels.Nodup →
    (t.subtreeAt p).labels.Nodup
  | leaf _, [], h => h
  | leaf _, _ :: _, h => h
  | node _ _ _, [], h => h
  | node _ l _, false :: p, h => nodup_subtreeAt l p (List.nodup_append.1 h).1
  | node _ _ r, true :: p, h => nodup_subtreeAt r p (List.nodup_append.1 h).2.1

lemma isShuffle_replaceAt : ∀ (t : LTree E) (p : List Bool) (u : LTree E),
    (∃ e l r, t.subtreeAt p = node e l r) → t.IsShuffle → u.IsShuffle →
    u.labels.Perm (t.subtreeAt p).labels → (t.replaceAt p u).IsShuffle
  | leaf _, [], _, _, _, hu, _ => hu
  | leaf _, _ :: _, _, ⟨_, _, _, h⟩, _, _, _ => by simp [subtreeAt] at h
  | node _ _ _, [], _, _, _, hu, _ => hu
  | node e l r, false :: p, u, hv, ⟨hlr, hl, hr⟩, hu, hp => by
    refine ⟨?_, isShuffle_replaceAt l p u hv hl hu hp, hr⟩
    rw [minLabel_eq_of_perm (labels_replaceAt_perm l p u hv hp)]
    exact hlr
  | node e l r, true :: p, u, hv, ⟨hlr, hl, hr⟩, hu, hp => by
    refine ⟨?_, hl, isShuffle_replaceAt r p u hv hr hu hp⟩
    rw [minLabel_eq_of_perm (labels_replaceAt_perm r p u hv hp)]
    exact hlr

section Subst

variable {t : LTree E} {p : List Bool} {s : Bool}

lemma WinSpec.mono {u : LTree E} (h : u.WinSpec s) :
    ∀ j k, j < k → k < 3 → (u.winIns s j).minLabel < (u.winIns s k).minLabel := by
  intro j k hjk hk
  interval_cases k <;> interval_cases j
  · exact h.lt01
  · exact h.lt01.trans h.lt12
  · exact h.lt12

lemma winSpec_of_edge (he : t.IsEdge p s) (hs : t.IsShuffle) (hnd : t.labels.Nodup) :
    (t.subtreeAt p).WinSpec s :=
  winSpec he (isShuffle_subtreeAt t p hs) (nodup_subtreeAt t p hnd)

/-- **Substituting the window itself gives the monomial back.** -/
theorem substAt_windowAt (he : t.IsEdge p s) (hs : t.IsShuffle) (hnd : t.labels.Nodup) :
    t.substAt p s (t.windowAt p s) = t := by
  rw [substAt, windowAt, (winSpec_of_edge he hs hnd).window, replaceAt_subtreeAt]

variable {m : LTree E}

lemma perm_labels_plug_winIns (he : t.IsEdge p s) (hs : t.IsShuffle) (hnd : t.labels.Nodup)
    (hm : m.labels.Perm (List.range 3)) :
    (m.plug ((t.subtreeAt p).winIns s)).labels.Perm (t.subtreeAt p).labels :=
  (perm_labels_plug hm _).trans (winSpec_of_edge he hs hnd).perm.symm

/-- **Substitution keeps the labels.** -/
theorem perm_labels_substAt (he : t.IsEdge p s) (hs : t.IsShuffle) (hnd : t.labels.Nodup)
    (hm : m.labels.Perm (List.range 3)) : (t.substAt p s m).labels.Perm t.labels :=
  labels_replaceAt_perm t p _ he.exists_node (perm_labels_plug_winIns he hs hnd hm)

/-- **Substituting a shuffle monomial gives a shuffle monomial.** -/
theorem isShuffle_substAt (he : t.IsEdge p s) (hs : t.IsShuffle) (hnd : t.labels.Nodup)
    (hms : m.IsShuffle) (hm : m.labels.Perm (List.range 3)) : (t.substAt p s m).IsShuffle := by
  have hw := winSpec_of_edge he hs hnd
  exact isShuffle_replaceAt t p _ he.exists_node hs
    (isShuffle_plug hw.mono (fun k _ => hw.shuffle k) m hms (lt_three_of_perm hm))
    (perm_labels_plug_winIns he hs hnd hm)

lemma winIns_disjoint (he : t.IsEdge p s) (hs : t.IsShuffle) (hnd : t.labels.Nodup) :
    ∀ k < 3, ∀ k' < 3, k ≠ k' → ∀ i ∈ ((t.subtreeAt p).winIns s k).labels,
      i ∉ ((t.subtreeAt p).winIns s k').labels := by
  have hw := winSpec_of_edge he hs hnd
  have hnd' : ((t.subtreeAt p).winIns s 0).labels ++ ((t.subtreeAt p).winIns s 1).labels
      ++ ((t.subtreeAt p).winIns s 2).labels |>.Nodup :=
    hw.perm.nodup_iff.1 (nodup_subtreeAt t p hnd)
  rw [List.nodup_append, List.nodup_append] at hnd'
  obtain ⟨⟨-, -, h01⟩, -, h2⟩ := hnd'
  intro k hk k' hk' hkk' i hi hi'
  interval_cases k <;> interval_cases k'
  all_goals first
    | exact absurd rfl hkk'
    | exact h01 i hi i hi' rfl
    | exact h01 i hi' i hi rfl
    | exact h2 i (List.mem_append.2 (Or.inl hi)) i hi' rfl
    | exact h2 i (List.mem_append.2 (Or.inr hi)) i hi' rfl
    | exact h2 i (List.mem_append.2 (Or.inl hi')) i hi rfl
    | exact h2 i (List.mem_append.2 (Or.inr hi')) i hi rfl

/-- **The path to a leaf below the window**, after substitution: to the window, then in `m` to
the input containing the leaf, then inside that input. -/
theorem path_substAt_of_mem (he : t.IsEdge p s) (hs : t.IsShuffle) (hnd : t.labels.Nodup)
    (hm : m.labels.Perm (List.range 3)) {i k : ℕ} (hk : k < 3)
    (hi : i ∈ ((t.subtreeAt p).winIns s k).labels) :
    (t.substAt p s m).path i
      = t.decAt p ++ m.path k ++ ((t.subtreeAt p).winIns s k).path i := by
  have hmem : i ∈ (m.plug ((t.subtreeAt p).winIns s)).labels := by
    rw [labels_plug, List.mem_flatMap]
    exact ⟨k, hm.symm.subset (List.mem_range.2 hk), hi⟩
  rw [substAt, path_replaceAt_of_mem t p _ hnd he.exists_node
    (perm_labels_plug_winIns he hs hnd hm) hmem, List.append_assoc]
  rw [path_plug _ (winIns_disjoint he hs hnd) hk hi m (lt_three_of_perm hm)
    (hm.nodup_iff.2 List.nodup_range) (hm.symm.subset (List.mem_range.2 hk))]

/-- The path to a leaf away from the window does not change. -/
theorem path_substAt_of_not_mem (he : t.IsEdge p s) (hs : t.IsShuffle) (hnd : t.labels.Nodup)
    (hm : m.labels.Perm (List.range 3)) {i : ℕ} (hi : i ∈ t.labels)
    (hi' : i ∉ (t.subtreeAt p).labels) : (t.substAt p s m).path i = t.path i :=
  path_replaceAt_of_not_mem t p _ hnd he.exists_node (perm_labels_plug_winIns he hs hnd hm) hi hi'

end Subst

/-! ## Compatibility with the path-lexicographic key -/

/-- The part of the path-lexicographic key at one leaf: the length of its path, then the ranks of
the decorations along it. -/
def seg (rk : E → ℕ) (t : LTree E) (i : ℕ) : List ℕ := (t.path i).length :: (t.path i).map rk

lemma lengthCoded_seg (rk : E → ℕ) (t : LTree E) (i : ℕ) : LengthCoded (seg rk t i) :=
  ⟨(t.path i).map rk, by simp [seg]⟩

lemma pathKey_eq_flatten (rk : E → ℕ) (n : ℕ) (t : LTree E) :
    pathKey rk n t = ((List.range n).map (seg rk t)).flatten := rfl

/-- **Keys compare like their lists of segments**, leaf by leaf. -/
lemma pathKey_lt_iff (rk : E → ℕ) (n : ℕ) (t t' : LTree E) :
    pathKey rk n t < pathKey rk n t' ↔
      (List.range n).map (seg rk t) < (List.range n).map (seg rk t') := by
  rw [pathKey_eq_flatten, pathKey_eq_flatten]
  refine flatten_lt_flatten_iff (by simp) ?_ ?_ <;>
  · intro x hx
    obtain ⟨i, -, rfl⟩ := List.mem_map.1 hx
    exact lengthCoded_seg rk _ i

/-- **Substituting a smaller monomial gives a smaller monomial**: the path-lexicographic key is
compatible with substitution at a window. -/
theorem pathKey_substAt_lt (rk : E → ℕ) {n : ℕ} {t : LTree E} {p : List Bool} {s : Bool}
    (he : t.IsEdge p s) (hs : t.IsShuffle) (ht : t.labels.Perm (List.range n)) {m m' : LTree E}
    (hm : m.labels.Perm (List.range 3)) (hm' : m'.labels.Perm (List.range 3))
    (h : pathKey rk 3 m < pathKey rk 3 m') :
    pathKey rk n (t.substAt p s m) < pathKey rk n (t.substAt p s m') := by
  have hnd : t.labels.Nodup := ht.nodup_iff.2 List.nodup_range
  have hw := winSpec_of_edge he hs hnd
  set u := t.subtreeAt p with hu
  set ins := u.winIns s with hins
  rw [pathKey_lt_iff, map_range_lt_iff] at h ⊢
  obtain ⟨k₀, hk₀, heq, hlt⟩ := h
  -- the leaves of the window are those of its inputs
  have hmemu : ∀ i ∈ u.labels, ∃ k < 3, i ∈ (ins k).labels := by
    intro i hi
    have := hw.perm.subset hi
    simp only [List.mem_append] at this
    rcases this with (h | h) | h
    · exact ⟨0, by omega, h⟩
    · exact ⟨1, by omega, h⟩
    · exact ⟨2, by omega, h⟩
  have hinsu : ∀ k < 3, ∀ i ∈ (ins k).labels, i ∈ u.labels := by
    intro k hk i hi
    refine hw.perm.symm.subset ?_
    rw [hins] at hi
    interval_cases k <;> simp [hi]
  have hut : ∀ i ∈ u.labels, i ∈ t.labels := fun i hi => labels_subtreeAt_subset t p hi
  -- the segment at a leaf of the input `k` after substituting `m`
  have hseg : ∀ (m : LTree E), m.labels.Perm (List.range 3) → ∀ k < 3, ∀ i ∈ (ins k).labels,
      seg rk (t.substAt p s m) i
        = ((t.decAt p).length + (m.path k).length + ((ins k).path i).length) ::
          ((t.decAt p).map rk ++ (m.path k).map rk ++ ((ins k).path i).map rk) := by
    intro m hm k hk i hi
    rw [seg, path_substAt_of_mem he hs hnd hm hk hi, ← hu, ← hins]
    simp only [List.length_append, List.map_append, Nat.add_assoc, List.append_assoc]
  set i₀ := (ins k₀).minLabel with hi₀
  have hi₀mem : i₀ ∈ (ins k₀).labels := minLabel_mem _
  refine ⟨i₀, List.mem_range.1 (ht.subset (hut _ (hinsu k₀ hk₀ _ hi₀mem))), ?_, ?_⟩
  · intro j hj
    have hjt : j ∈ t.labels := ht.symm.subset (List.mem_range.2 (by
      have := List.mem_range.1 (ht.subset (hut _ (hinsu k₀ hk₀ _ hi₀mem)))
      omega))
    by_cases hju : j ∈ u.labels
    · obtain ⟨k, hk, hjk⟩ := hmemu j hju
      rcases lt_or_ge k k₀ with hkk | hkk
      · rw [hseg m hm k hk j hjk, hseg m' hm' k hk j hjk]
        have := heq k hkk
        simp only [seg, List.cons.injEq] at this
        rw [this.1, this.2]
      · exfalso
        have h1 : (ins k).minLabel ≤ j := minLabel_le_of_mem _ hjk
        have h2 : (ins k₀).minLabel ≤ (ins k).minLabel := by
          rcases hkk.lt_or_eq with hkk | hkk
          · exact (hw.mono k₀ k hkk hk).le
          · rw [hkk]
        omega
    · rw [seg, seg, path_substAt_of_not_mem he hs hnd hm hjt hju,
        path_substAt_of_not_mem he hs hnd hm' hjt hju]
  · rw [hseg m hm k₀ hk₀ i₀ hi₀mem, hseg m' hm' k₀ hk₀ i₀ hi₀mem]
    simp only [seg] at hlt
    rw [List.cons_lt_cons_iff] at hlt ⊢
    rcases hlt with hlt | ⟨hl, hlt⟩
    · left
      omega
    · right
      refine ⟨by rw [hl], ?_⟩
      rw [List.append_assoc, List.append_assoc, append_lt_append_left_iff]
      exact append_lt_append_of_length_eq (by simp [hl]) hlt _ _

/-! ## On the monomials of a given arity -/

section Monomials

variable [Fintype E] [DecidableEq E] {n : ℕ} {t : LTree E} {p : List Bool} {s : Bool}

/-- **Substituting a monomial of arity three** at a window of a monomial of arity `n` gives a
monomial of arity `n`. -/
theorem substAt_mem_monomials (ht : t ∈ monomials n) (he : t.IsEdge p s) {m : LTree E}
    (hm : m ∈ monomials 3) : t.substAt p s m ∈ monomials n := by
  rw [mem_monomials] at ht hm ⊢
  have hnd : t.labels.Nodup := ht.2.nodup_iff.2 List.nodup_range
  exact ⟨isShuffle_substAt he ht.1 hnd hm.1 hm.2, (perm_labels_substAt he ht.1 hnd hm.2).trans ht.2⟩

omit [Fintype E] [DecidableEq E] in
/-- **A monomial is not normal exactly when it has an edge whose window is a leading monomial.** -/
theorem not_isNormal_iff {L : Set (LTree E)} :
    ¬ IsNormal L t ↔ ∃ p s, t.IsEdge p s ∧ t.windowAt p s ∈ L := by
  simp only [IsNormal, not_forall, not_not, mem_windows_iff]
  constructor
  · rintro ⟨w, ⟨p, s, he, rfl⟩, hw⟩
    exact ⟨p, s, he, hw⟩
  · rintro ⟨p, s, he, hw⟩
    exact ⟨_, ⟨p, s, he, rfl⟩, hw⟩

theorem pathKey_substAt_lt' (rk : E → ℕ) (ht : t ∈ monomials n) (he : t.IsEdge p s)
    {m m' : LTree E} (hm : m ∈ monomials 3) (hm' : m' ∈ monomials 3)
    (h : pathKey rk 3 m < pathKey rk 3 m') :
    pathKey rk n (t.substAt p s m) < pathKey rk n (t.substAt p s m') := by
  rw [mem_monomials] at ht hm hm'
  exact pathKey_substAt_lt rk he ht.1 ht.2 hm.2 hm'.2 h

end Monomials

end LTree

end Operad
