/-
# Gröbner bases for shuffle operads with generators of any arity

**Monomials** (`STree.SMono E A`): shuffle trees whose leaves are the elements of a finite set
`A ⊆ ℕ`, each once. **Contexts** (`STree.IsSCtx`): the maps which replace the subtree at a
position of a tree by a monomial with its leaves substituted by inputs, shuffle trees increasing
with their least leaves (`STree.Inputs`). An **admissible order** (`STree.AdmOrder`) is a
well-founded transitive relation on the monomials on each set, preserved by the contexts; with it
the monomials and contexts are a `CtxOrder`, so that rules (leading monomials and smaller tails)
define a rewriting system whose ideal is the operadic ideal generated by the relations
`lead - tail` (`Rules.ideal_eq_span`), and whose irreducible monomials are the normal ones.

* **An occurrence gives a context** (`STree.ctxOf`): when a monomial has the subtree
  `ℓ.subst xs` at a position, for a monomial `ℓ` and increasing `xs`, replacing `ℓ` by any
  monomial on the same leaves gives a monomial.
* **Classification of ambiguities** (`STree.classify`): two occurrences of leading monomials in a
  monomial are at incomparable positions, or one sits inside an input of the other — the
  ambiguity is disjoint — or they overlap, and the ambiguity factors through the truncation of
  the monomial to the union of the two occurrences, a **critical ambiguity**
  (`STree.Critical`): the two occurrences cover its monomial and share a vertex.
* **The Buchberger criterion for shuffle operads** (`STree.isCompl_of_critical`): if no leading
  monomial is a leaf and every critical ambiguity is resolvable, then in every arity the normal
  monomials are a basis of the quotient by the ideal generated by the rules
  (`STree.basisOfCritical`); conversely every critical ambiguity of a Gröbner basis is resolvable
  (`STree.Critical.res_of_isCompl`).
-/
import Operad.ShuffleAny
import Operad.DiamondCtx

universe v

namespace Operad

namespace STree

variable {E : ℕ → Type v}

/-! ## Monomials and contexts -/

variable (E) in
/-- **The shuffle monomials on a finite set `A` of leaves**: shuffle trees whose leaves are the
elements of `A`, each once. -/
abbrev SMono (A : Finset ℕ) : Type v := {t : STree E // t.IsShuffle ∧ t.labels = A.val}

namespace SMono

variable {A : Finset ℕ} (g : SMono E A)

lemma isShuffle : g.1.IsShuffle := g.2.1

lemma labels_eq : g.1.labels = A.val := g.2.2

lemma nodup : g.1.labels.Nodup := by rw [g.labels_eq]; exact A.nodup

lemma mem_labels {a : ℕ} : a ∈ g.1.labels ↔ a ∈ A := by rw [g.labels_eq]; rfl

lemma first_eq (g' : SMono E A) : g.1.first = g'.1.first :=
  first_eq_of_labels_eq g.isShuffle g'.isShuffle (g.labels_eq.trans g'.labels_eq.symm)

end SMono

/-- **Inputs for substitution** into the monomials on `A`, inside the monomials on `B`: shuffle
trees with leaves in `B`, increasing with their least leaves. -/
structure Inputs (A B : Finset ℕ) (xs : ℕ → STree E) : Prop where
  shuffle : ∀ a ∈ A, (xs a).IsShuffle
  labels : ∀ a ∈ A, ∀ b ∈ (xs a).labels, b ∈ B
  mono : StrictMonoOn (fun a => (xs a).first) (A : Set ℕ)

lemma Inputs.subst_isShuffle {A B : Finset ℕ} {xs : ℕ → STree E} (h : Inputs A B xs)
    (g : SMono E A) : (g.1.subst xs).IsShuffle :=
  isShuffle_subst g.isShuffle (fun a ha => h.shuffle a (g.mem_labels.1 ha))
    (fun _ ha _ hb hab => h.mono (g.mem_labels.1 ha) (g.mem_labels.1 hb) hab)

lemma inputs_leaf (A : Finset ℕ) : Inputs A A (leaf : ℕ → STree E) where
  shuffle _ _ := trivial
  labels _ ha _ hb := by rw [labels_leaf, Multiset.mem_singleton] at hb; exact hb ▸ ha
  mono _ _ _ _ h := h

lemma Inputs.comp {A A' B : Finset ℕ} {xs xs' : ℕ → STree E} (h : Inputs A B xs)
    (h' : Inputs A' A xs') : Inputs A' B fun a => (xs' a).subst xs where
  shuffle a ha := isShuffle_subst (h'.shuffle a ha) (fun b hb => h.shuffle b (h'.labels a ha b hb))
    (fun b hb c hc hbc => h.mono (h'.labels a ha b hb) (h'.labels a ha c hc) hbc)
  labels a ha b hb := by
    rw [labels_subst, Multiset.mem_bind] at hb
    obtain ⟨c, hc, hbc⟩ := hb
    exact h.labels c (h'.labels a ha c hc) b hbc
  mono a ha a' ha' haa' := by
    simp only [first_subst (h'.shuffle a ha), first_subst (h'.shuffle a' ha')]
    exact h.mono (h'.labels a ha _ (first_mem (h'.shuffle a ha)))
      (h'.labels a' ha' _ (first_mem (h'.shuffle a' ha'))) (h'.mono ha ha' haa')

/-- **A context** from the monomials on `A` to those on `B`: replace the subtree at a position of
a tree by the monomial with its leaves substituted by inputs. -/
def IsSCtx {A B : Finset ℕ} (f : SMono E A → SMono E B) : Prop :=
  ∃ (T : STree E) (p : List ℕ) (xs : ℕ → STree E), (T.get? p).isSome ∧ Inputs A B xs ∧
    ∀ g, (f g).1 = T.replace p (g.1.subst xs)

theorem isSCtx_id (A : Finset ℕ) : IsSCtx (id : SMono E A → SMono E A) :=
  ⟨leaf 0, [], leaf, rfl, inputs_leaf A, fun g => by rw [replace_nil, subst_leaf]; rfl⟩

/-- **Contexts compose.** -/
theorem isSCtx_comp {A A' B : Finset ℕ} {f : SMono E A → SMono E B}
    {g : SMono E A' → SMono E A} (hf : IsSCtx f) (hg : IsSCtx g) : IsSCtx (f ∘ g) := by
  obtain ⟨T, p, xs, hp, hxs, hf⟩ := hf
  obtain ⟨T', p', xs', hp', hxs', hg⟩ := hg
  obtain ⟨w, hw⟩ := Option.isSome_iff_exists.1 hp'
  refine ⟨T.replace p (T'.subst xs), p ++ p', fun a => (xs' a).subst xs, ?_, hxs.comp hxs',
    fun h => ?_⟩
  · rw [get?_replace_append hp, get?_subst hw]
    rfl
  · rw [Function.comp_apply, hf, hg, replace_subst hp', subst_subst,
      replace_append (get?_replace hp _), replace_replace]

variable (E) in
/-- **An admissible order** on shuffle monomials: a well-founded transitive relation on the
monomials on each set of leaves, preserved by the contexts. -/
structure AdmOrder where
  /-- the order -/
  lt : ∀ {A : Finset ℕ}, SMono E A → SMono E A → Prop
  /-- it is well-founded -/
  wf : ∀ A, WellFounded (@lt A)
  /-- it is transitive -/
  trans : ∀ {A : Finset ℕ} {x y z : SMono E A}, lt x y → lt y z → lt x z
  /-- the contexts preserve it -/
  lt_ctx : ∀ {A B : Finset ℕ} {f : SMono E A → SMono E B}, IsSCtx f →
    ∀ {x y : SMono E A}, lt x y → lt (f x) (f y)

/-- **Shuffle monomials with their contexts and an admissible order.** -/
def AdmOrder.toCtxOrder (O : AdmOrder E) : CtxOrder (Finset ℕ) (SMono E) where
  lt := O.lt
  wf := O.wf
  trans := O.trans
  IsCtx := IsSCtx
  ctx_id := isSCtx_id
  ctx_comp := isSCtx_comp
  lt_ctx := O.lt_ctx

/-! ## Occurrences -/

/-- **The inputs of an occurrence** are subtrees. -/
lemma get?_input {U ℓ : STree E} {p : List ℕ} {xs : ℕ → STree E}
    (hU : U.get? p = some (ℓ.subst xs)) {a : ℕ} (ha : a ∈ ℓ.labels) :
    U.get? (p ++ ℓ.pos a) = some (xs a) := by
  rw [get?_append_of hU, get?_subst (get?_pos ha)]
  rfl

theorem inputs_of_occ {A B : Finset ℕ} (U : SMono E B) {p : List ℕ} {ℓ : SMono E A}
    {xs : ℕ → STree E} (hU : U.1.get? p = some (ℓ.1.subst xs))
    (hm : StrictMonoOn (fun a => (xs a).first) (A : Set ℕ)) : Inputs A B xs where
  shuffle _ ha := isShuffle_get? U.isShuffle (get?_input hU (ℓ.mem_labels.2 ha))
  labels _ ha _ hb := U.mem_labels.1
    (Multiset.mem_of_le (labels_get?_le (get?_input hU (ℓ.mem_labels.2 ha))) hb)
  mono := hm

/-- **An occurrence gives a monomial for each monomial on its leaves.** -/
theorem replace_mem {A B : Finset ℕ} (U : SMono E B) {p : List ℕ} {ℓ : SMono E A}
    {xs : ℕ → STree E} (hU : U.1.get? p = some (ℓ.1.subst xs))
    (hm : StrictMonoOn (fun a => (xs a).first) (A : Set ℕ)) (g : SMono E A) :
    (U.1.replace p (g.1.subst xs)).IsShuffle ∧
      (U.1.replace p (g.1.subst xs)).labels = B.val := by
  have hin := inputs_of_occ U hU hm
  refine ⟨isShuffle_replace U.isShuffle hU (hin.subst_isShuffle g) ?_, ?_⟩
  · rw [first_subst g.isShuffle, first_subst ℓ.isShuffle, g.first_eq ℓ]
  · rw [labels_replace_of_eq hU (by rw [labels_subst, labels_subst, g.labels_eq, ℓ.labels_eq]),
      U.labels_eq]

/-- **The context of an occurrence**: replace the occurring monomial. -/
def ctxOf {A B : Finset ℕ} (U : SMono E B) (p : List ℕ) (ℓ : SMono E A) (xs : ℕ → STree E)
    (hU : U.1.get? p = some (ℓ.1.subst xs))
    (hm : StrictMonoOn (fun a => (xs a).first) (A : Set ℕ)) : SMono E A → SMono E B :=
  fun g => ⟨U.1.replace p (g.1.subst xs), replace_mem U hU hm g⟩

section CtxOf

variable {A B : Finset ℕ} (U : SMono E B) (p : List ℕ) (ℓ : SMono E A) (xs : ℕ → STree E)
  (hU : U.1.get? p = some (ℓ.1.subst xs)) (hm : StrictMonoOn (fun a => (xs a).first) (A : Set ℕ))

@[simp] lemma ctxOf_val (g : SMono E A) :
    (ctxOf U p ℓ xs hU hm g).1 = U.1.replace p (g.1.subst xs) := rfl

theorem isSCtx_ctxOf : IsSCtx (ctxOf U p ℓ xs hU hm) :=
  ⟨U.1, p, xs, by rw [hU]; rfl, inputs_of_occ U hU hm, fun _ => rfl⟩

lemma ctxOf_self : ctxOf U p ℓ xs hU hm ℓ = U := Subtype.ext (replace_self hU)

end CtxOf

/-- **A context at its value**: a context `f` replaces at a position of `f ℓ` itself. -/
lemma IsSCtx.normal {A B : Finset ℕ} {f : SMono E A → SMono E B} (hf : IsSCtx f)
    (ℓ : SMono E A) : ∃ p xs, (f ℓ).1.get? p = some (ℓ.1.subst xs) ∧ Inputs A B xs ∧
      ∀ g, (f g).1 = (f ℓ).1.replace p (g.1.subst xs) := by
  obtain ⟨T, p, xs, hp, hxs, hf⟩ := hf
  refine ⟨p, xs, ?_, hxs, fun g => ?_⟩
  · rw [hf]
    exact get?_replace hp _
  · rw [hf, hf, replace_replace]

/-! ## Vertices and critical ambiguities -/

/-- **The vertices of a tree**: the positions of its vertices. -/
def vert (t : STree E) : Set (List ℕ) := {q | ∃ k, ∃ (e : E k) (c : Fin k → STree E),
  t.get? q = some (node e c)}

/-- **The vertices of an occurrence** at `p` of a tree `ℓ`. -/
def occVert (p : List ℕ) (ℓ : STree E) : Set (List ℕ) := (p ++ ·) '' vert ℓ

/-- **The proper prefixes of a vertex are vertices.** -/
lemma vert_of_prefix {t : STree E} {q q' : List ℕ} (hq : q ∈ vert t) (h : q' <+: q)
    (hne : q' ≠ q) : q' ∈ vert t := by
  obtain ⟨k, e, c, hq⟩ := hq
  obtain ⟨r, rfl⟩ := h
  cases r with
  | nil => exact absurd (List.append_nil q') (Ne.symm hne)
  | cons i r =>
    rw [get?_append] at hq
    cases hw : t.get? q' with
    | none => rw [hw] at hq; simp at hq
    | some w =>
      rw [hw, Option.bind_some] at hq
      cases w with
      | leaf a => simp at hq
      | node e' c' => exact ⟨_, e', c', hw⟩

lemma nil_mem_vert {t : STree E} (h : ∀ a, t ≠ leaf a) : [] ∈ vert t := by
  cases t with
  | leaf a => exact absurd rfl (h a)
  | node e c => exact ⟨_, e, c, get?_nil _⟩

/-! ## Classification of ambiguities -/

/-- **Occurrences at incomparable positions are disjoint.** -/
theorem disjoint_of_incomp {A₁ A₂ B : Finset ℕ} {f₁ : SMono E A₁ → SMono E B}
    {f₂ : SMono E A₂ → SMono E B} {ℓ₁ : SMono E A₁} {ℓ₂ : SMono E A₂} {T : SMono E B}
    {p₁ p₂ : List ℕ} {xs₁ xs₂ : ℕ → STree E}
    (hT₁ : T.1.get? p₁ = some (ℓ₁.1.subst xs₁)) (hT₂ : T.1.get? p₂ = some (ℓ₂.1.subst xs₂))
    (hin₁ : Inputs A₁ B xs₁) (hin₂ : Inputs A₂ B xs₂)
    (hf₁ : ∀ g, (f₁ g).1 = T.1.replace p₁ (g.1.subst xs₁))
    (hf₂ : ∀ g, (f₂ g).1 = T.1.replace p₂ (g.1.subst xs₂)) (h : Incomp p₁ p₂) :
    ∃ d : SMono E A₁ → SMono E A₂ → SMono E B, (∀ y, IsSCtx (d · y)) ∧ (∀ x, IsSCtx (d x)) ∧
      f₁ = (d · ℓ₂) ∧ f₂ = d ℓ₁ := by
  have hx : ∀ x, (f₁ x).1.get? p₂ = some (ℓ₂.1.subst xs₂) := fun x => by
    rw [hf₁, get?_replace_of_incomp' h, hT₂]
  refine ⟨fun x => ctxOf (f₁ x) p₂ ℓ₂ xs₂ (hx x) hin₂.mono, fun y => ?_,
    fun x => isSCtx_ctxOf _ _ _ _ _ _, ?_, ?_⟩
  · refine ⟨(f₂ y).1, p₁, xs₁, ?_, hin₁, fun x => ?_⟩
    · rw [hf₂, get?_replace_of_incomp' h.symm, hT₁]
      rfl
    · simp only [ctxOf_val]
      rw [hf₁, hf₂, replace_comm h]
  · funext x
    exact Subtype.ext (replace_self (hx x)).symm
  · funext y
    apply Subtype.ext
    simp only [ctxOf_val]
    rw [hf₁, replace_self hT₁, hf₂]

/-- **Replace inside the input `a`** of substituted inputs. -/
def updIn (xs : ℕ → STree E) (a : ℕ) (q : List ℕ) (u : STree E) : ℕ → STree E :=
  Function.update xs a ((xs a).replace q u)

/-- **An occurrence inside an input of another one is disjoint from it.** -/
theorem disjoint_of_nested {A₁ A₂ B : Finset ℕ} {f₁ : SMono E A₁ → SMono E B}
    {f₂ : SMono E A₂ → SMono E B} {ℓ₁ : SMono E A₁} {ℓ₂ : SMono E A₂} {T : SMono E B}
    {p₁ q₀ q'' : List ℕ} {a : ℕ} {xs₁ xs₂ : ℕ → STree E}
    (hT₁ : T.1.get? p₁ = some (ℓ₁.1.subst xs₁)) (hin₁ : Inputs A₁ B xs₁)
    (hin₂ : Inputs A₂ B xs₂) (hf₁ : ∀ g, (f₁ g).1 = T.1.replace p₁ (g.1.subst xs₁))
    (hf₂ : ∀ g, (f₂ g).1 = T.1.replace (p₁ ++ (q₀ ++ q'')) (g.1.subst xs₂))
    (h₀ : ℓ₁.1.get? q₀ = some (leaf a)) (h'' : (xs₁ a).get? q'' = some (ℓ₂.1.subst xs₂)) :
    ∃ d : SMono E A₁ → SMono E A₂ → SMono E B, (∀ y, IsSCtx (d · y)) ∧ (∀ x, IsSCtx (d x)) ∧
      f₁ = (d · ℓ₂) ∧ f₂ = d ℓ₁ := by
  have hv : (T.1.get? p₁).isSome := by rw [hT₁]; rfl
  have hU₀ : (ℓ₁.1.subst xs₁).get? q₀ = some (xs₁ a) := get?_subst h₀ xs₁
  have hXf : ∀ (y : SMono E A₂) b, (updIn xs₁ a q'' (y.1.subst xs₂) b).first = (xs₁ b).first :=
    fun y b => by
      by_cases hb : b = a
      · subst hb
        rw [updIn, Function.update_self]
        exact first_replace h'' (by
          rw [first_subst y.isShuffle, first_subst ℓ₂.isShuffle, y.first_eq ℓ₂])
      · rw [updIn, Function.update_of_ne hb]
  have hXm : ∀ y : SMono E A₂,
      StrictMonoOn (fun b => (updIn xs₁ a q'' (y.1.subst xs₂) b).first) (A₁ : Set ℕ) :=
    fun y b hb b' hb' hbb' => by
      simp only [hXf]
      exact hin₁.mono hb hb' hbb'
  have F1 : ∀ y, (f₂ y).1 = T.1.replace p₁ (ℓ₁.1.subst (updIn xs₁ a q'' (y.1.subst xs₂))) :=
    fun y => by rw [hf₂, replace_append hT₁, replace_append hU₀, updIn,
      subst_update ℓ₁.nodup h₀]
  have F2 : ∀ y, (f₂ y).1.get? p₁ = some (ℓ₁.1.subst (updIn xs₁ a q'' (y.1.subst xs₂))) :=
    fun y => by rw [F1]; exact get?_replace hv _
  refine ⟨fun x y => ctxOf (f₂ y) p₁ ℓ₁ _ (F2 y) (hXm y) x,
    fun y => isSCtx_ctxOf _ _ _ _ _ _, fun x => ?_, ?_, ?_⟩
  · have hxa : a ∈ x.1.labels := x.mem_labels.2 (ℓ₁.mem_labels.1 (mem_labels_of_get? h₀))
    have hxp := get?_pos hxa
    have hxs : (x.1.subst xs₁).get? (x.1.pos a) = some (xs₁ a) := get?_subst hxp xs₁
    refine ⟨(f₁ x).1, p₁ ++ (x.1.pos a ++ q''), xs₂, ?_, hin₂, fun y => ?_⟩
    · rw [hf₁, get?_replace_append hv, get?_append_of hxs, h'']
      rfl
    · simp only [ctxOf_val]
      rw [F1, replace_replace, updIn, subst_update x.nodup hxp, ← replace_append hxs, hf₁,
        replace_append (get?_replace hv _), replace_replace]
  · funext x
    apply Subtype.ext
    have hX : updIn xs₁ a q'' (ℓ₂.1.subst xs₂) = xs₁ := by
      rw [updIn, replace_self h'', Function.update_eq_self]
    have hT₂ : T.1.get? (p₁ ++ (q₀ ++ q'')) = some (ℓ₂.1.subst xs₂) := by
      rw [get?_append_of hT₁, get?_append_of hU₀]
      exact h''
    simp only [ctxOf_val]
    rw [hX, hf₂, replace_self hT₂, hf₁]
  · funext y
    exact Subtype.ext (replace_self (F2 y)).symm

/-- **Overlapping occurrences factor through a critical ambiguity**: the truncation of the
monomial to the union of the two occurrences. -/
theorem factors_of_overlap {A₁ A₂ B : Finset ℕ} {f₁ : SMono E A₁ → SMono E B}
    {f₂ : SMono E A₂ → SMono E B} {ℓ₁ : SMono E A₁} {ℓ₂ : SMono E A₂} {T : SMono E B}
    {p₁ q : List ℕ} {xs₁ xs₂ : ℕ → STree E}
    (hT₁ : T.1.get? p₁ = some (ℓ₁.1.subst xs₁))
    (hT₂ : T.1.get? (p₁ ++ q) = some (ℓ₂.1.subst xs₂))
    (hin₁ : Inputs A₁ B xs₁) (hin₂ : Inputs A₂ B xs₂)
    (hf₁ : ∀ g, (f₁ g).1 = T.1.replace p₁ (g.1.subst xs₁))
    (hf₂ : ∀ g, (f₂ g).1 = T.1.replace (p₁ ++ q) (g.1.subst xs₂))
    (hq : q ∈ vert ℓ₁.1) (hℓ₂ : [] ∈ vert ℓ₂.1) :
    ∃ (C : Finset ℕ) (m : SMono E C) (e₁ : SMono E A₁ → SMono E C)
      (e₂ : SMono E A₂ → SMono E C) (g : SMono E C → SMono E B) (ys₁ ys₂ : ℕ → STree E),
      IsSCtx e₁ ∧ IsSCtx e₂ ∧ IsSCtx g ∧ e₁ ℓ₁ = m ∧ e₂ ℓ₂ = m ∧ f₁ = g ∘ e₁ ∧ f₂ = g ∘ e₂ ∧
      (∀ h, (e₁ h).1 = m.1.replace [] (h.1.subst ys₁)) ∧
      (∀ h, (e₂ h).1 = m.1.replace q (h.1.subst ys₂)) ∧
      vert m.1 ⊆ occVert [] ℓ₁.1 ∪ occVert q ℓ₂.1 ∧
      (occVert [] ℓ₁.1 ∩ occVert q ℓ₂.1).Nonempty := by
  classical
  have hUs : (ℓ₁.1.subst xs₁).IsShuffle := isShuffle_get? T.isShuffle hT₁
  have hUn : (ℓ₁.1.subst xs₁).labels.Nodup :=
    Multiset.nodup_of_le (labels_get?_le hT₁) T.nodup
  have hU₂ : (ℓ₁.1.subst xs₁).get? q = some (ℓ₂.1.subst xs₂) := by
    rw [get?_append_of hT₁] at hT₂
    exact hT₂
  let V : Set (List ℕ) := vert ℓ₁.1 ∪ occVert q ℓ₂.1
  obtain ⟨zs, hzs, hzs'⟩ := exists_subst_trunc hUs hUn V
  have hm₀s : ((ℓ₁.1.subst xs₁).trunc V).IsShuffle := isShuffle_trunc hUs V
  have hm₀n : ((ℓ₁.1.subst xs₁).trunc V).labels.Nodup :=
    Multiset.nodup_of_le (labels_trunc_le hUs V) hUn
  let C := ((ℓ₁.1.subst xs₁).trunc V).labels.toFinset
  let m : SMono E C := ⟨(ℓ₁.1.subst xs₁).trunc V, hm₀s,
    ((Multiset.toFinset_val _).trans (Multiset.dedup_eq_self.2 hm₀n)).symm⟩
  have hmv : m.1 = (ℓ₁.1.subst xs₁).trunc V := rfl
  -- the inputs of the two occurrences in the truncation
  let ys₁ : ℕ → STree E := fun a => (xs₁ a).trunc (shift V (ℓ₁.1.pos a))
  let ys₂ : ℕ → STree E := fun b => (xs₂ b).trunc (shift V (q ++ ℓ₂.1.pos b))
  have M1 : m.1 = ℓ₁.1.subst ys₁ :=
    trunc_subst ℓ₁.nodup xs₁ (V := V) fun r k e c h => Or.inl ⟨k, e, c, h⟩
  have M2 : m.1.get? q = some (ℓ₂.1.subst ys₂) := by
    rw [hmv, get?_trunc hU₂ (V := V) fun q' h1 h2 => Or.inl (vert_of_prefix hq h1 h2),
      trunc_subst ℓ₂.nodup xs₂ (V := shift V q) fun r k e c h => Or.inr ⟨r, ⟨k, e, c, h⟩, rfl⟩]
    simp only [ys₂, shift_shift]
  have hm₁ : StrictMonoOn (fun a => (ys₁ a).first) (A₁ : Set ℕ) := fun a ha a' ha' h => by
    simp only [ys₁, first_trunc (hin₁.shuffle a ha), first_trunc (hin₁.shuffle a' ha')]
    exact hin₁.mono ha ha' h
  have hm₂ : StrictMonoOn (fun b => (ys₂ b).first) (A₂ : Set ℕ) := fun b hb b' hb' h => by
    simp only [ys₂, first_trunc (hin₂.shuffle b hb), first_trunc (hin₂.shuffle b' hb')]
    exact hin₂.mono hb hb' h
  have hM1 : m.1.get? [] = some (ℓ₁.1.subst ys₁) := by rw [get?_nil, M1]
  have hTm : T.1.get? p₁ = some (m.1.subst zs) := by rw [hT₁, hmv, hzs]
  have hzm : StrictMonoOn (fun a => (zs a).first) (C : Set ℕ) := fun a ha a' ha' h => by
    have ha2 : a ∈ ((ℓ₁.1.subst xs₁).trunc V).labels := Multiset.mem_toFinset.1 ha
    have ha2' : a' ∈ ((ℓ₁.1.subst xs₁).trunc V).labels := Multiset.mem_toFinset.1 ha'
    simp only [(hzs' a ha2).2.1, (hzs' a' ha2').2.1]
    exact h
  -- the cut subtrees recover the inputs
  have hsub₁ : ∀ a ∈ A₁, (ys₁ a).subst zs = xs₁ a := fun a ha => by
    have h1 : m.1.get? (ℓ₁.1.pos a) = some (ys₁ a) := by
      rw [M1]
      exact get?_subst (get?_pos (ℓ₁.mem_labels.2 ha)) ys₁
    have h2 := get?_subst h1 zs
    rw [hmv, hzs, get?_subst (get?_pos (ℓ₁.mem_labels.2 ha)) xs₁, Option.some_inj] at h2
    exact h2.symm
  have hsub₂ : ∀ b ∈ A₂, (ys₂ b).subst zs = xs₂ b := fun b hb => by
    have h1 : m.1.get? (q ++ ℓ₂.1.pos b) = some (ys₂ b) := by
      rw [get?_append_of M2]
      exact get?_subst (get?_pos (ℓ₂.mem_labels.2 hb)) ys₂
    have h2 := get?_subst h1 zs
    rw [hmv, hzs, get?_append_of hU₂, get?_subst (get?_pos (ℓ₂.mem_labels.2 hb)) xs₂,
      Option.some_inj] at h2
    exact h2.symm
  refine ⟨C, m, ctxOf m [] ℓ₁ ys₁ hM1 hm₁, ctxOf m q ℓ₂ ys₂ M2 hm₂, ctxOf T p₁ m zs hTm hzm,
    ys₁, ys₂, isSCtx_ctxOf _ _ _ _ _ _, isSCtx_ctxOf _ _ _ _ _ _, isSCtx_ctxOf _ _ _ _ _ _,
    Subtype.ext ?_, ctxOf_self _ _ _ _ _ _, ?_, ?_, fun _ => rfl, fun _ => rfl, ?_, ?_⟩
  · simp only [ctxOf_val, replace_nil]
    exact M1.symm
  · funext h
    apply Subtype.ext
    simp only [Function.comp_apply, ctxOf_val, replace_nil]
    rw [subst_subst, subst_congr h.1 fun a ha => hsub₁ a (h.mem_labels.1 ha), hf₁]
  · funext h
    apply Subtype.ext
    simp only [Function.comp_apply, ctxOf_val]
    rw [replace_subst (by rw [M2]; rfl), subst_subst,
      subst_congr h.1 fun b hb => hsub₂ b (h.mem_labels.1 hb), hmv, hzs, hf₂, replace_append hT₁]
  · rintro r ⟨k, e, c, hr⟩
    rcases get?_trunc_node hr with hr | hr
    · exact Or.inl ⟨r, hr, rfl⟩
    · exact Or.inr hr
  · exact ⟨q, ⟨q, hq, rfl⟩, ⟨[], hℓ₂, List.append_nil q⟩⟩

/-! ## The Buchberger criterion -/

variable {R : Type*} [CommRing R] {ρ : Type*} {O : AdmOrder E} (G : Rules R ρ O.toCtxOrder)

/-- **A critical ambiguity**: the two occurrences of leading monomials cover its monomial —
every vertex is a vertex of one of them — and share a vertex. -/
def Critical {C : Finset ℕ} {r₁ r₂ : ρ} (B : G.Amb C r₁ r₂) : Prop :=
  ∃ (p₁ p₂ : List ℕ) (xs₁ xs₂ : ℕ → STree E),
    (∀ h, (B.f₁ h).1 = B.top.1.replace p₁ (h.1.subst xs₁)) ∧
    (∀ h, (B.f₂ h).1 = B.top.1.replace p₂ (h.1.subst xs₂)) ∧
    vert B.top.1 ⊆ occVert p₁ (G.lead r₁).1 ∪ occVert p₂ (G.lead r₂).1 ∧
    (occVert p₁ (G.lead r₁).1 ∩ occVert p₂ (G.lead r₂).1).Nonempty

variable {G}

lemma Critical.swap {C : Finset ℕ} {r₁ r₂ : ρ} {B : G.Amb C r₁ r₂} (h : Critical G B) :
    Critical G B.swap := by
  obtain ⟨p₁, p₂, xs₁, xs₂, h₁, h₂, hc, ho⟩ := h
  refine ⟨p₂, p₁, xs₂, xs₁, ?_, ?_, ?_, ?_⟩
  · rw [Rules.Amb.swap_top]
    exact h₂
  · rw [Rules.Amb.swap_top]
    exact h₁
  · rw [Rules.Amb.swap_top, Set.union_comm]
    exact hc
  · rw [Set.inter_comm]
    exact ho

variable (G)

/-- The data of an ambiguity: the two occurrences in its monomial. -/
lemma Amb.data {B : Finset ℕ} {r₁ r₂ : ρ} (A : G.Amb B r₁ r₂) :
    ∃ p₁ xs₁ p₂ xs₂, A.top.1.get? p₁ = some ((G.lead r₁).1.subst xs₁) ∧
      A.top.1.get? p₂ = some ((G.lead r₂).1.subst xs₂) ∧
      Inputs (G.src r₁) B xs₁ ∧ Inputs (G.src r₂) B xs₂ ∧
      (∀ g, (A.f₁ g).1 = A.top.1.replace p₁ (g.1.subst xs₁)) ∧
      (∀ g, (A.f₂ g).1 = A.top.1.replace p₂ (g.1.subst xs₂)) := by
  obtain ⟨p₁, xs₁, h₁, hin₁, hf₁⟩ := IsSCtx.normal A.ctx₁ (G.lead r₁)
  obtain ⟨p₂, xs₂, h₂, hin₂, hf₂⟩ := IsSCtx.normal A.ctx₂ (G.lead r₂)
  have ht : A.f₂ (G.lead r₂) = A.top := A.eq.symm
  rw [ht] at h₂ hf₂
  exact ⟨p₁, xs₁, p₂, xs₂, h₁, h₂, hin₁, hin₂, hf₁, hf₂⟩

/-- **Classification**, when the position of the first occurrence is a prefix of the second. -/
theorem classify_of_prefix (hlead : ∀ r a, (G.lead r).1 ≠ leaf a) {B : Finset ℕ} {r₁ r₂ : ρ}
    (A : G.Amb B r₁ r₂) {p₁ p₂ : List ℕ} {xs₁ xs₂ : ℕ → STree E}
    (hT₁ : A.top.1.get? p₁ = some ((G.lead r₁).1.subst xs₁))
    (hT₂ : A.top.1.get? p₂ = some ((G.lead r₂).1.subst xs₂))
    (hin₁ : Inputs (G.src r₁) B xs₁) (hin₂ : Inputs (G.src r₂) B xs₂)
    (hf₁ : ∀ g, (A.f₁ g).1 = A.top.1.replace p₁ (g.1.subst xs₁))
    (hf₂ : ∀ g, (A.f₂ g).1 = A.top.1.replace p₂ (g.1.subst xs₂)) (hp : p₁ <+: p₂) :
    A.IsDisjoint ∨ ∃ C, ∃ B' : G.Amb C r₁ r₂, Critical G B' ∧ A.FactorsThrough B' := by
  obtain ⟨q, rfl⟩ := hp
  have hU₂ : ((G.lead r₁).1.subst xs₁).get? q = some ((G.lead r₂).1.subst xs₂) := by
    rw [get?_append_of hT₁] at hT₂
    exact hT₂
  rcases get?_subst_cases hU₂ with ⟨u, hu, heq⟩ | ⟨q₀, i, q', a, rfl, h₀, h''⟩
  · cases u with
    | leaf a =>
      left
      exact disjoint_of_nested (q'' := []) hT₁ hin₁ hin₂ hf₁
        (by rw [List.append_nil]; exact hf₂) hu (by rw [get?_nil, heq]; rfl)
    | node e c =>
      right
      obtain ⟨C, m, e₁, e₂, g, ys₁, ys₂, he₁, he₂, hg, hm₁, hm₂, hfe₁, hfe₂, hy₁, hy₂, hc, ho⟩ :=
        factors_of_overlap hT₁ hT₂ hin₁ hin₂ hf₁ hf₂ ⟨_, e, c, hu⟩
          (nil_mem_vert (hlead r₂))
      have htop : e₁ (G.lead r₁) = m := hm₁
      refine ⟨C, ⟨e₁, e₂, he₁, he₂, hm₁.trans hm₂.symm⟩, ⟨[], q, ys₁, ys₂, ?_, ?_, ?_, ho⟩,
        ⟨g, hg, hfe₁, hfe₂⟩⟩
      · show ∀ h, (e₁ h).1 = (e₁ (G.lead r₁)).1.replace [] (h.1.subst ys₁)
        rw [htop]
        exact hy₁
      · show ∀ h, (e₂ h).1 = (e₁ (G.lead r₁)).1.replace q (h.1.subst ys₂)
        rw [htop]
        exact hy₂
      · show vert (e₁ (G.lead r₁)).1 ⊆ _
        rw [htop]
        exact hc
  · left
    exact disjoint_of_nested hT₁ hin₁ hin₂ hf₁ hf₂ h₀ h''

/-- **Classification of ambiguities**: every ambiguity between rules whose leading monomials are
not leaves is disjoint or factors through a critical ambiguity. -/
theorem classify (hlead : ∀ r a, (G.lead r).1 ≠ leaf a) {B : Finset ℕ} {r₁ r₂ : ρ}
    (A : G.Amb B r₁ r₂) :
    A.IsDisjoint ∨ ∃ C, ∃ B' : G.Amb C r₁ r₂, Critical G B' ∧ A.FactorsThrough B' := by
  obtain ⟨p₁, xs₁, p₂, xs₂, hT₁, hT₂, hin₁, hin₂, hf₁, hf₂⟩ := Amb.data G A
  rcases prefix_or_incomp p₁ p₂ with hp | hp | hp
  · exact classify_of_prefix G hlead A hT₁ hT₂ hin₁ hin₂ hf₁ hf₂ hp
  · have hT : A.swap.top = A.top := Rules.Amb.swap_top A
    rcases classify_of_prefix G hlead A.swap (hT ▸ hT₂) (hT ▸ hT₁) hin₂ hin₁ (hT ▸ hf₂)
      (hT ▸ hf₁) hp with h | ⟨C, B', hB', h⟩
    · exact Or.inl (Rules.Amb.IsDisjoint.of_swap h)
    · exact Or.inr ⟨C, B'.swap, hB'.swap, Rules.Amb.FactorsThrough.of_swap h⟩
  · exact Or.inl (disjoint_of_incomp hT₁ hT₂ hin₁ hin₂ hf₁ hf₂ hp)

/-- **The Buchberger criterion for shuffle operads**: if no leading monomial is a leaf and every
critical ambiguity is resolvable, every ambiguity is resolvable. -/
theorem resolvable_of_critical (hlead : ∀ r a, (G.lead r).1 ≠ leaf a)
    (hcrit : ∀ {C : Finset ℕ} {r₁ r₂ : ρ} (B : G.Amb C r₁ r₂), Critical G B → B.Res)
    (A : Finset ℕ) : (G.rw A).Resolvable :=
  Rules.resolvable_of_crit (fun B => Critical G B) (fun B hB => hcrit B hB)
    (fun A => classify G hlead A) A

/-- **The Buchberger criterion for shuffle operads**: if no leading monomial is a leaf and every
critical ambiguity is resolvable, then on every set of leaves the normal monomials span a
complement of the ideal generated by the rules. -/
theorem isCompl_of_critical (hlead : ∀ r a, (G.lead r).1 ≠ leaf a)
    (hcrit : ∀ {C : Finset ℕ} {r₁ r₂ : ρ} (B : G.Amb C r₁ r₂), Critical G B → B.Res)
    (A : Finset ℕ) :
    IsCompl (Finsupp.supported R R {t : SMono E A | G.Normal t}) (G.rw A).ideal := by
  rw [← G.irr_eq]
  exact (resolvable_of_critical G hlead hcrit A).isCompl

/-- **The normal monomials are a basis of the quotient** by the ideal generated by the rules,
when every critical ambiguity is resolvable. -/
noncomputable def basisOfCritical (hlead : ∀ r a, (G.lead r).1 ≠ leaf a)
    (hcrit : ∀ {C : Finset ℕ} {r₁ r₂ : ρ} (B : G.Amb C r₁ r₂), Critical G B → B.Res)
    (A : Finset ℕ) : Module.Basis (G.rw A).Irr R ((SMono E A →₀ R) ⧸ (G.rw A).ideal) :=
  (resolvable_of_critical G hlead hcrit A).basis

/-- **Conversely**, if the normal monomials are independent modulo the ideal, every critical
ambiguity is resolvable. -/
theorem Critical.res_of_isCompl {C : Finset ℕ} {r₁ r₂ : ρ} (B : G.Amb C r₁ r₂)
    (h : Disjoint (Finsupp.supported R R {t : SMono E C | G.Normal t}) (G.rw C).ideal) :
    B.Res :=
  B.res_of_isCompl h

end STree

end Operad
