/-
# The Koszul dual operad of a shuffle operad

For relators `R` of arity three, functions on the shuffle monomials of arity three, **the Koszul
dual relators** `dualRel R` are those orthogonal to `R` for the pairing `Σ_σ chi3(σ) r(σ) ρ(σ)`,
twisted by the sign `chi3` of the monomials of arity three (`+1` for `e(f(0, 1), 2)`, `-1` for the
other two). The operad they present is **the Koszul dual operad**, and its linear dual in arity `n`
is the Koszul dual cooperad: the top homology `KD R n` of the bar construction.

* **Fully cut bar trees are monomials** (`ShuffleBar.fullBar`): in the top degree `n - 1` the
  chains are the functions on the monomials, through `toMono` and `ofMono`, which twist by the
  orientation sign `LTree.tauS` (`toMono_ofMono`, `ofMono_toMono`).
* **The differential of a chain of top degree**, at a bar tree with one uncut edge, is the value
  at the merged monomial times the sign of the edge (`d_ofMono_substBar`); by the coherence of the
  signs (`LTree.topSgn_mul_tauS_substAt`) its coefficients along the substitutions at the edge are
  `± chi3(σ)` times the values at the substituted monomials (`winCoef_d_ofMono`).
* So, by the description of the relator subcomplex in degree `n - 2`
  (`ShuffleBar.mem_J_iff_winCoef`), **the Koszul dual cooperad is the space `KDmono R n` of
  functions on the monomials whose values at the substitutions at every edge, twisted by `chi3`,
  form a relator** (`KD_equiv_KDmono`).
* **Duality** (`KDmono_eq_orthogonal`): that space is the orthogonal of the ideal generated by the
  Koszul dual relators, for the standard pairing on the monomials; the pairing on the relators is
  perfect (`dualRel_dualRel`, `finrank_dualRel`).
* **The Koszul dual operad has the dimension of the Koszul dual cooperad** in every arity `n ≥ 2`
  (`finrank_quotient_dualRel`), and when `R` is a quadratic Gröbner basis with leading monomials
  `L`, **its dimension is the number of monomials all of whose windows lie in `L`**
  (`finrank_quotient_dualRel_eq_ncard`).
-/
import Operad.ShuffleBarEdge
import Mathlib.LinearAlgebra.BilinearForm.Orthogonal
import Mathlib.Tactic.LinearCombination

universe u v

namespace Operad

/-! ## Diagonal bilinear forms -/

section Forms

variable {K : Type u} [Field K] {ι : Type*} [Fintype ι]

/-- **The diagonal bilinear form** `Σ_i c_i x_i y_i`. -/
noncomputable def diagForm (c : ι → K) : LinearMap.BilinForm K (ι → K) :=
  LinearMap.mk₂ K (fun x y => ∑ i, c i * x i * y i)
    (fun x x' y => by
      simp only [Pi.add_apply, ← Finset.sum_add_distrib]
      exact Finset.sum_congr rfl fun i _ => by ring)
    (fun a x y => by
      simp only [Pi.smul_apply, smul_eq_mul, Finset.mul_sum]
      exact Finset.sum_congr rfl fun i _ => by ring)
    (fun x y y' => by
      simp only [Pi.add_apply, ← Finset.sum_add_distrib]
      exact Finset.sum_congr rfl fun i _ => by ring)
    (fun a x y => by
      simp only [Pi.smul_apply, smul_eq_mul, Finset.mul_sum]
      exact Finset.sum_congr rfl fun i _ => by ring)

lemma diagForm_apply (c : ι → K) (x y : ι → K) : diagForm c x y = ∑ i, c i * x i * y i := rfl

lemma diagForm_isRefl (c : ι → K) : (diagForm c).IsRefl := fun x y h => by
  rw [diagForm_apply] at h ⊢
  rw [← h]
  exact Finset.sum_congr rfl fun i _ => by ring

lemma diagForm_nondegenerate {c : ι → K} (hc : ∀ i, c i ≠ 0) : (diagForm c).Nondegenerate := by
  classical
  refine ⟨fun x hx => funext fun i => ?_, fun y hy => funext fun i => ?_⟩
  · have h := hx (Pi.single i 1)
    rw [diagForm_apply, Finset.sum_eq_single i] at h
    · simpa [hc i] using h
    · intro j _ hj
      simp [hj]
    · simp
  · have h := hy (Pi.single i 1)
    rw [diagForm_apply, Finset.sum_eq_single i] at h
    · simpa [hc i] using h
    · intro j _ hj
      simp [hj]
    · simp

end Forms

namespace ShuffleBar

open LTree Module


variable {E : Type v}

/-! ## Fully cut bar trees -/

/-- **The fully cut bar tree of a monomial**: every edge is cut. -/
def fullBar (m : LTree E) : BarTree E := flagBy m.edgeKeys m

lemma full_fullBar (m : LTree E) : (fullBar m).mapDec Prod.fst = m := full_flagBy _ m

lemma cutKeys_fullBar (m : LTree E) : cutKeys (fullBar m) = m.edgeKeys := by
  rw [fullBar, cutKeys_flagBy, Finset.inter_eq_left.2 (edgeKeys_subset_nodeKeys m)]

/-- **Merging a cut edge of a flagged monomial** uncuts it. -/
lemma mergeK_flagBy (C : Finset (ℕ ×ₗ ℕ)) (k : ℕ ×ₗ ℕ) {m : LTree E} (hnd : m.labels.Nodup) :
    mergeK (flagBy C m) k = flagBy (C.erase k) m := by
  have hnd' : (flagBy C m).labels.Nodup := by rwa [labels_flagBy]
  have hc : cutKeys (mergeK (flagBy C m) k) = (C ∩ m.nodeKeys).erase k := by
    by_cases hk : k ∈ cutKeys (flagBy C m)
    · rw [cutKeys_mergeK _ hnd' hk, cutKeys_flagBy]
    · rw [mergeK_of_not_mem _ hk, cutKeys_flagBy]
      rw [cutKeys_flagBy] at hk
      exact (Finset.erase_eq_of_notMem hk).symm
  have hndm : (mergeK (flagBy C m) k).labels.Nodup := by rwa [labels_mergeK]
  rw [← flagBy_cutKeys _ hndm, hc, full_mergeK, full_flagBy]
  refine flagBy_congr m fun k' hk' => ?_
  simp only [Finset.mem_erase, Finset.mem_inter]
  tauto

lemma key_subtreeAt_flagBy (C : Finset (ℕ ×ₗ ℕ)) (m : LTree E) (q : List Bool) :
    key ((flagBy C m).subtreeAt q) = key (m.subtreeAt q) := by
  rw [← key_mapDec Prod.fst, ← subtreeAt_mapDec, full_flagBy]

/-- **The flag of a vertex of a flagged monomial** says whether its key is flagged. -/
lemma flagAt_flagBy (C : Finset (ℕ ×ₗ ℕ)) {m : LTree E} (hnd : m.labels.Nodup) {q : List Bool}
    (hq : ∃ e l r, m.subtreeAt q = node e l r) :
    flagAt (flagBy C m) q = decide (key (m.subtreeAt q) ∈ C) := by
  have hnd' : (flagBy C m).labels.Nodup := by rwa [labels_flagBy]
  have hq' : ∃ d l r, (flagBy C m).subtreeAt q = node d l r := by
    obtain ⟨e, l, r, h⟩ := hq
    have h' : ((flagBy C m).subtreeAt q).mapDec Prod.fst = node e l r := by
      rw [← subtreeAt_mapDec, full_flagBy, h]
    generalize (flagBy C m).subtreeAt q = u at h'
    cases u with
    | leaf => simp at h'
    | node d a b => exact ⟨d, a, b, rfl⟩
  rw [flagAt_eq _ q hnd' hq', key_subtreeAt_flagBy, cutKeys_flagBy]
  refine decide_eq_decide.2 ⟨fun h => (Finset.mem_inter.1 h).1, fun h => Finset.mem_inter.2
    ⟨h, key_subtreeAt_mem_nodeKeys m q hq⟩⟩

section Mono

variable [Fintype E] [DecidableEq E]

lemma nodup_of_mem_monomials {n : ℕ} {m : LTree E} (hm : m ∈ monomials n) : m.labels.Nodup :=
  ((mem_monomials n m).1 hm).2.nodup_iff.2 List.nodup_range

lemma arity_of_mem_monomials {n : ℕ} {m : LTree E} (hm : m ∈ monomials n) : m.arity = n := by
  rw [← length_labels, ((mem_monomials n m).1 hm).2.length_eq, List.length_range]

lemma card_edgeKeys_of_mem_monomials {n : ℕ} (hn : 2 ≤ n) {m : LTree E} (hm : m ∈ monomials n) :
    m.edgeKeys.card + 2 = n := by
  have ha := arity_of_mem_monomials hm
  cases m with
  | leaf => simp [arity] at ha; omega
  | node e l r => rw [card_edgeKeys (nodup_of_mem_monomials hm), ha]

omit [Fintype E] [DecidableEq E] in
lemma valid_flagBy {C : Finset (ℕ ×ₗ ℕ)} {m : LTree E} (hs : m.IsShuffle) (hnd : m.labels.Nodup)
    (hC : C ⊆ m.edgeKeys) : Valid (flagBy C m) :=
  ⟨by rw [← isShuffle_mapDec Prod.fst, full_flagBy]; exact hs, by rwa [labels_flagBy],
    rootFlag_flagBy hC⟩

/-- **The fully cut bar tree of a monomial** has the top degree. -/
lemma adm_fullBar {n : ℕ} (hn : 2 ≤ n) {m : LTree E} (hm : m ∈ monomials n) :
    Adm n (n - 1) (fullBar m) := by
  have h := (mem_monomials n m).1 hm
  refine ⟨valid_flagBy h.1 (nodup_of_mem_monomials hm) subset_rfl, ?_, ?_⟩
  · rw [fullBar, labels_flagBy]
    exact h.2
  · rw [cutKeys_fullBar]
    have := card_edgeKeys_of_mem_monomials hn hm
    omega

/-- **A bar tree of the top degree is fully cut.** -/
lemma eq_fullBar_of_adm {n : ℕ} {x : BarTree E} (hx : Adm n (n - 1) x) :
    x = fullBar (x.mapDec Prod.fst) := by
  have hm := full_mem_monomials hx
  have hsub := cutKeys_subset_edgeKeys hx.1.root
  have h1 := hx.2.2
  have hn : 2 ≤ n := by omega
  have h2 := card_edgeKeys_of_mem_monomials hn hm
  have heq : cutKeys x = (x.mapDec Prod.fst).edgeKeys :=
    Finset.eq_of_subset_of_card_le hsub (by omega)
  rw [fullBar, ← heq, flagBy_cutKeys x hx.1.nodup]

omit [Fintype E] [DecidableEq E] in
lemma fullBar_injective {m m' : LTree E} (h : fullBar m = fullBar m') : m = m' := by
  rw [← full_fullBar m, h, full_fullBar]

/-! ## Chains of top degree as functions on the monomials -/

variable (K : Type u) [Field K]

/-- **A function on the monomials of arity `n`, at a tree**: zero off those monomials. -/
noncomputable def monoVal {n : ℕ} (x : Mono E n → K) (t : LTree E) : K :=
  if h : t ∈ monomials n then x ⟨t, h⟩ else 0

variable {K}

lemma monoVal_mono {n : ℕ} (x : Mono E n → K) (t : Mono E n) : monoVal K x t.1 = x t := by
  simp [monoVal, t.2]

lemma monoVal_of_mem {n : ℕ} (x : Mono E n → K) {t : LTree E} (ht : t ∈ monomials n) :
    monoVal K x t = x ⟨t, ht⟩ := by
  simp [monoVal, ht]

lemma monoVal_add {n : ℕ} (x y : Mono E n → K) (t : LTree E) :
    monoVal K (x + y) t = monoVal K x t + monoVal K y t := by
  unfold monoVal
  split_ifs <;> simp

lemma monoVal_smul {n : ℕ} (c : K) (x : Mono E n → K) (t : LTree E) :
    monoVal K (c • x) t = c * monoVal K x t := by
  unfold monoVal
  split_ifs <;> simp

lemma sum_vecOf_mul {n : ℕ} (t : LTree E) (x : Mono E n → K) :
    ∑ m, vecOf K n t m * x m = monoVal K x t := by
  unfold monoVal vecOf
  split_ifs with ht
  · rw [Finset.sum_eq_single ⟨t, ht⟩]
    · simp
    · intro m _ hm
      rw [if_neg fun h => hm (Subtype.ext h), zero_mul]
    · simp
  · exact Finset.sum_eq_zero fun m _ => by
      rw [if_neg fun h => ht (by rw [← h]; exact m.2), zero_mul]

variable (K)

/-- **The coefficients of a chain on the fully cut bar trees**, as a function on the monomials,
twisted by the orientation sign. -/
noncomputable def toMono (n : ℕ) : (BarTree E →₀ K) →ₗ[K] (Mono E n → K) where
  toFun v m := (tauS m.1 : K) * v (fullBar m.1)
  map_add' v w := by
    funext m
    simp [mul_add]
  map_smul' c v := by
    funext m
    simp only [Finsupp.smul_apply, smul_eq_mul, Pi.smul_apply, RingHom.id_apply]
    ring

/-- **The chain of top degree of a function on the monomials**, twisted by the orientation sign. -/
noncomputable def ofMono (n : ℕ) : (Mono E n → K) →ₗ[K] (BarTree E →₀ K) where
  toFun x := ∑ m, ((tauS m.1 : K) * x m) • Finsupp.single (fullBar m.1) 1
  map_add' x y := by
    simp only [Pi.add_apply, mul_add, add_smul, Finset.sum_add_distrib]
  map_smul' c x := by
    simp only [Pi.smul_apply, smul_eq_mul, Finset.smul_sum, smul_smul, RingHom.id_apply]
    exact Finset.sum_congr rfl fun m _ => by ring_nf

variable {K}

omit [Fintype E] [DecidableEq E] in
lemma tauS_cast_mul_self (t : LTree E) : (tauS t : K) * (tauS t : K) = 1 := by
  rw [← Int.cast_mul, tauS_mul_self, Int.cast_one]

lemma ofMono_apply {n : ℕ} (x : Mono E n → K) (b : BarTree E) :
    ofMono K n x b = ∑ m : Mono E n, (tauS m.1 : K) * x m * if fullBar m.1 = b then 1 else 0 := by
  simp [ofMono, Finsupp.finsetSum_apply, Finsupp.single_apply]

lemma ofMono_apply_fullBar {n : ℕ} (x : Mono E n → K) (m : Mono E n) :
    ofMono K n x (fullBar m.1) = (tauS m.1 : K) * x m := by
  rw [ofMono_apply, Finset.sum_eq_single m]
  · simp
  · intro m' _ hm'
    rw [if_neg fun h => hm' (Subtype.ext (fullBar_injective h)), mul_zero]
  · simp

theorem toMono_ofMono {n : ℕ} (x : Mono E n → K) : toMono K n (ofMono K n x) = x := by
  funext m
  show (tauS m.1 : K) * ofMono K n x (fullBar m.1) = x m
  rw [ofMono_apply_fullBar, ← mul_assoc, tauS_cast_mul_self, one_mul]

lemma ofMono_mem_C {n : ℕ} (hn : 2 ≤ n) (x : Mono E n → K) : ofMono K n x ∈ C K n (n - 1) :=
  Submodule.sum_mem _ fun m _ => Submodule.smul_mem _ _
    (Finsupp.single_mem_supported K _ (adm_fullBar hn m.2))

theorem ofMono_toMono {n : ℕ} {v : BarTree E →₀ K} (hv : v ∈ C K n (n - 1)) :
    ofMono K n (toMono K n v) = v := by
  ext b
  rw [ofMono_apply]
  by_cases hb : ∃ m : Mono E n, fullBar m.1 = b
  · obtain ⟨m, rfl⟩ := hb
    rw [Finset.sum_eq_single m]
    · show (tauS m.1 : K) * ((tauS m.1 : K) * v (fullBar m.1)) * _ = _
      rw [if_pos rfl, mul_one, ← mul_assoc, tauS_cast_mul_self, one_mul]
    · intro m' _ hm'
      rw [if_neg fun h => hm' (Subtype.ext (fullBar_injective h)), mul_zero]
    · simp
  · push Not at hb
    rw [Finset.sum_eq_zero fun m _ => by rw [if_neg (hb m), mul_zero]]
    by_contra h0
    have hA : Adm n (n - 1) b := hv (Finsupp.mem_support_iff.2 (Ne.symm h0))
    exact hb ⟨_, full_mem_monomials hA⟩ (eq_fullBar_of_adm hA).symm

/-! ## The differential of a chain of top degree -/

omit [Fintype E] [DecidableEq E] in
lemma sgn_fullBar (m : LTree E) (k : ℕ ×ₗ ℕ) : sgn K (fullBar m) k = (topSgn m k : K) := by
  simp [sgn, topSgn, cutKeys_fullBar]

omit [Fintype E] in
lemma dTree_fullBar_apply {m : LTree E} (hnd : m.labels.Nodup) (b : BarTree E) :
    dTree K (fullBar m) b =
      ∑ k ∈ m.edgeKeys, (topSgn m k : K) * if flagBy (m.edgeKeys.erase k) m = b then 1 else 0 := by
  simp only [dTree, Finsupp.finsetSum_apply, Finsupp.smul_apply, smul_eq_mul,
    Finsupp.single_apply, cutKeys_fullBar, sgn_fullBar]
  refine Finset.sum_congr rfl fun k _ => ?_
  rw [fullBar, mergeK_flagBy _ _ hnd]

/-- **The key of the lower vertex of the window of a substitution** is an edge key of the
substituted monomial, and not a cut key of the bar tree. -/
lemma key_side3_mem {y : BarTree E} (hy : Valid y) {p : List Bool} {s : Bool}
    (h : IsUncut y p s) (σ : Mono E 3) :
    key (((y.mapDec Prod.fst).substAt p s σ.1).subtreeAt (p ++ [side3 σ.1])) ∈
        ((y.mapDec Prod.fst).substAt p s σ.1).edgeKeys ∧
      key (((y.mapDec Prod.fst).substAt p s σ.1).subtreeAt (p ++ [side3 σ.1])) ∉
        cutKeys (substBar y p s σ.1) := by
  obtain ⟨hσs, hσl, -⟩ := mono_shape σ
  obtain ⟨b₀, q₀, hq₀⟩ : ∃ b q, p ++ [side3 σ.1] = b :: q := by
    cases p <;> exact ⟨_, _, rfl⟩
  obtain ⟨f, A, B, hfab⟩ := substBar_subtreeAt_side3 h.1 hσs hσl
  have hY : Valid (substBar y p s σ.1) := hy.substBar h σ
  rw [← full_substBar h.1 σ.1, edgeKeys_mapDec, subtreeAt_mapDec, key_mapDec]
  refine ⟨?_, fun h' => ?_⟩
  · rw [hq₀]
    exact key_subtreeAt_mem_edgeKeys _ b₀ q₀ ⟨_, _, _, hq₀ ▸ hfab⟩
  · have hf := flagAt_eq _ _ hY.nodup ⟨_, _, _, hfab⟩
    rw [show flagAt (substBar y p s σ.1) (p ++ [side3 σ.1]) = false by
      simp [flagAt, hfab, rootFlag]] at hf
    simp [h'] at hf

/-- **The cut keys of a substitution at the uncut edge** are the edge keys of the substituted
monomial but the key of the lower vertex of the window. -/
lemma cutKeys_substBar_eq_erase {n : ℕ} {y : BarTree E} (hy : Adm n (n - 2) y) {p : List Bool}
    {s : Bool} (h : IsUncut y p s) (σ : Mono E 3) :
    cutKeys (substBar y p s σ.1) = ((y.mapDec Prod.fst).substAt p s σ.1).edgeKeys.erase
      (key (((y.mapDec Prod.fst).substAt p s σ.1).subtreeAt (p ++ [side3 σ.1]))) := by
  obtain ⟨hσs, hσl, hσn⟩ := mono_shape σ
  obtain ⟨hk₀E, hk₀C⟩ := key_side3_mem hy.1 h σ
  have hY : Valid (substBar y p s σ.1) := hy.1.substBar h σ
  have hfull := full_substBar h.1 σ.1
  have hsubY : cutKeys (substBar y p s σ.1) ⊆ ((y.mapDec Prod.fst).substAt p s σ.1).edgeKeys := by
    have := cutKeys_subset_edgeKeys hY.root
    rwa [hfull] at this
  refine Finset.eq_of_subset_of_card_le (fun k' hk' => Finset.mem_erase.2
    ⟨fun h' => hk₀C (h' ▸ hk'), hsubY hk'⟩) ?_
  rw [Finset.card_erase_of_mem hk₀E]
  have hMm : (y.mapDec Prod.fst).substAt p s σ.1 ∈ monomials n :=
    substAt_mem_monomials (full_mem_monomials hy) ((isEdge_mapDec _ _ _ _).2 h.1) σ.2
  have hn : 2 ≤ n := by have := hy.2.2; omega
  have h1 := card_edgeKeys_of_mem_monomials hn hMm
  have h2 := card_add_three_of_adm hy
  have h3 : y.arity = n := by rw [← length_labels, hy.2.1.length_eq, List.length_range]
  rw [cutKeys_substBar hy.1.shuffle hy.1.nodup h hσl hσn]
  omega

/-- **The bar tree with one uncut edge of a substitution** is the merge of the fully cut bar tree
of the substituted monomial along exactly one edge, that of the lower vertex of the window. -/
lemma flagBy_erase_eq_substBar_iff {n : ℕ} {y : BarTree E} (hy : Adm n (n - 2) y)
    {p : List Bool} {s : Bool} (h : IsUncut y p s) (σ : Mono E 3) {m : LTree E}
    {k : ℕ ×ₗ ℕ} (hk : k ∈ m.edgeKeys) :
    flagBy (m.edgeKeys.erase k) m = substBar y p s σ.1 ↔
      m = (y.mapDec Prod.fst).substAt p s σ.1 ∧
        k = key (((y.mapDec Prod.fst).substAt p s σ.1).subtreeAt (p ++ [side3 σ.1])) := by
  have hY : Valid (substBar y p s σ.1) := hy.1.substBar h σ
  have hfull := full_substBar h.1 σ.1
  have hcutY := cutKeys_substBar_eq_erase hy h σ
  have hk₀E := (key_side3_mem hy.1 h σ).1
  constructor
  · intro heq
    have hm : m = (y.mapDec Prod.fst).substAt p s σ.1 := by
      rw [← full_flagBy (m.edgeKeys.erase k) m, heq, hfull]
    subst hm
    refine ⟨rfl, ?_⟩
    have hc := congrArg cutKeys heq
    rw [cutKeys_flagBy, Finset.inter_eq_left.2 ((Finset.erase_subset _ _).trans
      (edgeKeys_subset_nodeKeys _)), hcutY] at hc
    by_contra hne
    have h' := Finset.mem_erase.2 ⟨Ne.symm hne, hk₀E⟩
    rw [hc] at h'
    exact (Finset.notMem_erase _ _) h'
  · rintro ⟨rfl, rfl⟩
    rw [← hcutY, ← hfull]
    exact flagBy_cutKeys _ hY.nodup

/-- **The differential of a chain of top degree at a substitution**: the value at the substituted
monomial times the orientation sign and the sign of the edge. -/
theorem d_ofMono_substBar {n : ℕ} {y : BarTree E} (hy : Adm n (n - 2) y) {p : List Bool}
    {s : Bool} (h : IsUncut y p s) (x : Mono E n → K) (σ : Mono E 3) :
    d K (ofMono K n x) (substBar y p s σ.1) =
      (tauS ((y.mapDec Prod.fst).substAt p s σ.1) : K) *
        monoVal K x ((y.mapDec Prod.fst).substAt p s σ.1) *
        (topSgn ((y.mapDec Prod.fst).substAt p s σ.1)
          (key (((y.mapDec Prod.fst).substAt p s σ.1).subtreeAt (p ++ [side3 σ.1]))) : K) := by
  have hMm : (y.mapDec Prod.fst).substAt p s σ.1 ∈ monomials n :=
    substAt_mem_monomials (full_mem_monomials hy) ((isEdge_mapDec _ _ _ _).2 h.1) σ.2
  have hk₀E := (key_side3_mem hy.1 h σ).1
  have hd : d K (ofMono K n x) =
      ∑ m : Mono E n, ((tauS m.1 : K) * x m) • dTree K (fullBar m.1) := by
    simp only [ofMono, LinearMap.coe_mk, AddHom.coe_mk, map_sum, map_smul, d_single, one_smul]
  rw [hd, Finsupp.finsetSum_apply, Finset.sum_eq_single ⟨_, hMm⟩]
  · rw [Finsupp.smul_apply, smul_eq_mul, dTree_fullBar_apply (nodup_of_mem_monomials hMm),
      Finset.sum_eq_single
        (key (((y.mapDec Prod.fst).substAt p s σ.1).subtreeAt (p ++ [side3 σ.1]))),
      monoVal_of_mem x hMm]
    · rw [if_pos ((flagBy_erase_eq_substBar_iff hy h σ hk₀E).2 ⟨rfl, rfl⟩)]
      dsimp only
      ring
    · intro k hk hkk
      rw [if_neg fun h' => hkk ((flagBy_erase_eq_substBar_iff hy h σ hk).1 h').2, mul_zero]
    · exact fun h' => absurd hk₀E h'
  · intro m _ hm
    rw [Finsupp.smul_apply, smul_eq_mul, dTree_fullBar_apply (nodup_of_mem_monomials m.2)]
    refine mul_eq_zero_of_right _ (Finset.sum_eq_zero fun k hk => ?_)
    rw [if_neg fun h' => hm (Subtype.ext ((flagBy_erase_eq_substBar_iff hy h σ hk).1 h').1),
      mul_zero]
  · simp

/-! ## The Koszul dual cooperad on the monomials -/

/-- **A monomial with one edge uncut** is a bar tree of degree `n - 2`. -/
lemma adm_flagBy_erase {n : ℕ} (hn : 2 ≤ n) {t : LTree E} (ht : t ∈ monomials n)
    {p : List Bool} {s : Bool} (he : t.IsEdge p s) :
    Adm n (n - 2) (flagBy (t.edgeKeys.erase (key (t.subtreeAt (p ++ [s])))) t) ∧
      IsUncut (flagBy (t.edgeKeys.erase (key (t.subtreeAt (p ++ [s])))) t) p s := by
  have hst := (mem_monomials n t).1 ht
  have hnd := nodup_of_mem_monomials ht
  obtain ⟨b, q, hq⟩ : ∃ b q, p ++ [s] = b :: q := by
    cases p <;> exact ⟨_, _, rfl⟩
  have hkE : key (t.subtreeAt (p ++ [s])) ∈ t.edgeKeys := by
    have hn' := he.exists_node_child
    rw [hq] at hn' ⊢
    exact key_subtreeAt_mem_edgeKeys t b q hn'
  refine ⟨⟨valid_flagBy hst.1 hnd (Finset.erase_subset _ _), by rw [labels_flagBy]; exact hst.2,
    ?_⟩, (isEdge_mapDec Prod.fst _ p s).1 (by rw [full_flagBy]; exact he), ?_⟩
  · rw [cutKeys_flagBy, Finset.inter_eq_left.2 ((Finset.erase_subset _ _).trans
      (edgeKeys_subset_nodeKeys t)), Finset.card_erase_of_mem hkE]
    have := card_edgeKeys_of_mem_monomials hn ht
    have : 1 ≤ t.edgeKeys.card := Finset.card_pos.2 ⟨_, hkE⟩
    omega
  · rw [flagAt_flagBy _ hnd he.exists_node_child]
    simp

variable (K)

/-- **The values at the substitutions at an edge**, twisted by `chi3`. -/
noncomputable def winVal {n : ℕ} (x : Mono E n → K) (t : LTree E) (p : List Bool) (s : Bool) :
    Mono E 3 → K :=
  fun σ => (chi3 σ.1 : K) * monoVal K x (t.substAt p s σ.1)

/-- **The Koszul dual cooperad, on the monomials**: the functions on the monomials of arity `n`
whose values at the substitutions at every edge, twisted by `chi3`, form a relator. -/
noncomputable def KDmono (R : Submodule K (Mono E 3 → K)) (n : ℕ) :
    Submodule K (Mono E n → K) where
  carrier := {x | ∀ t : Mono E n, ∀ p s, t.1.IsEdge p s → winVal K x t.1 p s ∈ R}
  add_mem' {x y} hx hy t p s he := by
    have : winVal K (x + y) t.1 p s = winVal K x t.1 p s + winVal K y t.1 p s := by
      funext σ
      simp [winVal, monoVal_add, mul_add]
    rw [this]
    exact add_mem (hx t p s he) (hy t p s he)
  zero_mem' t p s he := by
    have : winVal K (0 : Mono E n → K) t.1 p s = 0 := by
      funext σ
      simp [winVal, monoVal]
    rw [this]
    exact zero_mem _
  smul_mem' c x hx t p s he := by
    have : winVal K (c • x) t.1 p s = c • winVal K x t.1 p s := by
      funext σ
      simp only [winVal, monoVal_smul, Pi.smul_apply, smul_eq_mul]
      ring
    rw [this]
    exact Submodule.smul_mem _ c (hx t p s he)

variable {K}

/-- **The coefficients of the differential of a chain of top degree along the substitutions at an
edge** are `± chi3(σ)` times its values at the substituted monomials, by the coherence of the
signs. -/
theorem winCoef_d_ofMono {n : ℕ} {y : BarTree E} (hy : Adm n (n - 2) y) {p : List Bool}
    {s : Bool} (h : IsUncut y p s) : ∃ c : K, c * c = 1 ∧ ∀ x : Mono E n → K,
      winCoef K y p s (d K (ofMono K n x)) = c • winVal K x (y.mapDec Prod.fst) p s := by
  obtain ⟨c, hc, hcoh⟩ := topSgn_mul_tauS_substAt (t := y.mapDec Prod.fst)
    ((isShuffle_mapDec _ _).2 hy.1.shuffle) (by simpa using hy.1.nodup)
    ((isEdge_mapDec _ _ _ _).2 h.1)
  refine ⟨(c : K), by rw [← Int.cast_mul, hc, Int.cast_one], fun x => funext fun σ => ?_⟩
  obtain ⟨hσs, hσl, -⟩ := mono_shape σ
  have hcast := congrArg (fun z : ℤ => (z : K)) (hcoh σ.1 hσs hσl)
  push_cast at hcast
  rw [winCoef_apply, d_ofMono_substBar hy h x σ, Pi.smul_apply, smul_eq_mul, winVal]
  calc _ = ((topSgn ((y.mapDec Prod.fst).substAt p s σ.1)
          (key (((y.mapDec Prod.fst).substAt p s σ.1).subtreeAt (p ++ [side3 σ.1]))) : K) *
          (tauS ((y.mapDec Prod.fst).substAt p s σ.1) : K)) *
          monoVal K x ((y.mapDec Prod.fst).substAt p s σ.1) := by ring
    _ = _ := by
      rw [hcast]
      ring

/-- **A chain of top degree is a cycle modulo the relators** exactly when its function on the
monomials lies in `KDmono`. -/
theorem d_ofMono_mem_J_iff {R : Submodule K (Mono E 3 → K)} {n : ℕ} (hn : 2 ≤ n)
    (x : Mono E n → K) : d K (ofMono K n x) ∈ J K R ↔ x ∈ KDmono K R n := by
  have hC : d K (ofMono K n x) ∈ C K n (n - 2) := by
    have := ofMono_mem_C hn x
    rw [show n - 1 = (n - 2) + 1 by omega] at this
    exact d_mem_C K this
  rw [mem_J_iff_winCoef hC]
  constructor
  · intro hJ t p s he
    obtain ⟨hy, hu⟩ := adm_flagBy_erase hn t.2 he
    obtain ⟨c, hc, hw⟩ := winCoef_d_ofMono (K := K) hy hu
    have h1 := hJ _ p s hy hu
    rw [hw x, full_flagBy] at h1
    have : winVal K x t.1 p s = c • (c • winVal K x t.1 p s) := by rw [smul_smul, hc, one_smul]
    rw [this]
    exact Submodule.smul_mem _ c h1
  · intro hx y p s hy hu
    obtain ⟨c, -, hw⟩ := winCoef_d_ofMono (K := K) hy hu
    rw [hw x]
    exact Submodule.smul_mem _ c
      (hx ⟨_, full_mem_monomials hy⟩ p s ((isEdge_mapDec _ _ _ _).2 hu.1))

/-- **The Koszul dual cooperad is the space `KDmono` of functions on the monomials**, through the
fully cut bar trees, in every arity `n ≥ 2`. -/
noncomputable def KD_equiv_KDmono (R : Submodule K (Mono E 3 → K)) {n : ℕ} (hn : 2 ≤ n) :
    KD K R n ≃ₗ[K] KDmono K R n where
  toFun v := ⟨toMono K n v.1, by
    rw [← d_ofMono_mem_J_iff hn, ofMono_toMono (Submodule.mem_inf.1 v.2).1]
    exact (Submodule.mem_inf.1 v.2).2⟩
  invFun x := ⟨ofMono K n x.1, Submodule.mem_inf.2 ⟨ofMono_mem_C hn x.1,
    (d_ofMono_mem_J_iff hn x.1).2 x.2⟩⟩
  map_add' v w := Subtype.ext (map_add _ _ _)
  map_smul' c v := Subtype.ext (map_smul _ _ _)
  left_inv v := Subtype.ext (ofMono_toMono (Submodule.mem_inf.1 v.2).1)
  right_inv x := Subtype.ext (toMono_ofMono x.1)

/-! ## The Koszul dual relators -/

variable (K)

/-- **The Koszul dual relators**: those orthogonal to `R` for the pairing twisted by `chi3`. -/
noncomputable def dualRel (R : Submodule K (Mono E 3 → K)) : Submodule K (Mono E 3 → K) :=
  (diagForm fun σ : Mono E 3 => (chi3 σ.1 : K)).orthogonal R

variable {K}

omit [Fintype E] [DecidableEq E] in
lemma chi3_cast_ne_zero (σ : LTree E) : (chi3 σ : K) ≠ 0 := by
  intro h
  have := congrArg (fun z : ℤ => (z : K)) (chi3_sq σ)
  push_cast at this
  rw [h, zero_mul] at this
  exact zero_ne_one this

lemma mem_dualRel {R : Submodule K (Mono E 3 → K)} {ρ : Mono E 3 → K} :
    ρ ∈ dualRel K R ↔ ∀ r ∈ R, ∑ σ, (chi3 σ.1 : K) * r σ * ρ σ = 0 := Iff.rfl

/-- **The Koszul dual of the Koszul dual relators** is the space of relators. -/
theorem dualRel_dualRel (R : Submodule K (Mono E 3 → K)) : dualRel K (dualRel K R) = R :=
  LinearMap.BilinForm.orthogonal_orthogonal
    (diagForm_nondegenerate (c := fun σ : Mono E 3 => (chi3 σ.1 : K))
      fun σ => chi3_cast_ne_zero σ.1) (diagForm_isRefl _) R

/-- **The Koszul dual relators have the complementary dimension.** -/
theorem finrank_dualRel (R : Submodule K (Mono E 3 → K)) :
    finrank K (dualRel K R) = finrank K (Mono E 3 → K) - finrank K R :=
  LinearMap.BilinForm.finrank_orthogonal
    (diagForm_nondegenerate (c := fun σ : Mono E 3 => (chi3 σ.1 : K))
      fun σ => chi3_cast_ne_zero σ.1) R

/-- The pairing of a substituted relator with a function on the monomials. -/
lemma diagForm_one_substVec {n : ℕ} (t : LTree E) (p : List Bool) (s : Bool)
    (ρ : Mono E 3 → K) (x : Mono E n → K) :
    diagForm (fun _ : Mono E n => (1 : K)) (substVec K n t p s ρ) x =
      ∑ σ, ρ σ * monoVal K x (t.substAt p s σ.1) := by
  rw [diagForm_apply]
  simp only [one_mul, substVec, Finset.sum_apply, Pi.smul_apply, smul_eq_mul, Finset.sum_mul]
  rw [Finset.sum_comm]
  refine Finset.sum_congr rfl fun σ _ => ?_
  rw [← sum_vecOf_mul, Finset.mul_sum]
  exact Finset.sum_congr rfl fun m _ => by ring

/-- **Duality: the Koszul dual cooperad, on the monomials, is the orthogonal of the ideal of the
Koszul dual relators**, for the standard pairing of the functions on the monomials. -/
theorem KDmono_eq_orthogonal (R : Submodule K (Mono E 3 → K)) (n : ℕ) :
    KDmono K R n =
      (diagForm fun _ : Mono E n => (1 : K)).orthogonal (idealOf K (dualRel K R) n) := by
  ext x
  rw [LinearMap.BilinForm.mem_orthogonal_iff]
  constructor
  · intro hx v hv
    induction hv using Submodule.span_induction with
    | mem v hv =>
      obtain ⟨t, p, s, ρ, hρ, he, rfl⟩ := hv
      show diagForm _ (substVec K n t.1 p s ρ) x = 0
      rw [diagForm_one_substVec, ← hρ _ (hx t p s he)]
      refine Finset.sum_congr rfl fun σ _ => ?_
      have h2 : (chi3 σ.1 : K) * (chi3 σ.1 : K) = 1 := by
        rw [← Int.cast_mul, chi3_sq, Int.cast_one]
      simp only [winVal]
      linear_combination (-(ρ σ * monoVal K x (t.1.substAt p s σ.1))) * h2
    | zero => exact LinearMap.BilinForm.isOrtho_zero_left x
    | add v w _ _ hv hw =>
      show diagForm _ (v + w) x = 0
      rw [map_add, LinearMap.add_apply, hv, hw, add_zero]
    | smul c v _ hv =>
      show diagForm _ (c • v) x = 0
      rw [map_smul, LinearMap.smul_apply, hv, smul_zero]
  · intro hx t p s he
    rw [← dualRel_dualRel R, mem_dualRel]
    intro ρ hρ
    have h1 := hx _ (substVec_mem_idealOf K (dualRel K R) t he hρ)
    change diagForm _ (substVec K n t.1 p s ρ) x = 0 at h1
    rw [diagForm_one_substVec] at h1
    rw [← h1]
    refine Finset.sum_congr rfl fun σ _ => ?_
    have h2 : (chi3 σ.1 : K) * (chi3 σ.1 : K) = 1 := by
      rw [← Int.cast_mul, chi3_sq, Int.cast_one]
    simp only [winVal]
    linear_combination (ρ σ * monoVal K x (t.1.substAt p s σ.1)) * h2

/-- **The dimension of `KDmono` is that of the operad presented by the Koszul dual relators.** -/
theorem finrank_KDmono (R : Submodule K (Mono E 3 → K)) (n : ℕ) :
    finrank K (KDmono K R n) = finrank K ((Mono E n → K) ⧸ idealOf K (dualRel K R) n) := by
  rw [KDmono_eq_orthogonal, LinearMap.BilinForm.finrank_orthogonal
    (diagForm_nondegenerate fun _ => one_ne_zero)]
  have := Submodule.finrank_quotient_add_finrank (idealOf K (dualRel K R) n)
  omega

/-- **The Koszul dual operad has the dimension of the Koszul dual cooperad**: in every arity
`n ≥ 2`, the operad presented by the Koszul dual relators has the dimension of the top homology
of the bar construction of the operad presented by `R`. -/
theorem finrank_quotient_dualRel (R : Submodule K (Mono E 3 → K)) {n : ℕ} (hn : 2 ≤ n) :
    finrank K ((Mono E n → K) ⧸ idealOf K (dualRel K R) n) = finrank K (KD K R n) := by
  rw [← finrank_KDmono, (KD_equiv_KDmono R hn).finrank_eq]

/-- **The dimension of the Koszul dual operad of a quadratic Gröbner basis** with leading
monomials `L` is the number of monomials all of whose windows lie in `L`, in every arity
`n ≥ 2`. -/
theorem finrank_quotient_dualRel_eq_ncard (rk : E → ℕ) {L : Set (LTree E)}
    {R : Submodule K (Mono E 3 → K)} (hG : IsGroebner K rk L R) {n : ℕ} (hn : 2 ≤ n) :
    finrank K ((Mono E n → K) ⧸ idealOf K (dualRel K R) n) =
      {m | m ∈ monomials (E := E) n ∧ IsFull L m}.ncard := by
  rw [finrank_quotient_dualRel R hn, finrank_KD_eq_ncard K rk hG hn]

end Mono

end ShuffleBar

end Operad
