/-
# Generated ideals, and symmetric operads presented by relators

The ideals of a symmetric operad are ordered by inclusion and closed under intersections
(`SymOperadIdeal.sInf`), so every family of elements `r n ⊆ P (Fin n)` generates an ideal, the
smallest one containing it (`SymOperadIdeal.span`, `subset_span`, `span_le`). Relators are given on
the standard input sets `Fin n`: an ideal is stable under relabelling, so it contains every
relabelling of a relator as soon as it contains the relator (`map_mem_span`).

The quotient by a generated ideal is **the operad presented by the relators**. A morphism out of it
is a morphism out of `P` killing the relators (`presHomEquiv`), because a morphism kills an ideal
exactly when the ideal lies in its kernel (`span_le_ker_iff`). Taking for `P` the linearization of
a set operad presented by generators and relations, `Lin R (Pres T ρ)` (for instance the free one,
`FreeSet T`, or the one in which some generators are symmetric), this is the operad in `R`-modules
presented by generators, by set-theoretic relations, and by linear relators, and its morphisms are
the generator values satisfying both kinds of relation (`presLinHomEquiv`).
-/
import Operad.SymQuot
import Operad.SetPresentation

universe u v w

namespace Operad

open Sym

namespace SymOperadIdeal

variable {R : Type u} [CommRing R]
  {P : (A : Type) → [Fintype A] → [DecidableEq A] → Type v}
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (P A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (P A)] [SymOperad R P]

@[ext] lemma ext {I J : SymOperadIdeal R P}
    (h : ∀ (A : Type) [Fintype A] [DecidableEq A], I.sub A = J.sub A) : I = J := by
  obtain ⟨I, _, _, _⟩ := I
  obtain ⟨J, _, _, _⟩ := J
  have : @I = @J := by
    funext A _ _
    exact h A
  subst this
  rfl

/-- **Ideals are ordered by inclusion**, input set by input set. -/
instance : PartialOrder (SymOperadIdeal R P) where
  le I J := ∀ (A : Type) [Fintype A] [DecidableEq A], I.sub A ≤ J.sub A
  le_refl _ _ _ _ := le_rfl
  le_trans _ _ _ hIJ hJK A _ _ := (hIJ A).trans (hJK A)
  le_antisymm _ _ hIJ hJI := ext fun A _ _ => le_antisymm (hIJ A) (hJI A)

lemma le_def {I J : SymOperadIdeal R P} :
    I ≤ J ↔ ∀ (A : Type) [Fintype A] [DecidableEq A], I.sub A ≤ J.sub A := Iff.rfl

/-- **The intersection of a set of ideals is an ideal.** -/
def sInf (S : Set (SymOperadIdeal R P)) : SymOperadIdeal R P where
  sub A _ _ := ⨅ I ∈ S, I.sub A
  map_mem := by
    intro A B _ _ _ _ e x hx
    simp only [Submodule.mem_iInf] at hx ⊢
    exact fun I hI => I.map_mem e (hx I hI)
  comp_mem_left := by
    intro A B _ _ _ _ i x y hx
    simp only [Submodule.mem_iInf] at hx ⊢
    exact fun I hI => I.comp_mem_left i y (hx I hI)
  comp_mem_right := by
    intro A B _ _ _ _ i x y hy
    simp only [Submodule.mem_iInf] at hy ⊢
    exact fun I hI => I.comp_mem_right i x (hy I hI)

lemma mem_sInf {S : Set (SymOperadIdeal R P)} {A : Type} [Fintype A] [DecidableEq A] {x : P A} :
    x ∈ (sInf S).sub A ↔ ∀ I ∈ S, x ∈ I.sub A := by
  simp only [sInf, Submodule.mem_iInf]

lemma sInf_le {S : Set (SymOperadIdeal R P)} {I : SymOperadIdeal R P} (h : I ∈ S) :
    sInf S ≤ I :=
  fun _ _ _ _ hx => mem_sInf.1 hx I h

lemma le_sInf {S : Set (SymOperadIdeal R P)} {J : SymOperadIdeal R P} (h : ∀ I ∈ S, J ≤ I) :
    J ≤ sInf S :=
  fun A _ _ _ hx => mem_sInf.2 fun I hI => h I hI A hx

variable (R) in
/-- **The ideal generated by relators** `r n ⊆ P (Fin n)`: the smallest ideal containing them. -/
def span (r : ∀ n : ℕ, Set (P (Fin n))) : SymOperadIdeal R P :=
  sInf {I | ∀ n, r n ⊆ I.sub (Fin n)}

variable {r : ∀ n : ℕ, Set (P (Fin n))}

lemma subset_span (n : ℕ) : r n ⊆ (span R r).sub (Fin n) :=
  fun _ hx => mem_sInf.2 fun _ hI => hI n hx

/-- Every relabelling of a relator lies in the generated ideal. -/
lemma map_mem_span {n : ℕ} {A : Type} [Fintype A] [DecidableEq A] (e : Fin n ≃ A) {x : P (Fin n)}
    (hx : x ∈ r n) : SymOperad.map (R := R) e x ∈ (span R r).sub A :=
  (span R r).map_mem e (subset_span n hx)

/-- **The generated ideal lies in an ideal exactly when the relators do.** -/
lemma span_le {I : SymOperadIdeal R P} : span R r ≤ I ↔ ∀ n, r n ⊆ I.sub (Fin n) :=
  ⟨fun h n _ hx => h _ (subset_span n hx), fun h => sInf_le h⟩

lemma span_mono {r' : ∀ n : ℕ, Set (P (Fin n))} (h : ∀ n, r n ⊆ r' n) :
    span R r ≤ span R r' :=
  span_le.2 fun n => (h n).trans (subset_span n)

variable {Q : (A : Type) → [Fintype A] → [DecidableEq A] → Type w}
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (Q A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (Q A)] [SymOperad R Q]

/-- **A morphism kills the generated ideal exactly when it kills the relators.** -/
lemma span_le_ker_iff (φ : SymOperadHom R P Q) :
    span R r ≤ φ.ker ↔ ∀ n, ∀ x ∈ r n, φ.app (Fin n) x = 0 := by
  rw [span_le]
  refine forall_congr' fun n => ⟨fun h x hx => ?_, fun h x hx => ?_⟩
  · exact (SymOperadHom.mem_ker φ x).1 (h hx)
  · exact (SymOperadHom.mem_ker φ x).2 (h x hx)

/-- A morphism killing the relators kills every element of the generated ideal. -/
lemma app_eq_zero_of_mem_span (φ : SymOperadHom R P Q) (hφ : ∀ n, ∀ x ∈ r n, φ.app (Fin n) x = 0)
    {A : Type} [Fintype A] [DecidableEq A] {x : P A} (hx : x ∈ (span R r).sub A) :
    φ.app A x = 0 :=
  (SymOperadHom.mem_ker φ x).1 ((span_le_ker_iff φ).2 hφ A hx)

/-- **The universal property of a presented operad**: a morphism out of the quotient by the ideal
generated by `r` is a morphism out of `P` killing `r`. -/
noncomputable def presHomEquiv :
    SymOperadHom R (span R r).Quot Q
      ≃ {φ : SymOperadHom R P Q // ∀ n, ∀ x ∈ r n, φ.app (Fin n) x = 0} where
  toFun ψ := ⟨ψ.comp (span R r).projHom, fun n x hx => by
    show ψ.app _ ((span R r).proj _ x) = 0
    rw [((span R r).proj_eq_zero_iff x).2 (subset_span n hx), map_zero]⟩
  invFun φ := (span R r).liftHom φ.1 fun _ _ _ _ hx => app_eq_zero_of_mem_span φ.1 φ.2 hx
  left_inv ψ := ((span R r).liftHom_unique _ _ ψ rfl).symm
  right_inv φ := Subtype.ext ((span R r).liftHom_comp_projHom _ _)

@[simp] lemma presHomEquiv_symm_proj (φ : {φ : SymOperadHom R P Q // ∀ n, ∀ x ∈ r n,
    φ.app (Fin n) x = 0}) {A : Type} [Fintype A] [DecidableEq A] (x : P A) :
    (presHomEquiv.symm φ).app A ((span R r).proj A x) = φ.1.app A x := rfl

end SymOperadIdeal

section Linear

open SymOperadIdeal

variable (R : Type u) [CommRing R] {T : ℕ → Type w}
  {ρ : ∀ {A : Type} [Fintype A] [DecidableEq A], Syn T A → Syn T A → Prop}
  {Q : (A : Type) → [Fintype A] → [DecidableEq A] → Type w}
  [∀ (A : Type) [Fintype A] [DecidableEq A], AddCommGroup (Q A)]
  [∀ (A : Type) [Fintype A] [DecidableEq A], Module R (Q A)] [SymOperad R Q]
  (r : ∀ n : ℕ, Set (Lin R (Pres T ρ) (Fin n)))

/-- **Operads in modules presented by generators, set-theoretic relations and linear relators**:
a morphism out of `Lin R (Pres T ρ)` modulo the ideal generated by `r` is a choice of generator
values satisfying the relations `ρ`, whose linear extension kills `r`. -/
noncomputable def presLinHomEquiv :
    SymOperadHom R (span R r).Quot Q
      ≃ {f : {f : ∀ n, T n → Und R Q (Fin n) // Pres.Respects ρ f} //
          ∀ n, ∀ x ∈ r n, ((Pres.linHomEquiv R).symm f).app (Fin n) x = 0} :=
  presHomEquiv.trans
    { toFun := fun φ => ⟨Pres.linHomEquiv R φ.1, by
        rw [Equiv.symm_apply_apply]
        exact φ.2⟩
      invFun := fun f => ⟨(Pres.linHomEquiv R).symm f.1, f.2⟩
      left_inv := fun φ => Subtype.ext (Equiv.symm_apply_apply _ _)
      right_inv := fun f => Subtype.ext (Equiv.apply_symm_apply _ _) }

end Linear

end Operad
