/-
# Relabelling the vertices of planar trees

A map of generators `f : E k → E' k`, arity by arity, relabels the vertices of planar trees
(`Tree.relabel`), keeping their shapes. Relabelling commutes with grafting
(`Tree.relabel_graft`), and **cuts lift along relabelling**: a cut of a relabelled tree is the
relabelling of a cut of the tree (`Tree.exists_graft_of_relabel_graft`), and the cuts of a tree at
a leaf are determined by the relabellings of their outer parts (`Tree.graft_cancel`).

On the regular operad of planar trees, relabelling is a morphism of set operads
(`FreeReg.relabel`) inducing **bijections between the factorizations** of an operation and those
of its relabelling (`FreeReg.relabel_fact`, `FreeReg.relabel_fact_unique`). It preserves the sign
data of trees when it preserves the parities of the generators (`FreeReg.treeSgn_relabel`).

The regular operad of planar trees is generated by the corollas: **a property of its operations
holding for the corollas and the unit and stable under relabelling and composition holds for all
operations** (`FreeReg.induction`).
-/
import Operad.FreeGraded

universe u v w

namespace Operad

namespace Tree

variable {E E' E'' : ℕ → Type v} (f : ∀ k, E k → E' k)

mutual

/-- **Relabel the vertices** of a planar tree. -/
def relabel : Tree E → Tree E'
  | .leaf => .leaf
  | .node e fo => .node (f _ e) (Forest.relabelF fo)

/-- Relabel the vertices of a forest. -/
def _root_.Operad.Forest.relabelF : ∀ {k : ℕ}, Forest E k → Forest E' k
  | _, .nil => .nil
  | _, .cons t fo => .cons (relabel t) (Forest.relabelF fo)

end

@[simp] lemma relabel_leaf : relabel f (.leaf : Tree E) = .leaf := rfl

@[simp] lemma relabel_node {k : ℕ} (e : E k) (fo : Forest E k) :
    relabel f (.node e fo) = .node (f _ e) (Forest.relabelF f fo) := rfl

@[simp] lemma relabelF_nil : Forest.relabelF f (.nil : Forest E 0) = .nil := rfl

@[simp] lemma relabelF_cons {k : ℕ} (t : Tree E) (fo : Forest E k) :
    Forest.relabelF f (.cons t fo) = .cons (relabel f t) (Forest.relabelF f fo) := rfl

mutual

/-- **Relabelling keeps the arity.** -/
theorem arity_relabel : ∀ t : Tree E, (relabel f t).arity = t.arity
  | .leaf => rfl
  | .node _ fo => Forest.arityF_relabelF fo

/-- The forest half of `arity_relabel`. -/
theorem _root_.Operad.Forest.arityF_relabelF : ∀ {k : ℕ} (fo : Forest E k),
    (Forest.relabelF f fo).arityF = fo.arityF
  | _, .nil => rfl
  | _, .cons t fo => by
    simp only [relabelF_cons, arityF_cons, arity_relabel t, Forest.arityF_relabelF fo]

end

mutual

/-- **Relabelling commutes with grafting.** -/
theorem relabel_graft : ∀ (t : Tree E) (i : ℕ) (s : Tree E),
    relabel f (t.graft i s) = (relabel f t).graft i (relabel f s)
  | .leaf, _, _ => rfl
  | .node _ fo, i, s => by
    simp only [graft_node, relabel_node, Forest.relabelF_graftF fo i s]

/-- The forest half of `relabel_graft`. -/
theorem _root_.Operad.Forest.relabelF_graftF : ∀ {k : ℕ} (fo : Forest E k) (i : ℕ) (s : Tree E),
    Forest.relabelF f (fo.graftF i s) = (Forest.relabelF f fo).graftF i (relabel f s)
  | _, .nil, _, _ => rfl
  | _, .cons t fo, i, s => by
    by_cases h : i < t.arity
    · rw [graftF_cons_of_lt s h, relabelF_cons, relabelF_cons,
        graftF_cons_of_lt _ (by rwa [arity_relabel]), relabel_graft t i s]
    · rw [graftF_cons_of_ge s (by omega), relabelF_cons, relabelF_cons,
        graftF_cons_of_ge _ (by rw [arity_relabel]; omega), Forest.relabelF_graftF fo,
        arity_relabel]

end

mutual

/-- Relabelling is functorial. -/
theorem relabel_relabel (g : ∀ k, E' k → E'' k) : ∀ t : Tree E,
    relabel g (relabel f t) = relabel (fun k e => g k (f k e)) t
  | .leaf => rfl
  | .node _ fo => by simp only [relabel_node, Forest.relabelF_relabelF g fo]

/-- The forest half of `relabel_relabel`. -/
theorem _root_.Operad.Forest.relabelF_relabelF (g : ∀ k, E' k → E'' k) :
    ∀ {k : ℕ} (fo : Forest E k),
    Forest.relabelF g (Forest.relabelF f fo) = Forest.relabelF (fun k e => g k (f k e)) fo
  | _, .nil => rfl
  | _, .cons t fo => by simp only [relabelF_cons, relabel_relabel g t, Forest.relabelF_relabelF g fo]

end

/-- A graft is the trivial tree only when both trees are. -/
lemma graft_eq_leaf' {s u : Tree E} {p : ℕ} (h : s.graft p u = .leaf) :
    s = .leaf ∧ u = .leaf := by
  cases s with
  | leaf => exact ⟨rfl, by simpa using h⟩
  | node e fo => simp at h

/-- Only the trivial tree relabels to the trivial tree. -/
lemma eq_leaf_of_relabel {t : Tree E} (h : relabel f t = .leaf) : t = .leaf := by
  cases t with
  | leaf => rfl
  | node e fo => simp at h

mutual

/-- **Cuts at a leaf are determined by the relabelling of their outer parts.** -/
theorem graft_cancel : ∀ (s₁ s₂ u₁ u₂ : Tree E) (i : ℕ), i < s₁.arity →
    s₁.graft i u₁ = s₂.graft i u₂ → relabel f s₁ = relabel f s₂ → s₁ = s₂ ∧ u₁ = u₂
  | .leaf, s₂, u₁, u₂, i, _, h, hr => by
    have hs₂ : s₂ = .leaf := eq_leaf_of_relabel f hr.symm
    subst hs₂
    exact ⟨rfl, h⟩
  | .node e₁ fo₁, .leaf, _, _, _, _, _, hr => by simp at hr
  | .node e₁ fo₁, .node e₂ fo₂, u₁, u₂, i, hi, h, hr => by
    simp only [graft_node, Tree.node.injEq] at h
    obtain ⟨hk, he, hfo⟩ := h
    subst hk
    have he' : e₁ = e₂ := eq_of_heq he
    subst he'
    have hfo' := eq_of_heq hfo
    simp only [relabel_node, Tree.node.injEq, heq_eq_eq, true_and] at hr
    obtain ⟨hf, hr'⟩ := Forest.graftF_cancel fo₁ fo₂ u₁ u₂ i hi hfo' hr
    subst hf
    exact ⟨rfl, hr'⟩

/-- The forest half of `graft_cancel`. -/
theorem _root_.Operad.Forest.graftF_cancel : ∀ {k : ℕ} (fo₁ fo₂ : Forest E k) (u₁ u₂ : Tree E)
    (i : ℕ), i < fo₁.arityF → fo₁.graftF i u₁ = fo₂.graftF i u₂ →
    Forest.relabelF f fo₁ = Forest.relabelF f fo₂ → fo₁ = fo₂ ∧ u₁ = u₂
  | _, .nil, _, _, _, _, hi, _, _ => by simp at hi
  | _, .cons t₁ fo₁, .cons t₂ fo₂, u₁, u₂, i, hi, h, hr => by
    simp only [relabelF_cons, Forest.cons.injEq] at hr
    obtain ⟨hrt, hrf⟩ := hr
    have ha : t₁.arity = t₂.arity := by
      rw [← arity_relabel f t₁, ← arity_relabel f t₂, hrt]
    simp only [arityF_cons] at hi
    by_cases hlt : i < t₁.arity
    · rw [graftF_cons_of_lt _ hlt, graftF_cons_of_lt _ (by rwa [← ha])] at h
      simp only [Forest.cons.injEq] at h
      obtain ⟨ht, hfo⟩ := graft_cancel t₁ t₂ u₁ u₂ i hlt h.1 hrt
      subst ht
      exact ⟨by rw [h.2], hfo⟩
    · rw [graftF_cons_of_ge _ (by omega), graftF_cons_of_ge _ (by omega)] at h
      simp only [Forest.cons.injEq] at h
      obtain ⟨ht, hf⟩ := h
      subst ht
      obtain ⟨hfo, hu⟩ := Forest.graftF_cancel fo₁ fo₂ u₁ u₂ (i - t₁.arity)
        (by omega) hf hrf
      exact ⟨by rw [hfo], hu⟩

end

mutual

/-- **Cuts lift along relabelling**: a cut of a relabelled tree is the relabelling of a cut. -/
theorem exists_graft_of_relabel_graft : ∀ (t : Tree E) (s' u' : Tree E') (i : ℕ),
    i < s'.arity → s'.graft i u' = relabel f t →
    ∃ s u, s.graft i u = t ∧ relabel f s = s' ∧ relabel f u = u'
  | t, .leaf, u', i, _, h => ⟨.leaf, t, rfl, rfl, h.symm⟩
  | .leaf, .node e' fo', u', i, _, h => by simp at h
  | .node e fo, .node e' fo', u', i, hi, h => by
    simp only [graft_node, relabel_node, Tree.node.injEq] at h
    obtain ⟨hk, he, hfo⟩ := h
    subst hk
    have he' := eq_of_heq he
    subst he'
    obtain ⟨fo₀, u, h₀, hr, hu⟩ :=
      Forest.exists_graftF_of_relabelF_graftF fo fo' u' i hi (eq_of_heq hfo)
    exact ⟨.node e fo₀, u, by rw [graft_node, h₀], by rw [relabel_node, hr], hu⟩

/-- The forest half of `exists_graft_of_relabel_graft`. -/
theorem _root_.Operad.Forest.exists_graftF_of_relabelF_graftF : ∀ {k : ℕ} (fo : Forest E k)
    (fo' : Forest E' k) (u' : Tree E') (i : ℕ), i < fo'.arityF →
    fo'.graftF i u' = Forest.relabelF f fo →
    ∃ fo₀ u, fo₀.graftF i u = fo ∧ Forest.relabelF f fo₀ = fo' ∧ relabel f u = u'
  | _, .nil, _, _, _, hi, _ => by cases ‹Forest E' 0›; simp at hi
  | _, .cons t fo, .cons t' fo', u', i, hi, h => by
    simp only [arityF_cons] at hi
    by_cases hlt : i < t'.arity
    · rw [graftF_cons_of_lt _ hlt, relabelF_cons] at h
      simp only [Forest.cons.injEq] at h
      obtain ⟨ht, hfo⟩ := h
      obtain ⟨s, u, hs, hr, hu⟩ := exists_graft_of_relabel_graft t t' u' i hlt ht
      refine ⟨.cons s fo, u, ?_, by rw [relabelF_cons, hr, hfo], hu⟩
      have hsa : i < s.arity := by rw [← arity_relabel f s, hr]; exact hlt
      rw [graftF_cons_of_lt _ hsa, hs]
    · rw [graftF_cons_of_ge _ (by omega), relabelF_cons] at h
      simp only [Forest.cons.injEq] at h
      obtain ⟨ht, hfo⟩ := h
      have ha : t.arity = t'.arity := by rw [← arity_relabel f t, ht]
      obtain ⟨fo₀, u, h₀, hr, hu⟩ :=
        Forest.exists_graftF_of_relabelF_graftF fo fo' u' (i - t'.arity) (by omega) hfo
      refine ⟨.cons t fo₀, u, ?_, by rw [relabelF_cons, hr, ← ht], hu⟩
      rw [graftF_cons_of_ge _ (by omega), ha, h₀]

end

section Parity

variable {gp : ∀ k, E k → Bool} {gp' : ∀ k, E' k → Bool}

mutual

/-- **Relabelling preserving parities keeps the parity of a tree.** -/
theorem tpar_relabel (hgp : ∀ k e, gp' k (f k e) = gp k e) :
    ∀ t : Tree E, tpar gp' (relabel f t) = tpar gp t
  | .leaf => rfl
  | .node e fo => by
    simp only [relabel_node, tpar_node, hgp, Forest.tparF_relabelF hgp fo]

/-- The forest half of `tpar_relabel`. -/
theorem _root_.Operad.Forest.tparF_relabelF (hgp : ∀ k e, gp' k (f k e) = gp k e) :
    ∀ {k : ℕ} (fo : Forest E k), Forest.tparF gp' (Forest.relabelF f fo) = Forest.tparF gp fo
  | _, .nil => rfl
  | _, .cons t fo => by
    simp only [relabelF_cons, tparF_cons, tpar_relabel hgp t, Forest.tparF_relabelF hgp fo]

end

mutual

/-- **Relabelling preserving parities keeps the parities after the leaves.** -/
theorem apar_relabel (hgp : ∀ k e, gp' k (f k e) = gp k e) :
    ∀ (t : Tree E) (p : ℕ), apar gp' (relabel f t) p = apar gp t p
  | .leaf, _ => rfl
  | .node _ fo, p => by
    simp only [relabel_node, apar_node, Forest.aparF_relabelF hgp fo p]

/-- The forest half of `apar_relabel`. -/
theorem _root_.Operad.Forest.aparF_relabelF (hgp : ∀ k e, gp' k (f k e) = gp k e) :
    ∀ {k : ℕ} (fo : Forest E k) (p : ℕ),
    Forest.aparF gp' (Forest.relabelF f fo) p = Forest.aparF gp fo p
  | _, .nil, _ => rfl
  | _, .cons t fo, p => by
    rw [relabelF_cons]
    by_cases h : p < t.arity
    · rw [aparF_cons_of_lt _ _ _ (by rwa [arity_relabel]), aparF_cons_of_lt _ _ _ h,
        apar_relabel hgp t p, Forest.tparF_relabelF f hgp fo]
    · rw [aparF_cons_of_ge _ _ _ (by rw [arity_relabel]; omega),
        aparF_cons_of_ge _ _ _ (by omega), arity_relabel, Forest.aparF_relabelF hgp fo]

end

end Parity

end Tree

/-! ## Relabelling the regular operad of trees -/

namespace FreeReg

open TreeOfArity FreeGr Sym

variable {T T' : ℕ → Type v} (f : ∀ k, T k → T' k)
variable {A B : Type} [Fintype A] [DecidableEq A] [Fintype B] [DecidableEq B]

/-- Relabel the vertices of an operation of the regular operad of trees. -/
def relabelR (x : Reg (TreeOfArity T) A) : Reg (TreeOfArity T') A :=
  (x.1, ⟨⟨x.2.1.1, ⟨Tree.relabel f x.2.1.2.1, (Tree.arity_relabel f _).trans x.2.1.2.2⟩⟩, x.2.2⟩)

@[simp] lemma relabelR_fst (x : Reg (TreeOfArity T) A) : (relabelR f x).1 = x.1 := rfl

@[simp] lemma treeOf_relabelR (x : Reg (TreeOfArity T) A) :
    treeOf (relabelR f x) = Tree.relabel f (treeOf x) := rfl

/-- **Relabelling is a morphism of set operads.** -/
def relabel : SetOperadHom (Reg (TreeOfArity T)) (Reg (TreeOfArity T')) where
  app _ _ _ x := relabelR f x
  app_map _ _ := Reg.ext rfl (arr_ext rfl)
  app_one := Reg.ext rfl (arr_ext rfl)
  app_comp i x y := Reg.ext rfl (arr_ext (by
    show Tree.relabel f (treeOf (SetOperad.comp i x y))
      = treeOf (SetOperad.comp i (relabelR f x) (relabelR f y))
    rw [treeOf_comp, treeOf_comp, Tree.relabel_graft]
    rfl))

@[simp] lemma relabel_app (x : Reg (TreeOfArity T) A) : (relabel f).app A x = relabelR f x := rfl

lemma relabelF_leaves : ∀ k : ℕ, Forest.relabelF f (leaves (E := T) k) = leaves k
  | 0 => rfl
  | k + 1 => by
    show Forest.cons (Tree.relabel f .leaf) (Forest.relabelF f (leaves k)) = _
    rw [relabelF_leaves k]
    rfl

lemma relabel_std {k : ℕ} (e : T k) :
    (relabel f).app (Fin k) (Reg.std (corolla e)) = Reg.std (corolla (f k e)) :=
  Reg.ext rfl (arr_ext (by
    show Tree.relabel f (.node e (leaves k)) = .node (f k e) (leaves k)
    rw [Tree.relabel_node, relabelF_leaves f k]))

/-- **Relabelling lifts factorizations.** -/
theorem relabel_fact (i : A) (x : Reg (TreeOfArity T) (Without A i ⊕ B))
    (p' : Reg (TreeOfArity T') A) (q' : Reg (TreeOfArity T') B)
    (h : SetOperad.comp i p' q' = relabelR f x) :
    ∃ p q, SetOperad.comp i p q = x ∧ relabelR f p = p' ∧ relabelR f q = q' := by
  have ho := congrArg Prod.fst h
  have ht := congrArg treeOf h
  rw [treeOf_comp, treeOf_relabelR] at ht
  obtain ⟨s, u, hsu, hs, hu⟩ := Tree.exists_graft_of_relabel_graft f (treeOf x) (treeOf p')
    (treeOf q') (p'.1.rank i) (rank_lt_arity p' i) ht
  refine ⟨(p'.1, ⟨⟨p'.2.1.1, ⟨s, ?_⟩⟩, p'.2.2⟩), (q'.1, ⟨⟨q'.2.1.1, ⟨u, ?_⟩⟩, q'.2.2⟩), ?_, ?_, ?_⟩
  · rw [← Tree.arity_relabel f s, hs, treeOf_arity]
  · rw [← Tree.arity_relabel f u, hu, treeOf_arity]
  · refine Reg.ext ho (arr_ext ?_)
    show treeOf (SetOperad.comp i _ _) = treeOf x
    rw [treeOf_comp]
    exact hsu
  · exact Reg.ext rfl (arr_ext hs)
  · exact Reg.ext rfl (arr_ext hu)

/-- **Factorizations with the same relabelling are equal.** -/
theorem relabel_fact_unique (i : A) {p₁ p₂ : Reg (TreeOfArity T) A}
    {q₁ q₂ : Reg (TreeOfArity T) B} (h : SetOperad.comp i p₁ q₁ = SetOperad.comp i p₂ q₂)
    (hp : relabelR f p₁ = relabelR f p₂) (hq : relabelR f q₁ = relabelR f q₂) :
    p₁ = p₂ ∧ q₁ = q₂ := by
  have hp1 : p₁.1 = p₂.1 := by simpa using congrArg Prod.fst hp
  have hq1 : q₁.1 = q₂.1 := by simpa using congrArg Prod.fst hq
  have ht := congrArg treeOf h
  rw [treeOf_comp, treeOf_comp, hp1] at ht
  have hrp : Tree.relabel f (treeOf p₁) = Tree.relabel f (treeOf p₂) := congrArg treeOf hp
  obtain ⟨h1, h2⟩ := Tree.graft_cancel f (treeOf p₁) (treeOf p₂) (treeOf q₁) (treeOf q₂)
    (p₂.1.rank i) (by rw [← hp1]; exact rank_lt_arity p₁ i) ht hrp
  exact ⟨Reg.ext hp1 (arr_ext h1), Reg.ext hq1 (arr_ext h2)⟩

/-- **Relabelling preserving parities preserves the sign data of trees.** -/
lemma treeSgn_relabel {gp : ∀ k, T k → Bool} {gp' : ∀ k, T' k → Bool}
    (hgp : ∀ k e, gp' k (f k e) = gp k e) (x : Reg (TreeOfArity T) A) :
    (treeSgn gp').app A (relabelR f x) = (treeSgn gp).app A x :=
  SgnData.ext rfl (funext fun _ => Tree.apar_relabel f hgp _ _) (Tree.tpar_relabel f hgp _)

/-! ## Induction on the regular operad of trees -/

section Induction

variable {P : ∀ (A : Type) [Fintype A] [DecidableEq A], Reg (TreeOfArity T) A → Prop}
  (hmap : ∀ {A B : Type} [Fintype A] [DecidableEq A] [Fintype B] [DecidableEq B] (e : A ≃ B)
    (x : Reg (TreeOfArity T) A), P A x → P B (SetOperad.map e x))
  (hone : P Unit SetOperad.one)
  (hcomp : ∀ {A B : Type} [Fintype A] [DecidableEq A] [Fintype B] [DecidableEq B] (i : A)
    (x : Reg (TreeOfArity T) A) (y : Reg (TreeOfArity T) B), P A x → P B y →
      P (Without A i ⊕ B) (SetOperad.comp i x y))

variable (P) in
/-- The operations satisfying `P`. -/
@[nolint unusedArguments]
def SubR (A : Type) [Fintype A] [DecidableEq A] : Type v := {x : Reg (TreeOfArity T) A // P A x}

include hmap hone hcomp in
/-- **Induction on the regular operad of trees**: a property of its operations holding for the
corollas and the unit and stable under relabelling and composition holds for all operations. -/
theorem induction (hgen : ∀ k (e : T k), P (Fin k) (Reg.std (corolla e)))
    (x : Reg (TreeOfArity T) A) : P A x := by
  letI : SetOperad (SubR P) :=
    { map := fun e x => ⟨SetOperad.map e x.1, hmap e x.1 x.2⟩
      map_refl := fun x => Subtype.ext (SetOperad.map_refl x.1)
      map_trans := fun e e' x => Subtype.ext (SetOperad.map_trans e e' x.1)
      one := ⟨SetOperad.one, hone⟩
      comp := fun i x y => ⟨SetOperad.comp i x.1 y.1, hcomp i x.1 y.1 x.2 y.2⟩
      map_comp := fun σ' τ i x y => Subtype.ext (SetOperad.map_comp σ' τ i x.1 y.1)
      comp_one := fun i x => Subtype.ext (SetOperad.comp_one i x.1)
      one_comp := fun y => Subtype.ext (SetOperad.one_comp y.1)
      comp_assoc_seq := fun i j x y z => Subtype.ext (SetOperad.comp_assoc_seq i j x.1 y.1 z.1)
      comp_assoc_par := fun hik x y z => Subtype.ext (SetOperad.comp_assoc_par hik x.1 y.1 z.1) }
  let ι : SetOperadHom (SubR P) (Reg (TreeOfArity T)) :=
    { app := fun _ _ _ z => z.1
      app_map := fun _ _ => rfl
      app_one := rfl
      app_comp := fun _ _ _ => rfl }
  let L : SetOperadHom (Reg (TreeOfArity T)) (SubR P) :=
    Reg.lift (TreeOfArity.lift (S := SetOperad.toNSSet (SubR P))
      fun k e => (⟨Reg.std (corolla e), hgen k e⟩ : SubR P (Fin k)))
  have hid : ι.comp L = SetOperadHom.id := regHom_ext fun k e => by
    show (L.app (Fin k) (Reg.std (corolla e))).1 = Reg.std (corolla e)
    rw [show L.app (Fin k) (Reg.std (corolla e)) = ⟨Reg.std (corolla e), hgen k e⟩ by
      rw [Reg.lift_std]
      exact TreeOfArity.lift_corolla (S := SetOperad.toNSSet (SubR P)) _ e]
  have hx : (L.app A x).1 = x := congrArg (fun φ : SetOperadHom _ _ => φ.app A x) hid
  rw [← hx]
  exact (L.app A x).2

end Induction

end FreeReg

end Operad
